package com.codeator.www._1_2_DB_entities;
// Generated Aug 3, 2021 9:29:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccAccountUnits generated by hbm2java
 */
@Entity
@Table(name="ACC_ACCOUNT_UNITS"
    ,schema="CODEATOR"
)
public class AccAccountUnits  implements java.io.Serializable {


     private String accountUnitCode;
     private String accountUnitName;
     private boolean reviewFlag;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private boolean accountUnitMain;

    public AccAccountUnits() {
    }

	
    public AccAccountUnits(String accountUnitCode, String accountUnitName, boolean reviewFlag, boolean accountUnitMain) {
        this.accountUnitCode = accountUnitCode;
        this.accountUnitName = accountUnitName;
        this.reviewFlag = reviewFlag;
        this.accountUnitMain = accountUnitMain;
    }
    public AccAccountUnits(String accountUnitCode, String accountUnitName, boolean reviewFlag, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, boolean accountUnitMain) {
       this.accountUnitCode = accountUnitCode;
       this.accountUnitName = accountUnitName;
       this.reviewFlag = reviewFlag;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.accountUnitMain = accountUnitMain;
    }
   
     @Id 

    
    @Column(name="ACCOUNT_UNIT_CODE", unique=true, nullable=false, length=4)
    public String getAccountUnitCode() {
        return this.accountUnitCode;
    }
    
    public void setAccountUnitCode(String accountUnitCode) {
        this.accountUnitCode = accountUnitCode;
    }

    
    @Column(name="ACCOUNT_UNIT_NAME", nullable=false, length=100)
    public String getAccountUnitName() {
        return this.accountUnitName;
    }
    
    public void setAccountUnitName(String accountUnitName) {
        this.accountUnitName = accountUnitName;
    }

    
    @Column(name="REVIEW_FLAG", nullable=false, precision=1, scale=0)
    public boolean isReviewFlag() {
        return this.reviewFlag;
    }
    
    public void setReviewFlag(boolean reviewFlag) {
        this.reviewFlag = reviewFlag;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    
    @Column(name="ACCOUNT_UNIT_MAIN", nullable=false, precision=1, scale=0)
    public boolean isAccountUnitMain() {
        return this.accountUnitMain;
    }
    
    public void setAccountUnitMain(boolean accountUnitMain) {
        this.accountUnitMain = accountUnitMain;
    }




}


