package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 9:58:05 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AppAuthJavaUsers generated by hbm2java
 */
@Entity
@Table(name="APP_AUTH_JAVA_USERS"
    ,schema="CODEATOR"
)
public class AppAuthJavaUsers  implements java.io.Serializable {


     private long employeeId;
     private PerEmploymentMaster perEmploymentMaster;
     private InvoAccUintDept invoAccUintDept;
     private String employeePassword;
     private String employeeEmail;
     private String updateIpAddress;
     private String rmrk;
     private String chkLock;
     private String passwordResetStatus;
     private String bossManagerChk;

    public AppAuthJavaUsers() {
    }

	
    public AppAuthJavaUsers(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }
    public AppAuthJavaUsers(PerEmploymentMaster perEmploymentMaster, InvoAccUintDept invoAccUintDept, String employeePassword, String employeeEmail, String updateIpAddress, String rmrk, String chkLock, String passwordResetStatus, String bossManagerChk) {
       this.perEmploymentMaster = perEmploymentMaster;
       this.invoAccUintDept = invoAccUintDept;
       this.employeePassword = employeePassword;
       this.employeeEmail = employeeEmail;
       this.updateIpAddress = updateIpAddress;
       this.rmrk = rmrk;
       this.chkLock = chkLock;
       this.passwordResetStatus = passwordResetStatus;
       this.bossManagerChk = bossManagerChk;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="perEmploymentMaster"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="EMPLOYEE_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }

@OneToOne(fetch=FetchType.EAGER)@PrimaryKeyJoinColumn
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE"), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD"), 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD") } )
    public InvoAccUintDept getInvoAccUintDept() {
        return this.invoAccUintDept;
    }
    
    public void setInvoAccUintDept(InvoAccUintDept invoAccUintDept) {
        this.invoAccUintDept = invoAccUintDept;
    }

    
    @Column(name="EMPLOYEE_PASSWORD", length=70)
    public String getEmployeePassword() {
        return this.employeePassword;
    }
    
    public void setEmployeePassword(String employeePassword) {
        this.employeePassword = employeePassword;
    }

    
    @Column(name="EMPLOYEE_EMAIL", length=70)
    public String getEmployeeEmail() {
        return this.employeeEmail;
    }
    
    public void setEmployeeEmail(String employeeEmail) {
        this.employeeEmail = employeeEmail;
    }

    
    @Column(name="UPDATE_IP_ADDRESS", length=20)
    public String getUpdateIpAddress() {
        return this.updateIpAddress;
    }
    
    public void setUpdateIpAddress(String updateIpAddress) {
        this.updateIpAddress = updateIpAddress;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }
    
    @Column(name="CHK_LOCK", length=1)
    public String getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(String chkLock) {
        this.chkLock = chkLock;
    }

    
    @Column(name="PASSWORD_RESET_STATUS", length=2)
    public String getPasswordResetStatus() {
        return this.passwordResetStatus;
    }
    
    public void setPasswordResetStatus(String passwordResetStatus) {
        this.passwordResetStatus = passwordResetStatus;
    }

    
    @Column(name="BOSS_MANAGER_CHK", length=2)
    public String getBossManagerChk() {
        return this.bossManagerChk;
    }
    
    public void setBossManagerChk(String bossManagerChk) {
        this.bossManagerChk = bossManagerChk;
    }




}


