package com.codeator.www._1_2_DB_entities;
// Generated Jul 27, 2021 2:00:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AppSubTab generated by hbm2java
 */
@Entity
@Table(name="APP_SUB_TAB"
    ,schema="CODEATOR"
)
public class AppSubTab  implements java.io.Serializable {


     private AppSubTabId id;
     private AppTabs appTabs;
     private AppSubTabAuthType appSubTabAuthType;
     private String subTabName;
     private String subTabAccessservlet;
     private String availableToUserControl;
     private Integer subTabIndex;
     private Set<AppSubTabSpecAuth> appSubTabSpecAuths = new HashSet<AppSubTabSpecAuth>(0);
     private Set<AppSubElem> appSubElems = new HashSet<AppSubElem>(0);

    public AppSubTab() {
    }

	
    public AppSubTab(AppSubTabId id, AppTabs appTabs, String subTabName, String subTabAccessservlet) {
        this.id = id;
        this.appTabs = appTabs;
        this.subTabName = subTabName;
        this.subTabAccessservlet = subTabAccessservlet;
    }
    public AppSubTab(AppSubTabId id, AppTabs appTabs, AppSubTabAuthType appSubTabAuthType, String subTabName, String subTabAccessservlet, String availableToUserControl, Integer subTabIndex, Set<AppSubTabSpecAuth> appSubTabSpecAuths, Set<AppSubElem> appSubElems) {
       this.id = id;
       this.appTabs = appTabs;
       this.appSubTabAuthType = appSubTabAuthType;
       this.subTabName = subTabName;
       this.subTabAccessservlet = subTabAccessservlet;
       this.availableToUserControl = availableToUserControl;
       this.subTabIndex = subTabIndex;
       this.appSubTabSpecAuths = appSubTabSpecAuths;
       this.appSubElems = appSubElems;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="applicationId", column=@Column(name="APPLICATION_ID", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="tabId", column=@Column(name="TAB_ID", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="subTabId", column=@Column(name="SUB_TAB_ID", nullable=false, precision=8, scale=0) ) } )
    public AppSubTabId getId() {
        return this.id;
    }
    
    public void setId(AppSubTabId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="APPLICATION_ID", referencedColumnName="APPLICATION_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TAB_ID", referencedColumnName="TAB_ID", nullable=false, insertable=false, updatable=false) } )
    public AppTabs getAppTabs() {
        return this.appTabs;
    }
    
    public void setAppTabs(AppTabs appTabs) {
        this.appTabs = appTabs;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="AUTH_TYPE_ID")
    public AppSubTabAuthType getAppSubTabAuthType() {
        return this.appSubTabAuthType;
    }
    
    public void setAppSubTabAuthType(AppSubTabAuthType appSubTabAuthType) {
        this.appSubTabAuthType = appSubTabAuthType;
    }

    
    @Column(name="SUB_TAB_NAME", nullable=false, length=100)
    public String getSubTabName() {
        return this.subTabName;
    }
    
    public void setSubTabName(String subTabName) {
        this.subTabName = subTabName;
    }

    
    @Column(name="SUB_TAB_ACCESSSERVLET", nullable=false, length=100)
    public String getSubTabAccessservlet() {
        return this.subTabAccessservlet;
    }
    
    public void setSubTabAccessservlet(String subTabAccessservlet) {
        this.subTabAccessservlet = subTabAccessservlet;
    }

    
    @Column(name="AVAILABLE_TO_USER_CONTROL", length=10)
    public String getAvailableToUserControl() {
        return this.availableToUserControl;
    }
    
    public void setAvailableToUserControl(String availableToUserControl) {
        this.availableToUserControl = availableToUserControl;
    }

    
    @Column(name="SUB_TAB_INDEX", precision=8, scale=0)
    public Integer getSubTabIndex() {
        return this.subTabIndex;
    }
    
    public void setSubTabIndex(Integer subTabIndex) {
        this.subTabIndex = subTabIndex;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="appSubTab")
    public Set<AppSubTabSpecAuth> getAppSubTabSpecAuths() {
        return this.appSubTabSpecAuths;
    }
    
    public void setAppSubTabSpecAuths(Set<AppSubTabSpecAuth> appSubTabSpecAuths) {
        this.appSubTabSpecAuths = appSubTabSpecAuths;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="appSubTab")
    public Set<AppSubElem> getAppSubElems() {
        return this.appSubElems;
    }
    
    public void setAppSubElems(Set<AppSubElem> appSubElems) {
        this.appSubElems = appSubElems;
    }




}


