package com.codeator.www._1_2_DB_entities;
// Generated Jul 27, 2021 2:00:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AppSubTabAuthType generated by hbm2java
 */
@Entity
@Table(name="APP_SUB_TAB_AUTH_TYPE"
    ,schema="CODEATOR"
)
public class AppSubTabAuthType  implements java.io.Serializable {


     private short authTypeId;
     private String authTypeName;
     private Set<AppSubTab> appSubTabs = new HashSet<AppSubTab>(0);

    public AppSubTabAuthType() {
    }

	
    public AppSubTabAuthType(short authTypeId, String authTypeName) {
        this.authTypeId = authTypeId;
        this.authTypeName = authTypeName;
    }
    public AppSubTabAuthType(short authTypeId, String authTypeName, Set<AppSubTab> appSubTabs) {
       this.authTypeId = authTypeId;
       this.authTypeName = authTypeName;
       this.appSubTabs = appSubTabs;
    }
   
     @Id 

    
    @Column(name="AUTH_TYPE_ID", unique=true, nullable=false, precision=3, scale=0)
    public short getAuthTypeId() {
        return this.authTypeId;
    }
    
    public void setAuthTypeId(short authTypeId) {
        this.authTypeId = authTypeId;
    }

    
    @Column(name="AUTH_TYPE_NAME", nullable=false, length=30)
    public String getAuthTypeName() {
        return this.authTypeName;
    }
    
    public void setAuthTypeName(String authTypeName) {
        this.authTypeName = authTypeName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="appSubTabAuthType")
    public Set<AppSubTab> getAppSubTabs() {
        return this.appSubTabs;
    }
    
    public void setAppSubTabs(Set<AppSubTab> appSubTabs) {
        this.appSubTabs = appSubTabs;
    }




}


