package com.codeator.www._1_2_DB_entities;
// Generated Jul 27, 2021 2:00:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AppTabs generated by hbm2java
 */
@Entity
@Table(name="APP_TABS"
    ,schema="CODEATOR"
)
public class AppTabs  implements java.io.Serializable {


     private AppTabsId id;
     private AppName appName;
     private String tabName;
     private String tabFafaIcon;
     private Integer tabIndex;
     private Set<AppSubTab> appSubTabs = new HashSet<AppSubTab>(0);

    public AppTabs() {
    }

	
    public AppTabs(AppTabsId id, AppName appName, String tabName) {
        this.id = id;
        this.appName = appName;
        this.tabName = tabName;
    }
    public AppTabs(AppTabsId id, AppName appName, String tabName, String tabFafaIcon, Integer tabIndex, Set<AppSubTab> appSubTabs) {
       this.id = id;
       this.appName = appName;
       this.tabName = tabName;
       this.tabFafaIcon = tabFafaIcon;
       this.tabIndex = tabIndex;
       this.appSubTabs = appSubTabs;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="applicationId", column=@Column(name="APPLICATION_ID", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="tabId", column=@Column(name="TAB_ID", nullable=false, precision=5, scale=0) ) } )
    public AppTabsId getId() {
        return this.id;
    }
    
    public void setId(AppTabsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="APPLICATION_ID", nullable=false, insertable=false, updatable=false)
    public AppName getAppName() {
        return this.appName;
    }
    
    public void setAppName(AppName appName) {
        this.appName = appName;
    }

    
    @Column(name="TAB_NAME", nullable=false, length=50)
    public String getTabName() {
        return this.tabName;
    }
    
    public void setTabName(String tabName) {
        this.tabName = tabName;
    }

    
    @Column(name="TAB_FAFA_ICON", length=50)
    public String getTabFafaIcon() {
        return this.tabFafaIcon;
    }
    
    public void setTabFafaIcon(String tabFafaIcon) {
        this.tabFafaIcon = tabFafaIcon;
    }

    
    @Column(name="TAB_INDEX", precision=5, scale=0)
    public Integer getTabIndex() {
        return this.tabIndex;
    }
    
    public void setTabIndex(Integer tabIndex) {
        this.tabIndex = tabIndex;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="appTabs")
    public Set<AppSubTab> getAppSubTabs() {
        return this.appSubTabs;
    }
    
    public void setAppSubTabs(Set<AppSubTab> appSubTabs) {
        this.appSubTabs = appSubTabs;
    }




}


