package com.codeator.www._1_2_DB_entities;
// Generated Aug 3, 2021 9:29:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BudLocation generated by hbm2java
 */
@Entity
@Table(name="BUD_LOCATION"
    ,schema="CODEATOR"
)
public class BudLocation  implements java.io.Serializable {


     private String locationCode;
     private String locationName;
     private String filterLocationName;
     private String recordCreationUser;
     private Date recordCreationDate;
     private String lastUpdateUser;
     private Date lastUpdateDate;
     private String lastUpdateTransaction;
     private String locationDatabaseName;
     private String taxCardNo;
     private String locationAddress;

    public BudLocation() {
    }

	
    public BudLocation(String locationCode, String locationName) {
        this.locationCode = locationCode;
        this.locationName = locationName;
    }
    public BudLocation(String locationCode, String locationName, String filterLocationName, String recordCreationUser, Date recordCreationDate, String lastUpdateUser, Date lastUpdateDate, String lastUpdateTransaction, String locationDatabaseName, String taxCardNo, String locationAddress) {
       this.locationCode = locationCode;
       this.locationName = locationName;
       this.filterLocationName = filterLocationName;
       this.recordCreationUser = recordCreationUser;
       this.recordCreationDate = recordCreationDate;
       this.lastUpdateUser = lastUpdateUser;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdateTransaction = lastUpdateTransaction;
       this.locationDatabaseName = locationDatabaseName;
       this.taxCardNo = taxCardNo;
       this.locationAddress = locationAddress;
    }
   
     @Id 

    
    @Column(name="LOCATION_CODE", unique=true, nullable=false, length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    
    @Column(name="LOCATION_NAME", nullable=false, length=150)
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    
    @Column(name="FILTER_LOCATION_NAME", length=150)
    public String getFilterLocationName() {
        return this.filterLocationName;
    }
    
    public void setFilterLocationName(String filterLocationName) {
        this.filterLocationName = filterLocationName;
    }

    
    @Column(name="RECORD_CREATION_USER", length=30)
    public String getRecordCreationUser() {
        return this.recordCreationUser;
    }
    
    public void setRecordCreationUser(String recordCreationUser) {
        this.recordCreationUser = recordCreationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATION_DATE", length=7)
    public Date getRecordCreationDate() {
        return this.recordCreationDate;
    }
    
    public void setRecordCreationDate(Date recordCreationDate) {
        this.recordCreationDate = recordCreationDate;
    }

    
    @Column(name="LAST_UPDATE_USER", length=30)
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }
    
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_UPDATE_DATE", length=7)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    
    @Column(name="LAST_UPDATE_TRANSACTION", length=1)
    public String getLastUpdateTransaction() {
        return this.lastUpdateTransaction;
    }
    
    public void setLastUpdateTransaction(String lastUpdateTransaction) {
        this.lastUpdateTransaction = lastUpdateTransaction;
    }

    
    @Column(name="LOCATION_DATABASE_NAME", length=30)
    public String getLocationDatabaseName() {
        return this.locationDatabaseName;
    }
    
    public void setLocationDatabaseName(String locationDatabaseName) {
        this.locationDatabaseName = locationDatabaseName;
    }

    
    @Column(name="TAX_CARD_NO", length=30)
    public String getTaxCardNo() {
        return this.taxCardNo;
    }
    
    public void setTaxCardNo(String taxCardNo) {
        this.taxCardNo = taxCardNo;
    }

    
    @Column(name="LOCATION_ADDRESS", length=100)
    public String getLocationAddress() {
        return this.locationAddress;
    }
    
    public void setLocationAddress(String locationAddress) {
        this.locationAddress = locationAddress;
    }




}


