package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 10:27:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvoDeptItemJoin generated by hbm2java
 */
@Entity
@Table(name="INVO_DEPT_ITEM_JOIN"
    ,schema="CODEATOR"
)
public class InvoDeptItemJoin  implements java.io.Serializable {


     private InvoDeptItemJoinId id;
     private InvoItemCode invoItemCode;
     private InvoAccUintDept invoAccUintDept;
     private String chkLang;
     private Set<InvoDeptItemJoinDescDtl> invoDeptItemJoinDescDtls = new HashSet<InvoDeptItemJoinDescDtl>(0);

    public InvoDeptItemJoin() {
    }

	
    public InvoDeptItemJoin(InvoDeptItemJoinId id, InvoItemCode invoItemCode, InvoAccUintDept invoAccUintDept) {
        this.id = id;
        this.invoItemCode = invoItemCode;
        this.invoAccUintDept = invoAccUintDept;
    }
    public InvoDeptItemJoin(InvoDeptItemJoinId id, InvoItemCode invoItemCode, InvoAccUintDept invoAccUintDept, String chkLang, Set<InvoDeptItemJoinDescDtl> invoDeptItemJoinDescDtls) {
       this.id = id;
       this.invoItemCode = invoItemCode;
       this.invoAccUintDept = invoAccUintDept;
       this.chkLang = chkLang;
       this.invoDeptItemJoinDescDtls = invoDeptItemJoinDescDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="itemCode", column=@Column(name="ITEM_CODE", nullable=false, length=25) ), 
        @AttributeOverride(name="accUnitCode", column=@Column(name="ACC_UNIT_CODE", nullable=false, length=2) ) } )
    public InvoDeptItemJoinId getId() {
        return this.id;
    }
    
    public void setId(InvoDeptItemJoinId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ITEM_CODE", nullable=false, insertable=false, updatable=false)
    public InvoItemCode getInvoItemCode() {
        return this.invoItemCode;
    }
    
    public void setInvoItemCode(InvoItemCode invoItemCode) {
        this.invoItemCode = invoItemCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false) } )
    public InvoAccUintDept getInvoAccUintDept() {
        return this.invoAccUintDept;
    }
    
    public void setInvoAccUintDept(InvoAccUintDept invoAccUintDept) {
        this.invoAccUintDept = invoAccUintDept;
    }

    
    @Column(name="CHK_LANG", length=1)
    public String getChkLang() {
        return this.chkLang;
    }
    
    public void setChkLang(String chkLang) {
        this.chkLang = chkLang;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoDeptItemJoin")
    public Set<InvoDeptItemJoinDescDtl> getInvoDeptItemJoinDescDtls() {
        return this.invoDeptItemJoinDescDtls;
    }
    
    public void setInvoDeptItemJoinDescDtls(Set<InvoDeptItemJoinDescDtl> invoDeptItemJoinDescDtls) {
        this.invoDeptItemJoinDescDtls = invoDeptItemJoinDescDtls;
    }




}


