package com.codeator.www._1_2_DB_entities;
// Generated Dec 24, 2021 10:50:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvoInvoiceMaster generated by hbm2java
 */
@Entity
@Table(name="INVO_INVOICE_MASTER"
    ,schema="CODEATOR"
)
public class InvoInvoiceMaster  implements java.io.Serializable {


     private InvoInvoiceMasterId id;
     private PerGovernorateCode perGovernorateCode;
     private PurSupplier purSupplier;
     private PerCountryCode perCountryCode;
     private PerEmploymentMaster perEmploymentMasterByEmployeeIdPaid;
     private PerEmploymentMaster perEmploymentMasterByEmployeeId;
     private PurSuppWork purSuppWork;
     private PurContractMasterDtl purContractMasterDtl;
     private InvoDocumentStatus invoDocumentStatus;
     private InvoSuppPaymentType invoSuppPaymentType;
     private PurContractServiceType purContractServiceType;
     private InvoAccUintDept invoAccUintDept;
     private InvoInvoiceMaster invoInvoiceMasterByInvoimsInvoimsSplitFk;
     private InvoInvoiceMaster invoInvoiceMasterByInvoimsInvoimsFk;
     private PurSuppWorkDtl purSuppWorkDtl;
     private InvoAdvProducerCode invoAdvProducerCode;
     private InvoAdvCollectorCode invoAdvCollectorCode;
     private String receiverType;
     private String documentType;
     private Date issueDate;
     private String internalId;
     private String statusTax;
     private String dateTimeIssued;
     private String suppInfoId;
     private String uuid;
     private BigDecimal extraDiscountAmount;
     private BigDecimal totalSalesAmount;
     private BigDecimal totalDiscountAmount;
     private BigDecimal totalItemsDiscountAmount;
     private BigDecimal totalAmount;
     private BigDecimal netAmount;
     private Date reviewSendDate;
     private Date reviewDate;
     private Date approvedSendDate;
     private Date approvedDate;
     private Date sendDate;
     private Date finalSendDate;
     private Date createdDate;
     private String suppName;
     private String buildingNum;
     private String address;
     private Date paidDate;
     private String paidRmrk;
     private String chkPaid;
     private String paidDateTime;
     private String suppNameBr;
     private String addressBr;
     private String chkLock;
     private String notes;
     private String rmrk;
     private String paidFormCode;
     private String serviceCode;
     private String chkPaidDirect;
     private String suppMainFrameCodeBr;
     private String permToReceiveCode;
     private Date permToReceiveDate;
     private String permToDeliverCode;
     private Date permToDeliverDate;
     private String uuidReference;
     private Date invoRealDate;
     private Short advCollectorCode;
     private Short advProducerCode;
     private String advCollectorName;
     private String advProducerName;
     private Set<InvoInvoiceMaster> invoInvoiceMastersForInvoimsInvoimsSplitFk = new HashSet<InvoInvoiceMaster>(0);
     private Set<InvoInvoiceMaster> invoInvoiceMastersForInvoimsInvoimsFk = new HashSet<InvoInvoiceMaster>(0);
     private Set<InvoInvoiceMasterStatus> invoInvoiceMasterStatuses = new HashSet<InvoInvoiceMasterStatus>(0);
     private Set<InvoInvoiceMasterItem> invoInvoiceMasterItems = new HashSet<InvoInvoiceMasterItem>(0);

    public InvoInvoiceMaster() {
    }

	
    public InvoInvoiceMaster(InvoInvoiceMasterId id, InvoAccUintDept invoAccUintDept, String receiverType, String documentType, Date issueDate, String internalId, String statusTax) {
        this.id = id;
        this.invoAccUintDept = invoAccUintDept;
        this.receiverType = receiverType;
        this.documentType = documentType;
        this.issueDate = issueDate;
        this.internalId = internalId;
        this.statusTax = statusTax;
    }
    public InvoInvoiceMaster(InvoInvoiceMasterId id, PerGovernorateCode perGovernorateCode, PurSupplier purSupplier, PerCountryCode perCountryCode, PerEmploymentMaster perEmploymentMasterByEmployeeIdPaid, PerEmploymentMaster perEmploymentMasterByEmployeeId, PurSuppWork purSuppWork, PurContractMasterDtl purContractMasterDtl, InvoDocumentStatus invoDocumentStatus, InvoSuppPaymentType invoSuppPaymentType, PurContractServiceType purContractServiceType, InvoAccUintDept invoAccUintDept, InvoInvoiceMaster invoInvoiceMasterByInvoimsInvoimsSplitFk, InvoInvoiceMaster invoInvoiceMasterByInvoimsInvoimsFk, PurSuppWorkDtl purSuppWorkDtl, InvoAdvProducerCode invoAdvProducerCode, InvoAdvCollectorCode invoAdvCollectorCode, String receiverType, String documentType, Date issueDate, String internalId, String statusTax, String dateTimeIssued, String suppInfoId, String uuid, BigDecimal extraDiscountAmount, BigDecimal totalSalesAmount, BigDecimal totalDiscountAmount, BigDecimal totalItemsDiscountAmount, BigDecimal totalAmount, BigDecimal netAmount, Date reviewSendDate, Date reviewDate, Date approvedSendDate, Date approvedDate, Date sendDate, Date finalSendDate, Date createdDate, String suppName, String buildingNum, String address, Date paidDate, String paidRmrk, String chkPaid, String paidDateTime, String suppNameBr, String addressBr, String chkLock, String notes, String rmrk, String paidFormCode, String serviceCode, String chkPaidDirect, String suppMainFrameCodeBr, String permToReceiveCode, Date permToReceiveDate, String permToDeliverCode, Date permToDeliverDate, String uuidReference, Date invoRealDate, Short advCollectorCode, Short advProducerCode, String advCollectorName, String advProducerName, Set<InvoInvoiceMaster> invoInvoiceMastersForInvoimsInvoimsSplitFk, Set<InvoInvoiceMaster> invoInvoiceMastersForInvoimsInvoimsFk, Set<InvoInvoiceMasterStatus> invoInvoiceMasterStatuses, Set<InvoInvoiceMasterItem> invoInvoiceMasterItems) {
       this.id = id;
       this.perGovernorateCode = perGovernorateCode;
       this.purSupplier = purSupplier;
       this.perCountryCode = perCountryCode;
       this.perEmploymentMasterByEmployeeIdPaid = perEmploymentMasterByEmployeeIdPaid;
       this.perEmploymentMasterByEmployeeId = perEmploymentMasterByEmployeeId;
       this.purSuppWork = purSuppWork;
       this.purContractMasterDtl = purContractMasterDtl;
       this.invoDocumentStatus = invoDocumentStatus;
       this.invoSuppPaymentType = invoSuppPaymentType;
       this.purContractServiceType = purContractServiceType;
       this.invoAccUintDept = invoAccUintDept;
       this.invoInvoiceMasterByInvoimsInvoimsSplitFk = invoInvoiceMasterByInvoimsInvoimsSplitFk;
       this.invoInvoiceMasterByInvoimsInvoimsFk = invoInvoiceMasterByInvoimsInvoimsFk;
       this.purSuppWorkDtl = purSuppWorkDtl;
       this.invoAdvProducerCode = invoAdvProducerCode;
       this.invoAdvCollectorCode = invoAdvCollectorCode;
       this.receiverType = receiverType;
       this.documentType = documentType;
       this.issueDate = issueDate;
       this.internalId = internalId;
       this.statusTax = statusTax;
       this.dateTimeIssued = dateTimeIssued;
       this.suppInfoId = suppInfoId;
       this.uuid = uuid;
       this.extraDiscountAmount = extraDiscountAmount;
       this.totalSalesAmount = totalSalesAmount;
       this.totalDiscountAmount = totalDiscountAmount;
       this.totalItemsDiscountAmount = totalItemsDiscountAmount;
       this.totalAmount = totalAmount;
       this.netAmount = netAmount;
       this.reviewSendDate = reviewSendDate;
       this.reviewDate = reviewDate;
       this.approvedSendDate = approvedSendDate;
       this.approvedDate = approvedDate;
       this.sendDate = sendDate;
       this.finalSendDate = finalSendDate;
       this.createdDate = createdDate;
       this.suppName = suppName;
       this.buildingNum = buildingNum;
       this.address = address;
       this.paidDate = paidDate;
       this.paidRmrk = paidRmrk;
       this.chkPaid = chkPaid;
       this.paidDateTime = paidDateTime;
       this.suppNameBr = suppNameBr;
       this.addressBr = addressBr;
       this.chkLock = chkLock;
       this.notes = notes;
       this.rmrk = rmrk;
       this.paidFormCode = paidFormCode;
       this.serviceCode = serviceCode;
       this.chkPaidDirect = chkPaidDirect;
       this.suppMainFrameCodeBr = suppMainFrameCodeBr;
       this.permToReceiveCode = permToReceiveCode;
       this.permToReceiveDate = permToReceiveDate;
       this.permToDeliverCode = permToDeliverCode;
       this.permToDeliverDate = permToDeliverDate;
       this.uuidReference = uuidReference;
       this.invoRealDate = invoRealDate;
       this.advCollectorCode = advCollectorCode;
       this.advProducerCode = advProducerCode;
       this.advCollectorName = advCollectorName;
       this.advProducerName = advProducerName;
       this.invoInvoiceMastersForInvoimsInvoimsSplitFk = invoInvoiceMastersForInvoimsInvoimsSplitFk;
       this.invoInvoiceMastersForInvoimsInvoimsFk = invoInvoiceMastersForInvoimsInvoimsFk;
       this.invoInvoiceMasterStatuses = invoInvoiceMasterStatuses;
       this.invoInvoiceMasterItems = invoInvoiceMasterItems;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="accUnitCode", column=@Column(name="ACC_UNIT_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="invoSp", column=@Column(name="INVO_SP", nullable=false, precision=16, scale=0) ) } )
    public InvoInvoiceMasterId getId() {
        return this.id;
    }
    
    public void setId(InvoInvoiceMasterId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="COUNTRY_CODE", referencedColumnName="COUNTRY_CODE"), 
        @JoinColumn(name="GOV_CODE", referencedColumnName="GOV_CODE") } )
    public PerGovernorateCode getPerGovernorateCode() {
        return this.perGovernorateCode;
    }
    
    public void setPerGovernorateCode(PerGovernorateCode perGovernorateCode) {
        this.perGovernorateCode = perGovernorateCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUPP_CODE")
    public PurSupplier getPurSupplier() {
        return this.purSupplier;
    }
    
    public void setPurSupplier(PurSupplier purSupplier) {
        this.purSupplier = purSupplier;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COUNTRY_CODE_FOREIGN")
    public PerCountryCode getPerCountryCode() {
        return this.perCountryCode;
    }
    
    public void setPerCountryCode(PerCountryCode perCountryCode) {
        this.perCountryCode = perCountryCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID_PAID")
    public PerEmploymentMaster getPerEmploymentMasterByEmployeeIdPaid() {
        return this.perEmploymentMasterByEmployeeIdPaid;
    }
    
    public void setPerEmploymentMasterByEmployeeIdPaid(PerEmploymentMaster perEmploymentMasterByEmployeeIdPaid) {
        this.perEmploymentMasterByEmployeeIdPaid = perEmploymentMasterByEmployeeIdPaid;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMasterByEmployeeId() {
        return this.perEmploymentMasterByEmployeeId;
    }
    
    public void setPerEmploymentMasterByEmployeeId(PerEmploymentMaster perEmploymentMasterByEmployeeId) {
        this.perEmploymentMasterByEmployeeId = perEmploymentMasterByEmployeeId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUPP_SEQ")
    public PurSuppWork getPurSuppWork() {
        return this.purSuppWork;
    }
    
    public void setPurSuppWork(PurSuppWork purSuppWork) {
        this.purSuppWork = purSuppWork;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="CONTRACT_SP", referencedColumnName="CONTRACT_SP"), 
        @JoinColumn(name="DEP_NO_OLD_CON", referencedColumnName="DEP_NO_OLD"), 
        @JoinColumn(name="TITEL_SP", referencedColumnName="TITEL_SP"), 
        @JoinColumn(name="SECTION_NO_OLD_CON", referencedColumnName="SECTION_NO_OLD"), 
        @JoinColumn(name="CONTRACT_SEQ", referencedColumnName="CONTRACT_SEQ"), 
        @JoinColumn(name="ACC_UNIT_CODE_CON", referencedColumnName="ACC_UNIT_CODE") } )
    public PurContractMasterDtl getPurContractMasterDtl() {
        return this.purContractMasterDtl;
    }
    
    public void setPurContractMasterDtl(PurContractMasterDtl purContractMasterDtl) {
        this.purContractMasterDtl = purContractMasterDtl;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="DOC_STATUS")
    public InvoDocumentStatus getInvoDocumentStatus() {
        return this.invoDocumentStatus;
    }
    
    public void setInvoDocumentStatus(InvoDocumentStatus invoDocumentStatus) {
        this.invoDocumentStatus = invoDocumentStatus;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="PAYMENT_TYPE")
    public InvoSuppPaymentType getInvoSuppPaymentType() {
        return this.invoSuppPaymentType;
    }
    
    public void setInvoSuppPaymentType(InvoSuppPaymentType invoSuppPaymentType) {
        this.invoSuppPaymentType = invoSuppPaymentType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SERVICE_SEQ")
    public PurContractServiceType getPurContractServiceType() {
        return this.purContractServiceType;
    }
    
    public void setPurContractServiceType(PurContractServiceType purContractServiceType) {
        this.purContractServiceType = purContractServiceType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false) } )
    public InvoAccUintDept getInvoAccUintDept() {
        return this.invoAccUintDept;
    }
    
    public void setInvoAccUintDept(InvoAccUintDept invoAccUintDept) {
        this.invoAccUintDept = invoAccUintDept;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="DEP_NO_OLD_SPLIT", referencedColumnName="DEP_NO_OLD"), 
        @JoinColumn(name="ACC_UNIT_CODE_SPLIT", referencedColumnName="ACC_UNIT_CODE"), 
        @JoinColumn(name="SECTION_NO_OLD_SPLIT", referencedColumnName="SECTION_NO_OLD"), 
        @JoinColumn(name="INVO_SP_SPLIT", referencedColumnName="INVO_SP") } )
    public InvoInvoiceMaster getInvoInvoiceMasterByInvoimsInvoimsSplitFk() {
        return this.invoInvoiceMasterByInvoimsInvoimsSplitFk;
    }
    
    public void setInvoInvoiceMasterByInvoimsInvoimsSplitFk(InvoInvoiceMaster invoInvoiceMasterByInvoimsInvoimsSplitFk) {
        this.invoInvoiceMasterByInvoimsInvoimsSplitFk = invoInvoiceMasterByInvoimsInvoimsSplitFk;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="DEP_NO_OLD_MAIN", referencedColumnName="DEP_NO_OLD"), 
        @JoinColumn(name="ACC_UNIT_CODE_MAIN", referencedColumnName="ACC_UNIT_CODE"), 
        @JoinColumn(name="SECTION_NO_OLD_MAIN", referencedColumnName="SECTION_NO_OLD"), 
        @JoinColumn(name="INVO_SP_MAIN", referencedColumnName="INVO_SP") } )
    public InvoInvoiceMaster getInvoInvoiceMasterByInvoimsInvoimsFk() {
        return this.invoInvoiceMasterByInvoimsInvoimsFk;
    }
    
    public void setInvoInvoiceMasterByInvoimsInvoimsFk(InvoInvoiceMaster invoInvoiceMasterByInvoimsInvoimsFk) {
        this.invoInvoiceMasterByInvoimsInvoimsFk = invoInvoiceMasterByInvoimsInvoimsFk;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUPP_SEQ_BR")
    public PurSuppWorkDtl getPurSuppWorkDtl() {
        return this.purSuppWorkDtl;
    }
    
    public void setPurSuppWorkDtl(PurSuppWorkDtl purSuppWorkDtl) {
        this.purSuppWorkDtl = purSuppWorkDtl;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ADV_PRODUCER_SEQ")
    public InvoAdvProducerCode getInvoAdvProducerCode() {
        return this.invoAdvProducerCode;
    }
    
    public void setInvoAdvProducerCode(InvoAdvProducerCode invoAdvProducerCode) {
        this.invoAdvProducerCode = invoAdvProducerCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ADV_COLLECTOR_SEQ")
    public InvoAdvCollectorCode getInvoAdvCollectorCode() {
        return this.invoAdvCollectorCode;
    }
    
    public void setInvoAdvCollectorCode(InvoAdvCollectorCode invoAdvCollectorCode) {
        this.invoAdvCollectorCode = invoAdvCollectorCode;
    }

    
    @Column(name="RECEIVER_TYPE", nullable=false, length=1)
    public String getReceiverType() {
        return this.receiverType;
    }
    
    public void setReceiverType(String receiverType) {
        this.receiverType = receiverType;
    }

    
    @Column(name="DOCUMENT_TYPE", nullable=false, length=1)
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DATE", nullable=false, length=7)
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    
    @Column(name="INTERNAL_ID", nullable=false, length=15)
    public String getInternalId() {
        return this.internalId;
    }
    
    public void setInternalId(String internalId) {
        this.internalId = internalId;
    }

    
    @Column(name="STATUS_TAX", nullable=false, length=400)
    public String getStatusTax() {
        return this.statusTax;
    }
    
    public void setStatusTax(String statusTax) {
        this.statusTax = statusTax;
    }

    
    @Column(name="DATE_TIME_ISSUED", length=20)
    public String getDateTimeIssued() {
        return this.dateTimeIssued;
    }
    
    public void setDateTimeIssued(String dateTimeIssued) {
        this.dateTimeIssued = dateTimeIssued;
    }

    
    @Column(name="SUPP_INFO_ID", length=20)
    public String getSuppInfoId() {
        return this.suppInfoId;
    }
    
    public void setSuppInfoId(String suppInfoId) {
        this.suppInfoId = suppInfoId;
    }

    
    @Column(name="UUID", length=30)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    
    @Column(name="EXTRA_DISCOUNT_AMOUNT", precision=16, scale=5)
    public BigDecimal getExtraDiscountAmount() {
        return this.extraDiscountAmount;
    }
    
    public void setExtraDiscountAmount(BigDecimal extraDiscountAmount) {
        this.extraDiscountAmount = extraDiscountAmount;
    }

    
    @Column(name="TOTAL_SALES_AMOUNT", precision=16, scale=5)
    public BigDecimal getTotalSalesAmount() {
        return this.totalSalesAmount;
    }
    
    public void setTotalSalesAmount(BigDecimal totalSalesAmount) {
        this.totalSalesAmount = totalSalesAmount;
    }

    
    @Column(name="TOTAL_DISCOUNT_AMOUNT", precision=16, scale=5)
    public BigDecimal getTotalDiscountAmount() {
        return this.totalDiscountAmount;
    }
    
    public void setTotalDiscountAmount(BigDecimal totalDiscountAmount) {
        this.totalDiscountAmount = totalDiscountAmount;
    }

    
    @Column(name="TOTAL_ITEMS_DISCOUNT_AMOUNT", precision=16, scale=5)
    public BigDecimal getTotalItemsDiscountAmount() {
        return this.totalItemsDiscountAmount;
    }
    
    public void setTotalItemsDiscountAmount(BigDecimal totalItemsDiscountAmount) {
        this.totalItemsDiscountAmount = totalItemsDiscountAmount;
    }

    
    @Column(name="TOTAL_AMOUNT", precision=16, scale=5)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    
    @Column(name="NET_AMOUNT", precision=16, scale=5)
    public BigDecimal getNetAmount() {
        return this.netAmount;
    }
    
    public void setNetAmount(BigDecimal netAmount) {
        this.netAmount = netAmount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REVIEW_SEND_DATE", length=7)
    public Date getReviewSendDate() {
        return this.reviewSendDate;
    }
    
    public void setReviewSendDate(Date reviewSendDate) {
        this.reviewSendDate = reviewSendDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REVIEW_DATE", length=7)
    public Date getReviewDate() {
        return this.reviewDate;
    }
    
    public void setReviewDate(Date reviewDate) {
        this.reviewDate = reviewDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="APPROVED_SEND_DATE", length=7)
    public Date getApprovedSendDate() {
        return this.approvedSendDate;
    }
    
    public void setApprovedSendDate(Date approvedSendDate) {
        this.approvedSendDate = approvedSendDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="APPROVED_DATE", length=7)
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SEND_DATE", length=7)
    public Date getSendDate() {
        return this.sendDate;
    }
    
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FINAL_SEND_DATE", length=7)
    public Date getFinalSendDate() {
        return this.finalSendDate;
    }
    
    public void setFinalSendDate(Date finalSendDate) {
        this.finalSendDate = finalSendDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="SUPP_NAME", length=100)
    public String getSuppName() {
        return this.suppName;
    }
    
    public void setSuppName(String suppName) {
        this.suppName = suppName;
    }

    
    @Column(name="BUILDING_NUM", length=10)
    public String getBuildingNum() {
        return this.buildingNum;
    }
    
    public void setBuildingNum(String buildingNum) {
        this.buildingNum = buildingNum;
    }

    
    @Column(name="ADDRESS", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PAID_DATE", length=7)
    public Date getPaidDate() {
        return this.paidDate;
    }
    
    public void setPaidDate(Date paidDate) {
        this.paidDate = paidDate;
    }

    
    @Column(name="PAID_RMRK", length=100)
    public String getPaidRmrk() {
        return this.paidRmrk;
    }
    
    public void setPaidRmrk(String paidRmrk) {
        this.paidRmrk = paidRmrk;
    }

    
    @Column(name="CHK_PAID", length=1)
    public String getChkPaid() {
        return this.chkPaid;
    }
    
    public void setChkPaid(String chkPaid) {
        this.chkPaid = chkPaid;
    }

    
    @Column(name="PAID_DATE_TIME", length=20)
    public String getPaidDateTime() {
        return this.paidDateTime;
    }
    
    public void setPaidDateTime(String paidDateTime) {
        this.paidDateTime = paidDateTime;
    }

    
    @Column(name="SUPP_NAME_BR", length=100)
    public String getSuppNameBr() {
        return this.suppNameBr;
    }
    
    public void setSuppNameBr(String suppNameBr) {
        this.suppNameBr = suppNameBr;
    }

    
    @Column(name="ADDRESS_BR", length=200)
    public String getAddressBr() {
        return this.addressBr;
    }
    
    public void setAddressBr(String addressBr) {
        this.addressBr = addressBr;
    }

    
    @Column(name="CHK_LOCK", length=1)
    public String getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(String chkLock) {
        this.chkLock = chkLock;
    }

    
    @Column(name="NOTES", length=200)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="PAID_FORM_CODE", length=20)
    public String getPaidFormCode() {
        return this.paidFormCode;
    }
    
    public void setPaidFormCode(String paidFormCode) {
        this.paidFormCode = paidFormCode;
    }

    
    @Column(name="SERVICE_CODE", length=20)
    public String getServiceCode() {
        return this.serviceCode;
    }
    
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }

    
    @Column(name="CHK_PAID_DIRECT", length=1)
    public String getChkPaidDirect() {
        return this.chkPaidDirect;
    }
    
    public void setChkPaidDirect(String chkPaidDirect) {
        this.chkPaidDirect = chkPaidDirect;
    }

    
    @Column(name="SUPP_MAIN_FRAME_CODE_BR", length=20)
    public String getSuppMainFrameCodeBr() {
        return this.suppMainFrameCodeBr;
    }
    
    public void setSuppMainFrameCodeBr(String suppMainFrameCodeBr) {
        this.suppMainFrameCodeBr = suppMainFrameCodeBr;
    }

    
    @Column(name="PERM_TO_RECEIVE_CODE", length=20)
    public String getPermToReceiveCode() {
        return this.permToReceiveCode;
    }
    
    public void setPermToReceiveCode(String permToReceiveCode) {
        this.permToReceiveCode = permToReceiveCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PERM_TO_RECEIVE_DATE", length=7)
    public Date getPermToReceiveDate() {
        return this.permToReceiveDate;
    }
    
    public void setPermToReceiveDate(Date permToReceiveDate) {
        this.permToReceiveDate = permToReceiveDate;
    }

    
    @Column(name="PERM_TO_DELIVER_CODE", length=20)
    public String getPermToDeliverCode() {
        return this.permToDeliverCode;
    }
    
    public void setPermToDeliverCode(String permToDeliverCode) {
        this.permToDeliverCode = permToDeliverCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PERM_TO_DELIVER_DATE", length=7)
    public Date getPermToDeliverDate() {
        return this.permToDeliverDate;
    }
    
    public void setPermToDeliverDate(Date permToDeliverDate) {
        this.permToDeliverDate = permToDeliverDate;
    }

    
    @Column(name="UUID_REFERENCE", length=30)
    public String getUuidReference() {
        return this.uuidReference;
    }
    
    public void setUuidReference(String uuidReference) {
        this.uuidReference = uuidReference;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INVO_REAL_DATE", length=7)
    public Date getInvoRealDate() {
        return this.invoRealDate;
    }
    
    public void setInvoRealDate(Date invoRealDate) {
        this.invoRealDate = invoRealDate;
    }

    
    @Column(name="ADV_COLLECTOR_CODE", precision=3, scale=0)
    public Short getAdvCollectorCode() {
        return this.advCollectorCode;
    }
    
    public void setAdvCollectorCode(Short advCollectorCode) {
        this.advCollectorCode = advCollectorCode;
    }

    
    @Column(name="ADV_PRODUCER_CODE", precision=4, scale=0)
    public Short getAdvProducerCode() {
        return this.advProducerCode;
    }
    
    public void setAdvProducerCode(Short advProducerCode) {
        this.advProducerCode = advProducerCode;
    }

    
    @Column(name="ADV_COLLECTOR_NAME", length=100)
    public String getAdvCollectorName() {
        return this.advCollectorName;
    }
    
    public void setAdvCollectorName(String advCollectorName) {
        this.advCollectorName = advCollectorName;
    }

    
    @Column(name="ADV_PRODUCER_NAME", length=100)
    public String getAdvProducerName() {
        return this.advProducerName;
    }
    
    public void setAdvProducerName(String advProducerName) {
        this.advProducerName = advProducerName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoInvoiceMasterByInvoimsInvoimsSplitFk")
    public Set<InvoInvoiceMaster> getInvoInvoiceMastersForInvoimsInvoimsSplitFk() {
        return this.invoInvoiceMastersForInvoimsInvoimsSplitFk;
    }
    
    public void setInvoInvoiceMastersForInvoimsInvoimsSplitFk(Set<InvoInvoiceMaster> invoInvoiceMastersForInvoimsInvoimsSplitFk) {
        this.invoInvoiceMastersForInvoimsInvoimsSplitFk = invoInvoiceMastersForInvoimsInvoimsSplitFk;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoInvoiceMasterByInvoimsInvoimsFk")
    public Set<InvoInvoiceMaster> getInvoInvoiceMastersForInvoimsInvoimsFk() {
        return this.invoInvoiceMastersForInvoimsInvoimsFk;
    }
    
    public void setInvoInvoiceMastersForInvoimsInvoimsFk(Set<InvoInvoiceMaster> invoInvoiceMastersForInvoimsInvoimsFk) {
        this.invoInvoiceMastersForInvoimsInvoimsFk = invoInvoiceMastersForInvoimsInvoimsFk;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoInvoiceMaster")
    public Set<InvoInvoiceMasterStatus> getInvoInvoiceMasterStatuses() {
        return this.invoInvoiceMasterStatuses;
    }
    
    public void setInvoInvoiceMasterStatuses(Set<InvoInvoiceMasterStatus> invoInvoiceMasterStatuses) {
        this.invoInvoiceMasterStatuses = invoInvoiceMasterStatuses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoInvoiceMaster")
    public Set<InvoInvoiceMasterItem> getInvoInvoiceMasterItems() {
        return this.invoInvoiceMasterItems;
    }
    
    public void setInvoInvoiceMasterItems(Set<InvoInvoiceMasterItem> invoInvoiceMasterItems) {
        this.invoInvoiceMasterItems = invoInvoiceMasterItems;
    }




}


