package com.codeator.www._1_2_DB_entities;
// Generated Sep 11, 2021 5:44:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoInvoiceMasterStatusId generated by hbm2java
 */
@Embeddable
public class InvoInvoiceMasterStatusId  implements java.io.Serializable {


     private int sectionNoOld;
     private long depNoOld;
     private long invoSp;
     private String accUnitCode;
     private short logSeq;

    public InvoInvoiceMasterStatusId() {
    }

    public InvoInvoiceMasterStatusId(int sectionNoOld, long depNoOld, long invoSp, String accUnitCode, short logSeq) {
       this.sectionNoOld = sectionNoOld;
       this.depNoOld = depNoOld;
       this.invoSp = invoSp;
       this.accUnitCode = accUnitCode;
       this.logSeq = logSeq;
    }
   


    @Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0)
    public int getSectionNoOld() {
        return this.sectionNoOld;
    }
    
    public void setSectionNoOld(int sectionNoOld) {
        this.sectionNoOld = sectionNoOld;
    }


    @Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0)
    public long getDepNoOld() {
        return this.depNoOld;
    }
    
    public void setDepNoOld(long depNoOld) {
        this.depNoOld = depNoOld;
    }


    @Column(name="INVO_SP", nullable=false, precision=16, scale=0)
    public long getInvoSp() {
        return this.invoSp;
    }
    
    public void setInvoSp(long invoSp) {
        this.invoSp = invoSp;
    }


    @Column(name="ACC_UNIT_CODE", nullable=false, length=2)
    public String getAccUnitCode() {
        return this.accUnitCode;
    }
    
    public void setAccUnitCode(String accUnitCode) {
        this.accUnitCode = accUnitCode;
    }


    @Column(name="LOG_SEQ", nullable=false, precision=4, scale=0)
    public short getLogSeq() {
        return this.logSeq;
    }
    
    public void setLogSeq(short logSeq) {
        this.logSeq = logSeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvoInvoiceMasterStatusId) ) return false;
		 InvoInvoiceMasterStatusId castOther = ( InvoInvoiceMasterStatusId ) other; 
         
		 return (this.getSectionNoOld()==castOther.getSectionNoOld())
 && (this.getDepNoOld()==castOther.getDepNoOld())
 && (this.getInvoSp()==castOther.getInvoSp())
 && ( (this.getAccUnitCode()==castOther.getAccUnitCode()) || ( this.getAccUnitCode()!=null && castOther.getAccUnitCode()!=null && this.getAccUnitCode().equals(castOther.getAccUnitCode()) ) )
 && (this.getLogSeq()==castOther.getLogSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSectionNoOld();
         result = 37 * result + (int) this.getDepNoOld();
         result = 37 * result + (int) this.getInvoSp();
         result = 37 * result + ( getAccUnitCode() == null ? 0 : this.getAccUnitCode().hashCode() );
         result = 37 * result + this.getLogSeq();
         return result;
   }   


}


