package com.codeator.www._1_2_DB_entities;
// Generated Sep 11, 2021 5:44:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvoSuppPaymentType generated by hbm2java
 */
@Entity
@Table(name="INVO_SUPP_PAYMENT_TYPE"
    ,schema="CODEATOR"
)
public class InvoSuppPaymentType  implements java.io.Serializable {


     private byte paymentType;
     private String paymentName;
     private Set<PurContractMaster> purContractMasters = new HashSet<PurContractMaster>(0);
     private Set<InvoInvoiceMaster> invoInvoiceMasters = new HashSet<InvoInvoiceMaster>(0);

    public InvoSuppPaymentType() {
    }

	
    public InvoSuppPaymentType(byte paymentType) {
        this.paymentType = paymentType;
    }
    public InvoSuppPaymentType(byte paymentType, String paymentName, Set<PurContractMaster> purContractMasters, Set<InvoInvoiceMaster> invoInvoiceMasters) {
       this.paymentType = paymentType;
       this.paymentName = paymentName;
       this.purContractMasters = purContractMasters;
       this.invoInvoiceMasters = invoInvoiceMasters;
    }
   
     @Id 

    
    @Column(name="PAYMENT_TYPE", unique=true, nullable=false, precision=2, scale=0)
    public byte getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(byte paymentType) {
        this.paymentType = paymentType;
    }

    
    @Column(name="PAYMENT_NAME", length=75)
    public String getPaymentName() {
        return this.paymentName;
    }
    
    public void setPaymentName(String paymentName) {
        this.paymentName = paymentName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoSuppPaymentType")
    public Set<PurContractMaster> getPurContractMasters() {
        return this.purContractMasters;
    }
    
    public void setPurContractMasters(Set<PurContractMaster> purContractMasters) {
        this.purContractMasters = purContractMasters;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoSuppPaymentType")
    public Set<InvoInvoiceMaster> getInvoInvoiceMasters() {
        return this.invoInvoiceMasters;
    }
    
    public void setInvoInvoiceMasters(Set<InvoInvoiceMaster> invoInvoiceMasters) {
        this.invoInvoiceMasters = invoInvoiceMasters;
    }




}


