package com.codeator.www._1_2_DB_entities;
// Generated Sep 11, 2021 5:44:32 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvoTaxTypeDtl generated by hbm2java
 */
@Entity
@Table(name="INVO_TAX_TYPE_DTL"
    ,schema="CODEATOR"
)
public class InvoTaxTypeDtl  implements java.io.Serializable {


     private InvoTaxTypeDtlId id;
     private InvoTaxType invoTaxType;
     private String ATaxSubname;
     private String etaxSubname;
     private BigDecimal rate;
     private Set<InvoDeptTaxJoin> invoDeptTaxJoins = new HashSet<InvoDeptTaxJoin>(0);
     private Set<InvoInvoiceMasterTax> invoInvoiceMasterTaxes = new HashSet<InvoInvoiceMasterTax>(0);

    public InvoTaxTypeDtl() {
    }

	
    public InvoTaxTypeDtl(InvoTaxTypeDtlId id, InvoTaxType invoTaxType, String ATaxSubname) {
        this.id = id;
        this.invoTaxType = invoTaxType;
        this.ATaxSubname = ATaxSubname;
    }
    public InvoTaxTypeDtl(InvoTaxTypeDtlId id, InvoTaxType invoTaxType, String ATaxSubname, String etaxSubname, BigDecimal rate, Set<InvoDeptTaxJoin> invoDeptTaxJoins, Set<InvoInvoiceMasterTax> invoInvoiceMasterTaxes) {
       this.id = id;
       this.invoTaxType = invoTaxType;
       this.ATaxSubname = ATaxSubname;
       this.etaxSubname = etaxSubname;
       this.rate = rate;
       this.invoDeptTaxJoins = invoDeptTaxJoins;
       this.invoInvoiceMasterTaxes = invoInvoiceMasterTaxes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="taxType", column=@Column(name="TAX_TYPE", nullable=false, length=5) ), 
        @AttributeOverride(name="taxSubtype", column=@Column(name="TAX_SUBTYPE", nullable=false, length=5) ) } )
    public InvoTaxTypeDtlId getId() {
        return this.id;
    }
    
    public void setId(InvoTaxTypeDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="TAX_TYPE", nullable=false, insertable=false, updatable=false)
    public InvoTaxType getInvoTaxType() {
        return this.invoTaxType;
    }
    
    public void setInvoTaxType(InvoTaxType invoTaxType) {
        this.invoTaxType = invoTaxType;
    }

    
    @Column(name="A_TAX_SUBNAME", nullable=false, length=100)
    public String getATaxSubname() {
        return this.ATaxSubname;
    }
    
    public void setATaxSubname(String ATaxSubname) {
        this.ATaxSubname = ATaxSubname;
    }

    
    @Column(name="ETAX_SUBNAME", length=100)
    public String getEtaxSubname() {
        return this.etaxSubname;
    }
    
    public void setEtaxSubname(String etaxSubname) {
        this.etaxSubname = etaxSubname;
    }

    
    @Column(name="RATE", precision=5, scale=3)
    public BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoTaxTypeDtl")
    public Set<InvoDeptTaxJoin> getInvoDeptTaxJoins() {
        return this.invoDeptTaxJoins;
    }
    
    public void setInvoDeptTaxJoins(Set<InvoDeptTaxJoin> invoDeptTaxJoins) {
        this.invoDeptTaxJoins = invoDeptTaxJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoTaxTypeDtl")
    public Set<InvoInvoiceMasterTax> getInvoInvoiceMasterTaxes() {
        return this.invoInvoiceMasterTaxes;
    }
    
    public void setInvoInvoiceMasterTaxes(Set<InvoInvoiceMasterTax> invoInvoiceMasterTaxes) {
        this.invoInvoiceMasterTaxes = invoInvoiceMasterTaxes;
    }




}


