package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 9:58:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvoDeptTaxJoin generated by hbm2java
 */
@Entity
@Table(name="INVO_DEPT_TAX_JOIN"
    ,schema="CODEATOR"
)
public class InvoDeptTaxJoin  implements java.io.Serializable {


     private InvoDeptTaxJoinId id;
     private InvoTaxTypeDtl invoTaxTypeDtl;
     private InvoAccUintDept invoAccUintDept;
     private String taxNickname;
     private BigDecimal rate;

    public InvoDeptTaxJoin() {
    }

	
    public InvoDeptTaxJoin(InvoDeptTaxJoinId id, InvoTaxTypeDtl invoTaxTypeDtl, InvoAccUintDept invoAccUintDept) {
        this.id = id;
        this.invoTaxTypeDtl = invoTaxTypeDtl;
        this.invoAccUintDept = invoAccUintDept;
    }
    public InvoDeptTaxJoin(InvoDeptTaxJoinId id, InvoTaxTypeDtl invoTaxTypeDtl, InvoAccUintDept invoAccUintDept, String taxNickname, BigDecimal rate) {
       this.id = id;
       this.invoTaxTypeDtl = invoTaxTypeDtl;
       this.invoAccUintDept = invoAccUintDept;
       this.taxNickname = taxNickname;
       this.rate = rate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="taxType", column=@Column(name="TAX_TYPE", nullable=false, length=5) ), 
        @AttributeOverride(name="taxSubtype", column=@Column(name="TAX_SUBTYPE", nullable=false, length=5) ), 
        @AttributeOverride(name="accUnitCode", column=@Column(name="ACC_UNIT_CODE", nullable=false, length=2) ) } )
    public InvoDeptTaxJoinId getId() {
        return this.id;
    }
    
    public void setId(InvoDeptTaxJoinId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="TAX_TYPE", referencedColumnName="TAX_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TAX_SUBTYPE", referencedColumnName="TAX_SUBTYPE", nullable=false, insertable=false, updatable=false) } )
    public InvoTaxTypeDtl getInvoTaxTypeDtl() {
        return this.invoTaxTypeDtl;
    }
    
    public void setInvoTaxTypeDtl(InvoTaxTypeDtl invoTaxTypeDtl) {
        this.invoTaxTypeDtl = invoTaxTypeDtl;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false) } )
    public InvoAccUintDept getInvoAccUintDept() {
        return this.invoAccUintDept;
    }
    
    public void setInvoAccUintDept(InvoAccUintDept invoAccUintDept) {
        this.invoAccUintDept = invoAccUintDept;
    }

    
    @Column(name="TAX_NICKNAME", length=75)
    public String getTaxNickname() {
        return this.taxNickname;
    }
    
    public void setTaxNickname(String taxNickname) {
        this.taxNickname = taxNickname;
    }

    
    @Column(name="RATE", precision=5, scale=3)
    public BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }




}


