package com.codeator.www._1_2_DB_entities;
// Generated Sep 11, 2021 5:44:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvoUnitType generated by hbm2java
 */
@Entity
@Table(name="INVO_UNIT_TYPE"
    ,schema="CODEATOR"
)
public class InvoUnitType  implements java.io.Serializable {


     private String unitType;
     private String AUnitName;
     private String EUnitName;
     private String calcType;
     private Set<InvoDeptUnitJoin> invoDeptUnitJoins = new HashSet<InvoDeptUnitJoin>(0);
     private Set<InvoInvoiceMasterItem> invoInvoiceMasterItems = new HashSet<InvoInvoiceMasterItem>(0);

    public InvoUnitType() {
    }

	
    public InvoUnitType(String unitType, String AUnitName) {
        this.unitType = unitType;
        this.AUnitName = AUnitName;
    }
    public InvoUnitType(String unitType, String AUnitName, String EUnitName, String calcType, Set<InvoDeptUnitJoin> invoDeptUnitJoins, Set<InvoInvoiceMasterItem> invoInvoiceMasterItems) {
       this.unitType = unitType;
       this.AUnitName = AUnitName;
       this.EUnitName = EUnitName;
       this.invoDeptUnitJoins = invoDeptUnitJoins;
       this.invoInvoiceMasterItems = invoInvoiceMasterItems;
       this.calcType = calcType;
    }
   
     @Id 

    
    @Column(name="UNIT_TYPE", unique=true, nullable=false, length=5)
    public String getUnitType() {
        return this.unitType;
    }
    
    public void setUnitType(String unitType) {
        this.unitType = unitType;
    }

    
    @Column(name="A_UNIT_NAME", nullable=false, length=75)
    public String getAUnitName() {
        return this.AUnitName;
    }
    
    public void setAUnitName(String AUnitName) {
        this.AUnitName = AUnitName;
    }

    
    @Column(name="E_UNIT_NAME", length=75)
    public String getEUnitName() {
        return this.EUnitName;
    }
    
    public void setEUnitName(String EUnitName) {
        this.EUnitName = EUnitName;
    }
    
    @Column(name="CALC_TYPE", length=1)
    public String getCalcType() {
        return this.calcType;
    }
    
    public void setCalcType(String calcType) {
        this.calcType = calcType;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoUnitType")
    public Set<InvoDeptUnitJoin> getInvoDeptUnitJoins() {
        return this.invoDeptUnitJoins;
    }
    
    public void setInvoDeptUnitJoins(Set<InvoDeptUnitJoin> invoDeptUnitJoins) {
        this.invoDeptUnitJoins = invoDeptUnitJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoUnitType")
    public Set<InvoInvoiceMasterItem> getInvoInvoiceMasterItems() {
        return this.invoInvoiceMasterItems;
    }
    
    public void setInvoInvoiceMasterItems(Set<InvoInvoiceMasterItem> invoInvoiceMasterItems) {
        this.invoInvoiceMasterItems = invoInvoiceMasterItems;
    }




}


