package com.codeator.www._1_2_DB_entities;
// Generated Sep 11, 2021 5:44:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvoTaxType generated by hbm2java
 */
@Entity
@Table(name="INVO_TAX_TYPE"
    ,schema="CODEATOR"
)
public class InvoTaxType  implements java.io.Serializable {


     private String taxType;
     private String ATaxName;
     private String EtaxName;
     private String taxable;
     private Set<InvoTaxTypeDtl> invoTaxTypeDtls = new HashSet<InvoTaxTypeDtl>(0);

    public InvoTaxType() {
    }

	
    public InvoTaxType(String taxType, String ATaxName) {
        this.taxType = taxType;
        this.ATaxName = ATaxName;
    }
    public InvoTaxType(String taxType, String ATaxName, String EtaxName, String taxable, Set<InvoTaxTypeDtl> invoTaxTypeDtls) {
       this.taxType = taxType;
       this.ATaxName = ATaxName;
       this.EtaxName = EtaxName;
       this.taxable = taxable;
       this.invoTaxTypeDtls = invoTaxTypeDtls;
    }
   
     @Id 

    
    @Column(name="TAX_TYPE", unique=true, nullable=false, length=5)
    public String getTaxType() {
        return this.taxType;
    }
    
    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }

    
    @Column(name="A_TAX_NAME", nullable=false, length=50)
    public String getATaxName() {
        return this.ATaxName;
    }
    
    public void setATaxName(String ATaxName) {
        this.ATaxName = ATaxName;
    }

    
    @Column(name="E_TAX_NAME", length=50)
    public String getEtaxName() {
        return this.EtaxName;
    }
    
    public void setEtaxName(String etaxName) {
        this.EtaxName = etaxName;
    }

    
    @Column(name="TAXABLE", length=1)
    public String getTaxable() {
        return this.taxable;
    }
    
    public void setTaxable(String taxable) {
        this.taxable = taxable;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="invoTaxType")
    public Set<InvoTaxTypeDtl> getInvoTaxTypeDtls() {
        return this.invoTaxTypeDtls;
    }
    
    public void setInvoTaxTypeDtls(Set<InvoTaxTypeDtl> invoTaxTypeDtls) {
        this.invoTaxTypeDtls = invoTaxTypeDtls;
    }




}


