package com.codeator.www._1_2_DB_entities;
// Generated Dec 22, 2021 5:43:28 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MainframeSuppMobawaba generated by hbm2java
 */
@Entity
@Table(name = "MAINFRAME_SUPP_MOBAWABA",
        schema = "AHRAM"
)
public class MainframeSuppMobawaba implements java.io.Serializable {

    private String mainFrameCode;
    private String prodCode;
    private String receiverCode;
    private String suppName;
    private String adress;
    private String taxCardNo;
    private String chkMoved;
    private String countryCode;
    private String govCode;
    private String serviceSeq;

    public MainframeSuppMobawaba() {
    }

    public MainframeSuppMobawaba(String mainFrameCode) {
        this.mainFrameCode = mainFrameCode;
    }

    public MainframeSuppMobawaba(String mainFrameCode, String prodCode, String receiverCode, String suppName, String adress, String taxCardNo, String chkMoved, String serviceSeq) {
        this.mainFrameCode = mainFrameCode;
        this.prodCode = prodCode;
        this.receiverCode = receiverCode;
        this.suppName = suppName;
        this.adress = adress;
        this.taxCardNo = taxCardNo;
        this.chkMoved = chkMoved;
        this.serviceSeq = serviceSeq;
    }

    @Id

    @Column(name = "MAIN_FRAME_CODE", unique = true, nullable = false, length = 100)
    public String getMainFrameCode() {
        return this.mainFrameCode;
    }

    public void setMainFrameCode(String mainFrameCode) {
        this.mainFrameCode = mainFrameCode;
    }

    @Column(name = "PROD_CODE", length = 100)
    public String getProdCode() {
        return this.prodCode;
    }

    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }

    @Column(name = "RECEIVER_CODE", length = 100)
    public String getReceiverCode() {
        return this.receiverCode;
    }

    public void setReceiverCode(String receiverCode) {
        this.receiverCode = receiverCode;
    }

    @Column(name = "SUPP_NAME", length = 500)
    public String getSuppName() {
        return this.suppName;
    }

    public void setSuppName(String suppName) {
        this.suppName = suppName;
    }

    @Column(name = "ADRESS", length = 500)
    public String getAdress() {
        return this.adress;
    }

    public void setAdress(String adress) {
        this.adress = adress;
    }

    @Column(name = "TAX_CARD_NO", length = 100)
    public String getTaxCardNo() {
        return this.taxCardNo;
    }

    public void setTaxCardNo(String taxCardNo) {
        this.taxCardNo = taxCardNo;
    }

    @Column(name = "CHK_MOVED", length = 1)
    public String getChkMoved() {
        return this.chkMoved;
    }

    public void setChkMoved(String chkMoved) {
        this.chkMoved = chkMoved;
    }

    @Column(name = "COUNTRY_CODE", length = 5)
    public String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    @Column(name = "GOV_CODE", length = 5)
    public String getGovCode() {
        return this.govCode;
    }

    public void setGovCode(String govCode) {
        this.govCode = govCode;
    }
    
    @Column(name = "SERVICE_SEQ", length = 5)
    public String getServiceSeq() {
        return this.serviceSeq;
    }

    public void setServiceSeq(String serviceSeq) {
        this.serviceSeq = serviceSeq;
    }

}
