package com.codeator.www._1_2_DB_entities;
// Generated Aug 3, 2021 9:29:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * NvUsers generated by hbm2java
 */
@Entity
@Table(name="NV_USERS"
    ,schema="CODEATOR"
    , uniqueConstraints = @UniqueConstraint(columnNames="LOGIN_NAME") 
)
public class NvUsers  implements java.io.Serializable {


     private BigDecimal userId;
     private String loginName;
     private String userName;
     private String userPass;
     private String confirmPass;
     private String userData;
     private String userType;
     private Byte userClass;
     private Byte userStatus;
     private Date stopDate;
     private String stopReason;

    public NvUsers() {
    }

	
    public NvUsers(BigDecimal userId, String loginName) {
        this.userId = userId;
        this.loginName = loginName;
    }
    public NvUsers(BigDecimal userId, String loginName, String userName, String userPass, String confirmPass, String userData, String userType, Byte userClass, Byte userStatus, Date stopDate, String stopReason) {
       this.userId = userId;
       this.loginName = loginName;
       this.userName = userName;
       this.userPass = userPass;
       this.confirmPass = confirmPass;
       this.userData = userData;
       this.userType = userType;
       this.userClass = userClass;
       this.userStatus = userStatus;
       this.stopDate = stopDate;
       this.stopReason = stopReason;
    }
   
     @Id 

    
    @Column(name="USER_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    
    @Column(name="LOGIN_NAME", unique=true, nullable=false, length=50)
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    
    @Column(name="USER_NAME", length=200)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="USER_PASS", length=20)
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    
    @Column(name="CONFIRM_PASS", length=20)
    public String getConfirmPass() {
        return this.confirmPass;
    }
    
    public void setConfirmPass(String confirmPass) {
        this.confirmPass = confirmPass;
    }

    
    @Column(name="USER_DATA", length=1000)
    public String getUserData() {
        return this.userData;
    }
    
    public void setUserData(String userData) {
        this.userData = userData;
    }

    
    @Column(name="USER_TYPE", length=1)
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }

    
    @Column(name="USER_CLASS", precision=2, scale=0)
    public Byte getUserClass() {
        return this.userClass;
    }
    
    public void setUserClass(Byte userClass) {
        this.userClass = userClass;
    }

    
    @Column(name="USER_STATUS", precision=2, scale=0)
    public Byte getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="STOP_DATE", length=7)
    public Date getStopDate() {
        return this.stopDate;
    }
    
    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    
    @Column(name="STOP_REASON", length=1000)
    public String getStopReason() {
        return this.stopReason;
    }
    
    public void setStopReason(String stopReason) {
        this.stopReason = stopReason;
    }




}


