package com.codeator.www._1_2_DB_entities;
// Generated Dec 24, 2021 10:50:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEmploymentMaster generated by hbm2java
 */
@Entity
@Table(name="PER_EMPLOYMENT_MASTER"
    ,schema="CODEATOR"
)
public class PerEmploymentMaster  implements java.io.Serializable {


     private long employeeId;
     private PerEmploymentParameter perEmploymentParameter;
     private PerGeneralCode perGeneralCode;
     private PerOrganizationStructure perOrganizationStructure;
     private PerOrgunitCode perOrgunitCode;
     private PerQualClass perQualClass;
     private PerQualCode perQualCode;
     private PerDeptOld perDeptOld;
     private PerLocationCode perLocationCode;
     private String employeeNo;
     private String empEname;
     private String empAname;
     private Date contractDate;
     private Date contractEnddate;
     private Date birthDate;
     private Date qualYear;
     private Long subDepNoOld;
     private Long secSubDepNo;
     private Set<StoResponsibilityHistoryEmp> stoResponsibilityHistoryEmps = new HashSet<StoResponsibilityHistoryEmp>(0);
     private Set<VcleVehicleDriverJoin> vcleVehicleDriverJoins = new HashSet<VcleVehicleDriverJoin>(0);
     private Set<StoResponsibilityDept> stoResponsibilityDepts = new HashSet<StoResponsibilityDept>(0);
     private Set<InvoAccUintDept> invoAccUintDepts = new HashSet<InvoAccUintDept>(0);
     private Set<StoResponsibilityDeptItm> stoResponsibilityDeptItms = new HashSet<StoResponsibilityDeptItm>(0);
     private Set<VcleIssueDocumentLiq> vcleIssueDocumentLiqs = new HashSet<VcleIssueDocumentLiq>(0);
     private StoRespEmpReq stoRespEmpReq;
     private Set<VcleVehicleRequire> vcleVehicleRequiresForEmployeeIdDriver = new HashSet<VcleVehicleRequire>(0);
     private Set<PurContractMaster> purContractMasters = new HashSet<PurContractMaster>(0);
     private Set<VcleIssueDocumentMainDtl> vcleIssueDocumentMainDtls = new HashSet<VcleIssueDocumentMainDtl>(0);
     private Set<VcleVehicleClassDtl> vcleVehicleClassDtls = new HashSet<VcleVehicleClassDtl>(0);
     private Set<PurSuppWorkDtl> purSuppWorkDtls = new HashSet<PurSuppWorkDtl>(0);
     private VcleVehicleRequireEmp vcleVehicleRequireEmp;
     private Set<VcleVehicleRequire> vcleVehicleRequiresForEmployeeId = new HashSet<VcleVehicleRequire>(0);
     private VcleAssociationEmp vcleAssociationEmp;
     private Set<InvoInvoiceMaster> invoInvoiceMastersForEmployeeIdPaid = new HashSet<InvoInvoiceMaster>(0);
     private Set<VcleTrafficEmpPerm> vcleTrafficEmpPerms = new HashSet<VcleTrafficEmpPerm>(0);
     private Set<VcleVehicleLicense> vcleVehicleLicensesForEmployeeId = new HashSet<VcleVehicleLicense>(0);
     private Set<InvoItemCode> invoItemCodes = new HashSet<InvoItemCode>(0);
     private Set<PurContractServiceType> purContractServiceTypes = new HashSet<PurContractServiceType>(0);
     private Set<PurSuppWork> purSuppWorksForUpdateEmpId = new HashSet<PurSuppWork>(0);
     private AppAuthJavaUsers appAuthJavaUsers;
     private Set<PurSuppWork> purSuppWorksForInsertEmpId = new HashSet<PurSuppWork>(0);
     private Set<VcleRecordMovement> vcleRecordMovements = new HashSet<VcleRecordMovement>(0);
     private Set<InvoInvoiceMaster> invoInvoiceMastersForEmployeeId = new HashSet<InvoInvoiceMaster>(0);
     private Set<InvoInvoiceMasterStatus> invoInvoiceMasterStatuses = new HashSet<InvoInvoiceMasterStatus>(0);
     private Set<VcleVehicleIncome> vcleVehicleIncomes = new HashSet<VcleVehicleIncome>(0);
     private Set<VcleTrafficLine> vcleTrafficLines = new HashSet<VcleTrafficLine>(0);
     private Set<VcleMotorChange> vcleMotorChanges = new HashSet<VcleMotorChange>(0);
     private Set<VcleVehicleRequireStatusDt> vcleVehicleRequireStatusDts = new HashSet<VcleVehicleRequireStatusDt>(0);
     private Set<VcleIssueDocumentMan> vcleIssueDocumentMans = new HashSet<VcleIssueDocumentMan>(0);
     private Set<InvoAdvProducerCode> invoAdvProducerCodes = new HashSet<InvoAdvProducerCode>(0);
     private Set<AppSubElemSpecAuth> appSubElemSpecAuthsForEmployeeId = new HashSet<AppSubElemSpecAuth>(0);
     private Set<VcleVehicleLicenseDtl> vcleVehicleLicenseDtls = new HashSet<VcleVehicleLicenseDtl>(0);
     private Set<AppSubElemSpecAuth> appSubElemSpecAuthsForEmployeeIdAction = new HashSet<AppSubElemSpecAuth>(0);
     private Set<InvoAdvCollectorCode> invoAdvCollectorCodes = new HashSet<InvoAdvCollectorCode>(0);
     private Set<AppSubTabSpecAuth> appSubTabSpecAuthsForEmployeeId = new HashSet<AppSubTabSpecAuth>(0);
     private Set<VcleTravelExchange> vcleTravelExchanges = new HashSet<VcleTravelExchange>(0);
     private Set<VcleVehicleLicense> vcleVehicleLicensesForEmployeeIdReceive = new HashSet<VcleVehicleLicense>(0);
     private Set<VcleRecordMovementJoin> vcleRecordMovementJoins = new HashSet<VcleRecordMovementJoin>(0);
     private Set<AppSubTabSpecAuth> appSubTabSpecAuthsForEmployeeIdAction = new HashSet<AppSubTabSpecAuth>(0);

    public PerEmploymentMaster() {
    }

	
    public PerEmploymentMaster(long employeeId, String employeeNo, String empAname) {
        this.employeeId = employeeId;
        this.employeeNo = employeeNo;
        this.empAname = empAname;
    }
    public PerEmploymentMaster(long employeeId, PerEmploymentParameter perEmploymentParameter, PerGeneralCode perGeneralCode, PerOrganizationStructure perOrganizationStructure, PerOrgunitCode perOrgunitCode, PerQualClass perQualClass, PerQualCode perQualCode, PerDeptOld perDeptOld, PerLocationCode perLocationCode, String employeeNo, String empEname, String empAname, Date contractDate, Date contractEnddate, Date birthDate, Date qualYear, Long subDepNoOld, Long secSubDepNo, Set<StoResponsibilityHistoryEmp> stoResponsibilityHistoryEmps, Set<VcleVehicleDriverJoin> vcleVehicleDriverJoins, Set<StoResponsibilityDept> stoResponsibilityDepts, Set<InvoAccUintDept> invoAccUintDepts, Set<StoResponsibilityDeptItm> stoResponsibilityDeptItms, Set<VcleIssueDocumentLiq> vcleIssueDocumentLiqs, StoRespEmpReq stoRespEmpReq, Set<VcleVehicleRequire> vcleVehicleRequiresForEmployeeIdDriver, Set<PurContractMaster> purContractMasters, Set<VcleIssueDocumentMainDtl> vcleIssueDocumentMainDtls, Set<VcleVehicleClassDtl> vcleVehicleClassDtls, Set<PurSuppWorkDtl> purSuppWorkDtls, VcleVehicleRequireEmp vcleVehicleRequireEmp, Set<VcleVehicleRequire> vcleVehicleRequiresForEmployeeId, VcleAssociationEmp vcleAssociationEmp, Set<InvoInvoiceMaster> invoInvoiceMastersForEmployeeIdPaid, Set<VcleTrafficEmpPerm> vcleTrafficEmpPerms, Set<VcleVehicleLicense> vcleVehicleLicensesForEmployeeId, Set<InvoItemCode> invoItemCodes, Set<PurContractServiceType> purContractServiceTypes, Set<PurSuppWork> purSuppWorksForUpdateEmpId, AppAuthJavaUsers appAuthJavaUsers, Set<PurSuppWork> purSuppWorksForInsertEmpId, Set<VcleRecordMovement> vcleRecordMovements, Set<InvoInvoiceMaster> invoInvoiceMastersForEmployeeId, Set<InvoInvoiceMasterStatus> invoInvoiceMasterStatuses, Set<VcleVehicleIncome> vcleVehicleIncomes, Set<VcleTrafficLine> vcleTrafficLines, Set<VcleMotorChange> vcleMotorChanges, Set<VcleVehicleRequireStatusDt> vcleVehicleRequireStatusDts, Set<VcleIssueDocumentMan> vcleIssueDocumentMans, Set<InvoAdvProducerCode> invoAdvProducerCodes, Set<AppSubElemSpecAuth> appSubElemSpecAuthsForEmployeeId, Set<VcleVehicleLicenseDtl> vcleVehicleLicenseDtls, Set<AppSubElemSpecAuth> appSubElemSpecAuthsForEmployeeIdAction, Set<InvoAdvCollectorCode> invoAdvCollectorCodes, Set<AppSubTabSpecAuth> appSubTabSpecAuthsForEmployeeId, Set<VcleTravelExchange> vcleTravelExchanges, Set<VcleVehicleLicense> vcleVehicleLicensesForEmployeeIdReceive, Set<VcleRecordMovementJoin> vcleRecordMovementJoins, Set<AppSubTabSpecAuth> appSubTabSpecAuthsForEmployeeIdAction) {
       this.employeeId = employeeId;
       this.perEmploymentParameter = perEmploymentParameter;
       this.perGeneralCode = perGeneralCode;
       this.perOrganizationStructure = perOrganizationStructure;
       this.perOrgunitCode = perOrgunitCode;
       this.perQualClass = perQualClass;
       this.perQualCode = perQualCode;
       this.perDeptOld = perDeptOld;
       this.perLocationCode = perLocationCode;
       this.employeeNo = employeeNo;
       this.empEname = empEname;
       this.empAname = empAname;
       this.contractDate = contractDate;
       this.contractEnddate = contractEnddate;
       this.birthDate = birthDate;
       this.qualYear = qualYear;
       this.subDepNoOld = subDepNoOld;
       this.secSubDepNo = secSubDepNo;
       this.stoResponsibilityHistoryEmps = stoResponsibilityHistoryEmps;
       this.vcleVehicleDriverJoins = vcleVehicleDriverJoins;
       this.stoResponsibilityDepts = stoResponsibilityDepts;
       this.invoAccUintDepts = invoAccUintDepts;
       this.stoResponsibilityDeptItms = stoResponsibilityDeptItms;
       this.vcleIssueDocumentLiqs = vcleIssueDocumentLiqs;
       this.stoRespEmpReq = stoRespEmpReq;
       this.vcleVehicleRequiresForEmployeeIdDriver = vcleVehicleRequiresForEmployeeIdDriver;
       this.purContractMasters = purContractMasters;
       this.vcleIssueDocumentMainDtls = vcleIssueDocumentMainDtls;
       this.vcleVehicleClassDtls = vcleVehicleClassDtls;
       this.purSuppWorkDtls = purSuppWorkDtls;
       this.vcleVehicleRequireEmp = vcleVehicleRequireEmp;
       this.vcleVehicleRequiresForEmployeeId = vcleVehicleRequiresForEmployeeId;
       this.vcleAssociationEmp = vcleAssociationEmp;
       this.invoInvoiceMastersForEmployeeIdPaid = invoInvoiceMastersForEmployeeIdPaid;
       this.vcleTrafficEmpPerms = vcleTrafficEmpPerms;
       this.vcleVehicleLicensesForEmployeeId = vcleVehicleLicensesForEmployeeId;
       this.invoItemCodes = invoItemCodes;
       this.purContractServiceTypes = purContractServiceTypes;
       this.purSuppWorksForUpdateEmpId = purSuppWorksForUpdateEmpId;
       this.appAuthJavaUsers = appAuthJavaUsers;
       this.purSuppWorksForInsertEmpId = purSuppWorksForInsertEmpId;
       this.vcleRecordMovements = vcleRecordMovements;
       this.invoInvoiceMastersForEmployeeId = invoInvoiceMastersForEmployeeId;
       this.invoInvoiceMasterStatuses = invoInvoiceMasterStatuses;
       this.vcleVehicleIncomes = vcleVehicleIncomes;
       this.vcleTrafficLines = vcleTrafficLines;
       this.vcleMotorChanges = vcleMotorChanges;
       this.vcleVehicleRequireStatusDts = vcleVehicleRequireStatusDts;
       this.vcleIssueDocumentMans = vcleIssueDocumentMans;
       this.invoAdvProducerCodes = invoAdvProducerCodes;
       this.appSubElemSpecAuthsForEmployeeId = appSubElemSpecAuthsForEmployeeId;
       this.vcleVehicleLicenseDtls = vcleVehicleLicenseDtls;
       this.appSubElemSpecAuthsForEmployeeIdAction = appSubElemSpecAuthsForEmployeeIdAction;
       this.invoAdvCollectorCodes = invoAdvCollectorCodes;
       this.appSubTabSpecAuthsForEmployeeId = appSubTabSpecAuthsForEmployeeId;
       this.vcleTravelExchanges = vcleTravelExchanges;
       this.vcleVehicleLicensesForEmployeeIdReceive = vcleVehicleLicensesForEmployeeIdReceive;
       this.vcleRecordMovementJoins = vcleRecordMovementJoins;
       this.appSubTabSpecAuthsForEmployeeIdAction = appSubTabSpecAuthsForEmployeeIdAction;
    }
   
     @Id 

    
    @Column(name="EMPLOYEE_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYMENT_SOURCE_CODE")
    public PerEmploymentParameter getPerEmploymentParameter() {
        return this.perEmploymentParameter;
    }
    
    public void setPerEmploymentParameter(PerEmploymentParameter perEmploymentParameter) {
        this.perEmploymentParameter = perEmploymentParameter;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="GENERAL_CODE")
    public PerGeneralCode getPerGeneralCode() {
        return this.perGeneralCode;
    }
    
    public void setPerGeneralCode(PerGeneralCode perGeneralCode) {
        this.perGeneralCode = perGeneralCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ORG_ID")
    public PerOrganizationStructure getPerOrganizationStructure() {
        return this.perOrganizationStructure;
    }
    
    public void setPerOrganizationStructure(PerOrganizationStructure perOrganizationStructure) {
        this.perOrganizationStructure = perOrganizationStructure;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ORGUNIT_CODE")
    public PerOrgunitCode getPerOrgunitCode() {
        return this.perOrgunitCode;
    }
    
    public void setPerOrgunitCode(PerOrgunitCode perOrgunitCode) {
        this.perOrgunitCode = perOrgunitCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="QUAL_CLASS_CODE")
    public PerQualClass getPerQualClass() {
        return this.perQualClass;
    }
    
    public void setPerQualClass(PerQualClass perQualClass) {
        this.perQualClass = perQualClass;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="QUAL_CODE")
    public PerQualCode getPerQualCode() {
        return this.perQualCode;
    }
    
    public void setPerQualCode(PerQualCode perQualCode) {
        this.perQualCode = perQualCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD"), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD") } )
    public PerDeptOld getPerDeptOld() {
        return this.perDeptOld;
    }
    
    public void setPerDeptOld(PerDeptOld perDeptOld) {
        this.perDeptOld = perDeptOld;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE"), 
        @JoinColumn(name="LOC_CODE", referencedColumnName="LOC_CODE") } )
    public PerLocationCode getPerLocationCode() {
        return this.perLocationCode;
    }
    
    public void setPerLocationCode(PerLocationCode perLocationCode) {
        this.perLocationCode = perLocationCode;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="EMP_ENAME", length=75)
    public String getEmpEname() {
        return this.empEname;
    }
    
    public void setEmpEname(String empEname) {
        this.empEname = empEname;
    }

    
    @Column(name="EMP_ANAME", nullable=false, length=75)
    public String getEmpAname() {
        return this.empAname;
    }
    
    public void setEmpAname(String empAname) {
        this.empAname = empAname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CONTRACT_DATE", length=7)
    public Date getContractDate() {
        return this.contractDate;
    }
    
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CONTRACT_ENDDATE", length=7)
    public Date getContractEnddate() {
        return this.contractEnddate;
    }
    
    public void setContractEnddate(Date contractEnddate) {
        this.contractEnddate = contractEnddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BIRTH_DATE", length=7)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="QUAL_YEAR", length=7)
    public Date getQualYear() {
        return this.qualYear;
    }
    
    public void setQualYear(Date qualYear) {
        this.qualYear = qualYear;
    }

    
    @Column(name="SUB_DEP_NO_OLD", precision=10, scale=0)
    public Long getSubDepNoOld() {
        return this.subDepNoOld;
    }
    
    public void setSubDepNoOld(Long subDepNoOld) {
        this.subDepNoOld = subDepNoOld;
    }

    
    @Column(name="SEC_SUB_DEP_NO", precision=10, scale=0)
    public Long getSecSubDepNo() {
        return this.secSubDepNo;
    }
    
    public void setSecSubDepNo(Long secSubDepNo) {
        this.secSubDepNo = secSubDepNo;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<StoResponsibilityHistoryEmp> getStoResponsibilityHistoryEmps() {
        return this.stoResponsibilityHistoryEmps;
    }
    
    public void setStoResponsibilityHistoryEmps(Set<StoResponsibilityHistoryEmp> stoResponsibilityHistoryEmps) {
        this.stoResponsibilityHistoryEmps = stoResponsibilityHistoryEmps;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleVehicleDriverJoin> getVcleVehicleDriverJoins() {
        return this.vcleVehicleDriverJoins;
    }
    
    public void setVcleVehicleDriverJoins(Set<VcleVehicleDriverJoin> vcleVehicleDriverJoins) {
        this.vcleVehicleDriverJoins = vcleVehicleDriverJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<StoResponsibilityDept> getStoResponsibilityDepts() {
        return this.stoResponsibilityDepts;
    }
    
    public void setStoResponsibilityDepts(Set<StoResponsibilityDept> stoResponsibilityDepts) {
        this.stoResponsibilityDepts = stoResponsibilityDepts;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<InvoAccUintDept> getInvoAccUintDepts() {
        return this.invoAccUintDepts;
    }
    
    public void setInvoAccUintDepts(Set<InvoAccUintDept> invoAccUintDepts) {
        this.invoAccUintDepts = invoAccUintDepts;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<StoResponsibilityDeptItm> getStoResponsibilityDeptItms() {
        return this.stoResponsibilityDeptItms;
    }
    
    public void setStoResponsibilityDeptItms(Set<StoResponsibilityDeptItm> stoResponsibilityDeptItms) {
        this.stoResponsibilityDeptItms = stoResponsibilityDeptItms;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleIssueDocumentLiq> getVcleIssueDocumentLiqs() {
        return this.vcleIssueDocumentLiqs;
    }
    
    public void setVcleIssueDocumentLiqs(Set<VcleIssueDocumentLiq> vcleIssueDocumentLiqs) {
        this.vcleIssueDocumentLiqs = vcleIssueDocumentLiqs;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public StoRespEmpReq getStoRespEmpReq() {
        return this.stoRespEmpReq;
    }
    
    public void setStoRespEmpReq(StoRespEmpReq stoRespEmpReq) {
        this.stoRespEmpReq = stoRespEmpReq;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeIdDriver")
    public Set<VcleVehicleRequire> getVcleVehicleRequiresForEmployeeIdDriver() {
        return this.vcleVehicleRequiresForEmployeeIdDriver;
    }
    
    public void setVcleVehicleRequiresForEmployeeIdDriver(Set<VcleVehicleRequire> vcleVehicleRequiresForEmployeeIdDriver) {
        this.vcleVehicleRequiresForEmployeeIdDriver = vcleVehicleRequiresForEmployeeIdDriver;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<PurContractMaster> getPurContractMasters() {
        return this.purContractMasters;
    }
    
    public void setPurContractMasters(Set<PurContractMaster> purContractMasters) {
        this.purContractMasters = purContractMasters;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleIssueDocumentMainDtl> getVcleIssueDocumentMainDtls() {
        return this.vcleIssueDocumentMainDtls;
    }
    
    public void setVcleIssueDocumentMainDtls(Set<VcleIssueDocumentMainDtl> vcleIssueDocumentMainDtls) {
        this.vcleIssueDocumentMainDtls = vcleIssueDocumentMainDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleVehicleClassDtl> getVcleVehicleClassDtls() {
        return this.vcleVehicleClassDtls;
    }
    
    public void setVcleVehicleClassDtls(Set<VcleVehicleClassDtl> vcleVehicleClassDtls) {
        this.vcleVehicleClassDtls = vcleVehicleClassDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<PurSuppWorkDtl> getPurSuppWorkDtls() {
        return this.purSuppWorkDtls;
    }
    
    public void setPurSuppWorkDtls(Set<PurSuppWorkDtl> purSuppWorkDtls) {
        this.purSuppWorkDtls = purSuppWorkDtls;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public VcleVehicleRequireEmp getVcleVehicleRequireEmp() {
        return this.vcleVehicleRequireEmp;
    }
    
    public void setVcleVehicleRequireEmp(VcleVehicleRequireEmp vcleVehicleRequireEmp) {
        this.vcleVehicleRequireEmp = vcleVehicleRequireEmp;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeId")
    public Set<VcleVehicleRequire> getVcleVehicleRequiresForEmployeeId() {
        return this.vcleVehicleRequiresForEmployeeId;
    }
    
    public void setVcleVehicleRequiresForEmployeeId(Set<VcleVehicleRequire> vcleVehicleRequiresForEmployeeId) {
        this.vcleVehicleRequiresForEmployeeId = vcleVehicleRequiresForEmployeeId;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public VcleAssociationEmp getVcleAssociationEmp() {
        return this.vcleAssociationEmp;
    }
    
    public void setVcleAssociationEmp(VcleAssociationEmp vcleAssociationEmp) {
        this.vcleAssociationEmp = vcleAssociationEmp;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeIdPaid")
    public Set<InvoInvoiceMaster> getInvoInvoiceMastersForEmployeeIdPaid() {
        return this.invoInvoiceMastersForEmployeeIdPaid;
    }
    
    public void setInvoInvoiceMastersForEmployeeIdPaid(Set<InvoInvoiceMaster> invoInvoiceMastersForEmployeeIdPaid) {
        this.invoInvoiceMastersForEmployeeIdPaid = invoInvoiceMastersForEmployeeIdPaid;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleTrafficEmpPerm> getVcleTrafficEmpPerms() {
        return this.vcleTrafficEmpPerms;
    }
    
    public void setVcleTrafficEmpPerms(Set<VcleTrafficEmpPerm> vcleTrafficEmpPerms) {
        this.vcleTrafficEmpPerms = vcleTrafficEmpPerms;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeId")
    public Set<VcleVehicleLicense> getVcleVehicleLicensesForEmployeeId() {
        return this.vcleVehicleLicensesForEmployeeId;
    }
    
    public void setVcleVehicleLicensesForEmployeeId(Set<VcleVehicleLicense> vcleVehicleLicensesForEmployeeId) {
        this.vcleVehicleLicensesForEmployeeId = vcleVehicleLicensesForEmployeeId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<InvoItemCode> getInvoItemCodes() {
        return this.invoItemCodes;
    }
    
    public void setInvoItemCodes(Set<InvoItemCode> invoItemCodes) {
        this.invoItemCodes = invoItemCodes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<PurContractServiceType> getPurContractServiceTypes() {
        return this.purContractServiceTypes;
    }
    
    public void setPurContractServiceTypes(Set<PurContractServiceType> purContractServiceTypes) {
        this.purContractServiceTypes = purContractServiceTypes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByUpdateEmpId")
    public Set<PurSuppWork> getPurSuppWorksForUpdateEmpId() {
        return this.purSuppWorksForUpdateEmpId;
    }
    
    public void setPurSuppWorksForUpdateEmpId(Set<PurSuppWork> purSuppWorksForUpdateEmpId) {
        this.purSuppWorksForUpdateEmpId = purSuppWorksForUpdateEmpId;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public AppAuthJavaUsers getAppAuthJavaUsers() {
        return this.appAuthJavaUsers;
    }
    
    public void setAppAuthJavaUsers(AppAuthJavaUsers appAuthJavaUsers) {
        this.appAuthJavaUsers = appAuthJavaUsers;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByInsertEmpId")
    public Set<PurSuppWork> getPurSuppWorksForInsertEmpId() {
        return this.purSuppWorksForInsertEmpId;
    }
    
    public void setPurSuppWorksForInsertEmpId(Set<PurSuppWork> purSuppWorksForInsertEmpId) {
        this.purSuppWorksForInsertEmpId = purSuppWorksForInsertEmpId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleRecordMovement> getVcleRecordMovements() {
        return this.vcleRecordMovements;
    }
    
    public void setVcleRecordMovements(Set<VcleRecordMovement> vcleRecordMovements) {
        this.vcleRecordMovements = vcleRecordMovements;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeId")
    public Set<InvoInvoiceMaster> getInvoInvoiceMastersForEmployeeId() {
        return this.invoInvoiceMastersForEmployeeId;
    }
    
    public void setInvoInvoiceMastersForEmployeeId(Set<InvoInvoiceMaster> invoInvoiceMastersForEmployeeId) {
        this.invoInvoiceMastersForEmployeeId = invoInvoiceMastersForEmployeeId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<InvoInvoiceMasterStatus> getInvoInvoiceMasterStatuses() {
        return this.invoInvoiceMasterStatuses;
    }
    
    public void setInvoInvoiceMasterStatuses(Set<InvoInvoiceMasterStatus> invoInvoiceMasterStatuses) {
        this.invoInvoiceMasterStatuses = invoInvoiceMasterStatuses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleVehicleIncome> getVcleVehicleIncomes() {
        return this.vcleVehicleIncomes;
    }
    
    public void setVcleVehicleIncomes(Set<VcleVehicleIncome> vcleVehicleIncomes) {
        this.vcleVehicleIncomes = vcleVehicleIncomes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleTrafficLine> getVcleTrafficLines() {
        return this.vcleTrafficLines;
    }
    
    public void setVcleTrafficLines(Set<VcleTrafficLine> vcleTrafficLines) {
        this.vcleTrafficLines = vcleTrafficLines;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleMotorChange> getVcleMotorChanges() {
        return this.vcleMotorChanges;
    }
    
    public void setVcleMotorChanges(Set<VcleMotorChange> vcleMotorChanges) {
        this.vcleMotorChanges = vcleMotorChanges;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleVehicleRequireStatusDt> getVcleVehicleRequireStatusDts() {
        return this.vcleVehicleRequireStatusDts;
    }
    
    public void setVcleVehicleRequireStatusDts(Set<VcleVehicleRequireStatusDt> vcleVehicleRequireStatusDts) {
        this.vcleVehicleRequireStatusDts = vcleVehicleRequireStatusDts;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleIssueDocumentMan> getVcleIssueDocumentMans() {
        return this.vcleIssueDocumentMans;
    }
    
    public void setVcleIssueDocumentMans(Set<VcleIssueDocumentMan> vcleIssueDocumentMans) {
        this.vcleIssueDocumentMans = vcleIssueDocumentMans;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<InvoAdvProducerCode> getInvoAdvProducerCodes() {
        return this.invoAdvProducerCodes;
    }
    
    public void setInvoAdvProducerCodes(Set<InvoAdvProducerCode> invoAdvProducerCodes) {
        this.invoAdvProducerCodes = invoAdvProducerCodes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeId")
    public Set<AppSubElemSpecAuth> getAppSubElemSpecAuthsForEmployeeId() {
        return this.appSubElemSpecAuthsForEmployeeId;
    }
    
    public void setAppSubElemSpecAuthsForEmployeeId(Set<AppSubElemSpecAuth> appSubElemSpecAuthsForEmployeeId) {
        this.appSubElemSpecAuthsForEmployeeId = appSubElemSpecAuthsForEmployeeId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleVehicleLicenseDtl> getVcleVehicleLicenseDtls() {
        return this.vcleVehicleLicenseDtls;
    }
    
    public void setVcleVehicleLicenseDtls(Set<VcleVehicleLicenseDtl> vcleVehicleLicenseDtls) {
        this.vcleVehicleLicenseDtls = vcleVehicleLicenseDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeIdAction")
    public Set<AppSubElemSpecAuth> getAppSubElemSpecAuthsForEmployeeIdAction() {
        return this.appSubElemSpecAuthsForEmployeeIdAction;
    }
    
    public void setAppSubElemSpecAuthsForEmployeeIdAction(Set<AppSubElemSpecAuth> appSubElemSpecAuthsForEmployeeIdAction) {
        this.appSubElemSpecAuthsForEmployeeIdAction = appSubElemSpecAuthsForEmployeeIdAction;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<InvoAdvCollectorCode> getInvoAdvCollectorCodes() {
        return this.invoAdvCollectorCodes;
    }
    
    public void setInvoAdvCollectorCodes(Set<InvoAdvCollectorCode> invoAdvCollectorCodes) {
        this.invoAdvCollectorCodes = invoAdvCollectorCodes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeId")
    public Set<AppSubTabSpecAuth> getAppSubTabSpecAuthsForEmployeeId() {
        return this.appSubTabSpecAuthsForEmployeeId;
    }
    
    public void setAppSubTabSpecAuthsForEmployeeId(Set<AppSubTabSpecAuth> appSubTabSpecAuthsForEmployeeId) {
        this.appSubTabSpecAuthsForEmployeeId = appSubTabSpecAuthsForEmployeeId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleTravelExchange> getVcleTravelExchanges() {
        return this.vcleTravelExchanges;
    }
    
    public void setVcleTravelExchanges(Set<VcleTravelExchange> vcleTravelExchanges) {
        this.vcleTravelExchanges = vcleTravelExchanges;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeIdReceive")
    public Set<VcleVehicleLicense> getVcleVehicleLicensesForEmployeeIdReceive() {
        return this.vcleVehicleLicensesForEmployeeIdReceive;
    }
    
    public void setVcleVehicleLicensesForEmployeeIdReceive(Set<VcleVehicleLicense> vcleVehicleLicensesForEmployeeIdReceive) {
        this.vcleVehicleLicensesForEmployeeIdReceive = vcleVehicleLicensesForEmployeeIdReceive;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMaster")
    public Set<VcleRecordMovementJoin> getVcleRecordMovementJoins() {
        return this.vcleRecordMovementJoins;
    }
    
    public void setVcleRecordMovementJoins(Set<VcleRecordMovementJoin> vcleRecordMovementJoins) {
        this.vcleRecordMovementJoins = vcleRecordMovementJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentMasterByEmployeeIdAction")
    public Set<AppSubTabSpecAuth> getAppSubTabSpecAuthsForEmployeeIdAction() {
        return this.appSubTabSpecAuthsForEmployeeIdAction;
    }
    
    public void setAppSubTabSpecAuthsForEmployeeIdAction(Set<AppSubTabSpecAuth> appSubTabSpecAuthsForEmployeeIdAction) {
        this.appSubTabSpecAuthsForEmployeeIdAction = appSubTabSpecAuthsForEmployeeIdAction;
    }




}


