package com.codeator.www._1_2_DB_entities;
// Generated Aug 3, 2021 9:29:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PerOrganizationStructure generated by hbm2java
 */
@Entity
@Table(name="PER_ORGANIZATION_STRUCTURE"
    ,schema="CODEATOR"
    , uniqueConstraints = @UniqueConstraint(columnNames={"LOCATION_CODE", "ORGUNIT_CODE", "ORG_ID"}) 
)
public class PerOrganizationStructure  implements java.io.Serializable {


     private String orgId;
     private PerOrgunitCode perOrgunitCode;
     private String orgCode;
     private String orgName;
     private String parentOrgId;
     private String orgDesc;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private String locationCode;
     private Boolean orgExec;
     private Set<VcleIssueDocumentLiq> vcleIssueDocumentLiqs = new HashSet<VcleIssueDocumentLiq>(0);
     private Set<VcleIssueDocumentMan> vcleIssueDocumentMans = new HashSet<VcleIssueDocumentMan>(0);
     private Set<PerEmploymentMaster> perEmploymentMasters = new HashSet<PerEmploymentMaster>(0);
     private Set<VcleIssueDocumentLin> vcleIssueDocumentLins = new HashSet<VcleIssueDocumentLin>(0);
     private Set<VcleIssueDocumentMain> vcleIssueDocumentMains = new HashSet<VcleIssueDocumentMain>(0);
     private Set<VcleIssueDocumentFin> vcleIssueDocumentFins = new HashSet<VcleIssueDocumentFin>(0);

    public PerOrganizationStructure() {
    }

	
    public PerOrganizationStructure(String orgId, PerOrgunitCode perOrgunitCode, String orgCode, String orgName, String locationCode) {
        this.orgId = orgId;
        this.perOrgunitCode = perOrgunitCode;
        this.orgCode = orgCode;
        this.orgName = orgName;
        this.locationCode = locationCode;
    }
    public PerOrganizationStructure(String orgId, PerOrgunitCode perOrgunitCode, String orgCode, String orgName, String parentOrgId, String orgDesc, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, String locationCode, Boolean orgExec, Set<VcleIssueDocumentLiq> vcleIssueDocumentLiqs, Set<VcleIssueDocumentMan> vcleIssueDocumentMans, Set<PerEmploymentMaster> perEmploymentMasters, Set<VcleIssueDocumentLin> vcleIssueDocumentLins, Set<VcleIssueDocumentMain> vcleIssueDocumentMains, Set<VcleIssueDocumentFin> vcleIssueDocumentFins) {
       this.orgId = orgId;
       this.perOrgunitCode = perOrgunitCode;
       this.orgCode = orgCode;
       this.orgName = orgName;
       this.parentOrgId = parentOrgId;
       this.orgDesc = orgDesc;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.locationCode = locationCode;
       this.orgExec = orgExec;
       this.vcleIssueDocumentLiqs = vcleIssueDocumentLiqs;
       this.vcleIssueDocumentMans = vcleIssueDocumentMans;
       this.perEmploymentMasters = perEmploymentMasters;
       this.vcleIssueDocumentLins = vcleIssueDocumentLins;
       this.vcleIssueDocumentMains = vcleIssueDocumentMains;
       this.vcleIssueDocumentFins = vcleIssueDocumentFins;
    }
   
     @Id 

    
    @Column(name="ORG_ID", unique=true, nullable=false, length=5)
    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ORGUNIT_CODE", nullable=false)
    public PerOrgunitCode getPerOrgunitCode() {
        return this.perOrgunitCode;
    }
    
    public void setPerOrgunitCode(PerOrgunitCode perOrgunitCode) {
        this.perOrgunitCode = perOrgunitCode;
    }

    
    @Column(name="ORG_CODE", nullable=false, length=15)
    public String getOrgCode() {
        return this.orgCode;
    }
    
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    
    @Column(name="ORG_NAME", nullable=false, length=100)
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    
    @Column(name="PARENT_ORG_ID", length=5)
    public String getParentOrgId() {
        return this.parentOrgId;
    }
    
    public void setParentOrgId(String parentOrgId) {
        this.parentOrgId = parentOrgId;
    }

    
    @Column(name="ORG_DESC", length=500)
    public String getOrgDesc() {
        return this.orgDesc;
    }
    
    public void setOrgDesc(String orgDesc) {
        this.orgDesc = orgDesc;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    
    @Column(name="LOCATION_CODE", nullable=false, length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    
    @Column(name="ORG_EXEC", precision=1, scale=0)
    public Boolean getOrgExec() {
        return this.orgExec;
    }
    
    public void setOrgExec(Boolean orgExec) {
        this.orgExec = orgExec;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<VcleIssueDocumentLiq> getVcleIssueDocumentLiqs() {
        return this.vcleIssueDocumentLiqs;
    }
    
    public void setVcleIssueDocumentLiqs(Set<VcleIssueDocumentLiq> vcleIssueDocumentLiqs) {
        this.vcleIssueDocumentLiqs = vcleIssueDocumentLiqs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<VcleIssueDocumentMan> getVcleIssueDocumentMans() {
        return this.vcleIssueDocumentMans;
    }
    
    public void setVcleIssueDocumentMans(Set<VcleIssueDocumentMan> vcleIssueDocumentMans) {
        this.vcleIssueDocumentMans = vcleIssueDocumentMans;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<PerEmploymentMaster> getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(Set<PerEmploymentMaster> perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<VcleIssueDocumentLin> getVcleIssueDocumentLins() {
        return this.vcleIssueDocumentLins;
    }
    
    public void setVcleIssueDocumentLins(Set<VcleIssueDocumentLin> vcleIssueDocumentLins) {
        this.vcleIssueDocumentLins = vcleIssueDocumentLins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<VcleIssueDocumentMain> getVcleIssueDocumentMains() {
        return this.vcleIssueDocumentMains;
    }
    
    public void setVcleIssueDocumentMains(Set<VcleIssueDocumentMain> vcleIssueDocumentMains) {
        this.vcleIssueDocumentMains = vcleIssueDocumentMains;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<VcleIssueDocumentFin> getVcleIssueDocumentFins() {
        return this.vcleIssueDocumentFins;
    }
    
    public void setVcleIssueDocumentFins(Set<VcleIssueDocumentFin> vcleIssueDocumentFins) {
        this.vcleIssueDocumentFins = vcleIssueDocumentFins;
    }




}


