package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerQualClass generated by hbm2java
 */
@Entity
@Table(name="PER_QUAL_CLASS"
    ,schema="CODEATOR"
)
public class PerQualClass  implements java.io.Serializable {


     private String qualClassCode;
     private String qualClassName;
     private byte priorityFlag;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerQualCode> perQualCodes = new HashSet<PerQualCode>(0);
     private Set<PerEmploymentMaster> perEmploymentMasters = new HashSet<PerEmploymentMaster>(0);

    public PerQualClass() {
    }

	
    public PerQualClass(String qualClassCode, String qualClassName, byte priorityFlag) {
        this.qualClassCode = qualClassCode;
        this.qualClassName = qualClassName;
        this.priorityFlag = priorityFlag;
    }
    public PerQualClass(String qualClassCode, String qualClassName, byte priorityFlag, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerQualCode> perQualCodes, Set<PerEmploymentMaster> perEmploymentMasters) {
       this.qualClassCode = qualClassCode;
       this.qualClassName = qualClassName;
       this.priorityFlag = priorityFlag;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perQualCodes = perQualCodes;
       this.perEmploymentMasters = perEmploymentMasters;
    }
   
     @Id 

    
    @Column(name="QUAL_CLASS_CODE", unique=true, nullable=false, length=2)
    public String getQualClassCode() {
        return this.qualClassCode;
    }
    
    public void setQualClassCode(String qualClassCode) {
        this.qualClassCode = qualClassCode;
    }

    
    @Column(name="QUAL_CLASS_NAME", nullable=false, length=30)
    public String getQualClassName() {
        return this.qualClassName;
    }
    
    public void setQualClassName(String qualClassName) {
        this.qualClassName = qualClassName;
    }

    
    @Column(name="PRIORITY_FLAG", nullable=false, precision=2, scale=0)
    public byte getPriorityFlag() {
        return this.priorityFlag;
    }
    
    public void setPriorityFlag(byte priorityFlag) {
        this.priorityFlag = priorityFlag;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualClass")
    public Set<PerQualCode> getPerQualCodes() {
        return this.perQualCodes;
    }
    
    public void setPerQualCodes(Set<PerQualCode> perQualCodes) {
        this.perQualCodes = perQualCodes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualClass")
    public Set<PerEmploymentMaster> getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(Set<PerEmploymentMaster> perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }




}


