package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerQualCode generated by hbm2java
 */
@Entity
@Table(name="PER_QUAL_CODE"
    ,schema="CODEATOR"
)
public class PerQualCode  implements java.io.Serializable {


     private String qualCode;
     private PerQualClass perQualClass;
     private String qualName;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerEmploymentMaster> perEmploymentMasters = new HashSet<PerEmploymentMaster>(0);

    public PerQualCode() {
    }

	
    public PerQualCode(String qualCode, PerQualClass perQualClass, String qualName) {
        this.qualCode = qualCode;
        this.perQualClass = perQualClass;
        this.qualName = qualName;
    }
    public PerQualCode(String qualCode, PerQualClass perQualClass, String qualName, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerEmploymentMaster> perEmploymentMasters) {
       this.qualCode = qualCode;
       this.perQualClass = perQualClass;
       this.qualName = qualName;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perEmploymentMasters = perEmploymentMasters;
    }
   
     @Id 

    
    @Column(name="QUAL_CODE", unique=true, nullable=false, length=5)
    public String getQualCode() {
        return this.qualCode;
    }
    
    public void setQualCode(String qualCode) {
        this.qualCode = qualCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="QUAL_CLASS_CODE", nullable=false)
    public PerQualClass getPerQualClass() {
        return this.perQualClass;
    }
    
    public void setPerQualClass(PerQualClass perQualClass) {
        this.perQualClass = perQualClass;
    }

    
    @Column(name="QUAL_NAME", nullable=false, length=50)
    public String getQualName() {
        return this.qualName;
    }
    
    public void setQualName(String qualName) {
        this.qualName = qualName;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualCode")
    public Set<PerEmploymentMaster> getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(Set<PerEmploymentMaster> perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }




}


