package com.codeator.www._1_2_DB_entities;
// Generated Sep 11, 2021 5:44:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerSectionOld generated by hbm2java
 */
@Entity
@Table(name="PER_SECTION_OLD"
    ,schema="CODEATOR"
)
public class PerSectionOld  implements java.io.Serializable {


     private int sectionNoOld;
     private String sectionName;
     private Set<PerDeptOld> perDeptOlds = new HashSet<PerDeptOld>(0);

    public PerSectionOld() {
    }

	
    public PerSectionOld(int sectionNoOld, String sectionName) {
        this.sectionNoOld = sectionNoOld;
        this.sectionName = sectionName;
    }
    public PerSectionOld(int sectionNoOld, String sectionName, Set<PerDeptOld> perDeptOlds) {
       this.sectionNoOld = sectionNoOld;
       this.sectionName = sectionName;
       this.perDeptOlds = perDeptOlds;
    }
   
     @Id 

    
    @Column(name="SECTION_NO_OLD", unique=true, nullable=false, precision=5, scale=0)
    public int getSectionNoOld() {
        return this.sectionNoOld;
    }
    
    public void setSectionNoOld(int sectionNoOld) {
        this.sectionNoOld = sectionNoOld;
    }

    
    @Column(name="SECTION_NAME", nullable=false, length=100)
    public String getSectionName() {
        return this.sectionName;
    }
    
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perSectionOld")
    public Set<PerDeptOld> getPerDeptOlds() {
        return this.perDeptOlds;
    }
    
    public void setPerDeptOlds(Set<PerDeptOld> perDeptOlds) {
        this.perDeptOlds = perDeptOlds;
    }




}


