package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 10:16:30 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurContractServiceType generated by hbm2java
 */
@Entity
@Table(name = "PUR_CONTRACT_SERVICE_TYPE",
         schema = "AHRAM"
)
public class PurContractServiceType implements java.io.Serializable {

    private long serviceSeq;
    private PerEmploymentMaster perEmploymentMaster;
    private InvoAccUintDept invoAccUintDept;
    private String serviceCode;
    private String serviceType;
    private String serviceName;
    private Date insertDate;
    private String insertDateTime;
    private Date updateDate;
    private String updateDateTime;
    private Set<PurContractServiceJoin> purContractServiceJoins = new HashSet<PurContractServiceJoin>(0);
    private Set<InvoInvoiceMaster> invoInvoiceMasters = new HashSet<InvoInvoiceMaster>(0);

    public PurContractServiceType() {
    }

    public PurContractServiceType(long serviceSeq, InvoAccUintDept invoAccUintDept, String serviceType) {
        this.serviceSeq = serviceSeq;
        this.invoAccUintDept = invoAccUintDept;
        this.serviceType = serviceType;
    }

    public PurContractServiceType(long serviceSeq, PerEmploymentMaster perEmploymentMaster, InvoAccUintDept invoAccUintDept, String serviceType, String serviceCode, String serviceName, Date insertDate, String insertDateTime, Date updateDate, String updateDateTime, Set<PurContractServiceJoin> purContractServiceJoins, Set<InvoInvoiceMaster> invoInvoiceMasters) {
        this.serviceSeq = serviceSeq;
        this.perEmploymentMaster = perEmploymentMaster;
        this.invoAccUintDept = invoAccUintDept;
        this.serviceType = serviceType;
        this.serviceCode = serviceCode;
        this.serviceName = serviceName;
        this.insertDate = insertDate;
        this.insertDateTime = insertDateTime;
        this.updateDate = updateDate;
        this.updateDateTime = updateDateTime;
        this.purContractServiceJoins = purContractServiceJoins;
        this.invoInvoiceMasters = invoInvoiceMasters;
    }

    @Id

    @Column(name = "SERVICE_SEQ", unique = true, nullable = false, precision = 16, scale = 0)
    public long getServiceSeq() {
        return this.serviceSeq;
    }

    public void setServiceSeq(long serviceSeq) {
        this.serviceSeq = serviceSeq;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }

    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumns({
        @JoinColumn(name = "ACC_UNIT_CODE", referencedColumnName = "ACC_UNIT_CODE")
        , 
        @JoinColumn(name = "DEP_NO_OLD", referencedColumnName = "DEP_NO_OLD", nullable = false)
        , 
        @JoinColumn(name = "SECTION_NO_OLD", referencedColumnName = "SECTION_NO_OLD", nullable = false)})
    public InvoAccUintDept getInvoAccUintDept() {
        return this.invoAccUintDept;
    }

    public void setInvoAccUintDept(InvoAccUintDept invoAccUintDept) {
        this.invoAccUintDept = invoAccUintDept;
    }

    @Column(name = "SERVICE_TYPE", nullable = false, length = 1)
    public String getServiceType() {
        return this.serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }
    
    @Column(name = "SERVICE_CODE", nullable = false, length = 20)
    public String getServiceCode() {
        return this.serviceCode;
    }

    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }

    @Column(name = "SERVICE_NAME", length = 200)
    public String getServiceName() {
        return this.serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "INSERT_DATE", length = 7)
    public Date getInsertDate() {
        return this.insertDate;
    }

    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    @Column(name = "INSERT_DATE_TIME", length = 20)
    public String getInsertDateTime() {
        return this.insertDateTime;
    }

    public void setInsertDateTime(String insertDateTime) {
        this.insertDateTime = insertDateTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "UPDATE_DATE", length = 7)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "UPDATE_DATE_TIME", length = 20)
    public String getUpdateDateTime() {
        return this.updateDateTime;
    }

    public void setUpdateDateTime(String updateDateTime) {
        this.updateDateTime = updateDateTime;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "purContractServiceType")
    public Set<PurContractServiceJoin> getPurContractServiceJoins() {
        return this.purContractServiceJoins;
    }

    public void setPurContractServiceJoins(Set<PurContractServiceJoin> purContractServiceJoins) {
        this.purContractServiceJoins = purContractServiceJoins;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "purContractServiceType")
    public Set<InvoInvoiceMaster> getInvoInvoiceMasters() {
        return this.invoInvoiceMasters;
    }

    public void setInvoInvoiceMasters(Set<InvoInvoiceMaster> invoInvoiceMasters) {
        this.invoInvoiceMasters = invoInvoiceMasters;
    }

}
