package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 10:16:30 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PurContractTitelId generated by hbm2java
 */
@Embeddable
public class PurContractTitelId  implements java.io.Serializable {


     private int titelSp;
     private long depNoOld;
     private int sectionNoOld;
     private String accUnitCode;

    public PurContractTitelId() {
    }

    public PurContractTitelId(int titelSp, long depNoOld, int sectionNoOld, String accUnitCode) {
       this.titelSp = titelSp;
       this.depNoOld = depNoOld;
       this.sectionNoOld = sectionNoOld;
       this.accUnitCode = accUnitCode;
    }
   


    @Column(name="TITEL_SP", nullable=false, precision=9, scale=0)
    public int getTitelSp() {
        return this.titelSp;
    }
    
    public void setTitelSp(int titelSp) {
        this.titelSp = titelSp;
    }


    @Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0)
    public long getDepNoOld() {
        return this.depNoOld;
    }
    
    public void setDepNoOld(long depNoOld) {
        this.depNoOld = depNoOld;
    }


    @Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0)
    public int getSectionNoOld() {
        return this.sectionNoOld;
    }
    
    public void setSectionNoOld(int sectionNoOld) {
        this.sectionNoOld = sectionNoOld;
    }


    @Column(name="ACC_UNIT_CODE", nullable=false, length=2)
    public String getAccUnitCode() {
        return this.accUnitCode;
    }
    
    public void setAccUnitCode(String accUnitCode) {
        this.accUnitCode = accUnitCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PurContractTitelId) ) return false;
		 PurContractTitelId castOther = ( PurContractTitelId ) other; 
         
		 return (this.getTitelSp()==castOther.getTitelSp())
 && (this.getDepNoOld()==castOther.getDepNoOld())
 && (this.getSectionNoOld()==castOther.getSectionNoOld())
 && ( (this.getAccUnitCode()==castOther.getAccUnitCode()) || ( this.getAccUnitCode()!=null && castOther.getAccUnitCode()!=null && this.getAccUnitCode().equals(castOther.getAccUnitCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTitelSp();
         result = 37 * result + (int) this.getDepNoOld();
         result = 37 * result + this.getSectionNoOld();
         result = 37 * result + ( getAccUnitCode() == null ? 0 : this.getAccUnitCode().hashCode() );
         return result;
   }   


}


