package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 10:16:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurContractMaster generated by hbm2java
 */
@Entity
@Table(name="PUR_CONTRACT_MASTER"
    ,schema="CODEATOR"
)
public class PurContractMaster  implements java.io.Serializable {


     private PurContractMasterId id;
     private PerEmploymentMaster perEmploymentMaster;
     private PurSuppWork purSuppWork;
     private PurContractTitel purContractTitel;
     private InvoSuppPaymentType invoSuppPaymentType;
     private PurContractPeriodType purContractPeriodType;
     private Date contractDate;
     private BigDecimal contractValue;
     private Date contractFromDate;
     private Date contractToDate;
     private String contractStatus;
     private String contractTax;
     private Integer periodVal;
     private Date contractAlertDate;
     private BigDecimal incRate;
     private String rmrk;
     private Date insertDate;
     private String insertDateTime;
     private Date updateDate;
     private String updateDateTime;
     private Set<PurContractMasterFile> purContractMasterFiles = new HashSet<PurContractMasterFile>(0);
     private Set<PurContractServiceJoin> purContractServiceJoins = new HashSet<PurContractServiceJoin>(0);
     private Set<PurContractMasterDtl> purContractMasterDtls = new HashSet<PurContractMasterDtl>(0);

    public PurContractMaster() {
    }

	
    public PurContractMaster(PurContractMasterId id, PurSuppWork purSuppWork, PurContractTitel purContractTitel, PurContractPeriodType purContractPeriodType, Date contractDate, BigDecimal contractValue) {
        this.id = id;
        this.purSuppWork = purSuppWork;
        this.purContractTitel = purContractTitel;
        this.purContractPeriodType = purContractPeriodType;
        this.contractDate = contractDate;
        this.contractValue = contractValue;
    }
    public PurContractMaster(PurContractMasterId id, PerEmploymentMaster perEmploymentMaster, PurSuppWork purSuppWork, PurContractTitel purContractTitel, InvoSuppPaymentType invoSuppPaymentType, PurContractPeriodType purContractPeriodType, Date contractDate, BigDecimal contractValue, Date contractFromDate, Date contractToDate, String contractStatus, String contractTax, Integer periodVal, Date contractAlertDate, BigDecimal incRate, String rmrk, Date insertDate, String insertDateTime, Date updateDate, String updateDateTime, Set<PurContractMasterFile> purContractMasterFiles, Set<PurContractServiceJoin> purContractServiceJoins, Set<PurContractMasterDtl> purContractMasterDtls) {
       this.id = id;
       this.perEmploymentMaster = perEmploymentMaster;
       this.purSuppWork = purSuppWork;
       this.purContractTitel = purContractTitel;
       this.invoSuppPaymentType = invoSuppPaymentType;
       this.purContractPeriodType = purContractPeriodType;
       this.contractDate = contractDate;
       this.contractValue = contractValue;
       this.contractFromDate = contractFromDate;
       this.contractToDate = contractToDate;
       this.contractStatus = contractStatus;
       this.contractTax = contractTax;
       this.periodVal = periodVal;
       this.contractAlertDate = contractAlertDate;
       this.incRate = incRate;
       this.rmrk = rmrk;
       this.insertDate = insertDate;
       this.insertDateTime = insertDateTime;
       this.updateDate = updateDate;
       this.updateDateTime = updateDateTime;
       this.purContractMasterFiles = purContractMasterFiles;
       this.purContractServiceJoins = purContractServiceJoins;
       this.purContractMasterDtls = purContractMasterDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="contractSp", column=@Column(name="CONTRACT_SP", nullable=false, precision=16, scale=0) ), 
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="titelSp", column=@Column(name="TITEL_SP", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="accUnitCode", column=@Column(name="ACC_UNIT_CODE", nullable=false, length=2) ) } )
    public PurContractMasterId getId() {
        return this.id;
    }
    
    public void setId(PurContractMasterId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUPP_SEQ", nullable=false)
    public PurSuppWork getPurSuppWork() {
        return this.purSuppWork;
    }
    
    public void setPurSuppWork(PurSuppWork purSuppWork) {
        this.purSuppWork = purSuppWork;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="TITEL_SP", referencedColumnName="TITEL_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE", nullable=false, insertable=false, updatable=false) } )
    public PurContractTitel getPurContractTitel() {
        return this.purContractTitel;
    }
    
    public void setPurContractTitel(PurContractTitel purContractTitel) {
        this.purContractTitel = purContractTitel;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="PAYMENT_TYPE")
    public InvoSuppPaymentType getInvoSuppPaymentType() {
        return this.invoSuppPaymentType;
    }
    
    public void setInvoSuppPaymentType(InvoSuppPaymentType invoSuppPaymentType) {
        this.invoSuppPaymentType = invoSuppPaymentType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="PERIOD_TYPE", nullable=false)
    public PurContractPeriodType getPurContractPeriodType() {
        return this.purContractPeriodType;
    }
    
    public void setPurContractPeriodType(PurContractPeriodType purContractPeriodType) {
        this.purContractPeriodType = purContractPeriodType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CONTRACT_DATE", nullable=false, length=7)
    public Date getContractDate() {
        return this.contractDate;
    }
    
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    
    @Column(name="CONTRACT_VALUE", nullable=false, precision=11)
    public BigDecimal getContractValue() {
        return this.contractValue;
    }
    
    public void setContractValue(BigDecimal contractValue) {
        this.contractValue = contractValue;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CONTRACT_FROM_DATE", length=7)
    public Date getContractFromDate() {
        return this.contractFromDate;
    }
    
    public void setContractFromDate(Date contractFromDate) {
        this.contractFromDate = contractFromDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CONTRACT_TO_DATE", length=7)
    public Date getContractToDate() {
        return this.contractToDate;
    }
    
    public void setContractToDate(Date contractToDate) {
        this.contractToDate = contractToDate;
    }

    
    @Column(name="CONTRACT_STATUS", length=1)
    public String getContractStatus() {
        return this.contractStatus;
    }
    
    public void setContractStatus(String contractStatus) {
        this.contractStatus = contractStatus;
    }

    
    @Column(name="CONTRACT_TAX", length=1)
    public String getContractTax() {
        return this.contractTax;
    }
    
    public void setContractTax(String contractTax) {
        this.contractTax = contractTax;
    }

    
    @Column(name="PERIOD_VAL", precision=6, scale=0)
    public Integer getPeriodVal() {
        return this.periodVal;
    }
    
    public void setPeriodVal(Integer periodVal) {
        this.periodVal = periodVal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CONTRACT_ALERT_DATE", length=7)
    public Date getContractAlertDate() {
        return this.contractAlertDate;
    }
    
    public void setContractAlertDate(Date contractAlertDate) {
        this.contractAlertDate = contractAlertDate;
    }

    
    @Column(name="INC_RATE", precision=5)
    public BigDecimal getIncRate() {
        return this.incRate;
    }
    
    public void setIncRate(BigDecimal incRate) {
        this.incRate = incRate;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATE", length=7)
    public Date getInsertDate() {
        return this.insertDate;
    }
    
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    
    @Column(name="INSERT_DATE_TIME", length=20)
    public String getInsertDateTime() {
        return this.insertDateTime;
    }
    
    public void setInsertDateTime(String insertDateTime) {
        this.insertDateTime = insertDateTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_DATE_TIME", length=20)
    public String getUpdateDateTime() {
        return this.updateDateTime;
    }
    
    public void setUpdateDateTime(String updateDateTime) {
        this.updateDateTime = updateDateTime;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purContractMaster")
    public Set<PurContractMasterFile> getPurContractMasterFiles() {
        return this.purContractMasterFiles;
    }
    
    public void setPurContractMasterFiles(Set<PurContractMasterFile> purContractMasterFiles) {
        this.purContractMasterFiles = purContractMasterFiles;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purContractMaster")
    public Set<PurContractServiceJoin> getPurContractServiceJoins() {
        return this.purContractServiceJoins;
    }
    
    public void setPurContractServiceJoins(Set<PurContractServiceJoin> purContractServiceJoins) {
        this.purContractServiceJoins = purContractServiceJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purContractMaster")
    public Set<PurContractMasterDtl> getPurContractMasterDtls() {
        return this.purContractMasterDtls;
    }
    
    public void setPurContractMasterDtls(Set<PurContractMasterDtl> purContractMasterDtls) {
        this.purContractMasterDtls = purContractMasterDtls;
    }




}


