package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 10:16:30 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PurContractMasterFileBand generated by hbm2java
 */
@Entity
@Table(name="PUR_CONTRACT_MASTER_FILE_BAND"
    ,schema="CODEATOR"
)
public class PurContractMasterFileBand  implements java.io.Serializable {


     private PurContractMasterFileBandId id;
     private PurContractMasterFile purContractMasterFile;
     private String bandName;
     private String bandContent;

    public PurContractMasterFileBand() {
    }

	
    public PurContractMasterFileBand(PurContractMasterFileBandId id, PurContractMasterFile purContractMasterFile) {
        this.id = id;
        this.purContractMasterFile = purContractMasterFile;
    }
    public PurContractMasterFileBand(PurContractMasterFileBandId id, PurContractMasterFile purContractMasterFile, String bandName, String bandContent) {
       this.id = id;
       this.purContractMasterFile = purContractMasterFile;
       this.bandName = bandName;
       this.bandContent = bandContent;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="titelSp", column=@Column(name="TITEL_SP", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="fileSp", column=@Column(name="FILE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="contractSp", column=@Column(name="CONTRACT_SP", nullable=false, precision=16, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="bandSp", column=@Column(name="BAND_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="accUnitCode", column=@Column(name="ACC_UNIT_CODE", nullable=false, length=2) ) } )
    public PurContractMasterFileBandId getId() {
        return this.id;
    }
    
    public void setId(PurContractMasterFileBandId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TITEL_SP", referencedColumnName="TITEL_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="CONTRACT_SP", referencedColumnName="CONTRACT_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="FILE_SP", referencedColumnName="FILE_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE", nullable=false, insertable=false, updatable=false) } )
    public PurContractMasterFile getPurContractMasterFile() {
        return this.purContractMasterFile;
    }
    
    public void setPurContractMasterFile(PurContractMasterFile purContractMasterFile) {
        this.purContractMasterFile = purContractMasterFile;
    }

    
    @Column(name="BAND_NAME", length=75)
    public String getBandName() {
        return this.bandName;
    }
    
    public void setBandName(String bandName) {
        this.bandName = bandName;
    }

    
    @Column(name="BAND_CONTENT", length=400)
    public String getBandContent() {
        return this.bandContent;
    }
    
    public void setBandContent(String bandContent) {
        this.bandContent = bandContent;
    }




}


