package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 10:16:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PurContractPeriodType generated by hbm2java
 */
@Entity
@Table(name="PUR_CONTRACT_PERIOD_TYPE"
    ,schema="CODEATOR"
)
public class PurContractPeriodType  implements java.io.Serializable {


     private byte periodType;
     private String periodName;
     private Integer periodVal;
     private Integer periodValAlert;
     private Byte periodValSplit;
     private Set<PurContractMaster> purContractMasters = new HashSet<PurContractMaster>(0);

    public PurContractPeriodType() {
    }

	
    public PurContractPeriodType(byte periodType) {
        this.periodType = periodType;
    }
    public PurContractPeriodType(byte periodType, String periodName, Integer periodVal, Integer periodValAlert, Byte periodValSplit, Set<PurContractMaster> purContractMasters) {
       this.periodType = periodType;
       this.periodName = periodName;
       this.periodVal = periodVal;
       this.periodValAlert = periodValAlert;
       this.periodValSplit = periodValSplit;
       this.purContractMasters = purContractMasters;
    }
   
     @Id 

    
    @Column(name="PERIOD_TYPE", unique=true, nullable=false, precision=2, scale=0)
    public byte getPeriodType() {
        return this.periodType;
    }
    
    public void setPeriodType(byte periodType) {
        this.periodType = periodType;
    }

    
    @Column(name="PERIOD_NAME", length=75)
    public String getPeriodName() {
        return this.periodName;
    }
    
    public void setPeriodName(String periodName) {
        this.periodName = periodName;
    }

    
    @Column(name="PERIOD_VAL", precision=6, scale=0)
    public Integer getPeriodVal() {
        return this.periodVal;
    }
    
    public void setPeriodVal(Integer periodVal) {
        this.periodVal = periodVal;
    }

    
    @Column(name="PERIOD_VAL_ALERT", precision=6, scale=0)
    public Integer getPeriodValAlert() {
        return this.periodValAlert;
    }
    
    public void setPeriodValAlert(Integer periodValAlert) {
        this.periodValAlert = periodValAlert;
    }

    
    @Column(name="PERIOD_VAL_SPLIT", precision=2, scale=0)
    public Byte getPeriodValSplit() {
        return this.periodValSplit;
    }
    
    public void setPeriodValSplit(Byte periodValSplit) {
        this.periodValSplit = periodValSplit;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purContractPeriodType")
    public Set<PurContractMaster> getPurContractMasters() {
        return this.purContractMasters;
    }
    
    public void setPurContractMasters(Set<PurContractMaster> purContractMasters) {
        this.purContractMasters = purContractMasters;
    }




}


