package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 10:16:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PurContractMasterFile generated by hbm2java
 */
@Entity
@Table(name="PUR_CONTRACT_MASTER_FILE"
    ,schema="CODEATOR"
)
public class PurContractMasterFile  implements java.io.Serializable {


     private PurContractMasterFileId id;
     private PurContractMaster purContractMaster;
     private String fileTitle;
     private Integer filePage;
     private byte[] fileImage;
     private Set<PurContractMasterFileBand> purContractMasterFileBands = new HashSet<PurContractMasterFileBand>(0);

    public PurContractMasterFile() {
    }

	
    public PurContractMasterFile(PurContractMasterFileId id, PurContractMaster purContractMaster) {
        this.id = id;
        this.purContractMaster = purContractMaster;
    }
    public PurContractMasterFile(PurContractMasterFileId id, PurContractMaster purContractMaster, String fileTitle, Integer filePage, byte[] fileImage, Set<PurContractMasterFileBand> purContractMasterFileBands) {
       this.id = id;
       this.purContractMaster = purContractMaster;
       this.fileTitle = fileTitle;
       this.filePage = filePage;
       this.fileImage = fileImage;
       this.purContractMasterFileBands = purContractMasterFileBands;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="titelSp", column=@Column(name="TITEL_SP", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="contractSp", column=@Column(name="CONTRACT_SP", nullable=false, precision=16, scale=0) ), 
        @AttributeOverride(name="fileSp", column=@Column(name="FILE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="accUnitCode", column=@Column(name="ACC_UNIT_CODE", nullable=false, length=2) ) } )
    public PurContractMasterFileId getId() {
        return this.id;
    }
    
    public void setId(PurContractMasterFileId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="CONTRACT_SP", referencedColumnName="CONTRACT_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TITEL_SP", referencedColumnName="TITEL_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE", nullable=false, insertable=false, updatable=false) } )
    public PurContractMaster getPurContractMaster() {
        return this.purContractMaster;
    }
    
    public void setPurContractMaster(PurContractMaster purContractMaster) {
        this.purContractMaster = purContractMaster;
    }

    
    @Column(name="FILE_TITLE", length=200)
    public String getFileTitle() {
        return this.fileTitle;
    }
    
    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle;
    }

    
    @Column(name="FILE_PAGE", precision=6, scale=0)
    public Integer getFilePage() {
        return this.filePage;
    }
    
    public void setFilePage(Integer filePage) {
        this.filePage = filePage;
    }

    
    @Column(name="FILE_IMAGE")
    public byte[] getFileImage() {
        return this.fileImage;
    }
    
    public void setFileImage(byte[] fileImage) {
        this.fileImage = fileImage;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purContractMasterFile")
    public Set<PurContractMasterFileBand> getPurContractMasterFileBands() {
        return this.purContractMasterFileBands;
    }
    
    public void setPurContractMasterFileBands(Set<PurContractMasterFileBand> purContractMasterFileBands) {
        this.purContractMasterFileBands = purContractMasterFileBands;
    }




}


