package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 10:16:30 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PurContractServiceJoin generated by hbm2java
 */
@Entity
@Table(name="PUR_CONTRACT_SERVICE_JOIN"
    ,schema="CODEATOR"
)
public class PurContractServiceJoin  implements java.io.Serializable {


     private PurContractServiceJoinId id;
     private PurContractMaster purContractMaster;
     private PurContractServiceType purContractServiceType;
     private String rmrk;

    public PurContractServiceJoin() {
    }

	
    public PurContractServiceJoin(PurContractServiceJoinId id, PurContractMaster purContractMaster, PurContractServiceType purContractServiceType) {
        this.id = id;
        this.purContractMaster = purContractMaster;
        this.purContractServiceType = purContractServiceType;
    }
    public PurContractServiceJoin(PurContractServiceJoinId id, PurContractMaster purContractMaster, PurContractServiceType purContractServiceType, String rmrk) {
       this.id = id;
       this.purContractMaster = purContractMaster;
       this.purContractServiceType = purContractServiceType;
       this.rmrk = rmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="titelSp", column=@Column(name="TITEL_SP", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="contractSp", column=@Column(name="CONTRACT_SP", nullable=false, precision=16, scale=0) ), 
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="serviceSeq", column=@Column(name="SERVICE_SEQ", nullable=false, precision=16, scale=0) ), 
        @AttributeOverride(name="accUnitCode", column=@Column(name="ACC_UNIT_CODE", nullable=false, length=2) ) } )
    public PurContractServiceJoinId getId() {
        return this.id;
    }
    
    public void setId(PurContractServiceJoinId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="CONTRACT_SP", referencedColumnName="CONTRACT_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TITEL_SP", referencedColumnName="TITEL_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE", nullable=false, insertable=false, updatable=false) } )
    public PurContractMaster getPurContractMaster() {
        return this.purContractMaster;
    }
    
    public void setPurContractMaster(PurContractMaster purContractMaster) {
        this.purContractMaster = purContractMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SERVICE_SEQ", nullable=false, insertable=false, updatable=false)
    public PurContractServiceType getPurContractServiceType() {
        return this.purContractServiceType;
    }
    
    public void setPurContractServiceType(PurContractServiceType purContractServiceType) {
        this.purContractServiceType = purContractServiceType;
    }

    
    @Column(name="RMRK", length=100)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


