package com.codeator.www._1_2_DB_entities;
// Generated Sep 12, 2021 10:16:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PurContractTitel generated by hbm2java
 */
@Entity
@Table(name="PUR_CONTRACT_TITEL"
    ,schema="CODEATOR"
)
public class PurContractTitel  implements java.io.Serializable {


     private PurContractTitelId id;
     private InvoAccUintDept invoAccUintDept;
     private String titelName;
     private Set<PurContractMaster> purContractMasters = new HashSet<PurContractMaster>(0);

    public PurContractTitel() {
    }

	
    public PurContractTitel(PurContractTitelId id, InvoAccUintDept invoAccUintDept) {
        this.id = id;
        this.invoAccUintDept = invoAccUintDept;
    }
    public PurContractTitel(PurContractTitelId id, InvoAccUintDept invoAccUintDept, String titelName, Set<PurContractMaster> purContractMasters) {
       this.id = id;
       this.invoAccUintDept = invoAccUintDept;
       this.titelName = titelName;
       this.purContractMasters = purContractMasters;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="titelSp", column=@Column(name="TITEL_SP", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="accUnitCode", column=@Column(name="ACC_UNIT_CODE", nullable=false, length=2) ) } )
    public PurContractTitelId getId() {
        return this.id;
    }
    
    public void setId(PurContractTitelId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false) } )
    public InvoAccUintDept getInvoAccUintDept() {
        return this.invoAccUintDept;
    }
    
    public void setInvoAccUintDept(InvoAccUintDept invoAccUintDept) {
        this.invoAccUintDept = invoAccUintDept;
    }

    
    @Column(name="TITEL_NAME", length=200)
    public String getTitelName() {
        return this.titelName;
    }
    
    public void setTitelName(String titelName) {
        this.titelName = titelName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purContractTitel")
    public Set<PurContractMaster> getPurContractMasters() {
        return this.purContractMasters;
    }
    
    public void setPurContractMasters(Set<PurContractMaster> purContractMasters) {
        this.purContractMasters = purContractMasters;
    }




}


