package com.codeator.www._1_2_DB_entities;
// Generated Jun 14, 2021 10:15:42 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PurSupplierActivity generated by hbm2java
 */
@Entity
@Table(name="PUR_SUPPLIER_ACTIVITY"
    ,schema="CODEATOR"
)
public class PurSupplierActivity  implements java.io.Serializable {


     private PurSupplierActivityId id;
     private PurSupplier purSupplier;

    public PurSupplierActivity() {
    }

    public PurSupplierActivity(PurSupplierActivityId id, PurSupplier purSupplier) {
       this.id = id;
       this.purSupplier = purSupplier;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="suppCode", column=@Column(name="SUPP_CODE", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="activityCode", column=@Column(name="ACTIVITY_CODE", nullable=false, length=5) ) } )
    public PurSupplierActivityId getId() {
        return this.id;
    }
    
    public void setId(PurSupplierActivityId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUPP_CODE", nullable=false, insertable=false, updatable=false)
    public PurSupplier getPurSupplier() {
        return this.purSupplier;
    }
    
    public void setPurSupplier(PurSupplier purSupplier) {
        this.purSupplier = purSupplier;
    }




}


