package com.codeator.www._1_2_DB_entities;
// Generated Dec 28, 2021 10:11:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurSuppWorkDtl generated by hbm2java
 */
@Entity
@Table(name="PUR_SUPP_WORK_DTL"
    ,schema="CODEATOR"
)
public class PurSuppWorkDtl  implements java.io.Serializable {


     private long suppSeqBr;
     private PerEmploymentMaster perEmploymentMaster;
     private PurSuppWork purSuppWork;
     private PurContractServiceType purContractServiceType;
     private InvoAccUintDept invoAccUintDept;
     private InvoAdvProducerCode invoAdvProducerCode;
     private InvoAdvCollectorCode invoAdvCollectorCode;
     private String suppNameBr;
     private String addressBr;
     private Date insertDate;
     private String insertDateTime;
     private Date updateDate;
     private String updateDateTime;
     private String suppMainFrameCode;
     private Set<InvoInvoiceMaster> invoInvoiceMasters = new HashSet<InvoInvoiceMaster>(0);

    public PurSuppWorkDtl() {
    }

	
    public PurSuppWorkDtl(long suppSeqBr, PurSuppWork purSuppWork) {
        this.suppSeqBr = suppSeqBr;
        this.purSuppWork = purSuppWork;
    }
    public PurSuppWorkDtl(long suppSeqBr, PerEmploymentMaster perEmploymentMaster, PurSuppWork purSuppWork, PurContractServiceType purContractServiceType, InvoAccUintDept invoAccUintDept, InvoAdvProducerCode invoAdvProducerCode, InvoAdvCollectorCode invoAdvCollectorCode, String suppNameBr, String addressBr, Date insertDate, String insertDateTime, Date updateDate, String updateDateTime, String suppMainFrameCode, Set<InvoInvoiceMaster> invoInvoiceMasters) {
       this.suppSeqBr = suppSeqBr;
       this.perEmploymentMaster = perEmploymentMaster;
       this.purSuppWork = purSuppWork;
       this.purContractServiceType = purContractServiceType;
       this.invoAccUintDept = invoAccUintDept;
       this.invoAdvProducerCode = invoAdvProducerCode;
       this.invoAdvCollectorCode = invoAdvCollectorCode;
       this.suppNameBr = suppNameBr;
       this.addressBr = addressBr;
       this.insertDate = insertDate;
       this.insertDateTime = insertDateTime;
       this.updateDate = updateDate;
       this.updateDateTime = updateDateTime;
       this.suppMainFrameCode = suppMainFrameCode;
       this.invoInvoiceMasters = invoInvoiceMasters;
    }
   
     @Id 

    
    @Column(name="SUPP_SEQ_BR", unique=true, nullable=false, precision=16, scale=0)
    public long getSuppSeqBr() {
        return this.suppSeqBr;
    }
    
    public void setSuppSeqBr(long suppSeqBr) {
        this.suppSeqBr = suppSeqBr;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUPP_SEQ", nullable=false)
    public PurSuppWork getPurSuppWork() {
        return this.purSuppWork;
    }
    
    public void setPurSuppWork(PurSuppWork purSuppWork) {
        this.purSuppWork = purSuppWork;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SERVICE_SEQ")
    public PurContractServiceType getPurContractServiceType() {
        return this.purContractServiceType;
    }
    
    public void setPurContractServiceType(PurContractServiceType purContractServiceType) {
        this.purContractServiceType = purContractServiceType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="ACC_UNIT_CODE", referencedColumnName="ACC_UNIT_CODE"), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD"), 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD") } )
    public InvoAccUintDept getInvoAccUintDept() {
        return this.invoAccUintDept;
    }
    
    public void setInvoAccUintDept(InvoAccUintDept invoAccUintDept) {
        this.invoAccUintDept = invoAccUintDept;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ADV_PRODUCER_SEQ")
    public InvoAdvProducerCode getInvoAdvProducerCode() {
        return this.invoAdvProducerCode;
    }
    
    public void setInvoAdvProducerCode(InvoAdvProducerCode invoAdvProducerCode) {
        this.invoAdvProducerCode = invoAdvProducerCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ADV_COLLECTOR_SEQ")
    public InvoAdvCollectorCode getInvoAdvCollectorCode() {
        return this.invoAdvCollectorCode;
    }
    
    public void setInvoAdvCollectorCode(InvoAdvCollectorCode invoAdvCollectorCode) {
        this.invoAdvCollectorCode = invoAdvCollectorCode;
    }

    
    @Column(name="SUPP_NAME_BR", length=100)
    public String getSuppNameBr() {
        return this.suppNameBr;
    }
    
    public void setSuppNameBr(String suppNameBr) {
        this.suppNameBr = suppNameBr;
    }

    
    @Column(name="ADDRESS_BR", length=200)
    public String getAddressBr() {
        return this.addressBr;
    }
    
    public void setAddressBr(String addressBr) {
        this.addressBr = addressBr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATE", length=7)
    public Date getInsertDate() {
        return this.insertDate;
    }
    
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    
    @Column(name="INSERT_DATE_TIME", length=20)
    public String getInsertDateTime() {
        return this.insertDateTime;
    }
    
    public void setInsertDateTime(String insertDateTime) {
        this.insertDateTime = insertDateTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_DATE_TIME", length=20)
    public String getUpdateDateTime() {
        return this.updateDateTime;
    }
    
    public void setUpdateDateTime(String updateDateTime) {
        this.updateDateTime = updateDateTime;
    }

    
    @Column(name="SUPP_MAIN_FRAME_CODE", length=20)
    public String getSuppMainFrameCode() {
        return this.suppMainFrameCode;
    }
    
    public void setSuppMainFrameCode(String suppMainFrameCode) {
        this.suppMainFrameCode = suppMainFrameCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purSuppWorkDtl")
    public Set<InvoInvoiceMaster> getInvoInvoiceMasters() {
        return this.invoInvoiceMasters;
    }
    
    public void setInvoInvoiceMasters(Set<InvoInvoiceMaster> invoInvoiceMasters) {
        this.invoInvoiceMasters = invoInvoiceMasters;
    }




}


