package com.codeator.www._1_2_DB_entities;
// Generated Dec 22, 2021 5:43:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurSuppWork generated by hbm2java
 */
@Entity
@Table(name="PUR_SUPP_WORK"
    ,schema="CODEATOR"
)
public class PurSuppWork  implements java.io.Serializable {


     private long suppSeq;
     private PerGovernorateCode perGovernorateCode;
     private PurSupplier purSupplier;
     private PerCountryCode perCountryCode;
     private PerEmploymentMaster perEmploymentMasterByUpdateEmpId;
     private PerEmploymentMaster perEmploymentMasterByInsertEmpId;
     private String locationCode;
     private String suppNo;
     private String suppName;
     private String suppStateType;
     private String suppStatus;
     private String buildingNum;
     private String address;
     private String identNo;
     private String taxCardNo;
     private String taxFileNo;
     private Date taxDate;
     private Date taxEnddate;
     private Integer taxCardNoNew;
     private String chkUpd;
     private Date insertDate;
     private String insertDateTime;
     private Date updateDate;
     private String updateDateTime;
     private String passportNum;
     private String identType;
     private String chkSource;
     private Set<PurContractMaster> purContractMasters = new HashSet<PurContractMaster>(0);
     private Set<PurSuppWorkDtl> purSuppWorkDtls = new HashSet<PurSuppWorkDtl>(0);
     private Set<InvoInvoiceMaster> invoInvoiceMasters = new HashSet<InvoInvoiceMaster>(0);

    public PurSuppWork() {
    }

	
    public PurSuppWork(long suppSeq) {
        this.suppSeq = suppSeq;
    }
    public PurSuppWork(long suppSeq, PerGovernorateCode perGovernorateCode, PurSupplier purSupplier, PerCountryCode perCountryCode, PerEmploymentMaster perEmploymentMasterByUpdateEmpId, PerEmploymentMaster perEmploymentMasterByInsertEmpId, String locationCode, String suppNo, String suppName, String suppStateType, String suppStatus, String buildingNum, String address, String identNo, String taxCardNo, String taxFileNo, Date taxDate, Date taxEnddate, Integer taxCardNoNew, String chkUpd, Date insertDate, String insertDateTime, Date updateDate, String updateDateTime, String passportNum, String identType, String chkSource, Set<PurContractMaster> purContractMasters, Set<PurSuppWorkDtl> purSuppWorkDtls, Set<InvoInvoiceMaster> invoInvoiceMasters) {
       this.suppSeq = suppSeq;
       this.perGovernorateCode = perGovernorateCode;
       this.purSupplier = purSupplier;
       this.perCountryCode = perCountryCode;
       this.perEmploymentMasterByUpdateEmpId = perEmploymentMasterByUpdateEmpId;
       this.perEmploymentMasterByInsertEmpId = perEmploymentMasterByInsertEmpId;
       this.locationCode = locationCode;
       this.suppNo = suppNo;
       this.suppName = suppName;
       this.suppStateType = suppStateType;
       this.suppStatus = suppStatus;
       this.buildingNum = buildingNum;
       this.address = address;
       this.identNo = identNo;
       this.taxCardNo = taxCardNo;
       this.taxFileNo = taxFileNo;
       this.taxDate = taxDate;
       this.taxEnddate = taxEnddate;
       this.taxCardNoNew = taxCardNoNew;
       this.chkUpd = chkUpd;
       this.insertDate = insertDate;
       this.insertDateTime = insertDateTime;
       this.updateDate = updateDate;
       this.updateDateTime = updateDateTime;
       this.passportNum = passportNum;
       this.identType = identType;
       this.chkSource = chkSource;
       this.purContractMasters = purContractMasters;
       this.purSuppWorkDtls = purSuppWorkDtls;
       this.invoInvoiceMasters = invoInvoiceMasters;
    }
   
     @Id 

    
    @Column(name="SUPP_SEQ", unique=true, nullable=false, precision=16, scale=0)
    public long getSuppSeq() {
        return this.suppSeq;
    }
    
    public void setSuppSeq(long suppSeq) {
        this.suppSeq = suppSeq;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="COUNTRY_CODE", referencedColumnName="COUNTRY_CODE"), 
        @JoinColumn(name="GOV_CODE", referencedColumnName="GOV_CODE") } )
    public PerGovernorateCode getPerGovernorateCode() {
        return this.perGovernorateCode;
    }
    
    public void setPerGovernorateCode(PerGovernorateCode perGovernorateCode) {
        this.perGovernorateCode = perGovernorateCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUPP_CODE")
    public PurSupplier getPurSupplier() {
        return this.purSupplier;
    }
    
    public void setPurSupplier(PurSupplier purSupplier) {
        this.purSupplier = purSupplier;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COUNTRY_CODE_FOREIGN")
    public PerCountryCode getPerCountryCode() {
        return this.perCountryCode;
    }
    
    public void setPerCountryCode(PerCountryCode perCountryCode) {
        this.perCountryCode = perCountryCode;
    }


@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="UPDATE_EMP_ID")
    public PerEmploymentMaster getPerEmploymentMasterByUpdateEmpId() {
        return this.perEmploymentMasterByUpdateEmpId;
    }
    
    public void setPerEmploymentMasterByUpdateEmpId(PerEmploymentMaster perEmploymentMasterByUpdateEmpId) {
        this.perEmploymentMasterByUpdateEmpId = perEmploymentMasterByUpdateEmpId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="INSERT_EMP_ID")
    public PerEmploymentMaster getPerEmploymentMasterByInsertEmpId() {
        return this.perEmploymentMasterByInsertEmpId;
    }
    
    public void setPerEmploymentMasterByInsertEmpId(PerEmploymentMaster perEmploymentMasterByInsertEmpId) {
        this.perEmploymentMasterByInsertEmpId = perEmploymentMasterByInsertEmpId;
    }

    
    @Column(name="LOCATION_CODE", length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    
    @Column(name="SUPP_NO", length=10)
    public String getSuppNo() {
        return this.suppNo;
    }
    
    public void setSuppNo(String suppNo) {
        this.suppNo = suppNo;
    }

    
    @Column(name="SUPP_NAME", length=100)
    public String getSuppName() {
        return this.suppName;
    }
    
    public void setSuppName(String suppName) {
        this.suppName = suppName;
    }

    
    @Column(name="SUPP_STATE_TYPE", length=1)
    public String getSuppStateType() {
        return this.suppStateType;
    }
    
    public void setSuppStateType(String suppStateType) {
        this.suppStateType = suppStateType;
    }

    
    @Column(name="SUPP_STATUS", length=1)
    public String getSuppStatus() {
        return this.suppStatus;
    }
    
    public void setSuppStatus(String suppStatus) {
        this.suppStatus = suppStatus;
    }

    
    @Column(name="BUILDING_NUM", length=10)
    public String getBuildingNum() {
        return this.buildingNum;
    }
    
    public void setBuildingNum(String buildingNum) {
        this.buildingNum = buildingNum;
    }

    
    @Column(name="ADDRESS", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="IDENT_NO", length=20)
    public String getIdentNo() {
        return this.identNo;
    }
    
    public void setIdentNo(String identNo) {
        this.identNo = identNo;
    }

    
    @Column(name="TAX_CARD_NO", length=30)
    public String getTaxCardNo() {
        return this.taxCardNo;
    }
    
    public void setTaxCardNo(String taxCardNo) {
        this.taxCardNo = taxCardNo;
    }

    
    @Column(name="TAX_FILE_NO", length=30)
    public String getTaxFileNo() {
        return this.taxFileNo;
    }
    
    public void setTaxFileNo(String taxFileNo) {
        this.taxFileNo = taxFileNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TAX_DATE", length=7)
    public Date getTaxDate() {
        return this.taxDate;
    }
    
    public void setTaxDate(Date taxDate) {
        this.taxDate = taxDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TAX_ENDDATE", length=7)
    public Date getTaxEnddate() {
        return this.taxEnddate;
    }
    
    public void setTaxEnddate(Date taxEnddate) {
        this.taxEnddate = taxEnddate;
    }

    
    @Column(name="TAX_CARD_NO_NEW", precision=9, scale=0)
    public Integer getTaxCardNoNew() {
        return this.taxCardNoNew;
    }
    
    public void setTaxCardNoNew(Integer taxCardNoNew) {
        this.taxCardNoNew = taxCardNoNew;
    }

    
    @Column(name="CHK_UPD", length=1)
    public String getChkUpd() {
        return this.chkUpd;
    }
    
    public void setChkUpd(String chkUpd) {
        this.chkUpd = chkUpd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATE", length=7)
    public Date getInsertDate() {
        return this.insertDate;
    }
    
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    
    @Column(name="INSERT_DATE_TIME", length=20)
    public String getInsertDateTime() {
        return this.insertDateTime;
    }
    
    public void setInsertDateTime(String insertDateTime) {
        this.insertDateTime = insertDateTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_DATE_TIME", length=20)
    public String getUpdateDateTime() {
        return this.updateDateTime;
    }
    
    public void setUpdateDateTime(String updateDateTime) {
        this.updateDateTime = updateDateTime;
    }

    
    @Column(name="PASSPORT_NUM", length=20)
    public String getPassportNum() {
        return this.passportNum;
    }
    
    public void setPassportNum(String passportNum) {
        this.passportNum = passportNum;
    }

    
    @Column(name="IDENT_TYPE", length=1)
    public String getIdentType() {
        return this.identType;
    }
    
    public void setIdentType(String identType) {
        this.identType = identType;
    }

    
    @Column(name="CHK_SOURCE", length=1)
    public String getChkSource() {
        return this.chkSource;
    }
    
    public void setChkSource(String chkSource) {
        this.chkSource = chkSource;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purSuppWork")
    public Set<PurContractMaster> getPurContractMasters() {
        return this.purContractMasters;
    }
    
    public void setPurContractMasters(Set<PurContractMaster> purContractMasters) {
        this.purContractMasters = purContractMasters;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purSuppWork")
    public Set<PurSuppWorkDtl> getPurSuppWorkDtls() {
        return this.purSuppWorkDtls;
    }
    
    public void setPurSuppWorkDtls(Set<PurSuppWorkDtl> purSuppWorkDtls) {
        this.purSuppWorkDtls = purSuppWorkDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="purSuppWork")
    public Set<InvoInvoiceMaster> getInvoInvoiceMasters() {
        return this.invoInvoiceMasters;
    }
    
    public void setInvoInvoiceMasters(Set<InvoInvoiceMaster> invoInvoiceMasters) {
        this.invoInvoiceMasters = invoInvoiceMasters;
    }




}


