package com.codeator.www._1_2_DB_entities;
// Generated Mar 21, 2021 6:34:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StoItemCateGroupSec generated by hbm2java
 */
@Entity
@Table(name="STO_ITEM_CATE_GROUP_SEC"
    ,schema="CODEATOR"
)
public class StoItemCateGroupSec  implements java.io.Serializable {


     private StoItemCateGroupSecId id;
     private StoItemCateGroup stoItemCateGroup;
     private String sectionName;
     private Set<StoItemCateGroupSecDtl> stoItemCateGroupSecDtls = new HashSet<StoItemCateGroupSecDtl>(0);

    public StoItemCateGroupSec() {
    }

	
    public StoItemCateGroupSec(StoItemCateGroupSecId id, StoItemCateGroup stoItemCateGroup, String sectionName) {
        this.id = id;
        this.stoItemCateGroup = stoItemCateGroup;
        this.sectionName = sectionName;
    }
    public StoItemCateGroupSec(StoItemCateGroupSecId id, StoItemCateGroup stoItemCateGroup, String sectionName, Set<StoItemCateGroupSecDtl> stoItemCateGroupSecDtls) {
       this.id = id;
       this.stoItemCateGroup = stoItemCateGroup;
       this.sectionName = sectionName;
       this.stoItemCateGroupSecDtls = stoItemCateGroupSecDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="groupCode", column=@Column(name="GROUP_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="cateCode", column=@Column(name="CATE_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="sectionCode", column=@Column(name="SECTION_CODE", nullable=false, length=3) ) } )
    public StoItemCateGroupSecId getId() {
        return this.id;
    }
    
    public void setId(StoItemCateGroupSecId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="CATE_CODE", referencedColumnName="CATE_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="GROUP_CODE", referencedColumnName="GROUP_CODE", nullable=false, insertable=false, updatable=false) } )
    public StoItemCateGroup getStoItemCateGroup() {
        return this.stoItemCateGroup;
    }
    
    public void setStoItemCateGroup(StoItemCateGroup stoItemCateGroup) {
        this.stoItemCateGroup = stoItemCateGroup;
    }

    
    @Column(name="SECTION_NAME", nullable=false, length=200)
    public String getSectionName() {
        return this.sectionName;
    }
    
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="stoItemCateGroupSec")
    public Set<StoItemCateGroupSecDtl> getStoItemCateGroupSecDtls() {
        return this.stoItemCateGroupSecDtls;
    }
    
    public void setStoItemCateGroupSecDtls(Set<StoItemCateGroupSecDtl> stoItemCateGroupSecDtls) {
        this.stoItemCateGroupSecDtls = stoItemCateGroupSecDtls;
    }




}


