package com.codeator.www._1_2_DB_entities;
// Generated Mar 21, 2021 6:34:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StoItemCateGroupSecSer generated by hbm2java
 */
@Entity
@Table(name="STO_ITEM_CATE_GROUP_SEC_SER"
    ,schema="CODEATOR"
)
public class StoItemCateGroupSecSer  implements java.io.Serializable {


     private int itemSerSp;
     private StoItemCateGroupSecDtl stoItemCateGroupSecDtl;
     private String accountNo;
     private String assLocCode;
     private String assGroupNo;
     private String assGroupName;
     private String assAssetNo;
     private String assAssetTitle;
     private String assMachineNo;
     private String assMotorNo;
     private String assShasaihNo;
     private Byte assAssetStatus;
     private Long itemDigital;
     private String cateCode;
     private String rmrk;

    public StoItemCateGroupSecSer() {
    }

	
    public StoItemCateGroupSecSer(int itemSerSp) {
        this.itemSerSp = itemSerSp;
    }
    public StoItemCateGroupSecSer(int itemSerSp, StoItemCateGroupSecDtl stoItemCateGroupSecDtl, String accountNo, String assLocCode, String assGroupNo, String assGroupName, String assAssetNo, String assAssetTitle, String assMachineNo, String assMotorNo, String assShasaihNo, Byte assAssetStatus, Long itemDigital, String cateCode, String rmrk) {
       this.itemSerSp = itemSerSp;
       this.stoItemCateGroupSecDtl = stoItemCateGroupSecDtl;
       this.accountNo = accountNo;
       this.assLocCode = assLocCode;
       this.assGroupNo = assGroupNo;
       this.assGroupName = assGroupName;
       this.assAssetNo = assAssetNo;
       this.assAssetTitle = assAssetTitle;
       this.assMachineNo = assMachineNo;
       this.assMotorNo = assMotorNo;
       this.assShasaihNo = assShasaihNo;
       this.assAssetStatus = assAssetStatus;
       this.itemDigital = itemDigital;
       this.cateCode = cateCode;
       this.rmrk = rmrk;
    }
   
     @Id 

    
    @Column(name="ITEM_SER_SP", unique=true, nullable=false, precision=9, scale=0)
    public int getItemSerSp() {
        return this.itemSerSp;
    }
    
    public void setItemSerSp(int itemSerSp) {
        this.itemSerSp = itemSerSp;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ITEM_NUMBER_SP")
    public StoItemCateGroupSecDtl getStoItemCateGroupSecDtl() {
        return this.stoItemCateGroupSecDtl;
    }
    
    public void setStoItemCateGroupSecDtl(StoItemCateGroupSecDtl stoItemCateGroupSecDtl) {
        this.stoItemCateGroupSecDtl = stoItemCateGroupSecDtl;
    }

    
    @Column(name="ACCOUNT_NO", length=15)
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    
    @Column(name="ASS_LOC_CODE", length=5)
    public String getAssLocCode() {
        return this.assLocCode;
    }
    
    public void setAssLocCode(String assLocCode) {
        this.assLocCode = assLocCode;
    }

    
    @Column(name="ASS_GROUP_NO", length=5)
    public String getAssGroupNo() {
        return this.assGroupNo;
    }
    
    public void setAssGroupNo(String assGroupNo) {
        this.assGroupNo = assGroupNo;
    }

    
    @Column(name="ASS_GROUP_NAME", length=50)
    public String getAssGroupName() {
        return this.assGroupName;
    }
    
    public void setAssGroupName(String assGroupName) {
        this.assGroupName = assGroupName;
    }

    
    @Column(name="ASS_ASSET_NO", length=5)
    public String getAssAssetNo() {
        return this.assAssetNo;
    }
    
    public void setAssAssetNo(String assAssetNo) {
        this.assAssetNo = assAssetNo;
    }

    
    @Column(name="ASS_ASSET_TITLE", length=100)
    public String getAssAssetTitle() {
        return this.assAssetTitle;
    }
    
    public void setAssAssetTitle(String assAssetTitle) {
        this.assAssetTitle = assAssetTitle;
    }

    
    @Column(name="ASS_MACHINE_NO", length=15)
    public String getAssMachineNo() {
        return this.assMachineNo;
    }
    
    public void setAssMachineNo(String assMachineNo) {
        this.assMachineNo = assMachineNo;
    }

    
    @Column(name="ASS_MOTOR_NO", length=15)
    public String getAssMotorNo() {
        return this.assMotorNo;
    }
    
    public void setAssMotorNo(String assMotorNo) {
        this.assMotorNo = assMotorNo;
    }

    
    @Column(name="ASS_SHASAIH_NO", length=15)
    public String getAssShasaihNo() {
        return this.assShasaihNo;
    }
    
    public void setAssShasaihNo(String assShasaihNo) {
        this.assShasaihNo = assShasaihNo;
    }

    
    @Column(name="ASS_ASSET_STATUS", precision=2, scale=0)
    public Byte getAssAssetStatus() {
        return this.assAssetStatus;
    }
    
    public void setAssAssetStatus(Byte assAssetStatus) {
        this.assAssetStatus = assAssetStatus;
    }

    
    @Column(name="ITEM_DIGITAL", precision=11, scale=0)
    public Long getItemDigital() {
        return this.itemDigital;
    }
    
    public void setItemDigital(Long itemDigital) {
        this.itemDigital = itemDigital;
    }

    
    @Column(name="CATE_CODE", length=2)
    public String getCateCode() {
        return this.cateCode;
    }
    
    public void setCateCode(String cateCode) {
        this.cateCode = cateCode;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


