package com.codeator.www._1_2_DB_entities;
// Generated Mar 21, 2021 6:34:02 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StoResponsibilityHistoryDtl generated by hbm2java
 */
@Entity
@Table(name="STO_RESPONSIBILITY_HISTORY_DTL"
    ,schema="CODEATOR"
)
public class StoResponsibilityHistoryDtl  implements java.io.Serializable {


     private StoResponsibilityHistoryDtlId id;
     private StoResponsibilityHistoryEmp stoResponsibilityHistoryEmp;
     private String itemRespDesc;
     private Long itemDigital;
     private String serialNoInc;
     private Boolean respTypeActDtl;
     private String rmrk;

    public StoResponsibilityHistoryDtl() {
    }

	
    public StoResponsibilityHistoryDtl(StoResponsibilityHistoryDtlId id, StoResponsibilityHistoryEmp stoResponsibilityHistoryEmp) {
        this.id = id;
        this.stoResponsibilityHistoryEmp = stoResponsibilityHistoryEmp;
    }
    public StoResponsibilityHistoryDtl(StoResponsibilityHistoryDtlId id, StoResponsibilityHistoryEmp stoResponsibilityHistoryEmp, String itemRespDesc, Long itemDigital, String serialNoInc, Boolean respTypeActDtl, String rmrk) {
       this.id = id;
       this.stoResponsibilityHistoryEmp = stoResponsibilityHistoryEmp;
       this.itemRespDesc = itemRespDesc;
       this.itemDigital = itemDigital;
       this.serialNoInc = serialNoInc;
       this.respTypeActDtl = respTypeActDtl;
       this.rmrk = rmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemDescSp", column=@Column(name="ITEM_DESC_SP", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="respType", column=@Column(name="RESP_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="respSp", column=@Column(name="RESP_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ) } )
    public StoResponsibilityHistoryDtlId getId() {
        return this.id;
    }
    
    public void setId(StoResponsibilityHistoryDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="RESP_SP", referencedColumnName="RESP_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="RESP_TYPE", referencedColumnName="RESP_TYPE", nullable=false, insertable=false, updatable=false) } )
    public StoResponsibilityHistoryEmp getStoResponsibilityHistoryEmp() {
        return this.stoResponsibilityHistoryEmp;
    }
    
    public void setStoResponsibilityHistoryEmp(StoResponsibilityHistoryEmp stoResponsibilityHistoryEmp) {
        this.stoResponsibilityHistoryEmp = stoResponsibilityHistoryEmp;
    }

    
    @Column(name="ITEM_RESP_DESC", length=200)
    public String getItemRespDesc() {
        return this.itemRespDesc;
    }
    
    public void setItemRespDesc(String itemRespDesc) {
        this.itemRespDesc = itemRespDesc;
    }

    
    @Column(name="ITEM_DIGITAL", precision=11, scale=0)
    public Long getItemDigital() {
        return this.itemDigital;
    }
    
    public void setItemDigital(Long itemDigital) {
        this.itemDigital = itemDigital;
    }

    
    @Column(name="SERIAL_NO_INC", length=60)
    public String getSerialNoInc() {
        return this.serialNoInc;
    }
    
    public void setSerialNoInc(String serialNoInc) {
        this.serialNoInc = serialNoInc;
    }

    
    @Column(name="RESP_TYPE_ACT_DTL", precision=1, scale=0)
    public Boolean getRespTypeActDtl() {
        return this.respTypeActDtl;
    }
    
    public void setRespTypeActDtl(Boolean respTypeActDtl) {
        this.respTypeActDtl = respTypeActDtl;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


