package com.codeator.www._1_2_DB_entities;
// Generated Mar 21, 2021 6:34:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoResponsibilityDeptItm generated by hbm2java
 */
@Entity
@Table(name="STO_RESPONSIBILITY_DEPT_ITM"
    ,schema="CODEATOR"
)
public class StoResponsibilityDeptItm  implements java.io.Serializable {


     private StoResponsibilityDeptItmId id;
     private PerEmploymentMaster perEmploymentMaster;
     private String itemName;
     private boolean recvType;
     private Date eznDate;
     private BigDecimal qty;
     private String extEmpName;
     private String itemClass;
     private Long eznNo;
     private Long employeeNo;
     private BigDecimal qtyInitial;
     private BigDecimal sal;
     private BigDecimal val;
     private Boolean statusItem;
     private Short unitCode;
     private Short unitCodeInitial;
     private Date issueDateInitial;
     private Long employeeNoTo;
     private Long employeeIdTo;
     private Long userId;
     private String cateCode;
     private String groupCode;
     private String sectionCode;
     private String itemCode;
     private Long itemDigital;
     private String serialNo;

    public StoResponsibilityDeptItm() {
    }

	
    public StoResponsibilityDeptItm(StoResponsibilityDeptItmId id, String itemName, boolean recvType, Date eznDate, BigDecimal qty) {
        this.id = id;
        this.itemName = itemName;
        this.recvType = recvType;
        this.eznDate = eznDate;
        this.qty = qty;
    }
    public StoResponsibilityDeptItm(StoResponsibilityDeptItmId id, PerEmploymentMaster perEmploymentMaster, String itemName, boolean recvType, Date eznDate, BigDecimal qty, String extEmpName, String itemClass, Long eznNo, Long employeeNo, BigDecimal qtyInitial, BigDecimal sal, BigDecimal val, Boolean statusItem, Short unitCode, Short unitCodeInitial, Date issueDateInitial, Long employeeNoTo, Long employeeIdTo, Long userId, String cateCode, String groupCode, String sectionCode, String itemCode, Long itemDigital, String serialNo) {
       this.id = id;
       this.perEmploymentMaster = perEmploymentMaster;
       this.itemName = itemName;
       this.recvType = recvType;
       this.eznDate = eznDate;
       this.qty = qty;
       this.extEmpName = extEmpName;
       this.itemClass = itemClass;
       this.eznNo = eznNo;
       this.employeeNo = employeeNo;
       this.qtyInitial = qtyInitial;
       this.sal = sal;
       this.val = val;
       this.statusItem = statusItem;
       this.unitCode = unitCode;
       this.unitCodeInitial = unitCodeInitial;
       this.issueDateInitial = issueDateInitial;
       this.employeeNoTo = employeeNoTo;
       this.employeeIdTo = employeeIdTo;
       this.userId = userId;
       this.cateCode = cateCode;
       this.groupCode = groupCode;
       this.sectionCode = sectionCode;
       this.itemCode = itemCode;
       this.itemDigital = itemDigital;
       this.serialNo = serialNo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="respSpHave", column=@Column(name="RESP_SP_HAVE", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="floorSp", column=@Column(name="FLOOR_SP", nullable=false, precision=7, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="respSp", column=@Column(name="RESP_SP", nullable=false, precision=7, scale=0) ) } )
    public StoResponsibilityDeptItmId getId() {
        return this.id;
    }
    
    public void setId(StoResponsibilityDeptItmId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

    
    @Column(name="ITEM_NAME", nullable=false, length=200)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    
    @Column(name="RECV_TYPE", nullable=false, precision=1, scale=0)
    public boolean isRecvType() {
        return this.recvType;
    }
    
    public void setRecvType(boolean recvType) {
        this.recvType = recvType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EZN_DATE", nullable=false, length=7)
    public Date getEznDate() {
        return this.eznDate;
    }
    
    public void setEznDate(Date eznDate) {
        this.eznDate = eznDate;
    }

    
    @Column(name="QTY", nullable=false, precision=11, scale=3)
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    
    @Column(name="EXT_EMP_NAME", length=200)
    public String getExtEmpName() {
        return this.extEmpName;
    }
    
    public void setExtEmpName(String extEmpName) {
        this.extEmpName = extEmpName;
    }

    
    @Column(name="ITEM_CLASS", length=200)
    public String getItemClass() {
        return this.itemClass;
    }
    
    public void setItemClass(String itemClass) {
        this.itemClass = itemClass;
    }

    
    @Column(name="EZN_NO", precision=11, scale=0)
    public Long getEznNo() {
        return this.eznNo;
    }
    
    public void setEznNo(Long eznNo) {
        this.eznNo = eznNo;
    }

    
    @Column(name="EMPLOYEE_NO", precision=10, scale=0)
    public Long getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(Long employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="QTY_INITIAL", precision=11, scale=3)
    public BigDecimal getQtyInitial() {
        return this.qtyInitial;
    }
    
    public void setQtyInitial(BigDecimal qtyInitial) {
        this.qtyInitial = qtyInitial;
    }

    
    @Column(name="SAL", precision=11, scale=3)
    public BigDecimal getSal() {
        return this.sal;
    }
    
    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }

    
    @Column(name="VAL", precision=20, scale=3)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="STATUS_ITEM", precision=1, scale=0)
    public Boolean getStatusItem() {
        return this.statusItem;
    }
    
    public void setStatusItem(Boolean statusItem) {
        this.statusItem = statusItem;
    }

    
    @Column(name="UNIT_CODE", precision=3, scale=0)
    public Short getUnitCode() {
        return this.unitCode;
    }
    
    public void setUnitCode(Short unitCode) {
        this.unitCode = unitCode;
    }

    
    @Column(name="UNIT_CODE_INITIAL", precision=3, scale=0)
    public Short getUnitCodeInitial() {
        return this.unitCodeInitial;
    }
    
    public void setUnitCodeInitial(Short unitCodeInitial) {
        this.unitCodeInitial = unitCodeInitial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DATE_INITIAL", length=7)
    public Date getIssueDateInitial() {
        return this.issueDateInitial;
    }
    
    public void setIssueDateInitial(Date issueDateInitial) {
        this.issueDateInitial = issueDateInitial;
    }

    
    @Column(name="EMPLOYEE_NO_TO", precision=10, scale=0)
    public Long getEmployeeNoTo() {
        return this.employeeNoTo;
    }
    
    public void setEmployeeNoTo(Long employeeNoTo) {
        this.employeeNoTo = employeeNoTo;
    }

    
    @Column(name="EMPLOYEE_ID_TO", precision=10, scale=0)
    public Long getEmployeeIdTo() {
        return this.employeeIdTo;
    }
    
    public void setEmployeeIdTo(Long employeeIdTo) {
        this.employeeIdTo = employeeIdTo;
    }

    
    @Column(name="USER_ID", precision=10, scale=0)
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    
    @Column(name="CATE_CODE", length=2)
    public String getCateCode() {
        return this.cateCode;
    }
    
    public void setCateCode(String cateCode) {
        this.cateCode = cateCode;
    }

    
    @Column(name="GROUP_CODE", length=3)
    public String getGroupCode() {
        return this.groupCode;
    }
    
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    
    @Column(name="SECTION_CODE", length=3)
    public String getSectionCode() {
        return this.sectionCode;
    }
    
    public void setSectionCode(String sectionCode) {
        this.sectionCode = sectionCode;
    }

    
    @Column(name="ITEM_CODE", length=3)
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    
    @Column(name="ITEM_DIGITAL", precision=11, scale=0)
    public Long getItemDigital() {
        return this.itemDigital;
    }
    
    public void setItemDigital(Long itemDigital) {
        this.itemDigital = itemDigital;
    }

    
    @Column(name="SERIAL_NO", length=60)
    public String getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }




}


