package com.codeator.www._1_2_DB_entities;
// Generated Mar 21, 2021 6:34:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoResponsibilityHistoryDel generated by hbm2java
 */
@Entity
@Table(name="STO_RESPONSIBILITY_HISTORY_DEL"
    ,schema="CODEATOR"
)
public class StoResponsibilityHistoryDel  implements java.io.Serializable {


     private StoResponsibilityHistoryDelId id;
     private StoResponsibilityHistoryEmp stoResponsibilityHistoryEmp;
     private boolean delRecvType;
     private Long eznNo;
     private Date eznDate;
     private BigDecimal qty;
     private BigDecimal sal;
     private BigDecimal val;
     private BigDecimal qtyOld;
     private BigDecimal salOld;
     private BigDecimal valOld;
     private Long employeeIdTo;
     private Date issueDateOld;
     private Boolean locType;
     private Boolean delType;

    public StoResponsibilityHistoryDel() {
    }

	
    public StoResponsibilityHistoryDel(StoResponsibilityHistoryDelId id, StoResponsibilityHistoryEmp stoResponsibilityHistoryEmp, boolean delRecvType, Date eznDate, BigDecimal qty) {
        this.id = id;
        this.stoResponsibilityHistoryEmp = stoResponsibilityHistoryEmp;
        this.delRecvType = delRecvType;
        this.eznDate = eznDate;
        this.qty = qty;
    }
    public StoResponsibilityHistoryDel(StoResponsibilityHistoryDelId id, StoResponsibilityHistoryEmp stoResponsibilityHistoryEmp, boolean delRecvType, Long eznNo, Date eznDate, BigDecimal qty, BigDecimal sal, BigDecimal val, BigDecimal qtyOld, BigDecimal salOld, BigDecimal valOld, Long employeeIdTo, Date issueDateOld, Boolean locType, Boolean delType) {
       this.id = id;
       this.stoResponsibilityHistoryEmp = stoResponsibilityHistoryEmp;
       this.delRecvType = delRecvType;
       this.eznNo = eznNo;
       this.eznDate = eznDate;
       this.qty = qty;
       this.sal = sal;
       this.val = val;
       this.qtyOld = qtyOld;
       this.salOld = salOld;
       this.valOld = valOld;
       this.employeeIdTo = employeeIdTo;
       this.issueDateOld = issueDateOld;
       this.locType = locType;
       this.delType = delType;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="respSp", column=@Column(name="RESP_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="respType", column=@Column(name="RESP_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="delSp", column=@Column(name="DEL_SP", nullable=false, precision=3, scale=0) ) } )
    public StoResponsibilityHistoryDelId getId() {
        return this.id;
    }
    
    public void setId(StoResponsibilityHistoryDelId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="RESP_SP", referencedColumnName="RESP_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="RESP_TYPE", referencedColumnName="RESP_TYPE", nullable=false, insertable=false, updatable=false) } )
    public StoResponsibilityHistoryEmp getStoResponsibilityHistoryEmp() {
        return this.stoResponsibilityHistoryEmp;
    }
    
    public void setStoResponsibilityHistoryEmp(StoResponsibilityHistoryEmp stoResponsibilityHistoryEmp) {
        this.stoResponsibilityHistoryEmp = stoResponsibilityHistoryEmp;
    }

    
    @Column(name="DEL_RECV_TYPE", nullable=false, precision=1, scale=0)
    public boolean isDelRecvType() {
        return this.delRecvType;
    }
    
    public void setDelRecvType(boolean delRecvType) {
        this.delRecvType = delRecvType;
    }

    
    @Column(name="EZN_NO", precision=11, scale=0)
    public Long getEznNo() {
        return this.eznNo;
    }
    
    public void setEznNo(Long eznNo) {
        this.eznNo = eznNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EZN_DATE", nullable=false, length=7)
    public Date getEznDate() {
        return this.eznDate;
    }
    
    public void setEznDate(Date eznDate) {
        this.eznDate = eznDate;
    }

    
    @Column(name="QTY", nullable=false, precision=11, scale=3)
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    
    @Column(name="SAL", precision=11, scale=3)
    public BigDecimal getSal() {
        return this.sal;
    }
    
    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }

    
    @Column(name="VAL", precision=11, scale=3)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="QTY_OLD", precision=11, scale=3)
    public BigDecimal getQtyOld() {
        return this.qtyOld;
    }
    
    public void setQtyOld(BigDecimal qtyOld) {
        this.qtyOld = qtyOld;
    }

    
    @Column(name="SAL_OLD", precision=11, scale=3)
    public BigDecimal getSalOld() {
        return this.salOld;
    }
    
    public void setSalOld(BigDecimal salOld) {
        this.salOld = salOld;
    }

    
    @Column(name="VAL_OLD", precision=11, scale=3)
    public BigDecimal getValOld() {
        return this.valOld;
    }
    
    public void setValOld(BigDecimal valOld) {
        this.valOld = valOld;
    }

    
    @Column(name="EMPLOYEE_ID_TO", precision=10, scale=0)
    public Long getEmployeeIdTo() {
        return this.employeeIdTo;
    }
    
    public void setEmployeeIdTo(Long employeeIdTo) {
        this.employeeIdTo = employeeIdTo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DATE_OLD", length=7)
    public Date getIssueDateOld() {
        return this.issueDateOld;
    }
    
    public void setIssueDateOld(Date issueDateOld) {
        this.issueDateOld = issueDateOld;
    }

    
    @Column(name="LOC_TYPE", precision=1, scale=0)
    public Boolean getLocType() {
        return this.locType;
    }
    
    public void setLocType(Boolean locType) {
        this.locType = locType;
    }

    
    @Column(name="DEL_TYPE", precision=1, scale=0)
    public Boolean getDelType() {
        return this.delType;
    }
    
    public void setDelType(Boolean delType) {
        this.delType = delType;
    }




}


