package com.codeator.www._1_2_DB_entities;
// Generated Mar 21, 2021 6:34:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoResponsibilityDept generated by hbm2java
 */
@Entity
@Table(name="STO_RESPONSIBILITY_DEPT"
    ,schema="CODEATOR"
)
public class StoResponsibilityDept  implements java.io.Serializable {


     private StoResponsibilityDeptId id;
     private StoResponsibilityDept stoResponsibilityDept;
     private PerDeptOld perDeptOld;
     private PerEmploymentMaster perEmploymentMaster;
     private PerLocationCode perLocationCode;
     private boolean recvType;
     private Date eznDate;
     private BigDecimal qty;
     private String itemName;
     private Boolean respTypeAct;
     private String itemDesc;
     private String itemClass;
     private Long eznNo;
     private BigDecimal qtyInitial;
     private BigDecimal sal;
     private BigDecimal val;
     private Boolean statusItem;
     private Short unitCode;
     private Short unitCodeInitial;
     private Date issueDateInitial;
     private Long employeeNo;
     private Long employeeNoErr;
     private String itemInclude;
     private Long userId;
     private String cateCode;
     private String groupCode;
     private String sectionCode;
     private String itemCode;
     private String itemDigital;
     private String serialNo;
     private String decisionNo;
     private Date decisionDate;
     private String rmrk;
     private Set<StoResponsibilityDept> stoResponsibilityDepts = new HashSet<StoResponsibilityDept>(0);
     private Set<StoResponsibilityDeptDel> stoResponsibilityDeptDels = new HashSet<StoResponsibilityDeptDel>(0);
     private Set<StoResponsibilityDeptDtl> stoResponsibilityDeptDtls = new HashSet<StoResponsibilityDeptDtl>(0);

    public StoResponsibilityDept() {
    }

	
    public StoResponsibilityDept(StoResponsibilityDeptId id, PerDeptOld perDeptOld, boolean recvType, Date eznDate, BigDecimal qty) {
        this.id = id;
        this.perDeptOld = perDeptOld;
        this.recvType = recvType;
        this.eznDate = eznDate;
        this.qty = qty;
    }
    public StoResponsibilityDept(StoResponsibilityDeptId id, StoResponsibilityDept stoResponsibilityDept, PerDeptOld perDeptOld, PerEmploymentMaster perEmploymentMaster, PerLocationCode perLocationCode, boolean recvType, Date eznDate, BigDecimal qty, String itemName, Boolean respTypeAct, String itemDesc, String itemClass, Long eznNo, BigDecimal qtyInitial, BigDecimal sal, BigDecimal val, Boolean statusItem, Short unitCode, Short unitCodeInitial, Date issueDateInitial, Long employeeNo, Long employeeNoErr, String itemInclude, Long userId, String cateCode, String groupCode, String sectionCode, String itemCode, String itemDigital, String serialNo, String decisionNo, Date decisionDate, String rmrk, Set<StoResponsibilityDept> stoResponsibilityDepts, Set<StoResponsibilityDeptDel> stoResponsibilityDeptDels, Set<StoResponsibilityDeptDtl> stoResponsibilityDeptDtls) {
       this.id = id;
       this.stoResponsibilityDept = stoResponsibilityDept;
       this.perDeptOld = perDeptOld;
       this.perEmploymentMaster = perEmploymentMaster;
       this.perLocationCode = perLocationCode;
       this.recvType = recvType;
       this.eznDate = eznDate;
       this.qty = qty;
       this.itemName = itemName;
       this.respTypeAct = respTypeAct;
       this.itemDesc = itemDesc;
       this.itemClass = itemClass;
       this.eznNo = eznNo;
       this.qtyInitial = qtyInitial;
       this.sal = sal;
       this.val = val;
       this.statusItem = statusItem;
       this.unitCode = unitCode;
       this.unitCodeInitial = unitCodeInitial;
       this.issueDateInitial = issueDateInitial;
       this.employeeNo = employeeNo;
       this.employeeNoErr = employeeNoErr;
       this.itemInclude = itemInclude;
       this.userId = userId;
       this.cateCode = cateCode;
       this.groupCode = groupCode;
       this.sectionCode = sectionCode;
       this.itemCode = itemCode;
       this.itemDigital = itemDigital;
       this.serialNo = serialNo;
       this.decisionNo = decisionNo;
       this.decisionDate = decisionDate;
       this.rmrk = rmrk;
       this.stoResponsibilityDepts = stoResponsibilityDepts;
       this.stoResponsibilityDeptDels = stoResponsibilityDeptDels;
       this.stoResponsibilityDeptDtls = stoResponsibilityDeptDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="respSp", column=@Column(name="RESP_SP", nullable=false, precision=6, scale=0) ) } )
    public StoResponsibilityDeptId getId() {
        return this.id;
    }
    
    public void setId(StoResponsibilityDeptId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD_FROM", referencedColumnName="SECTION_NO_OLD"), 
        @JoinColumn(name="DEP_NO_OLD_FROM", referencedColumnName="DEP_NO_OLD"), 
        @JoinColumn(name="RESP_SP_FROM", referencedColumnName="RESP_SP") } )
    public StoResponsibilityDept getStoResponsibilityDept() {
        return this.stoResponsibilityDept;
    }
    
    public void setStoResponsibilityDept(StoResponsibilityDept stoResponsibilityDept) {
        this.stoResponsibilityDept = stoResponsibilityDept;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false) } )
    public PerDeptOld getPerDeptOld() {
        return this.perDeptOld;
    }
    
    public void setPerDeptOld(PerDeptOld perDeptOld) {
        this.perDeptOld = perDeptOld;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE"), 
        @JoinColumn(name="LOC_CODE", referencedColumnName="LOC_CODE") } )
    public PerLocationCode getPerLocationCode() {
        return this.perLocationCode;
    }
    
    public void setPerLocationCode(PerLocationCode perLocationCode) {
        this.perLocationCode = perLocationCode;
    }

    
    @Column(name="RECV_TYPE", nullable=false, precision=1, scale=0)
    public boolean isRecvType() {
        return this.recvType;
    }
    
    public void setRecvType(boolean recvType) {
        this.recvType = recvType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EZN_DATE", nullable=false, length=7)
    public Date getEznDate() {
        return this.eznDate;
    }
    
    public void setEznDate(Date eznDate) {
        this.eznDate = eznDate;
    }

    
    @Column(name="QTY", nullable=false, precision=11, scale=3)
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    
    @Column(name="ITEM_NAME", length=200)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    
    @Column(name="RESP_TYPE_ACT", precision=1, scale=0)
    public Boolean getRespTypeAct() {
        return this.respTypeAct;
    }
    
    public void setRespTypeAct(Boolean respTypeAct) {
        this.respTypeAct = respTypeAct;
    }

    
    @Column(name="ITEM_DESC", length=200)
    public String getItemDesc() {
        return this.itemDesc;
    }
    
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    
    @Column(name="ITEM_CLASS", length=200)
    public String getItemClass() {
        return this.itemClass;
    }
    
    public void setItemClass(String itemClass) {
        this.itemClass = itemClass;
    }

    
    @Column(name="EZN_NO", precision=11, scale=0)
    public Long getEznNo() {
        return this.eznNo;
    }
    
    public void setEznNo(Long eznNo) {
        this.eznNo = eznNo;
    }

    
    @Column(name="QTY_INITIAL", precision=11, scale=3)
    public BigDecimal getQtyInitial() {
        return this.qtyInitial;
    }
    
    public void setQtyInitial(BigDecimal qtyInitial) {
        this.qtyInitial = qtyInitial;
    }

    
    @Column(name="SAL", precision=11, scale=3)
    public BigDecimal getSal() {
        return this.sal;
    }
    
    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }

    
    @Column(name="VAL", precision=11, scale=3)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="STATUS_ITEM", precision=1, scale=0)
    public Boolean getStatusItem() {
        return this.statusItem;
    }
    
    public void setStatusItem(Boolean statusItem) {
        this.statusItem = statusItem;
    }

    
    @Column(name="UNIT_CODE", precision=3, scale=0)
    public Short getUnitCode() {
        return this.unitCode;
    }
    
    public void setUnitCode(Short unitCode) {
        this.unitCode = unitCode;
    }

    
    @Column(name="UNIT_CODE_INITIAL", precision=3, scale=0)
    public Short getUnitCodeInitial() {
        return this.unitCodeInitial;
    }
    
    public void setUnitCodeInitial(Short unitCodeInitial) {
        this.unitCodeInitial = unitCodeInitial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DATE_INITIAL", length=7)
    public Date getIssueDateInitial() {
        return this.issueDateInitial;
    }
    
    public void setIssueDateInitial(Date issueDateInitial) {
        this.issueDateInitial = issueDateInitial;
    }

    
    @Column(name="EMPLOYEE_NO", precision=10, scale=0)
    public Long getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(Long employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="EMPLOYEE_NO_ERR", precision=10, scale=0)
    public Long getEmployeeNoErr() {
        return this.employeeNoErr;
    }
    
    public void setEmployeeNoErr(Long employeeNoErr) {
        this.employeeNoErr = employeeNoErr;
    }

    
    @Column(name="ITEM_INCLUDE", length=200)
    public String getItemInclude() {
        return this.itemInclude;
    }
    
    public void setItemInclude(String itemInclude) {
        this.itemInclude = itemInclude;
    }

    
    @Column(name="USER_ID", precision=10, scale=0)
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    
    @Column(name="CATE_CODE", length=2)
    public String getCateCode() {
        return this.cateCode;
    }
    
    public void setCateCode(String cateCode) {
        this.cateCode = cateCode;
    }

    
    @Column(name="GROUP_CODE", length=3)
    public String getGroupCode() {
        return this.groupCode;
    }
    
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    
    @Column(name="SECTION_CODE", length=3)
    public String getSectionCode() {
        return this.sectionCode;
    }
    
    public void setSectionCode(String sectionCode) {
        this.sectionCode = sectionCode;
    }

    
    @Column(name="ITEM_CODE", length=3)
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    
    @Column(name="ITEM_DIGITAL", length=11)
    public String getItemDigital() {
        return this.itemDigital;
    }
    
    public void setItemDigital(String itemDigital) {
        this.itemDigital = itemDigital;
    }

    
    @Column(name="SERIAL_NO", length=60)
    public String getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    
    @Column(name="DECISION_NO", length=20)
    public String getDecisionNo() {
        return this.decisionNo;
    }
    
    public void setDecisionNo(String decisionNo) {
        this.decisionNo = decisionNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DECISION_DATE", length=7)
    public Date getDecisionDate() {
        return this.decisionDate;
    }
    
    public void setDecisionDate(Date decisionDate) {
        this.decisionDate = decisionDate;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="stoResponsibilityDept")
    public Set<StoResponsibilityDept> getStoResponsibilityDepts() {
        return this.stoResponsibilityDepts;
    }
    
    public void setStoResponsibilityDepts(Set<StoResponsibilityDept> stoResponsibilityDepts) {
        this.stoResponsibilityDepts = stoResponsibilityDepts;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="stoResponsibilityDept")
    public Set<StoResponsibilityDeptDel> getStoResponsibilityDeptDels() {
        return this.stoResponsibilityDeptDels;
    }
    
    public void setStoResponsibilityDeptDels(Set<StoResponsibilityDeptDel> stoResponsibilityDeptDels) {
        this.stoResponsibilityDeptDels = stoResponsibilityDeptDels;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="stoResponsibilityDept")
    public Set<StoResponsibilityDeptDtl> getStoResponsibilityDeptDtls() {
        return this.stoResponsibilityDeptDtls;
    }
    
    public void setStoResponsibilityDeptDtls(Set<StoResponsibilityDeptDtl> stoResponsibilityDeptDtls) {
        this.stoResponsibilityDeptDtls = stoResponsibilityDeptDtls;
    }




}


