package com.codeator.www._1_2_DB_entities;
// Generated Mar 21, 2021 6:34:02 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StoResponsibilityDeptDtl generated by hbm2java
 */
@Entity
@Table(name="STO_RESPONSIBILITY_DEPT_DTL"
    ,schema="CODEATOR"
)
public class StoResponsibilityDeptDtl  implements java.io.Serializable {


     private StoResponsibilityDeptDtlId id;
     private StoResponsibilityDept stoResponsibilityDept;
     private String itemDigital;
     private String serialNoInc;
     private String itemRespDesc;
     private Boolean respTypeActDtl;
     private String rmrk;

    public StoResponsibilityDeptDtl() {
    }

	
    public StoResponsibilityDeptDtl(StoResponsibilityDeptDtlId id, StoResponsibilityDept stoResponsibilityDept, String itemRespDesc) {
        this.id = id;
        this.stoResponsibilityDept = stoResponsibilityDept;
        this.itemRespDesc = itemRespDesc;
    }
    public StoResponsibilityDeptDtl(StoResponsibilityDeptDtlId id, StoResponsibilityDept stoResponsibilityDept, String itemDigital, String serialNoInc, String itemRespDesc, Boolean respTypeActDtl, String rmrk) {
       this.id = id;
       this.stoResponsibilityDept = stoResponsibilityDept;
       this.itemDigital = itemDigital;
       this.serialNoInc = serialNoInc;
       this.itemRespDesc = itemRespDesc;
       this.respTypeActDtl = respTypeActDtl;
       this.rmrk = rmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="respSp", column=@Column(name="RESP_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="itemDescSp", column=@Column(name="ITEM_DESC_SP", nullable=false, precision=4, scale=0) ) } )
    public StoResponsibilityDeptDtlId getId() {
        return this.id;
    }
    
    public void setId(StoResponsibilityDeptDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="RESP_SP", referencedColumnName="RESP_SP", nullable=false, insertable=false, updatable=false) } )
    public StoResponsibilityDept getStoResponsibilityDept() {
        return this.stoResponsibilityDept;
    }
    
    public void setStoResponsibilityDept(StoResponsibilityDept stoResponsibilityDept) {
        this.stoResponsibilityDept = stoResponsibilityDept;
    }

    
    @Column(name="ITEM_DIGITAL", length=11)
    public String getItemDigital() {
        return this.itemDigital;
    }
    
    public void setItemDigital(String itemDigital) {
        this.itemDigital = itemDigital;
    }

    
    @Column(name="SERIAL_NO_INC", length=60)
    public String getSerialNoInc() {
        return this.serialNoInc;
    }
    
    public void setSerialNoInc(String serialNoInc) {
        this.serialNoInc = serialNoInc;
    }

    
    @Column(name="ITEM_RESP_DESC", nullable=false, length=200)
    public String getItemRespDesc() {
        return this.itemRespDesc;
    }
    
    public void setItemRespDesc(String itemRespDesc) {
        this.itemRespDesc = itemRespDesc;
    }

    
    @Column(name="RESP_TYPE_ACT_DTL", precision=1, scale=0)
    public Boolean getRespTypeActDtl() {
        return this.respTypeActDtl;
    }
    
    public void setRespTypeActDtl(Boolean respTypeActDtl) {
        this.respTypeActDtl = respTypeActDtl;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


