package com.codeator.www._1_2_DB_entities;
// Generated Mar 21, 2021 6:34:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoResponsibilityDeptDel generated by hbm2java
 */
@Entity
@Table(name="STO_RESPONSIBILITY_DEPT_DEL"
    ,schema="CODEATOR"
)
public class StoResponsibilityDeptDel  implements java.io.Serializable {


     private StoResponsibilityDeptDelId id;
     private StoResponsibilityDept stoResponsibilityDept;
     private PerDeptOld perDeptOld;
     private Date issueDateOld;
     private Long eznNo;
     private Date eznDate;
     private Boolean delType;
     private Byte locType;
     private BigDecimal qtyOld;
     private BigDecimal salOld;
     private BigDecimal valOld;
     private BigDecimal qty;
     private BigDecimal val;
     private BigDecimal sal;
     private Boolean respTypeActDel;
     private boolean delRecvType;
     private String rmrkDtl;

    public StoResponsibilityDeptDel() {
    }

	
    public StoResponsibilityDeptDel(StoResponsibilityDeptDelId id, StoResponsibilityDept stoResponsibilityDept, Date eznDate, BigDecimal qty, boolean delRecvType) {
        this.id = id;
        this.stoResponsibilityDept = stoResponsibilityDept;
        this.eznDate = eznDate;
        this.qty = qty;
        this.delRecvType = delRecvType;
    }
    public StoResponsibilityDeptDel(StoResponsibilityDeptDelId id, StoResponsibilityDept stoResponsibilityDept, PerDeptOld perDeptOld, Date issueDateOld, Long eznNo, Date eznDate, Boolean delType, Byte locType, BigDecimal qtyOld, BigDecimal salOld, BigDecimal valOld, BigDecimal qty, BigDecimal val, BigDecimal sal, Boolean respTypeActDel, boolean delRecvType, String rmrkDtl) {
       this.id = id;
       this.stoResponsibilityDept = stoResponsibilityDept;
       this.perDeptOld = perDeptOld;
       this.issueDateOld = issueDateOld;
       this.eznNo = eznNo;
       this.eznDate = eznDate;
       this.delType = delType;
       this.locType = locType;
       this.qtyOld = qtyOld;
       this.salOld = salOld;
       this.valOld = valOld;
       this.qty = qty;
       this.val = val;
       this.sal = sal;
       this.respTypeActDel = respTypeActDel;
       this.delRecvType = delRecvType;
       this.rmrkDtl = rmrkDtl;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="respSp", column=@Column(name="RESP_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="delSp", column=@Column(name="DEL_SP", nullable=false, precision=3, scale=0) ) } )
    public StoResponsibilityDeptDelId getId() {
        return this.id;
    }
    
    public void setId(StoResponsibilityDeptDelId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="RESP_SP", referencedColumnName="RESP_SP", nullable=false, insertable=false, updatable=false) } )
    public StoResponsibilityDept getStoResponsibilityDept() {
        return this.stoResponsibilityDept;
    }
    
    public void setStoResponsibilityDept(StoResponsibilityDept stoResponsibilityDept) {
        this.stoResponsibilityDept = stoResponsibilityDept;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD_TO", referencedColumnName="SECTION_NO_OLD"), 
        @JoinColumn(name="DEP_NO_OLD_TO", referencedColumnName="DEP_NO_OLD") } )
    public PerDeptOld getPerDeptOld() {
        return this.perDeptOld;
    }
    
    public void setPerDeptOld(PerDeptOld perDeptOld) {
        this.perDeptOld = perDeptOld;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DATE_OLD", length=7)
    public Date getIssueDateOld() {
        return this.issueDateOld;
    }
    
    public void setIssueDateOld(Date issueDateOld) {
        this.issueDateOld = issueDateOld;
    }

    
    @Column(name="EZN_NO", precision=11, scale=0)
    public Long getEznNo() {
        return this.eznNo;
    }
    
    public void setEznNo(Long eznNo) {
        this.eznNo = eznNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EZN_DATE", nullable=false, length=7)
    public Date getEznDate() {
        return this.eznDate;
    }
    
    public void setEznDate(Date eznDate) {
        this.eznDate = eznDate;
    }

    
    @Column(name="DEL_TYPE", precision=1, scale=0)
    public Boolean getDelType() {
        return this.delType;
    }
    
    public void setDelType(Boolean delType) {
        this.delType = delType;
    }

    
    @Column(name="LOC_TYPE", precision=2, scale=0)
    public Byte getLocType() {
        return this.locType;
    }
    
    public void setLocType(Byte locType) {
        this.locType = locType;
    }

    
    @Column(name="QTY_OLD", precision=11, scale=3)
    public BigDecimal getQtyOld() {
        return this.qtyOld;
    }
    
    public void setQtyOld(BigDecimal qtyOld) {
        this.qtyOld = qtyOld;
    }

    
    @Column(name="SAL_OLD", precision=11, scale=3)
    public BigDecimal getSalOld() {
        return this.salOld;
    }
    
    public void setSalOld(BigDecimal salOld) {
        this.salOld = salOld;
    }

    
    @Column(name="VAL_OLD", precision=11, scale=3)
    public BigDecimal getValOld() {
        return this.valOld;
    }
    
    public void setValOld(BigDecimal valOld) {
        this.valOld = valOld;
    }

    
    @Column(name="QTY", nullable=false, precision=11, scale=3)
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    
    @Column(name="VAL", precision=11, scale=3)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="SAL", precision=11, scale=3)
    public BigDecimal getSal() {
        return this.sal;
    }
    
    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }

    
    @Column(name="RESP_TYPE_ACT_DEL", precision=1, scale=0)
    public Boolean getRespTypeActDel() {
        return this.respTypeActDel;
    }
    
    public void setRespTypeActDel(Boolean respTypeActDel) {
        this.respTypeActDel = respTypeActDel;
    }

    
    @Column(name="DEL_RECV_TYPE", nullable=false, precision=1, scale=0)
    public boolean isDelRecvType() {
        return this.delRecvType;
    }
    
    public void setDelRecvType(boolean delRecvType) {
        this.delRecvType = delRecvType;
    }

    
    @Column(name="RMRK_DTL", length=200)
    public String getRmrkDtl() {
        return this.rmrkDtl;
    }
    
    public void setRmrkDtl(String rmrkDtl) {
        this.rmrkDtl = rmrkDtl;
    }




}


