package com.codeator.www._1_2_DB_entities;
// Generated Mar 25, 2021 10:52:38 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SupOpertionsTermsTest generated by hbm2java
 */
@Entity
@Table(name="SUP_OPERTIONS_TERMS_TEST"
    ,schema="CODEATOR"
)
public class SupOpertionsTermsTest  implements java.io.Serializable {


     private SupOpertionsTermsTestId id;
     private SupPurchasingOperationsTest supPurchasingOperationsTest;
     private String presentType;
     private String finncialResult;
     private String techResult;
     private String termName;

    public SupOpertionsTermsTest() {
    }

	
    public SupOpertionsTermsTest(SupOpertionsTermsTestId id, SupPurchasingOperationsTest supPurchasingOperationsTest, String termName) {
        this.id = id;
        this.supPurchasingOperationsTest = supPurchasingOperationsTest;
        this.termName = termName;
    }
    public SupOpertionsTermsTest(SupOpertionsTermsTestId id, SupPurchasingOperationsTest supPurchasingOperationsTest, String presentType, String finncialResult, String techResult, String termName) {
       this.id = id;
       this.supPurchasingOperationsTest = supPurchasingOperationsTest;
       this.presentType = presentType;
       this.finncialResult = finncialResult;
       this.techResult = techResult;
       this.termName = termName;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="supplierId", column=@Column(name="SUPPLIER_ID", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="operationId", column=@Column(name="OPERATION_ID", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="termId", column=@Column(name="TERM_ID", nullable=false, precision=6, scale=0) ) } )
    public SupOpertionsTermsTestId getId() {
        return this.id;
    }
    
    public void setId(SupOpertionsTermsTestId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SUPPLIER_ID", referencedColumnName="SUPPLIER_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="OPERATION_ID", referencedColumnName="OPERATION_ID", nullable=false, insertable=false, updatable=false) } )
    public SupPurchasingOperationsTest getSupPurchasingOperationsTest() {
        return this.supPurchasingOperationsTest;
    }
    
    public void setSupPurchasingOperationsTest(SupPurchasingOperationsTest supPurchasingOperationsTest) {
        this.supPurchasingOperationsTest = supPurchasingOperationsTest;
    }

    
    @Column(name="PRESENT_TYPE", length=1000)
    public String getPresentType() {
        return this.presentType;
    }
    
    public void setPresentType(String presentType) {
        this.presentType = presentType;
    }

    
    @Column(name="FINNCIAL_RESULT", length=1000)
    public String getFinncialResult() {
        return this.finncialResult;
    }
    
    public void setFinncialResult(String finncialResult) {
        this.finncialResult = finncialResult;
    }

    
    @Column(name="TECH_RESULT", length=1000)
    public String getTechResult() {
        return this.techResult;
    }
    
    public void setTechResult(String techResult) {
        this.techResult = techResult;
    }

    
    @Column(name="TERM_NAME", nullable=false, length=0)
    public String getTermName() {
        return this.termName;
    }
    
    public void setTermName(String termName) {
        this.termName = termName;
    }




}


