package com.codeator.www._1_2_DB_entities;
// Generated Mar 25, 2021 10:52:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SupPurchasingOperationsTest generated by hbm2java
 */
@Entity
@Table(name="SUP_PURCHASING_OPERATIONS_TEST"
    ,schema="CODEATOR"
)
public class SupPurchasingOperationsTest  implements java.io.Serializable {


     private SupPurchasingOperationsTestId id;
     private SupSuppliersInfoTest supSuppliersInfoTest;
     private String orgName;
     private String postDateTime;
     private String operationName;
     private String operationNo;
     private String operationRegDate;
     private String envelopesOpeneingDate;
     private String operationType;
     private String operationNatural;
     private String opertaionStatus;
     private String adsDate;
     private String partingAvil;
     private String anotherOffersAvil;
     private String evaluationSystem;
     private Long bidBookPrice;
     private String activeIn;
     private Long bidSmallBookPrice;
     private Long primaryInsurance;
     private String discription;
     private String conditions;
     private String notes;
     private Set<SupOpertionsTermsTest> supOpertionsTermsTests = new HashSet<SupOpertionsTermsTest>(0);

    public SupPurchasingOperationsTest() {
    }

	
    public SupPurchasingOperationsTest(SupPurchasingOperationsTestId id, SupSuppliersInfoTest supSuppliersInfoTest) {
        this.id = id;
        this.supSuppliersInfoTest = supSuppliersInfoTest;
    }
    public SupPurchasingOperationsTest(SupPurchasingOperationsTestId id, SupSuppliersInfoTest supSuppliersInfoTest, String orgName, String postDateTime, String operationName, String operationNo, String operationRegDate, String envelopesOpeneingDate, String operationType, String operationNatural, String opertaionStatus, String adsDate, String partingAvil, String anotherOffersAvil, String evaluationSystem, Long bidBookPrice, String activeIn, Long bidSmallBookPrice, Long primaryInsurance, String discription, String conditions, String notes, Set<SupOpertionsTermsTest> supOpertionsTermsTests) {
       this.id = id;
       this.supSuppliersInfoTest = supSuppliersInfoTest;
       this.orgName = orgName;
       this.postDateTime = postDateTime;
       this.operationName = operationName;
       this.operationNo = operationNo;
       this.operationRegDate = operationRegDate;
       this.envelopesOpeneingDate = envelopesOpeneingDate;
       this.operationType = operationType;
       this.operationNatural = operationNatural;
       this.opertaionStatus = opertaionStatus;
       this.adsDate = adsDate;
       this.partingAvil = partingAvil;
       this.anotherOffersAvil = anotherOffersAvil;
       this.evaluationSystem = evaluationSystem;
       this.bidBookPrice = bidBookPrice;
       this.activeIn = activeIn;
       this.bidSmallBookPrice = bidSmallBookPrice;
       this.primaryInsurance = primaryInsurance;
       this.discription = discription;
       this.conditions = conditions;
       this.notes = notes;
       this.supOpertionsTermsTests = supOpertionsTermsTests;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="supplierId", column=@Column(name="SUPPLIER_ID", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="operationId", column=@Column(name="OPERATION_ID", nullable=false, precision=5, scale=0) ) } )
    public SupPurchasingOperationsTestId getId() {
        return this.id;
    }
    
    public void setId(SupPurchasingOperationsTestId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUPPLIER_ID", nullable=false, insertable=false, updatable=false)
    public SupSuppliersInfoTest getSupSuppliersInfoTest() {
        return this.supSuppliersInfoTest;
    }
    
    public void setSupSuppliersInfoTest(SupSuppliersInfoTest supSuppliersInfoTest) {
        this.supSuppliersInfoTest = supSuppliersInfoTest;
    }

    
    @Column(name="ORG_NAME", length=1000)
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    
    @Column(name="POST_DATE_TIME", length=20)
    public String getPostDateTime() {
        return this.postDateTime;
    }
    
    public void setPostDateTime(String postDateTime) {
        this.postDateTime = postDateTime;
    }

    
    @Column(name="OPERATION_NAME", length=0)
    public String getOperationName() {
        return this.operationName;
    }
    
    public void setOperationName(String operationName) {
        this.operationName = operationName;
    }

    
    @Column(name="OPERATION_NO", length=50)
    public String getOperationNo() {
        return this.operationNo;
    }
    
    public void setOperationNo(String operationNo) {
        this.operationNo = operationNo;
    }

    
    @Column(name="OPERATION_REG_DATE", length=20)
    public String getOperationRegDate() {
        return this.operationRegDate;
    }
    
    public void setOperationRegDate(String operationRegDate) {
        this.operationRegDate = operationRegDate;
    }

    
    @Column(name="ENVELOPES_OPENEING_DATE", length=20)
    public String getEnvelopesOpeneingDate() {
        return this.envelopesOpeneingDate;
    }
    
    public void setEnvelopesOpeneingDate(String envelopesOpeneingDate) {
        this.envelopesOpeneingDate = envelopesOpeneingDate;
    }

    
    @Column(name="OPERATION_TYPE", length=500)
    public String getOperationType() {
        return this.operationType;
    }
    
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    
    @Column(name="OPERATION_NATURAL", length=500)
    public String getOperationNatural() {
        return this.operationNatural;
    }
    
    public void setOperationNatural(String operationNatural) {
        this.operationNatural = operationNatural;
    }

    
    @Column(name="OPERTAION_STATUS", length=500)
    public String getOpertaionStatus() {
        return this.opertaionStatus;
    }
    
    public void setOpertaionStatus(String opertaionStatus) {
        this.opertaionStatus = opertaionStatus;
    }

    
    @Column(name="ADS_DATE", length=20)
    public String getAdsDate() {
        return this.adsDate;
    }
    
    public void setAdsDate(String adsDate) {
        this.adsDate = adsDate;
    }

    
    @Column(name="PARTING_AVIL", length=1000)
    public String getPartingAvil() {
        return this.partingAvil;
    }
    
    public void setPartingAvil(String partingAvil) {
        this.partingAvil = partingAvil;
    }

    
    @Column(name="ANOTHER_OFFERS_AVIL", length=500)
    public String getAnotherOffersAvil() {
        return this.anotherOffersAvil;
    }
    
    public void setAnotherOffersAvil(String anotherOffersAvil) {
        this.anotherOffersAvil = anotherOffersAvil;
    }

    
    @Column(name="EVALUATION_SYSTEM", length=500)
    public String getEvaluationSystem() {
        return this.evaluationSystem;
    }
    
    public void setEvaluationSystem(String evaluationSystem) {
        this.evaluationSystem = evaluationSystem;
    }

    
    @Column(name="BID_BOOK_PRICE", precision=12, scale=0)
    public Long getBidBookPrice() {
        return this.bidBookPrice;
    }
    
    public void setBidBookPrice(Long bidBookPrice) {
        this.bidBookPrice = bidBookPrice;
    }

    
    @Column(name="ACTIVE_IN", length=2000)
    public String getActiveIn() {
        return this.activeIn;
    }
    
    public void setActiveIn(String activeIn) {
        this.activeIn = activeIn;
    }

    
    @Column(name="BID_SMALL_BOOK_PRICE", precision=12, scale=0)
    public Long getBidSmallBookPrice() {
        return this.bidSmallBookPrice;
    }
    
    public void setBidSmallBookPrice(Long bidSmallBookPrice) {
        this.bidSmallBookPrice = bidSmallBookPrice;
    }

    
    @Column(name="PRIMARY_INSURANCE", precision=12, scale=0)
    public Long getPrimaryInsurance() {
        return this.primaryInsurance;
    }
    
    public void setPrimaryInsurance(Long primaryInsurance) {
        this.primaryInsurance = primaryInsurance;
    }

    
    @Column(name="DISCRIPTION", length=4000)
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }

    
    @Column(name="CONDITIONS", length=4000)
    public String getConditions() {
        return this.conditions;
    }
    
    public void setConditions(String conditions) {
        this.conditions = conditions;
    }

    
    @Column(name="NOTES", length=4000)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="supPurchasingOperationsTest")
    public Set<SupOpertionsTermsTest> getSupOpertionsTermsTests() {
        return this.supOpertionsTermsTests;
    }
    
    public void setSupOpertionsTermsTests(Set<SupOpertionsTermsTest> supOpertionsTermsTests) {
        this.supOpertionsTermsTests = supOpertionsTermsTests;
    }




}


