package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleIssueDocumentMan generated by hbm2java
 */
@Entity
@Table(name="VCLE_ISSUE_DOCUMENT_MAN"
    ,schema="CODEATOR"
)
public class VcleIssueDocumentMan  implements java.io.Serializable {


     private VcleIssueDocumentManId id;
     private PerOrganizationStructure perOrganizationStructure;
     private PerEmploymentMaster perEmploymentMaster;
     private String currencyCode;
     private Long issueDocSerial;
     private Date issueDocDate;
     private String issueType;
     private BigDecimal editorUserId;
     private String issueDocStatus;
     private BigDecimal vcDeserveValue;
     private BigDecimal vcCutValue;
     private String vcDeserveNoyes;
     private String vcDeserveName;
     private String accountUnitCode;
     private Short vcDeserveDocCount;
     private String vcIssueDocType;
     private Set<VcleVehicleInvoiceMan> vcleVehicleInvoiceMans = new HashSet<VcleVehicleInvoiceMan>(0);
     private Set<VcleIssueDocumentManType> vcleIssueDocumentManTypes = new HashSet<VcleIssueDocumentManType>(0);

    public VcleIssueDocumentMan() {
    }

	
    public VcleIssueDocumentMan(VcleIssueDocumentManId id) {
        this.id = id;
    }
    public VcleIssueDocumentMan(VcleIssueDocumentManId id, PerOrganizationStructure perOrganizationStructure, PerEmploymentMaster perEmploymentMaster, String currencyCode, Long issueDocSerial, Date issueDocDate, String issueType, BigDecimal editorUserId, String issueDocStatus, BigDecimal vcDeserveValue, BigDecimal vcCutValue, String vcDeserveNoyes, String vcDeserveName, String accountUnitCode, Short vcDeserveDocCount, String vcIssueDocType, Set<VcleVehicleInvoiceMan> vcleVehicleInvoiceMans, Set<VcleIssueDocumentManType> vcleIssueDocumentManTypes) {
       this.id = id;
       this.perOrganizationStructure = perOrganizationStructure;
       this.perEmploymentMaster = perEmploymentMaster;
       this.currencyCode = currencyCode;
       this.issueDocSerial = issueDocSerial;
       this.issueDocDate = issueDocDate;
       this.issueType = issueType;
       this.editorUserId = editorUserId;
       this.issueDocStatus = issueDocStatus;
       this.vcDeserveValue = vcDeserveValue;
       this.vcCutValue = vcCutValue;
       this.vcDeserveNoyes = vcDeserveNoyes;
       this.vcDeserveName = vcDeserveName;
       this.accountUnitCode = accountUnitCode;
       this.vcDeserveDocCount = vcDeserveDocCount;
       this.vcIssueDocType = vcIssueDocType;
       this.vcleVehicleInvoiceMans = vcleVehicleInvoiceMans;
       this.vcleIssueDocumentManTypes = vcleIssueDocumentManTypes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalYear", column=@Column(name="FISCAL_YEAR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="vcIssueDocSp", column=@Column(name="VC_ISSUE_DOC_SP", nullable=false, precision=12, scale=0) ) } )
    public VcleIssueDocumentManId getId() {
        return this.id;
    }
    
    public void setId(VcleIssueDocumentManId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ORG_ID")
    public PerOrganizationStructure getPerOrganizationStructure() {
        return this.perOrganizationStructure;
    }
    
    public void setPerOrganizationStructure(PerOrganizationStructure perOrganizationStructure) {
        this.perOrganizationStructure = perOrganizationStructure;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

    
    @Column(name="CURRENCY_CODE", length=4)
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="ISSUE_DOC_SERIAL", precision=12, scale=0)
    public Long getIssueDocSerial() {
        return this.issueDocSerial;
    }
    
    public void setIssueDocSerial(Long issueDocSerial) {
        this.issueDocSerial = issueDocSerial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DOC_DATE", length=7)
    public Date getIssueDocDate() {
        return this.issueDocDate;
    }
    
    public void setIssueDocDate(Date issueDocDate) {
        this.issueDocDate = issueDocDate;
    }

    
    @Column(name="ISSUE_TYPE", length=2)
    public String getIssueType() {
        return this.issueType;
    }
    
    public void setIssueType(String issueType) {
        this.issueType = issueType;
    }

    
    @Column(name="EDITOR_USER_ID", precision=22, scale=0)
    public BigDecimal getEditorUserId() {
        return this.editorUserId;
    }
    
    public void setEditorUserId(BigDecimal editorUserId) {
        this.editorUserId = editorUserId;
    }

    
    @Column(name="ISSUE_DOC_STATUS", length=2)
    public String getIssueDocStatus() {
        return this.issueDocStatus;
    }
    
    public void setIssueDocStatus(String issueDocStatus) {
        this.issueDocStatus = issueDocStatus;
    }

    
    @Column(name="VC_DESERVE_VALUE", precision=16, scale=3)
    public BigDecimal getVcDeserveValue() {
        return this.vcDeserveValue;
    }
    
    public void setVcDeserveValue(BigDecimal vcDeserveValue) {
        this.vcDeserveValue = vcDeserveValue;
    }

    
    @Column(name="VC_CUT_VALUE", precision=16, scale=3)
    public BigDecimal getVcCutValue() {
        return this.vcCutValue;
    }
    
    public void setVcCutValue(BigDecimal vcCutValue) {
        this.vcCutValue = vcCutValue;
    }

    
    @Column(name="VC_DESERVE_NOYES", length=100)
    public String getVcDeserveNoyes() {
        return this.vcDeserveNoyes;
    }
    
    public void setVcDeserveNoyes(String vcDeserveNoyes) {
        this.vcDeserveNoyes = vcDeserveNoyes;
    }

    
    @Column(name="VC_DESERVE_NAME", length=150)
    public String getVcDeserveName() {
        return this.vcDeserveName;
    }
    
    public void setVcDeserveName(String vcDeserveName) {
        this.vcDeserveName = vcDeserveName;
    }

    
    @Column(name="ACCOUNT_UNIT_CODE", length=4)
    public String getAccountUnitCode() {
        return this.accountUnitCode;
    }
    
    public void setAccountUnitCode(String accountUnitCode) {
        this.accountUnitCode = accountUnitCode;
    }

    
    @Column(name="VC_DESERVE_DOC_COUNT", precision=3, scale=0)
    public Short getVcDeserveDocCount() {
        return this.vcDeserveDocCount;
    }
    
    public void setVcDeserveDocCount(Short vcDeserveDocCount) {
        this.vcDeserveDocCount = vcDeserveDocCount;
    }

    
    @Column(name="VC_ISSUE_DOC_TYPE", length=5)
    public String getVcIssueDocType() {
        return this.vcIssueDocType;
    }
    
    public void setVcIssueDocType(String vcIssueDocType) {
        this.vcIssueDocType = vcIssueDocType;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleIssueDocumentMan")
    public Set<VcleVehicleInvoiceMan> getVcleVehicleInvoiceMans() {
        return this.vcleVehicleInvoiceMans;
    }
    
    public void setVcleVehicleInvoiceMans(Set<VcleVehicleInvoiceMan> vcleVehicleInvoiceMans) {
        this.vcleVehicleInvoiceMans = vcleVehicleInvoiceMans;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleIssueDocumentMan")
    public Set<VcleIssueDocumentManType> getVcleIssueDocumentManTypes() {
        return this.vcleIssueDocumentManTypes;
    }
    
    public void setVcleIssueDocumentManTypes(Set<VcleIssueDocumentManType> vcleIssueDocumentManTypes) {
        this.vcleIssueDocumentManTypes = vcleIssueDocumentManTypes;
    }




}


