package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleVehicleTypeUser generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_TYPE_USER"
    ,schema="CODEATOR"
)
public class VcleVehicleTypeUser  implements java.io.Serializable {


     private VcleVehicleTypeUserId id;
     private VcleVehicleType vcleVehicleType;

    public VcleVehicleTypeUser() {
    }

    public VcleVehicleTypeUser(VcleVehicleTypeUserId id, VcleVehicleType vcleVehicleType) {
       this.id = id;
       this.vcleVehicleType = vcleVehicleType;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vcleType", column=@Column(name="VCLE_TYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="userId", column=@Column(name="USER_ID", nullable=false, precision=22, scale=0) ) } )
    public VcleVehicleTypeUserId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleTypeUserId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleVehicleType getVcleVehicleType() {
        return this.vcleVehicleType;
    }
    
    public void setVcleVehicleType(VcleVehicleType vcleVehicleType) {
        this.vcleVehicleType = vcleVehicleType;
    }




}


