package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleVehicleRequireStatus generated by hbm2java
 */
@Entity
@Table(name = "VCLE_VEHICLE_REQUIRE_STATUS",
         schema = "AHRAM"
)
public class VcleVehicleRequireStatus implements java.io.Serializable {

    private byte requireStatus;
    private String requireStatusNm;
    private Byte respType;
    private String requireStatusColor;
    private String requireStatusFafa;
    private Set<VcleVehicleRequire> vcleVehicleRequires = new HashSet<VcleVehicleRequire>(0);
    private Set<VcleVehicleRequireStatusDt> vcleVehicleRequireStatusDts = new HashSet<VcleVehicleRequireStatusDt>(0);

    public VcleVehicleRequireStatus() {
    }

    public VcleVehicleRequireStatus(byte requireStatus) {
        this.requireStatus = requireStatus;
    }

    public VcleVehicleRequireStatus(byte requireStatus, String requireStatusNm, Byte respType, Set<VcleVehicleRequire> vcleVehicleRequires, Set<VcleVehicleRequireStatusDt> vcleVehicleRequireStatusDts) {
        this.requireStatus = requireStatus;
        this.requireStatusNm = requireStatusNm;
        this.respType = respType;
        this.vcleVehicleRequires = vcleVehicleRequires;
        this.vcleVehicleRequireStatusDts = vcleVehicleRequireStatusDts;
    }

    @Id

    @Column(name = "REQUIRE_STATUS", unique = true, nullable = false, precision = 2, scale = 0)
    public byte getRequireStatus() {
        return this.requireStatus;
    }

    public void setRequireStatus(byte requireStatus) {
        this.requireStatus = requireStatus;
    }

    @Column(name = "REQUIRE_STATUS_NM", length = 200)
    public String getRequireStatusNm() {
        return this.requireStatusNm;
    }

    public void setRequireStatusNm(String requireStatusNm) {
        this.requireStatusNm = requireStatusNm;
    }

    @Column(name = "RESP_TYPE", precision = 2, scale = 0)
    public Byte getRespType() {
        return this.respType;
    }

    public void setRespType(Byte respType) {
        this.respType = respType;
    }

    @Column(name = "REQUIRE_STATUS_COLOR", length = 10)
    public String getRequireStatusColor() {
        return this.requireStatusColor;
    }

    public void setRequireStatusColor(String requireStatusColor) {
        this.requireStatusColor = requireStatusColor;
    }
    
    @Column(name = "REQUIRE_STATUS_FAFA", length = 50)
    public String getRequireStatusFafa() {
        return this.requireStatusFafa;
    }

    public void setRequireStatusFafa(String requireStatusFafa) {
        this.requireStatusFafa = requireStatusFafa;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "vcleVehicleRequireStatus")
    public Set<VcleVehicleRequire> getVcleVehicleRequires() {
        return this.vcleVehicleRequires;
    }

    public void setVcleVehicleRequires(Set<VcleVehicleRequire> vcleVehicleRequires) {
        this.vcleVehicleRequires = vcleVehicleRequires;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "vcleVehicleRequireStatus")
    public Set<VcleVehicleRequireStatusDt> getVcleVehicleRequireStatusDts() {
        return this.vcleVehicleRequireStatusDts;
    }

    public void setVcleVehicleRequireStatusDts(Set<VcleVehicleRequireStatusDt> vcleVehicleRequireStatusDts) {
        this.vcleVehicleRequireStatusDts = vcleVehicleRequireStatusDts;
    }

}
