package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleVehicleTransaction generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_TRANSACTION"
    ,schema="CODEATOR"
)
public class VcleVehicleTransaction  implements java.io.Serializable {


     private byte transType;
     private String transName;
     private Set<VcleVehicleTransactionDtl> vcleVehicleTransactionDtls = new HashSet<VcleVehicleTransactionDtl>(0);
     private Set<VcleVehicleResponsible> vcleVehicleResponsibles = new HashSet<VcleVehicleResponsible>(0);

    public VcleVehicleTransaction() {
    }

	
    public VcleVehicleTransaction(byte transType, String transName) {
        this.transType = transType;
        this.transName = transName;
    }
    public VcleVehicleTransaction(byte transType, String transName, Set<VcleVehicleTransactionDtl> vcleVehicleTransactionDtls, Set<VcleVehicleResponsible> vcleVehicleResponsibles) {
       this.transType = transType;
       this.transName = transName;
       this.vcleVehicleTransactionDtls = vcleVehicleTransactionDtls;
       this.vcleVehicleResponsibles = vcleVehicleResponsibles;
    }
   
     @Id 

    
    @Column(name="TRANS_TYPE", unique=true, nullable=false, precision=2, scale=0)
    public byte getTransType() {
        return this.transType;
    }
    
    public void setTransType(byte transType) {
        this.transType = transType;
    }

    
    @Column(name="TRANS_NAME", nullable=false, length=60)
    public String getTransName() {
        return this.transName;
    }
    
    public void setTransName(String transName) {
        this.transName = transName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleTransaction")
    public Set<VcleVehicleTransactionDtl> getVcleVehicleTransactionDtls() {
        return this.vcleVehicleTransactionDtls;
    }
    
    public void setVcleVehicleTransactionDtls(Set<VcleVehicleTransactionDtl> vcleVehicleTransactionDtls) {
        this.vcleVehicleTransactionDtls = vcleVehicleTransactionDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleTransaction")
    public Set<VcleVehicleResponsible> getVcleVehicleResponsibles() {
        return this.vcleVehicleResponsibles;
    }
    
    public void setVcleVehicleResponsibles(Set<VcleVehicleResponsible> vcleVehicleResponsibles) {
        this.vcleVehicleResponsibles = vcleVehicleResponsibles;
    }




}


