package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleVehicleInstructionDtl generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_INSTRUCTION_DTL"
    ,schema="CODEATOR"
)
public class VcleVehicleInstructionDtl  implements java.io.Serializable {


     private VcleVehicleInstructionDtlId id;
     private VcleVehicleInstruction vcleVehicleInstruction;
     private VcleSuspendType vcleSuspendType;
     private String rmrk;
     private String boardAlfa1;
     private Boolean repairSide;
     private String boardAlfa2;
     private String boardAlfa3;
     private Short suspendSeq;
     private Integer boardNumberOld;
     private Integer boardDigital;
     private Set<VcleVehicleInstructionItem> vcleVehicleInstructionItems = new HashSet<VcleVehicleInstructionItem>(0);

    public VcleVehicleInstructionDtl() {
    }

	
    public VcleVehicleInstructionDtl(VcleVehicleInstructionDtlId id, VcleVehicleInstruction vcleVehicleInstruction) {
        this.id = id;
        this.vcleVehicleInstruction = vcleVehicleInstruction;
    }
    public VcleVehicleInstructionDtl(VcleVehicleInstructionDtlId id, VcleVehicleInstruction vcleVehicleInstruction, VcleSuspendType vcleSuspendType, String rmrk, String boardAlfa1, Boolean repairSide, String boardAlfa2, String boardAlfa3, Short suspendSeq, Integer boardNumberOld, Integer boardDigital, Set<VcleVehicleInstructionItem> vcleVehicleInstructionItems) {
       this.id = id;
       this.vcleVehicleInstruction = vcleVehicleInstruction;
       this.vcleSuspendType = vcleSuspendType;
       this.rmrk = rmrk;
       this.boardAlfa1 = boardAlfa1;
       this.repairSide = repairSide;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
       this.suspendSeq = suspendSeq;
       this.boardNumberOld = boardNumberOld;
       this.boardDigital = boardDigital;
       this.vcleVehicleInstructionItems = vcleVehicleInstructionItems;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="workshopeCode", column=@Column(name="WORKSHOPE_CODE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="instructionNo", column=@Column(name="INSTRUCTION_NO", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="suspendSp", column=@Column(name="SUSPEND_SP", nullable=false, precision=6, scale=0) ) } )
    public VcleVehicleInstructionDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleInstructionDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="FISCAL_DATE", referencedColumnName="FISCAL_DATE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="VEHICLE_SP", referencedColumnName="VEHICLE_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="INSTRUCTION_NO", referencedColumnName="INSTRUCTION_NO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="WORKSHOPE_CODE", referencedColumnName="WORKSHOPE_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false) } )
    public VcleVehicleInstruction getVcleVehicleInstruction() {
        return this.vcleVehicleInstruction;
    }
    
    public void setVcleVehicleInstruction(VcleVehicleInstruction vcleVehicleInstruction) {
        this.vcleVehicleInstruction = vcleVehicleInstruction;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUSPEND_CODE")
    public VcleSuspendType getVcleSuspendType() {
        return this.vcleSuspendType;
    }
    
    public void setVcleSuspendType(VcleSuspendType vcleSuspendType) {
        this.vcleSuspendType = vcleSuspendType;
    }

    
    @Column(name="RMRK", length=400)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="REPAIR_SIDE", precision=1, scale=0)
    public Boolean getRepairSide() {
        return this.repairSide;
    }
    
    public void setRepairSide(Boolean repairSide) {
        this.repairSide = repairSide;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    
    @Column(name="SUSPEND_SEQ", precision=4, scale=0)
    public Short getSuspendSeq() {
        return this.suspendSeq;
    }
    
    public void setSuspendSeq(Short suspendSeq) {
        this.suspendSeq = suspendSeq;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleInstructionDtl")
    public Set<VcleVehicleInstructionItem> getVcleVehicleInstructionItems() {
        return this.vcleVehicleInstructionItems;
    }
    
    public void setVcleVehicleInstructionItems(Set<VcleVehicleInstructionItem> vcleVehicleInstructionItems) {
        this.vcleVehicleInstructionItems = vcleVehicleInstructionItems;
    }




}


