package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleNotifyTrans generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_NOTIFY_TRANS"
    ,schema="CODEATOR"
)
public class VcleVehicleNotifyTrans  implements java.io.Serializable {


     private VcleVehicleNotifyTransId id;
     private VcleWorkTypeJoin vcleWorkTypeJoin;
     private VcleVehicleType vcleVehicleType;
     private VcleVehicleMaster vcleVehicleMaster;
     private Long employeeNoDriv;
     private Byte notifyMm;
     private Boolean notifyType;
     private Long distanceN;
     private Short notifyYyyy;
     private Date notifyDate;
     private Integer boardNumberOld;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private Boolean chkLock;
     private String curTime;
     private String rmrk;
     private String boardAlfa3;
     private Date exitDate;
     private Set<VcleVehicleNotifyTransDtl> vcleVehicleNotifyTransDtls = new HashSet<VcleVehicleNotifyTransDtl>(0);

    public VcleVehicleNotifyTrans() {
    }

	
    public VcleVehicleNotifyTrans(VcleVehicleNotifyTransId id, VcleVehicleType vcleVehicleType, VcleVehicleMaster vcleVehicleMaster, Date notifyDate) {
        this.id = id;
        this.vcleVehicleType = vcleVehicleType;
        this.vcleVehicleMaster = vcleVehicleMaster;
        this.notifyDate = notifyDate;
    }
    public VcleVehicleNotifyTrans(VcleVehicleNotifyTransId id, VcleWorkTypeJoin vcleWorkTypeJoin, VcleVehicleType vcleVehicleType, VcleVehicleMaster vcleVehicleMaster, Long employeeNoDriv, Byte notifyMm, Boolean notifyType, Long distanceN, Short notifyYyyy, Date notifyDate, Integer boardNumberOld, Integer boardDigital, String boardAlfa1, String boardAlfa2, Boolean chkLock, String curTime, String rmrk, String boardAlfa3, Date exitDate, Set<VcleVehicleNotifyTransDtl> vcleVehicleNotifyTransDtls) {
       this.id = id;
       this.vcleWorkTypeJoin = vcleWorkTypeJoin;
       this.vcleVehicleType = vcleVehicleType;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.employeeNoDriv = employeeNoDriv;
       this.notifyMm = notifyMm;
       this.notifyType = notifyType;
       this.distanceN = distanceN;
       this.notifyYyyy = notifyYyyy;
       this.notifyDate = notifyDate;
       this.boardNumberOld = boardNumberOld;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.chkLock = chkLock;
       this.curTime = curTime;
       this.rmrk = rmrk;
       this.boardAlfa3 = boardAlfa3;
       this.exitDate = exitDate;
       this.vcleVehicleNotifyTransDtls = vcleVehicleNotifyTransDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="notifySp", column=@Column(name="NOTIFY_SP", nullable=false, precision=9, scale=0) ) } )
    public VcleVehicleNotifyTransId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleNotifyTransId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="WORK_TYPE", referencedColumnName="WORK_TYPE"), 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID") } )
    public VcleWorkTypeJoin getVcleWorkTypeJoin() {
        return this.vcleWorkTypeJoin;
    }
    
    public void setVcleWorkTypeJoin(VcleWorkTypeJoin vcleWorkTypeJoin) {
        this.vcleWorkTypeJoin = vcleWorkTypeJoin;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_TYPE", nullable=false)
    public VcleVehicleType getVcleVehicleType() {
        return this.vcleVehicleType;
    }
    
    public void setVcleVehicleType(VcleVehicleType vcleVehicleType) {
        this.vcleVehicleType = vcleVehicleType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

    
    @Column(name="EMPLOYEE_NO_DRIV", precision=10, scale=0)
    public Long getEmployeeNoDriv() {
        return this.employeeNoDriv;
    }
    
    public void setEmployeeNoDriv(Long employeeNoDriv) {
        this.employeeNoDriv = employeeNoDriv;
    }

    
    @Column(name="NOTIFY_MM", precision=2, scale=0)
    public Byte getNotifyMm() {
        return this.notifyMm;
    }
    
    public void setNotifyMm(Byte notifyMm) {
        this.notifyMm = notifyMm;
    }

    
    @Column(name="NOTIFY_TYPE", precision=1, scale=0)
    public Boolean getNotifyType() {
        return this.notifyType;
    }
    
    public void setNotifyType(Boolean notifyType) {
        this.notifyType = notifyType;
    }

    
    @Column(name="DISTANCE_N", precision=11, scale=0)
    public Long getDistanceN() {
        return this.distanceN;
    }
    
    public void setDistanceN(Long distanceN) {
        this.distanceN = distanceN;
    }

    
    @Column(name="NOTIFY_YYYY", precision=4, scale=0)
    public Short getNotifyYyyy() {
        return this.notifyYyyy;
    }
    
    public void setNotifyYyyy(Short notifyYyyy) {
        this.notifyYyyy = notifyYyyy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NOTIFY_DATE", nullable=false, length=7)
    public Date getNotifyDate() {
        return this.notifyDate;
    }
    
    public void setNotifyDate(Date notifyDate) {
        this.notifyDate = notifyDate;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="CHK_LOCK", precision=1, scale=0)
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }

    
    @Column(name="CUR_TIME", length=5)
    public String getCurTime() {
        return this.curTime;
    }
    
    public void setCurTime(String curTime) {
        this.curTime = curTime;
    }

    
    @Column(name="RMRK", length=400)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXIT_DATE", length=7)
    public Date getExitDate() {
        return this.exitDate;
    }
    
    public void setExitDate(Date exitDate) {
        this.exitDate = exitDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleNotifyTrans")
    public Set<VcleVehicleNotifyTransDtl> getVcleVehicleNotifyTransDtls() {
        return this.vcleVehicleNotifyTransDtls;
    }
    
    public void setVcleVehicleNotifyTransDtls(Set<VcleVehicleNotifyTransDtl> vcleVehicleNotifyTransDtls) {
        this.vcleVehicleNotifyTransDtls = vcleVehicleNotifyTransDtls;
    }




}


