package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleWorkOnSaturdays generated by hbm2java
 */
@Entity
@Table(name="VCLE_WORK_ON_SATURDAYS"
    ,schema="CODEATOR"
)
public class VcleWorkOnSaturdays  implements java.io.Serializable {


     private VcleWorkOnSaturdaysId id;
     private VcleJobType vcleJobType;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private Short val;
     private Boolean chkSuspend;
     private Boolean chkLock;
     private String rmrk;
     private Byte empStartMin;
     private Byte empStartHour;
     private Byte empEndMin;
     private Byte empEndHour;

    public VcleWorkOnSaturdays() {
    }

	
    public VcleWorkOnSaturdays(VcleWorkOnSaturdaysId id, VcleEmployeeMaster vcleEmployeeMaster) {
        this.id = id;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleWorkOnSaturdays(VcleWorkOnSaturdaysId id, VcleJobType vcleJobType, VcleEmployeeMaster vcleEmployeeMaster, Short val, Boolean chkSuspend, Boolean chkLock, String rmrk, Byte empStartMin, Byte empStartHour, Byte empEndMin, Byte empEndHour) {
       this.id = id;
       this.vcleJobType = vcleJobType;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.val = val;
       this.chkSuspend = chkSuspend;
       this.chkLock = chkLock;
       this.rmrk = rmrk;
       this.empStartMin = empStartMin;
       this.empStartHour = empStartHour;
       this.empEndMin = empEndMin;
       this.empEndHour = empEndHour;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="execDay", column=@Column(name="EXEC_DAY", nullable=false, length=7) ) } )
    public VcleWorkOnSaturdaysId getId() {
        return this.id;
    }
    
    public void setId(VcleWorkOnSaturdaysId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="JOB_TYPE")
    public VcleJobType getVcleJobType() {
        return this.vcleJobType;
    }
    
    public void setVcleJobType(VcleJobType vcleJobType) {
        this.vcleJobType = vcleJobType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

    
    @Column(name="VAL", precision=3, scale=0)
    public Short getVal() {
        return this.val;
    }
    
    public void setVal(Short val) {
        this.val = val;
    }

    
    @Column(name="CHK_SUSPEND", precision=1, scale=0)
    public Boolean getChkSuspend() {
        return this.chkSuspend;
    }
    
    public void setChkSuspend(Boolean chkSuspend) {
        this.chkSuspend = chkSuspend;
    }

    
    @Column(name="CHK_LOCK", precision=1, scale=0)
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }

    
    @Column(name="RMRK", length=100)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="EMP_START_MIN", precision=2, scale=0)
    public Byte getEmpStartMin() {
        return this.empStartMin;
    }
    
    public void setEmpStartMin(Byte empStartMin) {
        this.empStartMin = empStartMin;
    }

    
    @Column(name="EMP_START_HOUR", precision=2, scale=0)
    public Byte getEmpStartHour() {
        return this.empStartHour;
    }
    
    public void setEmpStartHour(Byte empStartHour) {
        this.empStartHour = empStartHour;
    }

    
    @Column(name="EMP_END_MIN", precision=2, scale=0)
    public Byte getEmpEndMin() {
        return this.empEndMin;
    }
    
    public void setEmpEndMin(Byte empEndMin) {
        this.empEndMin = empEndMin;
    }

    
    @Column(name="EMP_END_HOUR", precision=2, scale=0)
    public Byte getEmpEndHour() {
        return this.empEndHour;
    }
    
    public void setEmpEndHour(Byte empEndHour) {
        this.empEndHour = empEndHour;
    }




}


