package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VcleFuelBookNumberId generated by hbm2java
 */
@Embeddable
public class VcleFuelBookNumberId  implements java.io.Serializable {


     private Date fiscalDate;
     private boolean fuelType;
     private int bookSp;

    public VcleFuelBookNumberId() {
    }

    public VcleFuelBookNumberId(Date fiscalDate, boolean fuelType, int bookSp) {
       this.fiscalDate = fiscalDate;
       this.fuelType = fuelType;
       this.bookSp = bookSp;
    }
   


    @Column(name="FISCAL_DATE", nullable=false, length=7)
    public Date getFiscalDate() {
        return this.fiscalDate;
    }
    
    public void setFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }


    @Column(name="FUEL_TYPE", nullable=false, precision=1, scale=0)
    public boolean isFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(boolean fuelType) {
        this.fuelType = fuelType;
    }


    @Column(name="BOOK_SP", nullable=false, precision=9, scale=0)
    public int getBookSp() {
        return this.bookSp;
    }
    
    public void setBookSp(int bookSp) {
        this.bookSp = bookSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleFuelBookNumberId) ) return false;
		 VcleFuelBookNumberId castOther = ( VcleFuelBookNumberId ) other; 
         
		 return ( (this.getFiscalDate()==castOther.getFiscalDate()) || ( this.getFiscalDate()!=null && castOther.getFiscalDate()!=null && this.getFiscalDate().equals(castOther.getFiscalDate()) ) )
 && (this.isFuelType()==castOther.isFuelType())
 && (this.getBookSp()==castOther.getBookSp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFiscalDate() == null ? 0 : this.getFiscalDate().hashCode() );
         result = 37 * result + (this.isFuelType()?1:0);
         result = 37 * result + this.getBookSp();
         return result;
   }   


}


