package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleEmployeeVacationDate generated by hbm2java
 */
@Entity
@Table(name="VCLE_EMPLOYEE_VACATION_DATE"
    ,schema="CODEATOR"
)
public class VcleEmployeeVacationDate  implements java.io.Serializable {


     private VcleEmployeeVacationDateId id;
     private VcleEmployeeVacation vcleEmployeeVacation;
     private Boolean chkLock;

    public VcleEmployeeVacationDate() {
    }

	
    public VcleEmployeeVacationDate(VcleEmployeeVacationDateId id, VcleEmployeeVacation vcleEmployeeVacation) {
        this.id = id;
        this.vcleEmployeeVacation = vcleEmployeeVacation;
    }
    public VcleEmployeeVacationDate(VcleEmployeeVacationDateId id, VcleEmployeeVacation vcleEmployeeVacation, Boolean chkLock) {
       this.id = id;
       this.vcleEmployeeVacation = vcleEmployeeVacation;
       this.chkLock = chkLock;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalYear", column=@Column(name="FISCAL_YEAR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="vacStartDate", column=@Column(name="VAC_START_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="vacDate", column=@Column(name="VAC_DATE", nullable=false, length=7) ) } )
    public VcleEmployeeVacationDateId getId() {
        return this.id;
    }
    
    public void setId(VcleEmployeeVacationDateId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="FISCAL_YEAR", referencedColumnName="FISCAL_YEAR", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="VAC_START_DATE", referencedColumnName="VAC_START_DATE", nullable=false, insertable=false, updatable=false) } )
    public VcleEmployeeVacation getVcleEmployeeVacation() {
        return this.vcleEmployeeVacation;
    }
    
    public void setVcleEmployeeVacation(VcleEmployeeVacation vcleEmployeeVacation) {
        this.vcleEmployeeVacation = vcleEmployeeVacation;
    }

    
    @Column(name="CHK_LOCK", precision=1, scale=0)
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }




}


