package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleVehicleModel generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_MODEL"
    ,schema="CODEATOR"
)
public class VcleVehicleModel  implements java.io.Serializable {


     private VcleVehicleModelId id;
     private VcleVehicleType vcleVehicleType;
     private VcleMarkType vcleMarkType;
     private String modelName;
     private Set<VcleVehicleMaster> vcleVehicleMasters = new HashSet<VcleVehicleMaster>(0);

    public VcleVehicleModel() {
    }

	
    public VcleVehicleModel(VcleVehicleModelId id, VcleVehicleType vcleVehicleType, VcleMarkType vcleMarkType, String modelName) {
        this.id = id;
        this.vcleVehicleType = vcleVehicleType;
        this.vcleMarkType = vcleMarkType;
        this.modelName = modelName;
    }
    public VcleVehicleModel(VcleVehicleModelId id, VcleVehicleType vcleVehicleType, VcleMarkType vcleMarkType, String modelName, Set<VcleVehicleMaster> vcleVehicleMasters) {
       this.id = id;
       this.vcleVehicleType = vcleVehicleType;
       this.vcleMarkType = vcleMarkType;
       this.modelName = modelName;
       this.vcleVehicleMasters = vcleVehicleMasters;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vcleType", column=@Column(name="VCLE_TYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="markType", column=@Column(name="MARK_TYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="modelCode", column=@Column(name="MODEL_CODE", nullable=false, precision=6, scale=0) ) } )
    public VcleVehicleModelId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleModelId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleVehicleType getVcleVehicleType() {
        return this.vcleVehicleType;
    }
    
    public void setVcleVehicleType(VcleVehicleType vcleVehicleType) {
        this.vcleVehicleType = vcleVehicleType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="MARK_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleMarkType getVcleMarkType() {
        return this.vcleMarkType;
    }
    
    public void setVcleMarkType(VcleMarkType vcleMarkType) {
        this.vcleMarkType = vcleMarkType;
    }

    
    @Column(name="MODEL_NAME", nullable=false, length=100)
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleModel")
    public Set<VcleVehicleMaster> getVcleVehicleMasters() {
        return this.vcleVehicleMasters;
    }
    
    public void setVcleVehicleMasters(Set<VcleVehicleMaster> vcleVehicleMasters) {
        this.vcleVehicleMasters = vcleVehicleMasters;
    }




}


