package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleInvoiceLiq generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_INVOICE_LIQ"
    ,schema="CODEATOR"
)
public class VcleVehicleInvoiceLiq  implements java.io.Serializable {


     private VcleVehicleInvoiceLiqId id;
     private VcleVehicleMaster vcleVehicleMaster;
     private VcleIssueDocumentLiq vcleIssueDocumentLiq;
     private VcleCostType vcleCostType;
     private Integer invoiceN0;
     private Long userEmployeeNo;
     private String ghaName;
     private BigDecimal invoiceValue;
     private Date issueDocDate;
     private Long issueDocSerial;
     private String boardNumber;
     private Boolean fuelType;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;

    public VcleVehicleInvoiceLiq() {
    }

	
    public VcleVehicleInvoiceLiq(VcleVehicleInvoiceLiqId id, VcleCostType vcleCostType) {
        this.id = id;
        this.vcleCostType = vcleCostType;
    }
    public VcleVehicleInvoiceLiq(VcleVehicleInvoiceLiqId id, VcleVehicleMaster vcleVehicleMaster, VcleIssueDocumentLiq vcleIssueDocumentLiq, VcleCostType vcleCostType, Integer invoiceN0, Long userEmployeeNo, String ghaName, BigDecimal invoiceValue, Date issueDocDate, Long issueDocSerial, String boardNumber, Boolean fuelType, Integer boardDigital, String boardAlfa1, String boardAlfa2, String boardAlfa3) {
       this.id = id;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.vcleIssueDocumentLiq = vcleIssueDocumentLiq;
       this.vcleCostType = vcleCostType;
       this.invoiceN0 = invoiceN0;
       this.userEmployeeNo = userEmployeeNo;
       this.ghaName = ghaName;
       this.invoiceValue = invoiceValue;
       this.issueDocDate = issueDocDate;
       this.issueDocSerial = issueDocSerial;
       this.boardNumber = boardNumber;
       this.fuelType = fuelType;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="invoiceSp", column=@Column(name="INVOICE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="invoiceDate", column=@Column(name="INVOICE_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="currDate", column=@Column(name="CURR_DATE", nullable=false, length=7) ) } )
    public VcleVehicleInvoiceLiqId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleInvoiceLiqId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP")
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="FISCAL_YEAR", referencedColumnName="FISCAL_YEAR"), 
        @JoinColumn(name="VC_ISSUE_DOC_SP", referencedColumnName="VC_ISSUE_DOC_SP") } )
    public VcleIssueDocumentLiq getVcleIssueDocumentLiq() {
        return this.vcleIssueDocumentLiq;
    }
    
    public void setVcleIssueDocumentLiq(VcleIssueDocumentLiq vcleIssueDocumentLiq) {
        this.vcleIssueDocumentLiq = vcleIssueDocumentLiq;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="COST_TYPE", referencedColumnName="COST_TYPE", nullable=false), 
        @JoinColumn(name="COST_CODE", referencedColumnName="COST_CODE", nullable=false) } )
    public VcleCostType getVcleCostType() {
        return this.vcleCostType;
    }
    
    public void setVcleCostType(VcleCostType vcleCostType) {
        this.vcleCostType = vcleCostType;
    }

    
    @Column(name="INVOICE_N0", precision=6, scale=0)
    public Integer getInvoiceN0() {
        return this.invoiceN0;
    }
    
    public void setInvoiceN0(Integer invoiceN0) {
        this.invoiceN0 = invoiceN0;
    }

    
    @Column(name="USER_EMPLOYEE_NO", precision=10, scale=0)
    public Long getUserEmployeeNo() {
        return this.userEmployeeNo;
    }
    
    public void setUserEmployeeNo(Long userEmployeeNo) {
        this.userEmployeeNo = userEmployeeNo;
    }

    
    @Column(name="GHA_NAME", length=200)
    public String getGhaName() {
        return this.ghaName;
    }
    
    public void setGhaName(String ghaName) {
        this.ghaName = ghaName;
    }

    
    @Column(name="INVOICE_VALUE", precision=11)
    public BigDecimal getInvoiceValue() {
        return this.invoiceValue;
    }
    
    public void setInvoiceValue(BigDecimal invoiceValue) {
        this.invoiceValue = invoiceValue;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DOC_DATE", length=7)
    public Date getIssueDocDate() {
        return this.issueDocDate;
    }
    
    public void setIssueDocDate(Date issueDocDate) {
        this.issueDocDate = issueDocDate;
    }

    
    @Column(name="ISSUE_DOC_SERIAL", precision=12, scale=0)
    public Long getIssueDocSerial() {
        return this.issueDocSerial;
    }
    
    public void setIssueDocSerial(Long issueDocSerial) {
        this.issueDocSerial = issueDocSerial;
    }

    
    @Column(name="BOARD_NUMBER", length=240)
    public String getBoardNumber() {
        return this.boardNumber;
    }
    
    public void setBoardNumber(String boardNumber) {
        this.boardNumber = boardNumber;
    }

    
    @Column(name="FUEL_TYPE", precision=1, scale=0)
    public Boolean getFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(Boolean fuelType) {
        this.fuelType = fuelType;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }




}


