package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleIssueDocument generated by hbm2java
 */
@Entity
@Table(name="VCLE_ISSUE_DOCUMENT"
    ,schema="CODEATOR"
)
public class VcleIssueDocument  implements java.io.Serializable {


     private VcleIssueDocumentId id;
     private VcleMainCost vcleMainCost;
     private VcleFiscalDate vcleFiscalDate;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private Date issueDocDate;
     private String issueType;
     private BigDecimal editorUserId;
     private String editorPersonName;
     private Long employeeNoMan;
     private BigDecimal valAll;
     private Boolean chkLock;
     private Set<VcleIssueDocumentDtl> vcleIssueDocumentDtls = new HashSet<VcleIssueDocumentDtl>(0);

    public VcleIssueDocument() {
    }

	
    public VcleIssueDocument(VcleIssueDocumentId id, VcleMainCost vcleMainCost, VcleFiscalDate vcleFiscalDate, Date issueDocDate) {
        this.id = id;
        this.vcleMainCost = vcleMainCost;
        this.vcleFiscalDate = vcleFiscalDate;
        this.issueDocDate = issueDocDate;
    }
    public VcleIssueDocument(VcleIssueDocumentId id, VcleMainCost vcleMainCost, VcleFiscalDate vcleFiscalDate, VcleEmployeeMaster vcleEmployeeMaster, Date issueDocDate, String issueType, BigDecimal editorUserId, String editorPersonName, Long employeeNoMan, BigDecimal valAll, Boolean chkLock, Set<VcleIssueDocumentDtl> vcleIssueDocumentDtls) {
       this.id = id;
       this.vcleMainCost = vcleMainCost;
       this.vcleFiscalDate = vcleFiscalDate;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.issueDocDate = issueDocDate;
       this.issueType = issueType;
       this.editorUserId = editorUserId;
       this.editorPersonName = editorPersonName;
       this.employeeNoMan = employeeNoMan;
       this.valAll = valAll;
       this.chkLock = chkLock;
       this.vcleIssueDocumentDtls = vcleIssueDocumentDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="issueDocSp", column=@Column(name="ISSUE_DOC_SP", nullable=false, precision=6, scale=0) ) } )
    public VcleIssueDocumentId getId() {
        return this.id;
    }
    
    public void setId(VcleIssueDocumentId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="MAIN_CODE", nullable=false)
    public VcleMainCost getVcleMainCost() {
        return this.vcleMainCost;
    }
    
    public void setVcleMainCost(VcleMainCost vcleMainCost) {
        this.vcleMainCost = vcleMainCost;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DATE", nullable=false, insertable=false, updatable=false)
    public VcleFiscalDate getVcleFiscalDate() {
        return this.vcleFiscalDate;
    }
    
    public void setVcleFiscalDate(VcleFiscalDate vcleFiscalDate) {
        this.vcleFiscalDate = vcleFiscalDate;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DOC_DATE", nullable=false, length=7)
    public Date getIssueDocDate() {
        return this.issueDocDate;
    }
    
    public void setIssueDocDate(Date issueDocDate) {
        this.issueDocDate = issueDocDate;
    }

    
    @Column(name="ISSUE_TYPE", length=1)
    public String getIssueType() {
        return this.issueType;
    }
    
    public void setIssueType(String issueType) {
        this.issueType = issueType;
    }

    
    @Column(name="EDITOR_USER_ID", precision=22, scale=0)
    public BigDecimal getEditorUserId() {
        return this.editorUserId;
    }
    
    public void setEditorUserId(BigDecimal editorUserId) {
        this.editorUserId = editorUserId;
    }

    
    @Column(name="EDITOR_PERSON_NAME", length=75)
    public String getEditorPersonName() {
        return this.editorPersonName;
    }
    
    public void setEditorPersonName(String editorPersonName) {
        this.editorPersonName = editorPersonName;
    }

    
    @Column(name="EMPLOYEE_NO_MAN", precision=10, scale=0)
    public Long getEmployeeNoMan() {
        return this.employeeNoMan;
    }
    
    public void setEmployeeNoMan(Long employeeNoMan) {
        this.employeeNoMan = employeeNoMan;
    }

    
    @Column(name="VAL_ALL", precision=16, scale=3)
    public BigDecimal getValAll() {
        return this.valAll;
    }
    
    public void setValAll(BigDecimal valAll) {
        this.valAll = valAll;
    }

    
    @Column(name="CHK_LOCK", precision=1, scale=0)
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleIssueDocument")
    public Set<VcleIssueDocumentDtl> getVcleIssueDocumentDtls() {
        return this.vcleIssueDocumentDtls;
    }
    
    public void setVcleIssueDocumentDtls(Set<VcleIssueDocumentDtl> vcleIssueDocumentDtls) {
        this.vcleIssueDocumentDtls = vcleIssueDocumentDtls;
    }




}


