package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleVehicleCountMm generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_COUNT_MM"
    ,schema="CODEATOR"
)
public class VcleVehicleCountMm  implements java.io.Serializable {


     private VcleVehicleCountMmId id;
     private VcleVehicleMaster vcleVehicleMaster;
     private VcleExecutionDate vcleExecutionDate;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;
     private Integer boardNumberOld;
     private Long startCountVal;
     private Long endCountVal;
     private String chkLock;

    public VcleVehicleCountMm() {
    }

	
    public VcleVehicleCountMm(VcleVehicleCountMmId id, VcleVehicleMaster vcleVehicleMaster, VcleExecutionDate vcleExecutionDate) {
        this.id = id;
        this.vcleVehicleMaster = vcleVehicleMaster;
        this.vcleExecutionDate = vcleExecutionDate;
    }
    public VcleVehicleCountMm(VcleVehicleCountMmId id, VcleVehicleMaster vcleVehicleMaster, VcleExecutionDate vcleExecutionDate, Integer boardDigital, String boardAlfa1, String boardAlfa2, String boardAlfa3, Integer boardNumberOld, Long startCountVal, Long endCountVal, String chkLock) {
       this.id = id;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.vcleExecutionDate = vcleExecutionDate;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
       this.boardNumberOld = boardNumberOld;
       this.startCountVal = startCountVal;
       this.endCountVal = endCountVal;
       this.chkLock = chkLock;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="execMm", column=@Column(name="EXEC_MM", nullable=false, length=7) ) } )
    public VcleVehicleCountMmId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleCountMmId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EXEC_MM", nullable=false, insertable=false, updatable=false)
    public VcleExecutionDate getVcleExecutionDate() {
        return this.vcleExecutionDate;
    }
    
    public void setVcleExecutionDate(VcleExecutionDate vcleExecutionDate) {
        this.vcleExecutionDate = vcleExecutionDate;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    
    @Column(name="START_COUNT_VAL", precision=11, scale=0)
    public Long getStartCountVal() {
        return this.startCountVal;
    }
    
    public void setStartCountVal(Long startCountVal) {
        this.startCountVal = startCountVal;
    }

    
    @Column(name="END_COUNT_VAL", precision=11, scale=0)
    public Long getEndCountVal() {
        return this.endCountVal;
    }
    
    public void setEndCountVal(Long endCountVal) {
        this.endCountVal = endCountVal;
    }

    
    @Column(name="CHK_LOCK", length=1)
    public String getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(String chkLock) {
        this.chkLock = chkLock;
    }




}


