package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleWorkSide generated by hbm2java
 */
@Entity
@Table(name="VCLE_WORK_SIDE"
    ,schema="CODEATOR"
)
public class VcleWorkSide  implements java.io.Serializable {


     private byte workSideCode;
     private String workSideName;
     private Set<VcleVehicleIncome> vcleVehicleIncomes = new HashSet<VcleVehicleIncome>(0);
     private Set<VcleWorkSideDtl> vcleWorkSideDtls = new HashSet<VcleWorkSideDtl>(0);
     private Set<VcleVehicleMaster> vcleVehicleMasters = new HashSet<VcleVehicleMaster>(0);

    public VcleWorkSide() {
    }

	
    public VcleWorkSide(byte workSideCode, String workSideName) {
        this.workSideCode = workSideCode;
        this.workSideName = workSideName;
    }
    public VcleWorkSide(byte workSideCode, String workSideName, Set<VcleVehicleIncome> vcleVehicleIncomes, Set<VcleWorkSideDtl> vcleWorkSideDtls, Set<VcleVehicleMaster> vcleVehicleMasters) {
       this.workSideCode = workSideCode;
       this.workSideName = workSideName;
       this.vcleVehicleIncomes = vcleVehicleIncomes;
       this.vcleWorkSideDtls = vcleWorkSideDtls;
       this.vcleVehicleMasters = vcleVehicleMasters;
    }
   
     @Id 

    
    @Column(name="WORK_SIDE_CODE", unique=true, nullable=false, precision=2, scale=0)
    public byte getWorkSideCode() {
        return this.workSideCode;
    }
    
    public void setWorkSideCode(byte workSideCode) {
        this.workSideCode = workSideCode;
    }

    
    @Column(name="WORK_SIDE_NAME", nullable=false, length=100)
    public String getWorkSideName() {
        return this.workSideName;
    }
    
    public void setWorkSideName(String workSideName) {
        this.workSideName = workSideName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkSide")
    public Set<VcleVehicleIncome> getVcleVehicleIncomes() {
        return this.vcleVehicleIncomes;
    }
    
    public void setVcleVehicleIncomes(Set<VcleVehicleIncome> vcleVehicleIncomes) {
        this.vcleVehicleIncomes = vcleVehicleIncomes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkSide")
    public Set<VcleWorkSideDtl> getVcleWorkSideDtls() {
        return this.vcleWorkSideDtls;
    }
    
    public void setVcleWorkSideDtls(Set<VcleWorkSideDtl> vcleWorkSideDtls) {
        this.vcleWorkSideDtls = vcleWorkSideDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkSide")
    public Set<VcleVehicleMaster> getVcleVehicleMasters() {
        return this.vcleVehicleMasters;
    }
    
    public void setVcleVehicleMasters(Set<VcleVehicleMaster> vcleVehicleMasters) {
        this.vcleVehicleMasters = vcleVehicleMasters;
    }




}


