package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleVehicleInstructionTech generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_INSTRUCTION_TECH"
    ,schema="CODEATOR"
)
public class VcleVehicleInstructionTech  implements java.io.Serializable {


     private VcleVehicleInstructionTechId id;
     private VcleVehicleInstruction vcleVehicleInstruction;
     private VcleEmployeeMaster vcleEmployeeMaster;

    public VcleVehicleInstructionTech() {
    }

    public VcleVehicleInstructionTech(VcleVehicleInstructionTechId id, VcleVehicleInstruction vcleVehicleInstruction, VcleEmployeeMaster vcleEmployeeMaster) {
       this.id = id;
       this.vcleVehicleInstruction = vcleVehicleInstruction;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="instructionNo", column=@Column(name="INSTRUCTION_NO", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="workshopeCode", column=@Column(name="WORKSHOPE_CODE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="techSp", column=@Column(name="TECH_SP", nullable=false, precision=2, scale=0) ) } )
    public VcleVehicleInstructionTechId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleInstructionTechId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="FISCAL_DATE", referencedColumnName="FISCAL_DATE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="VEHICLE_SP", referencedColumnName="VEHICLE_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="INSTRUCTION_NO", referencedColumnName="INSTRUCTION_NO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="WORKSHOPE_CODE", referencedColumnName="WORKSHOPE_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false) } )
    public VcleVehicleInstruction getVcleVehicleInstruction() {
        return this.vcleVehicleInstruction;
    }
    
    public void setVcleVehicleInstruction(VcleVehicleInstruction vcleVehicleInstruction) {
        this.vcleVehicleInstruction = vcleVehicleInstruction;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID_TECH", nullable=false)
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }




}


