package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VcleDataEntryAdmin generated by hbm2java
 */
@Entity
@Table(name="VCLE_DATA_ENTRY_ADMIN"
    ,schema="CODEATOR"
)
public class VcleDataEntryAdmin  implements java.io.Serializable {


     private VcleDataEntryAdminId id;
     private BigDecimal userId;
     private String appAdminName;

    public VcleDataEntryAdmin() {
    }

	
    public VcleDataEntryAdmin(VcleDataEntryAdminId id) {
        this.id = id;
    }
    public VcleDataEntryAdmin(VcleDataEntryAdminId id, BigDecimal userId, String appAdminName) {
       this.id = id;
       this.userId = userId;
       this.appAdminName = appAdminName;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="appAdminType", column=@Column(name="APP_ADMIN_TYPE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="employeeNo", column=@Column(name="EMPLOYEE_NO", nullable=false, precision=10, scale=0) ) } )
    public VcleDataEntryAdminId getId() {
        return this.id;
    }
    
    public void setId(VcleDataEntryAdminId id) {
        this.id = id;
    }

    
    @Column(name="USER_ID", precision=22, scale=0)
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    
    @Column(name="APP_ADMIN_NAME", length=3)
    public String getAppAdminName() {
        return this.appAdminName;
    }
    
    public void setAppAdminName(String appAdminName) {
        this.appAdminName = appAdminName;
    }




}


