package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleExecutionDate generated by hbm2java
 */
@Entity
@Table(name="VCLE_EXECUTION_DATE"
    ,schema="CODEATOR"
)
public class VcleExecutionDate  implements java.io.Serializable {


     private Date execMm;
     private Boolean chkLock;
     private Set<VcleTravelExchange> vcleTravelExchanges = new HashSet<VcleTravelExchange>(0);
     private Set<VcleAssociationEmp> vcleAssociationEmps = new HashSet<VcleAssociationEmp>(0);
     private Set<VcleTrafficEmpPerm> vcleTrafficEmpPerms = new HashSet<VcleTrafficEmpPerm>(0);
     private Set<VcleVehicleCountMm> vcleVehicleCountMms = new HashSet<VcleVehicleCountMm>(0);
     private Set<VcleVehicleIncome> vcleVehicleIncomes = new HashSet<VcleVehicleIncome>(0);
     private Set<VcleAssociationEmpTrans> vcleAssociationEmpTranses = new HashSet<VcleAssociationEmpTrans>(0);
     private Set<VcleExecutionDay> vcleExecutionDays = new HashSet<VcleExecutionDay>(0);
     private Set<VcleRecordMovement> vcleRecordMovements = new HashSet<VcleRecordMovement>(0);

    public VcleExecutionDate() {
    }

	
    public VcleExecutionDate(Date execMm) {
        this.execMm = execMm;
    }
    public VcleExecutionDate(Date execMm, Boolean chkLock, Set<VcleTravelExchange> vcleTravelExchanges, Set<VcleAssociationEmp> vcleAssociationEmps, Set<VcleTrafficEmpPerm> vcleTrafficEmpPerms, Set<VcleVehicleCountMm> vcleVehicleCountMms, Set<VcleVehicleIncome> vcleVehicleIncomes, Set<VcleAssociationEmpTrans> vcleAssociationEmpTranses, Set<VcleExecutionDay> vcleExecutionDays, Set<VcleRecordMovement> vcleRecordMovements) {
       this.execMm = execMm;
       this.chkLock = chkLock;
       this.vcleTravelExchanges = vcleTravelExchanges;
       this.vcleAssociationEmps = vcleAssociationEmps;
       this.vcleTrafficEmpPerms = vcleTrafficEmpPerms;
       this.vcleVehicleCountMms = vcleVehicleCountMms;
       this.vcleVehicleIncomes = vcleVehicleIncomes;
       this.vcleAssociationEmpTranses = vcleAssociationEmpTranses;
       this.vcleExecutionDays = vcleExecutionDays;
       this.vcleRecordMovements = vcleRecordMovements;
    }
   
     @Id 

    @Temporal(TemporalType.DATE)
    @Column(name="EXEC_MM", unique=true, nullable=false, length=7)
    public Date getExecMm() {
        return this.execMm;
    }
    
    public void setExecMm(Date execMm) {
        this.execMm = execMm;
    }

    
    @Column(name="CHK_LOCK", precision=1, scale=0)
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleExecutionDate")
    public Set<VcleTravelExchange> getVcleTravelExchanges() {
        return this.vcleTravelExchanges;
    }
    
    public void setVcleTravelExchanges(Set<VcleTravelExchange> vcleTravelExchanges) {
        this.vcleTravelExchanges = vcleTravelExchanges;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleExecutionDate")
    public Set<VcleAssociationEmp> getVcleAssociationEmps() {
        return this.vcleAssociationEmps;
    }
    
    public void setVcleAssociationEmps(Set<VcleAssociationEmp> vcleAssociationEmps) {
        this.vcleAssociationEmps = vcleAssociationEmps;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleExecutionDate")
    public Set<VcleTrafficEmpPerm> getVcleTrafficEmpPerms() {
        return this.vcleTrafficEmpPerms;
    }
    
    public void setVcleTrafficEmpPerms(Set<VcleTrafficEmpPerm> vcleTrafficEmpPerms) {
        this.vcleTrafficEmpPerms = vcleTrafficEmpPerms;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleExecutionDate")
    public Set<VcleVehicleCountMm> getVcleVehicleCountMms() {
        return this.vcleVehicleCountMms;
    }
    
    public void setVcleVehicleCountMms(Set<VcleVehicleCountMm> vcleVehicleCountMms) {
        this.vcleVehicleCountMms = vcleVehicleCountMms;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleExecutionDate")
    public Set<VcleVehicleIncome> getVcleVehicleIncomes() {
        return this.vcleVehicleIncomes;
    }
    
    public void setVcleVehicleIncomes(Set<VcleVehicleIncome> vcleVehicleIncomes) {
        this.vcleVehicleIncomes = vcleVehicleIncomes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleExecutionDate")
    public Set<VcleAssociationEmpTrans> getVcleAssociationEmpTranses() {
        return this.vcleAssociationEmpTranses;
    }
    
    public void setVcleAssociationEmpTranses(Set<VcleAssociationEmpTrans> vcleAssociationEmpTranses) {
        this.vcleAssociationEmpTranses = vcleAssociationEmpTranses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleExecutionDate")
    public Set<VcleExecutionDay> getVcleExecutionDays() {
        return this.vcleExecutionDays;
    }
    
    public void setVcleExecutionDays(Set<VcleExecutionDay> vcleExecutionDays) {
        this.vcleExecutionDays = vcleExecutionDays;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleExecutionDate")
    public Set<VcleRecordMovement> getVcleRecordMovements() {
        return this.vcleRecordMovements;
    }
    
    public void setVcleRecordMovements(Set<VcleRecordMovement> vcleRecordMovements) {
        this.vcleRecordMovements = vcleRecordMovements;
    }




}


