package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VcleVehicleRequireStatusDtId generated by hbm2java
 */
@Embeddable
public class VcleVehicleRequireStatusDtId  implements java.io.Serializable {


     private long requireSp;
     private byte statusSeq;

    public VcleVehicleRequireStatusDtId() {
    }

    public VcleVehicleRequireStatusDtId(long requireSp, byte statusSeq) {
       this.requireSp = requireSp;
       this.statusSeq = statusSeq;
    }
   


    @Column(name="REQUIRE_SP", nullable=false, precision=11, scale=0)
    public long getRequireSp() {
        return this.requireSp;
    }
    
    public void setRequireSp(long requireSp) {
        this.requireSp = requireSp;
    }


    @Column(name="STATUS_SEQ", nullable=false, precision=2, scale=0)
    public byte getStatusSeq() {
        return this.statusSeq;
    }
    
    public void setStatusSeq(byte statusSeq) {
        this.statusSeq = statusSeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleVehicleRequireStatusDtId) ) return false;
		 VcleVehicleRequireStatusDtId castOther = ( VcleVehicleRequireStatusDtId ) other; 
         
		 return (this.getRequireSp()==castOther.getRequireSp())
 && (this.getStatusSeq()==castOther.getStatusSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getRequireSp();
         result = 37 * result + this.getStatusSeq();
         return result;
   }   


}


