package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleEmployeeVacation generated by hbm2java
 */
@Entity
@Table(name="VCLE_EMPLOYEE_VACATION"
    ,schema="CODEATOR"
)
public class VcleEmployeeVacation  implements java.io.Serializable {


     private VcleEmployeeVacationId id;
     private VcleVacationType vcleVacationType;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private Date recordDate;
     private Date vacToDate;
     private Byte vacVal;
     private Boolean vacStatus;
     private String rmrk;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Date vacationLockDate;
     private Set<VcleEmployeeVacationDate> vcleEmployeeVacationDates = new HashSet<VcleEmployeeVacationDate>(0);

    public VcleEmployeeVacation() {
    }

	
    public VcleEmployeeVacation(VcleEmployeeVacationId id, VcleVacationType vcleVacationType, VcleEmployeeMaster vcleEmployeeMaster) {
        this.id = id;
        this.vcleVacationType = vcleVacationType;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleEmployeeVacation(VcleEmployeeVacationId id, VcleVacationType vcleVacationType, VcleEmployeeMaster vcleEmployeeMaster, Date recordDate, Date vacToDate, Byte vacVal, Boolean vacStatus, String rmrk, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Date vacationLockDate, Set<VcleEmployeeVacationDate> vcleEmployeeVacationDates) {
       this.id = id;
       this.vcleVacationType = vcleVacationType;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.recordDate = recordDate;
       this.vacToDate = vacToDate;
       this.vacVal = vacVal;
       this.vacStatus = vacStatus;
       this.rmrk = rmrk;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.vacationLockDate = vacationLockDate;
       this.vcleEmployeeVacationDates = vcleEmployeeVacationDates;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="fiscalYear", column=@Column(name="FISCAL_YEAR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="vacStartDate", column=@Column(name="VAC_START_DATE", nullable=false, length=7) ) } )
    public VcleEmployeeVacationId getId() {
        return this.id;
    }
    
    public void setId(VcleEmployeeVacationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VACATION_TYPE", nullable=false)
    public VcleVacationType getVcleVacationType() {
        return this.vcleVacationType;
    }
    
    public void setVcleVacationType(VcleVacationType vcleVacationType) {
        this.vcleVacationType = vcleVacationType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_DATE", length=7)
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VAC_TO_DATE", length=7)
    public Date getVacToDate() {
        return this.vacToDate;
    }
    
    public void setVacToDate(Date vacToDate) {
        this.vacToDate = vacToDate;
    }

    
    @Column(name="VAC_VAL", precision=2, scale=0)
    public Byte getVacVal() {
        return this.vacVal;
    }
    
    public void setVacVal(Byte vacVal) {
        this.vacVal = vacVal;
    }

    
    @Column(name="VAC_STATUS", precision=1, scale=0)
    public Boolean getVacStatus() {
        return this.vacStatus;
    }
    
    public void setVacStatus(Boolean vacStatus) {
        this.vacStatus = vacStatus;
    }

    
    @Column(name="RMRK", length=100)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VACATION_LOCK_DATE", length=7)
    public Date getVacationLockDate() {
        return this.vacationLockDate;
    }
    
    public void setVacationLockDate(Date vacationLockDate) {
        this.vacationLockDate = vacationLockDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeVacation")
    public Set<VcleEmployeeVacationDate> getVcleEmployeeVacationDates() {
        return this.vcleEmployeeVacationDates;
    }
    
    public void setVcleEmployeeVacationDates(Set<VcleEmployeeVacationDate> vcleEmployeeVacationDates) {
        this.vcleEmployeeVacationDates = vcleEmployeeVacationDates;
    }




}


