package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleInstruction generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_INSTRUCTION"
    ,schema="CODEATOR"
)
public class VcleVehicleInstruction  implements java.io.Serializable {


     private VcleVehicleInstructionId id;
     private VcleWorkshopeResponse vcleWorkshopeResponse;
     private VcleVehicleMaster vcleVehicleMaster;
     private String insReason;
     private Date insEndDate;
     private Integer notifySp;
     private String boardAlfa1;
     private Byte localSp;
     private Boolean instructionType;
     private Byte insSeq;
     private Integer boardNumberOld;
     private String boardAlfa3;
     private Date instructionDate;
     private Integer boardDigital;
     private String boardAlfa2;
     private Date notifyDate;
     private String curTime;
     private Set<VcleVehicleInstructionDtl> vcleVehicleInstructionDtls = new HashSet<VcleVehicleInstructionDtl>(0);
     private Set<VcleVehicleInstructionTech> vcleVehicleInstructionTeches = new HashSet<VcleVehicleInstructionTech>(0);

    public VcleVehicleInstruction() {
    }

	
    public VcleVehicleInstruction(VcleVehicleInstructionId id, VcleWorkshopeResponse vcleWorkshopeResponse, VcleVehicleMaster vcleVehicleMaster, Date instructionDate) {
        this.id = id;
        this.vcleWorkshopeResponse = vcleWorkshopeResponse;
        this.vcleVehicleMaster = vcleVehicleMaster;
        this.instructionDate = instructionDate;
    }
    public VcleVehicleInstruction(VcleVehicleInstructionId id, VcleWorkshopeResponse vcleWorkshopeResponse, VcleVehicleMaster vcleVehicleMaster, String insReason, Date insEndDate, Integer notifySp, String boardAlfa1, Byte localSp, Boolean instructionType, Byte insSeq, Integer boardNumberOld, String boardAlfa3, Date instructionDate, Integer boardDigital, String boardAlfa2, Date notifyDate, String curTime, Set<VcleVehicleInstructionDtl> vcleVehicleInstructionDtls, Set<VcleVehicleInstructionTech> vcleVehicleInstructionTeches) {
       this.id = id;
       this.vcleWorkshopeResponse = vcleWorkshopeResponse;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.insReason = insReason;
       this.insEndDate = insEndDate;
       this.notifySp = notifySp;
       this.boardAlfa1 = boardAlfa1;
       this.localSp = localSp;
       this.instructionType = instructionType;
       this.insSeq = insSeq;
       this.boardNumberOld = boardNumberOld;
       this.boardAlfa3 = boardAlfa3;
       this.instructionDate = instructionDate;
       this.boardDigital = boardDigital;
       this.boardAlfa2 = boardAlfa2;
       this.notifyDate = notifyDate;
       this.curTime = curTime;
       this.vcleVehicleInstructionDtls = vcleVehicleInstructionDtls;
       this.vcleVehicleInstructionTeches = vcleVehicleInstructionTeches;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="instructionNo", column=@Column(name="INSTRUCTION_NO", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="workshopeCode", column=@Column(name="WORKSHOPE_CODE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ) } )
    public VcleVehicleInstructionId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleInstructionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="WORKSHOPE_CODE", referencedColumnName="WORKSHOPE_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false) } )
    public VcleWorkshopeResponse getVcleWorkshopeResponse() {
        return this.vcleWorkshopeResponse;
    }
    
    public void setVcleWorkshopeResponse(VcleWorkshopeResponse vcleWorkshopeResponse) {
        this.vcleWorkshopeResponse = vcleWorkshopeResponse;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

    
    @Column(name="INS_REASON", length=400)
    public String getInsReason() {
        return this.insReason;
    }
    
    public void setInsReason(String insReason) {
        this.insReason = insReason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INS_END_DATE", length=7)
    public Date getInsEndDate() {
        return this.insEndDate;
    }
    
    public void setInsEndDate(Date insEndDate) {
        this.insEndDate = insEndDate;
    }

    
    @Column(name="NOTIFY_SP", precision=5, scale=0)
    public Integer getNotifySp() {
        return this.notifySp;
    }
    
    public void setNotifySp(Integer notifySp) {
        this.notifySp = notifySp;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="LOCAL_SP", precision=2, scale=0)
    public Byte getLocalSp() {
        return this.localSp;
    }
    
    public void setLocalSp(Byte localSp) {
        this.localSp = localSp;
    }

    
    @Column(name="INSTRUCTION_TYPE", precision=1, scale=0)
    public Boolean getInstructionType() {
        return this.instructionType;
    }
    
    public void setInstructionType(Boolean instructionType) {
        this.instructionType = instructionType;
    }

    
    @Column(name="INS_SEQ", precision=2, scale=0)
    public Byte getInsSeq() {
        return this.insSeq;
    }
    
    public void setInsSeq(Byte insSeq) {
        this.insSeq = insSeq;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INSTRUCTION_DATE", nullable=false, length=7)
    public Date getInstructionDate() {
        return this.instructionDate;
    }
    
    public void setInstructionDate(Date instructionDate) {
        this.instructionDate = instructionDate;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NOTIFY_DATE", length=7)
    public Date getNotifyDate() {
        return this.notifyDate;
    }
    
    public void setNotifyDate(Date notifyDate) {
        this.notifyDate = notifyDate;
    }

    
    @Column(name="CUR_TIME", length=5)
    public String getCurTime() {
        return this.curTime;
    }
    
    public void setCurTime(String curTime) {
        this.curTime = curTime;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleInstruction")
    public Set<VcleVehicleInstructionDtl> getVcleVehicleInstructionDtls() {
        return this.vcleVehicleInstructionDtls;
    }
    
    public void setVcleVehicleInstructionDtls(Set<VcleVehicleInstructionDtl> vcleVehicleInstructionDtls) {
        this.vcleVehicleInstructionDtls = vcleVehicleInstructionDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleInstruction")
    public Set<VcleVehicleInstructionTech> getVcleVehicleInstructionTeches() {
        return this.vcleVehicleInstructionTeches;
    }
    
    public void setVcleVehicleInstructionTeches(Set<VcleVehicleInstructionTech> vcleVehicleInstructionTeches) {
        this.vcleVehicleInstructionTeches = vcleVehicleInstructionTeches;
    }




}


