package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleVehicleResponseWork generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_RESPONSE_WORK"
    ,schema="CODEATOR"
)
public class VcleVehicleResponseWork  implements java.io.Serializable {


     private VcleVehicleResponseWorkId id;
     private VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp;
     private VcleMainCostCode vcleMainCostCode;
     private VcleMainCost vcleMainCost;

    public VcleVehicleResponseWork() {
    }

	
    public VcleVehicleResponseWork(VcleVehicleResponseWorkId id, VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp, VcleMainCostCode vcleMainCostCode) {
        this.id = id;
        this.vcleVehicleResponsibleEmp = vcleVehicleResponsibleEmp;
        this.vcleMainCostCode = vcleMainCostCode;
    }
    public VcleVehicleResponseWork(VcleVehicleResponseWorkId id, VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp, VcleMainCostCode vcleMainCostCode, VcleMainCost vcleMainCost) {
       this.id = id;
       this.vcleVehicleResponsibleEmp = vcleVehicleResponsibleEmp;
       this.vcleMainCostCode = vcleMainCostCode;
       this.vcleMainCost = vcleMainCost;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="costCode", column=@Column(name="COST_CODE", nullable=false, length=10) ) } )
    public VcleVehicleResponseWorkId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleResponseWorkId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public VcleVehicleResponsibleEmp getVcleVehicleResponsibleEmp() {
        return this.vcleVehicleResponsibleEmp;
    }
    
    public void setVcleVehicleResponsibleEmp(VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp) {
        this.vcleVehicleResponsibleEmp = vcleVehicleResponsibleEmp;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COST_CODE", nullable=false, insertable=false, updatable=false)
    public VcleMainCostCode getVcleMainCostCode() {
        return this.vcleMainCostCode;
    }
    
    public void setVcleMainCostCode(VcleMainCostCode vcleMainCostCode) {
        this.vcleMainCostCode = vcleMainCostCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="MAIN_CODE")
    public VcleMainCost getVcleMainCost() {
        return this.vcleMainCost;
    }
    
    public void setVcleMainCost(VcleMainCost vcleMainCost) {
        this.vcleMainCost = vcleMainCost;
    }




}


