package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleIssueDocumentMain generated by hbm2java
 */
@Entity
@Table(name="VCLE_ISSUE_DOCUMENT_MAIN"
    ,schema="CODEATOR"
)
public class VcleIssueDocumentMain  implements java.io.Serializable {


     private boolean vcleDeptType;
     private PerOrganizationStructure perOrganizationStructure;
     private Boolean chkAccountUnit;
     private Boolean chkOrgId;
     private Boolean chkCurrency;
     private String currencyCode;
     private String accountUnitCode;
     private Short fiscalYear;
     private String issueDocStatus;
     private Set<VcleIssueDocumentMainType> vcleIssueDocumentMainTypes = new HashSet<VcleIssueDocumentMainType>(0);
     private Set<VcleIssueDocumentMainDtl> vcleIssueDocumentMainDtls = new HashSet<VcleIssueDocumentMainDtl>(0);

    public VcleIssueDocumentMain() {
    }

	
    public VcleIssueDocumentMain(boolean vcleDeptType) {
        this.vcleDeptType = vcleDeptType;
    }
    public VcleIssueDocumentMain(boolean vcleDeptType, PerOrganizationStructure perOrganizationStructure, Boolean chkAccountUnit, Boolean chkOrgId, Boolean chkCurrency, String currencyCode, String accountUnitCode, Short fiscalYear, String issueDocStatus, Set<VcleIssueDocumentMainType> vcleIssueDocumentMainTypes, Set<VcleIssueDocumentMainDtl> vcleIssueDocumentMainDtls) {
       this.vcleDeptType = vcleDeptType;
       this.perOrganizationStructure = perOrganizationStructure;
       this.chkAccountUnit = chkAccountUnit;
       this.chkOrgId = chkOrgId;
       this.chkCurrency = chkCurrency;
       this.currencyCode = currencyCode;
       this.accountUnitCode = accountUnitCode;
       this.fiscalYear = fiscalYear;
       this.issueDocStatus = issueDocStatus;
       this.vcleIssueDocumentMainTypes = vcleIssueDocumentMainTypes;
       this.vcleIssueDocumentMainDtls = vcleIssueDocumentMainDtls;
    }
   
     @Id 

    
    @Column(name="VCLE_DEPT_TYPE", unique=true, nullable=false, precision=1, scale=0)
    public boolean isVcleDeptType() {
        return this.vcleDeptType;
    }
    
    public void setVcleDeptType(boolean vcleDeptType) {
        this.vcleDeptType = vcleDeptType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ORG_ID")
    public PerOrganizationStructure getPerOrganizationStructure() {
        return this.perOrganizationStructure;
    }
    
    public void setPerOrganizationStructure(PerOrganizationStructure perOrganizationStructure) {
        this.perOrganizationStructure = perOrganizationStructure;
    }

    
    @Column(name="CHK_ACCOUNT_UNIT", precision=1, scale=0)
    public Boolean getChkAccountUnit() {
        return this.chkAccountUnit;
    }
    
    public void setChkAccountUnit(Boolean chkAccountUnit) {
        this.chkAccountUnit = chkAccountUnit;
    }

    
    @Column(name="CHK_ORG_ID", precision=1, scale=0)
    public Boolean getChkOrgId() {
        return this.chkOrgId;
    }
    
    public void setChkOrgId(Boolean chkOrgId) {
        this.chkOrgId = chkOrgId;
    }

    
    @Column(name="CHK_CURRENCY", precision=1, scale=0)
    public Boolean getChkCurrency() {
        return this.chkCurrency;
    }
    
    public void setChkCurrency(Boolean chkCurrency) {
        this.chkCurrency = chkCurrency;
    }

    
    @Column(name="CURRENCY_CODE", length=4)
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="ACCOUNT_UNIT_CODE", length=4)
    public String getAccountUnitCode() {
        return this.accountUnitCode;
    }
    
    public void setAccountUnitCode(String accountUnitCode) {
        this.accountUnitCode = accountUnitCode;
    }

    
    @Column(name="FISCAL_YEAR", precision=4, scale=0)
    public Short getFiscalYear() {
        return this.fiscalYear;
    }
    
    public void setFiscalYear(Short fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

    
    @Column(name="ISSUE_DOC_STATUS", length=2)
    public String getIssueDocStatus() {
        return this.issueDocStatus;
    }
    
    public void setIssueDocStatus(String issueDocStatus) {
        this.issueDocStatus = issueDocStatus;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleIssueDocumentMain")
    public Set<VcleIssueDocumentMainType> getVcleIssueDocumentMainTypes() {
        return this.vcleIssueDocumentMainTypes;
    }
    
    public void setVcleIssueDocumentMainTypes(Set<VcleIssueDocumentMainType> vcleIssueDocumentMainTypes) {
        this.vcleIssueDocumentMainTypes = vcleIssueDocumentMainTypes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleIssueDocumentMain")
    public Set<VcleIssueDocumentMainDtl> getVcleIssueDocumentMainDtls() {
        return this.vcleIssueDocumentMainDtls;
    }
    
    public void setVcleIssueDocumentMainDtls(Set<VcleIssueDocumentMainDtl> vcleIssueDocumentMainDtls) {
        this.vcleIssueDocumentMainDtls = vcleIssueDocumentMainDtls;
    }




}


