package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleVacationType generated by hbm2java
 */
@Entity
@Table(name="VCLE_VACATION_TYPE"
    ,schema="CODEATOR"
)
public class VcleVacationType  implements java.io.Serializable {


     private byte vacationType;
     private String vacationName;
     private Boolean chkBal;
     private Set<VcleEmployeeVacation> vcleEmployeeVacations = new HashSet<VcleEmployeeVacation>(0);

    public VcleVacationType() {
    }

	
    public VcleVacationType(byte vacationType, String vacationName) {
        this.vacationType = vacationType;
        this.vacationName = vacationName;
    }
    public VcleVacationType(byte vacationType, String vacationName, Boolean chkBal, Set<VcleEmployeeVacation> vcleEmployeeVacations) {
       this.vacationType = vacationType;
       this.vacationName = vacationName;
       this.chkBal = chkBal;
       this.vcleEmployeeVacations = vcleEmployeeVacations;
    }
   
     @Id 

    
    @Column(name="VACATION_TYPE", unique=true, nullable=false, precision=2, scale=0)
    public byte getVacationType() {
        return this.vacationType;
    }
    
    public void setVacationType(byte vacationType) {
        this.vacationType = vacationType;
    }

    
    @Column(name="VACATION_NAME", nullable=false, length=75)
    public String getVacationName() {
        return this.vacationName;
    }
    
    public void setVacationName(String vacationName) {
        this.vacationName = vacationName;
    }

    
    @Column(name="CHK_BAL", precision=1, scale=0)
    public Boolean getChkBal() {
        return this.chkBal;
    }
    
    public void setChkBal(Boolean chkBal) {
        this.chkBal = chkBal;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVacationType")
    public Set<VcleEmployeeVacation> getVcleEmployeeVacations() {
        return this.vcleEmployeeVacations;
    }
    
    public void setVcleEmployeeVacations(Set<VcleEmployeeVacation> vcleEmployeeVacations) {
        this.vcleEmployeeVacations = vcleEmployeeVacations;
    }




}


