package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleClassDtl generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_CLASS_DTL"
    ,schema="CODEATOR"
)
public class VcleVehicleClassDtl  implements java.io.Serializable {


     private VcleVehicleClassDtlId id;
     private VcleVehicleType vcleVehicleType;
     private VcleVehicleMaster vcleVehicleMaster;
     private VcleVehicleClassCode vcleVehicleClassCode;
     private VcleMarkType vcleMarkType;
     private PerLocationCode perLocationCode;
     private PerEmploymentMaster perEmploymentMaster;
     private PerDeptOld perDeptOld;
     private Date stopDate;
     private Integer boardDigital;
     private String boardNumber;
     private String boardAlfa1;
     private String boardAlfa3;
     private String boardAlfa2;
     private Integer boardNumberOld;
     private String stopReason;
     private String rmrk;

    public VcleVehicleClassDtl() {
    }

	
    public VcleVehicleClassDtl(VcleVehicleClassDtlId id, VcleVehicleMaster vcleVehicleMaster, VcleVehicleClassCode vcleVehicleClassCode) {
        this.id = id;
        this.vcleVehicleMaster = vcleVehicleMaster;
        this.vcleVehicleClassCode = vcleVehicleClassCode;
    }
    public VcleVehicleClassDtl(VcleVehicleClassDtlId id, VcleVehicleType vcleVehicleType, VcleVehicleMaster vcleVehicleMaster, VcleVehicleClassCode vcleVehicleClassCode, VcleMarkType vcleMarkType, PerLocationCode perLocationCode, PerEmploymentMaster perEmploymentMaster, PerDeptOld perDeptOld, Date stopDate, Integer boardDigital, String boardNumber, String boardAlfa1, String boardAlfa3, String boardAlfa2, Integer boardNumberOld, String stopReason, String rmrk) {
       this.id = id;
       this.vcleVehicleType = vcleVehicleType;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.vcleVehicleClassCode = vcleVehicleClassCode;
       this.vcleMarkType = vcleMarkType;
       this.perLocationCode = perLocationCode;
       this.perEmploymentMaster = perEmploymentMaster;
       this.perDeptOld = perDeptOld;
       this.stopDate = stopDate;
       this.boardDigital = boardDigital;
       this.boardNumber = boardNumber;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa3 = boardAlfa3;
       this.boardAlfa2 = boardAlfa2;
       this.boardNumberOld = boardNumberOld;
       this.stopReason = stopReason;
       this.rmrk = rmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="useDate", column=@Column(name="USE_DATE", nullable=false, length=7) ) } )
    public VcleVehicleClassDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleClassDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_TYPE")
    public VcleVehicleType getVcleVehicleType() {
        return this.vcleVehicleType;
    }
    
    public void setVcleVehicleType(VcleVehicleType vcleVehicleType) {
        this.vcleVehicleType = vcleVehicleType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="CLASS_CODE", nullable=false)
    public VcleVehicleClassCode getVcleVehicleClassCode() {
        return this.vcleVehicleClassCode;
    }
    
    public void setVcleVehicleClassCode(VcleVehicleClassCode vcleVehicleClassCode) {
        this.vcleVehicleClassCode = vcleVehicleClassCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="MARK_TYPE")
    public VcleMarkType getVcleMarkType() {
        return this.vcleMarkType;
    }
    
    public void setVcleMarkType(VcleMarkType vcleMarkType) {
        this.vcleMarkType = vcleMarkType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE"), 
        @JoinColumn(name="LOC_CODE", referencedColumnName="LOC_CODE") } )
    public PerLocationCode getPerLocationCode() {
        return this.perLocationCode;
    }
    
    public void setPerLocationCode(PerLocationCode perLocationCode) {
        this.perLocationCode = perLocationCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD"), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD") } )
    public PerDeptOld getPerDeptOld() {
        return this.perDeptOld;
    }
    
    public void setPerDeptOld(PerDeptOld perDeptOld) {
        this.perDeptOld = perDeptOld;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="STOP_DATE", length=7)
    public Date getStopDate() {
        return this.stopDate;
    }
    
    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_NUMBER", length=12)
    public String getBoardNumber() {
        return this.boardNumber;
    }
    
    public void setBoardNumber(String boardNumber) {
        this.boardNumber = boardNumber;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    
    @Column(name="STOP_REASON", length=400)
    public String getStopReason() {
        return this.stopReason;
    }
    
    public void setStopReason(String stopReason) {
        this.stopReason = stopReason;
    }

    
    @Column(name="RMRK", length=100)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


