package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleEquipmentType generated by hbm2java
 */
@Entity
@Table(name="VCLE_EQUIPMENT_TYPE"
    ,schema="CODEATOR"
)
public class VcleEquipmentType  implements java.io.Serializable {


     private int equipmentCode;
     private String equipmentName;
     private Set<VcleVehicleMaster> vcleVehicleMasters = new HashSet<VcleVehicleMaster>(0);

    public VcleEquipmentType() {
    }

	
    public VcleEquipmentType(int equipmentCode, String equipmentName) {
        this.equipmentCode = equipmentCode;
        this.equipmentName = equipmentName;
    }
    public VcleEquipmentType(int equipmentCode, String equipmentName, Set<VcleVehicleMaster> vcleVehicleMasters) {
       this.equipmentCode = equipmentCode;
       this.equipmentName = equipmentName;
       this.vcleVehicleMasters = vcleVehicleMasters;
    }
   
     @Id 

    
    @Column(name="EQUIPMENT_CODE", unique=true, nullable=false, precision=6, scale=0)
    public int getEquipmentCode() {
        return this.equipmentCode;
    }
    
    public void setEquipmentCode(int equipmentCode) {
        this.equipmentCode = equipmentCode;
    }

    
    @Column(name="EQUIPMENT_NAME", nullable=false, length=60)
    public String getEquipmentName() {
        return this.equipmentName;
    }
    
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEquipmentType")
    public Set<VcleVehicleMaster> getVcleVehicleMasters() {
        return this.vcleVehicleMasters;
    }
    
    public void setVcleVehicleMasters(Set<VcleVehicleMaster> vcleVehicleMasters) {
        this.vcleVehicleMasters = vcleVehicleMasters;
    }




}


