package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleCost generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_COST"
    ,schema="CODEATOR"
)
public class VcleVehicleCost  implements java.io.Serializable {


     private VcleVehicleCostId id;
     private VcleVehicleMaster vcleVehicleMaster;
     private String buyerName;
     private Date recordDate;
     private String rmrk;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;
     private Integer boardNumberOld;
     private Date execMm;
     private BigDecimal totDisCount;
     private BigDecimal totLitreQty;
     private BigDecimal totIssueQun;
     private BigDecimal totValLiq;
     private BigDecimal totValBook;
     private BigDecimal totValue;
     private Byte fuelType;

    public VcleVehicleCost() {
    }

	
    public VcleVehicleCost(VcleVehicleCostId id, VcleVehicleMaster vcleVehicleMaster) {
        this.id = id;
        this.vcleVehicleMaster = vcleVehicleMaster;
    }
    public VcleVehicleCost(VcleVehicleCostId id, VcleVehicleMaster vcleVehicleMaster, String buyerName, Date recordDate, String rmrk, Integer boardDigital, String boardAlfa1, String boardAlfa2, String boardAlfa3, Integer boardNumberOld, Date execMm, BigDecimal totDisCount, BigDecimal totLitreQty, BigDecimal totIssueQun, BigDecimal totValLiq, BigDecimal totValBook, BigDecimal totValue, Byte fuelType) {
       this.id = id;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.buyerName = buyerName;
       this.recordDate = recordDate;
       this.rmrk = rmrk;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
       this.boardNumberOld = boardNumberOld;
       this.execMm = execMm;
       this.totDisCount = totDisCount;
       this.totLitreQty = totLitreQty;
       this.totIssueQun = totIssueQun;
       this.totValLiq = totValLiq;
       this.totValBook = totValBook;
       this.totValue = totValue;
       this.fuelType = fuelType;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="saleDate", column=@Column(name="SALE_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ) } )
    public VcleVehicleCostId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleCostId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

    
    @Column(name="BUYER_NAME", length=150)
    public String getBuyerName() {
        return this.buyerName;
    }
    
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_DATE", length=7)
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    
    @Column(name="RMRK", length=400)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXEC_MM", length=7)
    public Date getExecMm() {
        return this.execMm;
    }
    
    public void setExecMm(Date execMm) {
        this.execMm = execMm;
    }

    
    @Column(name="TOT_DIS_COUNT", precision=9)
    public BigDecimal getTotDisCount() {
        return this.totDisCount;
    }
    
    public void setTotDisCount(BigDecimal totDisCount) {
        this.totDisCount = totDisCount;
    }

    
    @Column(name="TOT_LITRE_QTY", precision=7)
    public BigDecimal getTotLitreQty() {
        return this.totLitreQty;
    }
    
    public void setTotLitreQty(BigDecimal totLitreQty) {
        this.totLitreQty = totLitreQty;
    }

    
    @Column(name="TOT_ISSUE_QUN", precision=12, scale=3)
    public BigDecimal getTotIssueQun() {
        return this.totIssueQun;
    }
    
    public void setTotIssueQun(BigDecimal totIssueQun) {
        this.totIssueQun = totIssueQun;
    }

    
    @Column(name="TOT_VAL_LIQ", precision=9)
    public BigDecimal getTotValLiq() {
        return this.totValLiq;
    }
    
    public void setTotValLiq(BigDecimal totValLiq) {
        this.totValLiq = totValLiq;
    }

    
    @Column(name="TOT_VAL_BOOK", precision=9)
    public BigDecimal getTotValBook() {
        return this.totValBook;
    }
    
    public void setTotValBook(BigDecimal totValBook) {
        this.totValBook = totValBook;
    }

    
    @Column(name="TOT_VALUE", precision=9)
    public BigDecimal getTotValue() {
        return this.totValue;
    }
    
    public void setTotValue(BigDecimal totValue) {
        this.totValue = totValue;
    }

    
    @Column(name="FUEL_TYPE", precision=2, scale=0)
    public Byte getFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(Byte fuelType) {
        this.fuelType = fuelType;
    }




}


