package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleWorkType generated by hbm2java
 */
@Entity
@Table(name="VCLE_WORK_TYPE"
    ,schema="CODEATOR"
)
public class VcleWorkType  implements java.io.Serializable {


     private byte workType;
     private String workName;
     private Boolean chkWork;
     private Set<VcleEmployeeOvertime> vcleEmployeeOvertimes = new HashSet<VcleEmployeeOvertime>(0);
     private Set<VcleTravelExchange> vcleTravelExchanges = new HashSet<VcleTravelExchange>(0);
     private Set<VcleVehicleIncome> vcleVehicleIncomes = new HashSet<VcleVehicleIncome>(0);
     private Set<VcleEmployeeMaster> vcleEmployeeMasters = new HashSet<VcleEmployeeMaster>(0);
     private Set<VcleWorkTypeJoin> vcleWorkTypeJoins = new HashSet<VcleWorkTypeJoin>(0);
     private Set<VcleRecordMovement> vcleRecordMovements = new HashSet<VcleRecordMovement>(0);

    public VcleWorkType() {
    }

	
    public VcleWorkType(byte workType, String workName) {
        this.workType = workType;
        this.workName = workName;
    }
    public VcleWorkType(byte workType, String workName, Boolean chkWork, Set<VcleEmployeeOvertime> vcleEmployeeOvertimes, Set<VcleTravelExchange> vcleTravelExchanges, Set<VcleVehicleIncome> vcleVehicleIncomes, Set<VcleEmployeeMaster> vcleEmployeeMasters, Set<VcleWorkTypeJoin> vcleWorkTypeJoins, Set<VcleRecordMovement> vcleRecordMovements) {
       this.workType = workType;
       this.workName = workName;
       this.chkWork = chkWork;
       this.vcleEmployeeOvertimes = vcleEmployeeOvertimes;
       this.vcleTravelExchanges = vcleTravelExchanges;
       this.vcleVehicleIncomes = vcleVehicleIncomes;
       this.vcleEmployeeMasters = vcleEmployeeMasters;
       this.vcleWorkTypeJoins = vcleWorkTypeJoins;
       this.vcleRecordMovements = vcleRecordMovements;
    }
   
     @Id 

    
    @Column(name="WORK_TYPE", unique=true, nullable=false, precision=2, scale=0)
    public byte getWorkType() {
        return this.workType;
    }
    
    public void setWorkType(byte workType) {
        this.workType = workType;
    }

    
    @Column(name="WORK_NAME", nullable=false, length=60)
    public String getWorkName() {
        return this.workName;
    }
    
    public void setWorkName(String workName) {
        this.workName = workName;
    }

    
    @Column(name="CHK_WORK", precision=1, scale=0)
    public Boolean getChkWork() {
        return this.chkWork;
    }
    
    public void setChkWork(Boolean chkWork) {
        this.chkWork = chkWork;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkType")
    public Set<VcleEmployeeOvertime> getVcleEmployeeOvertimes() {
        return this.vcleEmployeeOvertimes;
    }
    
    public void setVcleEmployeeOvertimes(Set<VcleEmployeeOvertime> vcleEmployeeOvertimes) {
        this.vcleEmployeeOvertimes = vcleEmployeeOvertimes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkType")
    public Set<VcleTravelExchange> getVcleTravelExchanges() {
        return this.vcleTravelExchanges;
    }
    
    public void setVcleTravelExchanges(Set<VcleTravelExchange> vcleTravelExchanges) {
        this.vcleTravelExchanges = vcleTravelExchanges;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkType")
    public Set<VcleVehicleIncome> getVcleVehicleIncomes() {
        return this.vcleVehicleIncomes;
    }
    
    public void setVcleVehicleIncomes(Set<VcleVehicleIncome> vcleVehicleIncomes) {
        this.vcleVehicleIncomes = vcleVehicleIncomes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkType")
    public Set<VcleEmployeeMaster> getVcleEmployeeMasters() {
        return this.vcleEmployeeMasters;
    }
    
    public void setVcleEmployeeMasters(Set<VcleEmployeeMaster> vcleEmployeeMasters) {
        this.vcleEmployeeMasters = vcleEmployeeMasters;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkType")
    public Set<VcleWorkTypeJoin> getVcleWorkTypeJoins() {
        return this.vcleWorkTypeJoins;
    }
    
    public void setVcleWorkTypeJoins(Set<VcleWorkTypeJoin> vcleWorkTypeJoins) {
        this.vcleWorkTypeJoins = vcleWorkTypeJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkType")
    public Set<VcleRecordMovement> getVcleRecordMovements() {
        return this.vcleRecordMovements;
    }
    
    public void setVcleRecordMovements(Set<VcleRecordMovement> vcleRecordMovements) {
        this.vcleRecordMovements = vcleRecordMovements;
    }




}


