package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleDeptNumberUser generated by hbm2java
 */
@Entity
@Table(name="VCLE_DEPT_NUMBER_USER"
    ,schema="CODEATOR"
)
public class VcleDeptNumberUser  implements java.io.Serializable {


     private VcleDeptNumberUserId id;
     private VcleDeptNumber vcleDeptNumber;
     private Boolean chkDeptOk;

    public VcleDeptNumberUser() {
    }

	
    public VcleDeptNumberUser(VcleDeptNumberUserId id, VcleDeptNumber vcleDeptNumber) {
        this.id = id;
        this.vcleDeptNumber = vcleDeptNumber;
    }
    public VcleDeptNumberUser(VcleDeptNumberUserId id, VcleDeptNumber vcleDeptNumber, Boolean chkDeptOk) {
       this.id = id;
       this.vcleDeptNumber = vcleDeptNumber;
       this.chkDeptOk = chkDeptOk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="USER_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="deptId", column=@Column(name="DEPT_ID", nullable=false, precision=7, scale=0) ) } )
    public VcleDeptNumberUserId getId() {
        return this.id;
    }
    
    public void setId(VcleDeptNumberUserId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="DEPT_ID", nullable=false, insertable=false, updatable=false)
    public VcleDeptNumber getVcleDeptNumber() {
        return this.vcleDeptNumber;
    }
    
    public void setVcleDeptNumber(VcleDeptNumber vcleDeptNumber) {
        this.vcleDeptNumber = vcleDeptNumber;
    }

    
    @Column(name="CHK_DEPT_OK", precision=1, scale=0)
    public Boolean getChkDeptOk() {
        return this.chkDeptOk;
    }
    
    public void setChkDeptOk(Boolean chkDeptOk) {
        this.chkDeptOk = chkDeptOk;
    }




}


