package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VcleWorkOnSaturdaysId generated by hbm2java
 */
@Embeddable
public class VcleWorkOnSaturdaysId  implements java.io.Serializable {


     private long employeeId;
     private Date execDay;

    public VcleWorkOnSaturdaysId() {
    }

    public VcleWorkOnSaturdaysId(long employeeId, Date execDay) {
       this.employeeId = employeeId;
       this.execDay = execDay;
    }
   


    @Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0)
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }


    @Column(name="EXEC_DAY", nullable=false, length=7)
    public Date getExecDay() {
        return this.execDay;
    }
    
    public void setExecDay(Date execDay) {
        this.execDay = execDay;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleWorkOnSaturdaysId) ) return false;
		 VcleWorkOnSaturdaysId castOther = ( VcleWorkOnSaturdaysId ) other; 
         
		 return (this.getEmployeeId()==castOther.getEmployeeId())
 && ( (this.getExecDay()==castOther.getExecDay()) || ( this.getExecDay()!=null && castOther.getExecDay()!=null && this.getExecDay().equals(castOther.getExecDay()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getEmployeeId();
         result = 37 * result + ( getExecDay() == null ? 0 : this.getExecDay().hashCode() );
         return result;
   }   


}


