package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleInsuranceCompany generated by hbm2java
 */
@Entity
@Table(name="VCLE_INSURANCE_COMPANY"
    ,schema="CODEATOR"
)
public class VcleInsuranceCompany  implements java.io.Serializable {


     private byte companyCode;
     private String icompanyName;
     private Set<VcleVehicleLicense> vcleVehicleLicenses = new HashSet<VcleVehicleLicense>(0);

    public VcleInsuranceCompany() {
    }

	
    public VcleInsuranceCompany(byte companyCode, String icompanyName) {
        this.companyCode = companyCode;
        this.icompanyName = icompanyName;
    }
    public VcleInsuranceCompany(byte companyCode, String icompanyName, Set<VcleVehicleLicense> vcleVehicleLicenses) {
       this.companyCode = companyCode;
       this.icompanyName = icompanyName;
       this.vcleVehicleLicenses = vcleVehicleLicenses;
    }
   
     @Id 

    
    @Column(name="COMPANY_CODE", unique=true, nullable=false, precision=2, scale=0)
    public byte getCompanyCode() {
        return this.companyCode;
    }
    
    public void setCompanyCode(byte companyCode) {
        this.companyCode = companyCode;
    }

    
    @Column(name="ICOMPANY_NAME", nullable=false, length=60)
    public String getIcompanyName() {
        return this.icompanyName;
    }
    
    public void setIcompanyName(String icompanyName) {
        this.icompanyName = icompanyName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleInsuranceCompany")
    public Set<VcleVehicleLicense> getVcleVehicleLicenses() {
        return this.vcleVehicleLicenses;
    }
    
    public void setVcleVehicleLicenses(Set<VcleVehicleLicense> vcleVehicleLicenses) {
        this.vcleVehicleLicenses = vcleVehicleLicenses;
    }




}


