package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleAccident generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_ACCIDENT"
    ,schema="CODEATOR"
)
public class VcleVehicleAccident  implements java.io.Serializable {


     private VcleVehicleAccidentId id;
     private VcleVehicleMaster vcleVehicleMaster;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private String reportNo;
     private Date reportDate;
     private String accidentPlace;
     private String reportDesc;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;
     private Integer boardDigital;
     private Integer boardNumberOld;

    public VcleVehicleAccident() {
    }

	
    public VcleVehicleAccident(VcleVehicleAccidentId id, VcleVehicleMaster vcleVehicleMaster) {
        this.id = id;
        this.vcleVehicleMaster = vcleVehicleMaster;
    }
    public VcleVehicleAccident(VcleVehicleAccidentId id, VcleVehicleMaster vcleVehicleMaster, VcleEmployeeMaster vcleEmployeeMaster, String reportNo, Date reportDate, String accidentPlace, String reportDesc, String boardAlfa1, String boardAlfa2, String boardAlfa3, Integer boardDigital, Integer boardNumberOld) {
       this.id = id;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.reportNo = reportNo;
       this.reportDate = reportDate;
       this.accidentPlace = accidentPlace;
       this.reportDesc = reportDesc;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
       this.boardDigital = boardDigital;
       this.boardNumberOld = boardNumberOld;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="accidentDate", column=@Column(name="ACCIDENT_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ) } )
    public VcleVehicleAccidentId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleAccidentId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

    
    @Column(name="REPORT_NO", length=20)
    public String getReportNo() {
        return this.reportNo;
    }
    
    public void setReportNo(String reportNo) {
        this.reportNo = reportNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REPORT_DATE", length=7)
    public Date getReportDate() {
        return this.reportDate;
    }
    
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    
    @Column(name="ACCIDENT_PLACE", length=100)
    public String getAccidentPlace() {
        return this.accidentPlace;
    }
    
    public void setAccidentPlace(String accidentPlace) {
        this.accidentPlace = accidentPlace;
    }

    
    @Column(name="REPORT_DESC", length=400)
    public String getReportDesc() {
        return this.reportDesc;
    }
    
    public void setReportDesc(String reportDesc) {
        this.reportDesc = reportDesc;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }




}


