package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleIssueDocumentMainType generated by hbm2java
 */
@Entity
@Table(name="VCLE_ISSUE_DOCUMENT_MAIN_TYPE"
    ,schema="CODEATOR"
)
public class VcleIssueDocumentMainType  implements java.io.Serializable {


     private VcleIssueDocumentMainTypeId id;
     private VcleIssueDocumentMain vcleIssueDocumentMain;
     private String issueMainName;
     private Set<VcleIssueDocumentFinType> vcleIssueDocumentFinTypes = new HashSet<VcleIssueDocumentFinType>(0);
     private Set<VcleIssueDocumentLinType> vcleIssueDocumentLinTypes = new HashSet<VcleIssueDocumentLinType>(0);
     private Set<VcleIssueDocumentManType> vcleIssueDocumentManTypes = new HashSet<VcleIssueDocumentManType>(0);

    public VcleIssueDocumentMainType() {
    }

	
    public VcleIssueDocumentMainType(VcleIssueDocumentMainTypeId id, VcleIssueDocumentMain vcleIssueDocumentMain) {
        this.id = id;
        this.vcleIssueDocumentMain = vcleIssueDocumentMain;
    }
    public VcleIssueDocumentMainType(VcleIssueDocumentMainTypeId id, VcleIssueDocumentMain vcleIssueDocumentMain, String issueMainName, Set<VcleIssueDocumentFinType> vcleIssueDocumentFinTypes, Set<VcleIssueDocumentLinType> vcleIssueDocumentLinTypes, Set<VcleIssueDocumentManType> vcleIssueDocumentManTypes) {
       this.id = id;
       this.vcleIssueDocumentMain = vcleIssueDocumentMain;
       this.issueMainName = issueMainName;
       this.vcleIssueDocumentFinTypes = vcleIssueDocumentFinTypes;
       this.vcleIssueDocumentLinTypes = vcleIssueDocumentLinTypes;
       this.vcleIssueDocumentManTypes = vcleIssueDocumentManTypes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vcleDeptType", column=@Column(name="VCLE_DEPT_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="issueMainCode", column=@Column(name="ISSUE_MAIN_CODE", nullable=false, precision=2, scale=0) ) } )
    public VcleIssueDocumentMainTypeId getId() {
        return this.id;
    }
    
    public void setId(VcleIssueDocumentMainTypeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_DEPT_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleIssueDocumentMain getVcleIssueDocumentMain() {
        return this.vcleIssueDocumentMain;
    }
    
    public void setVcleIssueDocumentMain(VcleIssueDocumentMain vcleIssueDocumentMain) {
        this.vcleIssueDocumentMain = vcleIssueDocumentMain;
    }

    
    @Column(name="ISSUE_MAIN_NAME", length=100)
    public String getIssueMainName() {
        return this.issueMainName;
    }
    
    public void setIssueMainName(String issueMainName) {
        this.issueMainName = issueMainName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleIssueDocumentMainType")
    public Set<VcleIssueDocumentFinType> getVcleIssueDocumentFinTypes() {
        return this.vcleIssueDocumentFinTypes;
    }
    
    public void setVcleIssueDocumentFinTypes(Set<VcleIssueDocumentFinType> vcleIssueDocumentFinTypes) {
        this.vcleIssueDocumentFinTypes = vcleIssueDocumentFinTypes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleIssueDocumentMainType")
    public Set<VcleIssueDocumentLinType> getVcleIssueDocumentLinTypes() {
        return this.vcleIssueDocumentLinTypes;
    }
    
    public void setVcleIssueDocumentLinTypes(Set<VcleIssueDocumentLinType> vcleIssueDocumentLinTypes) {
        this.vcleIssueDocumentLinTypes = vcleIssueDocumentLinTypes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleIssueDocumentMainType")
    public Set<VcleIssueDocumentManType> getVcleIssueDocumentManTypes() {
        return this.vcleIssueDocumentManTypes;
    }
    
    public void setVcleIssueDocumentManTypes(Set<VcleIssueDocumentManType> vcleIssueDocumentManTypes) {
        this.vcleIssueDocumentManTypes = vcleIssueDocumentManTypes;
    }




}


