package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleInstructionItem generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_INSTRUCTION_ITEM"
    ,schema="CODEATOR"
)
public class VcleVehicleInstructionItem  implements java.io.Serializable {


     private VcleVehicleInstructionItemId id;
     private VcleVehicleInstructionDtl vcleVehicleInstructionDtl;
     private String itemDescVcle;
     private Long issueNo;
     private Date issueDate;
     private BigDecimal qty;
     private Long storeCodeItem;
     private Long itemNumber;
     private Boolean chkStore;

    public VcleVehicleInstructionItem() {
    }

	
    public VcleVehicleInstructionItem(VcleVehicleInstructionItemId id, VcleVehicleInstructionDtl vcleVehicleInstructionDtl) {
        this.id = id;
        this.vcleVehicleInstructionDtl = vcleVehicleInstructionDtl;
    }
    public VcleVehicleInstructionItem(VcleVehicleInstructionItemId id, VcleVehicleInstructionDtl vcleVehicleInstructionDtl, String itemDescVcle, Long issueNo, Date issueDate, BigDecimal qty, Long storeCodeItem, Long itemNumber, Boolean chkStore) {
       this.id = id;
       this.vcleVehicleInstructionDtl = vcleVehicleInstructionDtl;
       this.itemDescVcle = itemDescVcle;
       this.issueNo = issueNo;
       this.issueDate = issueDate;
       this.qty = qty;
       this.storeCodeItem = storeCodeItem;
       this.itemNumber = itemNumber;
       this.chkStore = chkStore;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="suspendSp", column=@Column(name="SUSPEND_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="instructionNo", column=@Column(name="INSTRUCTION_NO", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="workshopeCode", column=@Column(name="WORKSHOPE_CODE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="itemSp", column=@Column(name="ITEM_SP", nullable=false, precision=6, scale=0) ) } )
    public VcleVehicleInstructionItemId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleInstructionItemId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="VEHICLE_SP", referencedColumnName="VEHICLE_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="FISCAL_DATE", referencedColumnName="FISCAL_DATE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="WORKSHOPE_CODE", referencedColumnName="WORKSHOPE_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="INSTRUCTION_NO", referencedColumnName="INSTRUCTION_NO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SUSPEND_SP", referencedColumnName="SUSPEND_SP", nullable=false, insertable=false, updatable=false) } )
    public VcleVehicleInstructionDtl getVcleVehicleInstructionDtl() {
        return this.vcleVehicleInstructionDtl;
    }
    
    public void setVcleVehicleInstructionDtl(VcleVehicleInstructionDtl vcleVehicleInstructionDtl) {
        this.vcleVehicleInstructionDtl = vcleVehicleInstructionDtl;
    }

    
    @Column(name="ITEM_DESC_VCLE", length=250)
    public String getItemDescVcle() {
        return this.itemDescVcle;
    }
    
    public void setItemDescVcle(String itemDescVcle) {
        this.itemDescVcle = itemDescVcle;
    }

    
    @Column(name="ISSUE_NO", precision=11, scale=0)
    public Long getIssueNo() {
        return this.issueNo;
    }
    
    public void setIssueNo(Long issueNo) {
        this.issueNo = issueNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DATE", length=7)
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    
    @Column(name="QTY", precision=7)
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    
    @Column(name="STORE_CODE_ITEM", precision=12, scale=0)
    public Long getStoreCodeItem() {
        return this.storeCodeItem;
    }
    
    public void setStoreCodeItem(Long storeCodeItem) {
        this.storeCodeItem = storeCodeItem;
    }

    
    @Column(name="ITEM_NUMBER", precision=15, scale=0)
    public Long getItemNumber() {
        return this.itemNumber;
    }
    
    public void setItemNumber(Long itemNumber) {
        this.itemNumber = itemNumber;
    }

    
    @Column(name="CHK_STORE", precision=1, scale=0)
    public Boolean getChkStore() {
        return this.chkStore;
    }
    
    public void setChkStore(Boolean chkStore) {
        this.chkStore = chkStore;
    }




}


