package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VclePriceKilometer generated by hbm2java
 */
@Entity
@Table(name="VCLE_PRICE_KILOMETER"
    ,schema="CODEATOR"
)
public class VclePriceKilometer  implements java.io.Serializable {


     private VclePriceKilometerId id;
     private VcleVehicleType vcleVehicleType;
     private VclePriceDateMaster vclePriceDateMaster;
     private BigDecimal kiloHourPrice;
     private BigDecimal minVal;
     private BigDecimal maxVal;

    public VclePriceKilometer() {
    }

	
    public VclePriceKilometer(VclePriceKilometerId id, VcleVehicleType vcleVehicleType, VclePriceDateMaster vclePriceDateMaster, BigDecimal kiloHourPrice) {
        this.id = id;
        this.vcleVehicleType = vcleVehicleType;
        this.vclePriceDateMaster = vclePriceDateMaster;
        this.kiloHourPrice = kiloHourPrice;
    }
    public VclePriceKilometer(VclePriceKilometerId id, VcleVehicleType vcleVehicleType, VclePriceDateMaster vclePriceDateMaster, BigDecimal kiloHourPrice, BigDecimal minVal, BigDecimal maxVal) {
       this.id = id;
       this.vcleVehicleType = vcleVehicleType;
       this.vclePriceDateMaster = vclePriceDateMaster;
       this.kiloHourPrice = kiloHourPrice;
       this.minVal = minVal;
       this.maxVal = maxVal;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vcleType", column=@Column(name="VCLE_TYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="priceType", column=@Column(name="PRICE_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="priceDate", column=@Column(name="PRICE_DATE", nullable=false, length=7) ) } )
    public VclePriceKilometerId getId() {
        return this.id;
    }
    
    public void setId(VclePriceKilometerId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleVehicleType getVcleVehicleType() {
        return this.vcleVehicleType;
    }
    
    public void setVcleVehicleType(VcleVehicleType vcleVehicleType) {
        this.vcleVehicleType = vcleVehicleType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="PRICE_TYPE", referencedColumnName="PRICE_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PRICE_DATE", referencedColumnName="PRICE_DATE", nullable=false, insertable=false, updatable=false) } )
    public VclePriceDateMaster getVclePriceDateMaster() {
        return this.vclePriceDateMaster;
    }
    
    public void setVclePriceDateMaster(VclePriceDateMaster vclePriceDateMaster) {
        this.vclePriceDateMaster = vclePriceDateMaster;
    }

    
    @Column(name="KILO_HOUR_PRICE", nullable=false, precision=5)
    public BigDecimal getKiloHourPrice() {
        return this.kiloHourPrice;
    }
    
    public void setKiloHourPrice(BigDecimal kiloHourPrice) {
        this.kiloHourPrice = kiloHourPrice;
    }

    
    @Column(name="MIN_VAL", precision=6)
    public BigDecimal getMinVal() {
        return this.minVal;
    }
    
    public void setMinVal(BigDecimal minVal) {
        this.minVal = minVal;
    }

    
    @Column(name="MAX_VAL", precision=6)
    public BigDecimal getMaxVal() {
        return this.maxVal;
    }
    
    public void setMaxVal(BigDecimal maxVal) {
        this.maxVal = maxVal;
    }




}


