package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleTrafficPriceDate generated by hbm2java
 */
@Entity
@Table(name="VCLE_TRAFFIC_PRICE_DATE"
    ,schema="CODEATOR"
)
public class VcleTrafficPriceDate  implements java.io.Serializable {


     private Date priceDate;
     private String rmrk;
     private Set<VcleTrafficPriceDateVal> vcleTrafficPriceDateVals = new HashSet<VcleTrafficPriceDateVal>(0);

    public VcleTrafficPriceDate() {
    }

	
    public VcleTrafficPriceDate(Date priceDate) {
        this.priceDate = priceDate;
    }
    public VcleTrafficPriceDate(Date priceDate, String rmrk, Set<VcleTrafficPriceDateVal> vcleTrafficPriceDateVals) {
       this.priceDate = priceDate;
       this.rmrk = rmrk;
       this.vcleTrafficPriceDateVals = vcleTrafficPriceDateVals;
    }
   
     @Id 

    @Temporal(TemporalType.DATE)
    @Column(name="PRICE_DATE", unique=true, nullable=false, length=7)
    public Date getPriceDate() {
        return this.priceDate;
    }
    
    public void setPriceDate(Date priceDate) {
        this.priceDate = priceDate;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleTrafficPriceDate")
    public Set<VcleTrafficPriceDateVal> getVcleTrafficPriceDateVals() {
        return this.vcleTrafficPriceDateVals;
    }
    
    public void setVcleTrafficPriceDateVals(Set<VcleTrafficPriceDateVal> vcleTrafficPriceDateVals) {
        this.vcleTrafficPriceDateVals = vcleTrafficPriceDateVals;
    }




}


