package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * VcleVehicleResponsibleEmp generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_RESPONSIBLE_EMP"
    ,schema="CODEATOR"
)
public class VcleVehicleResponsibleEmp  implements java.io.Serializable {


     private long employeeId;
     private VcleWorkshopeCode vcleWorkshopeCode;
     private VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp;
     private VcleVehicleRepairType vcleVehicleRepairType;
     private VcleMainCost vcleMainCost;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private Long employeeNo;
     private Boolean responseType;
     private String rmrk;
     private String vcleType;
     private Set<VcleVehicleResponseWork> vcleVehicleResponseWorks = new HashSet<VcleVehicleResponseWork>(0);
     private Set<VcleVehicleResponsibleEmp> vcleVehicleResponsibleEmps = new HashSet<VcleVehicleResponsibleEmp>(0);

    public VcleVehicleResponsibleEmp() {
    }

	
    public VcleVehicleResponsibleEmp(VcleMainCost vcleMainCost, VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleMainCost = vcleMainCost;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleVehicleResponsibleEmp(VcleWorkshopeCode vcleWorkshopeCode, VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp, VcleVehicleRepairType vcleVehicleRepairType, VcleMainCost vcleMainCost, VcleEmployeeMaster vcleEmployeeMaster, Long employeeNo, Boolean responseType, String rmrk, String vcleType, Set<VcleVehicleResponseWork> vcleVehicleResponseWorks, Set<VcleVehicleResponsibleEmp> vcleVehicleResponsibleEmps) {
       this.vcleWorkshopeCode = vcleWorkshopeCode;
       this.vcleVehicleResponsibleEmp = vcleVehicleResponsibleEmp;
       this.vcleVehicleRepairType = vcleVehicleRepairType;
       this.vcleMainCost = vcleMainCost;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.employeeNo = employeeNo;
       this.responseType = responseType;
       this.rmrk = rmrk;
       this.vcleType = vcleType;
       this.vcleVehicleResponseWorks = vcleVehicleResponseWorks;
       this.vcleVehicleResponsibleEmps = vcleVehicleResponsibleEmps;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="vcleEmployeeMaster"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0)
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="WORKSHOPE_CODE")
    public VcleWorkshopeCode getVcleWorkshopeCode() {
        return this.vcleWorkshopeCode;
    }
    
    public void setVcleWorkshopeCode(VcleWorkshopeCode vcleWorkshopeCode) {
        this.vcleWorkshopeCode = vcleWorkshopeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID_BOSS")
    public VcleVehicleResponsibleEmp getVcleVehicleResponsibleEmp() {
        return this.vcleVehicleResponsibleEmp;
    }
    
    public void setVcleVehicleResponsibleEmp(VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp) {
        this.vcleVehicleResponsibleEmp = vcleVehicleResponsibleEmp;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="REPAIR_TYPE")
    public VcleVehicleRepairType getVcleVehicleRepairType() {
        return this.vcleVehicleRepairType;
    }
    
    public void setVcleVehicleRepairType(VcleVehicleRepairType vcleVehicleRepairType) {
        this.vcleVehicleRepairType = vcleVehicleRepairType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="MAIN_CODE", nullable=false)
    public VcleMainCost getVcleMainCost() {
        return this.vcleMainCost;
    }
    
    public void setVcleMainCost(VcleMainCost vcleMainCost) {
        this.vcleMainCost = vcleMainCost;
    }

@OneToOne(fetch=FetchType.EAGER)@PrimaryKeyJoinColumn
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

    
    @Column(name="EMPLOYEE_NO", precision=10, scale=0)
    public Long getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(Long employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="RESPONSE_TYPE", precision=1, scale=0)
    public Boolean getResponseType() {
        return this.responseType;
    }
    
    public void setResponseType(Boolean responseType) {
        this.responseType = responseType;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="VCLE_TYPE", length=2)
    public String getVcleType() {
        return this.vcleType;
    }
    
    public void setVcleType(String vcleType) {
        this.vcleType = vcleType;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleResponsibleEmp")
    public Set<VcleVehicleResponseWork> getVcleVehicleResponseWorks() {
        return this.vcleVehicleResponseWorks;
    }
    
    public void setVcleVehicleResponseWorks(Set<VcleVehicleResponseWork> vcleVehicleResponseWorks) {
        this.vcleVehicleResponseWorks = vcleVehicleResponseWorks;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleResponsibleEmp")
    public Set<VcleVehicleResponsibleEmp> getVcleVehicleResponsibleEmps() {
        return this.vcleVehicleResponsibleEmps;
    }
    
    public void setVcleVehicleResponsibleEmps(Set<VcleVehicleResponsibleEmp> vcleVehicleResponsibleEmps) {
        this.vcleVehicleResponsibleEmps = vcleVehicleResponsibleEmps;
    }




}


