package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VclePriceOil generated by hbm2java
 */
@Entity
@Table(name="VCLE_PRICE_OIL"
    ,schema="CODEATOR"
)
public class VclePriceOil  implements java.io.Serializable {


     private VclePriceOilId id;
     private VclePriceDateMaster vclePriceDateMaster;
     private VcleOilType vcleOilType;
     private BigDecimal oilPrice;

    public VclePriceOil() {
    }

    public VclePriceOil(VclePriceOilId id, VclePriceDateMaster vclePriceDateMaster, VcleOilType vcleOilType, BigDecimal oilPrice) {
       this.id = id;
       this.vclePriceDateMaster = vclePriceDateMaster;
       this.vcleOilType = vcleOilType;
       this.oilPrice = oilPrice;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="priceType", column=@Column(name="PRICE_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="priceDate", column=@Column(name="PRICE_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="oilType", column=@Column(name="OIL_TYPE", nullable=false, precision=2, scale=0) ) } )
    public VclePriceOilId getId() {
        return this.id;
    }
    
    public void setId(VclePriceOilId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="PRICE_TYPE", referencedColumnName="PRICE_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PRICE_DATE", referencedColumnName="PRICE_DATE", nullable=false, insertable=false, updatable=false) } )
    public VclePriceDateMaster getVclePriceDateMaster() {
        return this.vclePriceDateMaster;
    }
    
    public void setVclePriceDateMaster(VclePriceDateMaster vclePriceDateMaster) {
        this.vclePriceDateMaster = vclePriceDateMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="OIL_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleOilType getVcleOilType() {
        return this.vcleOilType;
    }
    
    public void setVcleOilType(VcleOilType vcleOilType) {
        this.vcleOilType = vcleOilType;
    }

    
    @Column(name="OIL_PRICE", nullable=false, precision=7)
    public BigDecimal getOilPrice() {
        return this.oilPrice;
    }
    
    public void setOilPrice(BigDecimal oilPrice) {
        this.oilPrice = oilPrice;
    }




}


