package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleDistributeDateAhramAm generated by hbm2java
 */
@Entity
@Table(name="VCLE_DISTRIBUTE_DATE_AHRAM_AM"
    ,schema="CODEATOR"
)
public class VcleDistributeDateAhramAm  implements java.io.Serializable {


     private VcleDistributeDateAhramAmId id;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private VcleDistributeLocation vcleDistributeLocation;
     private VcleDistributeDate vcleDistributeDate;
     private Date execMm;
     private BigDecimal val;
     private Boolean chkLock;

    public VcleDistributeDateAhramAm() {
    }

	
    public VcleDistributeDateAhramAm(VcleDistributeDateAhramAmId id, VcleEmployeeMaster vcleEmployeeMaster, VcleDistributeLocation vcleDistributeLocation, VcleDistributeDate vcleDistributeDate) {
        this.id = id;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
        this.vcleDistributeLocation = vcleDistributeLocation;
        this.vcleDistributeDate = vcleDistributeDate;
    }
    public VcleDistributeDateAhramAm(VcleDistributeDateAhramAmId id, VcleEmployeeMaster vcleEmployeeMaster, VcleDistributeLocation vcleDistributeLocation, VcleDistributeDate vcleDistributeDate, Date execMm, BigDecimal val, Boolean chkLock) {
       this.id = id;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.vcleDistributeLocation = vcleDistributeLocation;
       this.vcleDistributeDate = vcleDistributeDate;
       this.execMm = execMm;
       this.val = val;
       this.chkLock = chkLock;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="travelMm", column=@Column(name="TRAVEL_MM", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="fiscalYear", column=@Column(name="FISCAL_YEAR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="travelDd", column=@Column(name="TRAVEL_DD", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="travelSp", column=@Column(name="TRAVEL_SP", nullable=false, precision=6, scale=0) ) } )
    public VcleDistributeDateAhramAmId getId() {
        return this.id;
    }
    
    public void setId(VcleDistributeDateAhramAmId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false)
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="DISTRIBUTE_CODE", nullable=false)
    public VcleDistributeLocation getVcleDistributeLocation() {
        return this.vcleDistributeLocation;
    }
    
    public void setVcleDistributeLocation(VcleDistributeLocation vcleDistributeLocation) {
        this.vcleDistributeLocation = vcleDistributeLocation;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="TRAVEL_DD", referencedColumnName="TRAVEL_DD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TRAVEL_MM", referencedColumnName="TRAVEL_MM", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="FISCAL_YEAR", referencedColumnName="FISCAL_YEAR", nullable=false, insertable=false, updatable=false) } )
    public VcleDistributeDate getVcleDistributeDate() {
        return this.vcleDistributeDate;
    }
    
    public void setVcleDistributeDate(VcleDistributeDate vcleDistributeDate) {
        this.vcleDistributeDate = vcleDistributeDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXEC_MM", length=7)
    public Date getExecMm() {
        return this.execMm;
    }
    
    public void setExecMm(Date execMm) {
        this.execMm = execMm;
    }

    
    @Column(name="VAL", precision=7)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="CHK_LOCK", precision=1, scale=0)
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }




}


