package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleEmployeeVacationBal generated by hbm2java
 */
@Entity
@Table(name="VCLE_EMPLOYEE_VACATION_BAL"
    ,schema="CODEATOR"
)
public class VcleEmployeeVacationBal  implements java.io.Serializable {


     private VcleEmployeeVacationBalId id;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private Byte iniVacBal;
     private Byte totalVac;

    public VcleEmployeeVacationBal() {
    }

	
    public VcleEmployeeVacationBal(VcleEmployeeVacationBalId id, VcleEmployeeMaster vcleEmployeeMaster) {
        this.id = id;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleEmployeeVacationBal(VcleEmployeeVacationBalId id, VcleEmployeeMaster vcleEmployeeMaster, Byte iniVacBal, Byte totalVac) {
       this.id = id;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.iniVacBal = iniVacBal;
       this.totalVac = totalVac;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalYear", column=@Column(name="FISCAL_YEAR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ) } )
    public VcleEmployeeVacationBalId getId() {
        return this.id;
    }
    
    public void setId(VcleEmployeeVacationBalId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

    
    @Column(name="INI_VAC_BAL", precision=2, scale=0)
    public Byte getIniVacBal() {
        return this.iniVacBal;
    }
    
    public void setIniVacBal(Byte iniVacBal) {
        this.iniVacBal = iniVacBal;
    }

    
    @Column(name="TOTAL_VAC", precision=2, scale=0)
    public Byte getTotalVac() {
        return this.totalVac;
    }
    
    public void setTotalVac(Byte totalVac) {
        this.totalVac = totalVac;
    }




}


