package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VcleVehicleLicenseReportDtId generated by hbm2java
 */
@Embeddable
public class VcleVehicleLicenseReportDtId  implements java.io.Serializable {


     private boolean reportType;
     private Date fiscalDate;
     private int reportSp;
     private boolean costType;
     private int costCode;

    public VcleVehicleLicenseReportDtId() {
    }

    public VcleVehicleLicenseReportDtId(boolean reportType, Date fiscalDate, int reportSp, boolean costType, int costCode) {
       this.reportType = reportType;
       this.fiscalDate = fiscalDate;
       this.reportSp = reportSp;
       this.costType = costType;
       this.costCode = costCode;
    }
   


    @Column(name="REPORT_TYPE", nullable=false, precision=1, scale=0)
    public boolean isReportType() {
        return this.reportType;
    }
    
    public void setReportType(boolean reportType) {
        this.reportType = reportType;
    }


    @Column(name="FISCAL_DATE", nullable=false, length=7)
    public Date getFiscalDate() {
        return this.fiscalDate;
    }
    
    public void setFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }


    @Column(name="REPORT_SP", nullable=false, precision=6, scale=0)
    public int getReportSp() {
        return this.reportSp;
    }
    
    public void setReportSp(int reportSp) {
        this.reportSp = reportSp;
    }


    @Column(name="COST_TYPE", nullable=false, precision=1, scale=0)
    public boolean isCostType() {
        return this.costType;
    }
    
    public void setCostType(boolean costType) {
        this.costType = costType;
    }


    @Column(name="COST_CODE", nullable=false, precision=6, scale=0)
    public int getCostCode() {
        return this.costCode;
    }
    
    public void setCostCode(int costCode) {
        this.costCode = costCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleVehicleLicenseReportDtId) ) return false;
		 VcleVehicleLicenseReportDtId castOther = ( VcleVehicleLicenseReportDtId ) other; 
         
		 return (this.isReportType()==castOther.isReportType())
 && ( (this.getFiscalDate()==castOther.getFiscalDate()) || ( this.getFiscalDate()!=null && castOther.getFiscalDate()!=null && this.getFiscalDate().equals(castOther.getFiscalDate()) ) )
 && (this.getReportSp()==castOther.getReportSp())
 && (this.isCostType()==castOther.isCostType())
 && (this.getCostCode()==castOther.getCostCode());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (this.isReportType()?1:0);
         result = 37 * result + ( getFiscalDate() == null ? 0 : this.getFiscalDate().hashCode() );
         result = 37 * result + this.getReportSp();
         result = 37 * result + (this.isCostType()?1:0);
         result = 37 * result + this.getCostCode();
         return result;
   }   


}


