package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleEmployeeAbsent generated by hbm2java
 */
@Entity
@Table(name="VCLE_EMPLOYEE_ABSENT"
    ,schema="CODEATOR"
)
public class VcleEmployeeAbsent  implements java.io.Serializable {


     private VcleEmployeeAbsentId id;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private Date elaDate;
     private Boolean absentType;

    public VcleEmployeeAbsent() {
    }

	
    public VcleEmployeeAbsent(VcleEmployeeAbsentId id, VcleEmployeeMaster vcleEmployeeMaster) {
        this.id = id;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleEmployeeAbsent(VcleEmployeeAbsentId id, VcleEmployeeMaster vcleEmployeeMaster, Date elaDate, Boolean absentType) {
       this.id = id;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.elaDate = elaDate;
       this.absentType = absentType;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="workshopeCode", column=@Column(name="WORKSHOPE_CODE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="fromDate", column=@Column(name="FROM_DATE", nullable=false, length=7) ) } )
    public VcleEmployeeAbsentId getId() {
        return this.id;
    }
    
    public void setId(VcleEmployeeAbsentId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ELA_DATE", length=7)
    public Date getElaDate() {
        return this.elaDate;
    }
    
    public void setElaDate(Date elaDate) {
        this.elaDate = elaDate;
    }

    
    @Column(name="ABSENT_TYPE", precision=1, scale=0)
    public Boolean getAbsentType() {
        return this.absentType;
    }
    
    public void setAbsentType(Boolean absentType) {
        this.absentType = absentType;
    }




}


