package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleNotifyLocal generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_NOTIFY_LOCAL"
    ,schema="CODEATOR"
)
public class VcleVehicleNotifyLocal  implements java.io.Serializable {


     private VcleVehicleNotifyLocalId id;
     private Byte localSeq;
     private Date localStartDate;
     private Date localEndDate;
     private String localRmrk;

    public VcleVehicleNotifyLocal() {
    }

	
    public VcleVehicleNotifyLocal(VcleVehicleNotifyLocalId id) {
        this.id = id;
    }
    public VcleVehicleNotifyLocal(VcleVehicleNotifyLocalId id, Byte localSeq, Date localStartDate, Date localEndDate, String localRmrk) {
       this.id = id;
       this.localSeq = localSeq;
       this.localStartDate = localStartDate;
       this.localEndDate = localEndDate;
       this.localRmrk = localRmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="employeeIdEmp", column=@Column(name="EMPLOYEE_ID_EMP", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="instructionNo", column=@Column(name="INSTRUCTION_NO", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="workshopeCode", column=@Column(name="WORKSHOPE_CODE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="localSp", column=@Column(name="LOCAL_SP", nullable=false, precision=2, scale=0) ) } )
    public VcleVehicleNotifyLocalId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleNotifyLocalId id) {
        this.id = id;
    }

    
    @Column(name="LOCAL_SEQ", precision=2, scale=0)
    public Byte getLocalSeq() {
        return this.localSeq;
    }
    
    public void setLocalSeq(Byte localSeq) {
        this.localSeq = localSeq;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOCAL_START_DATE", length=7)
    public Date getLocalStartDate() {
        return this.localStartDate;
    }
    
    public void setLocalStartDate(Date localStartDate) {
        this.localStartDate = localStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOCAL_END_DATE", length=7)
    public Date getLocalEndDate() {
        return this.localEndDate;
    }
    
    public void setLocalEndDate(Date localEndDate) {
        this.localEndDate = localEndDate;
    }

    
    @Column(name="LOCAL_RMRK", length=400)
    public String getLocalRmrk() {
        return this.localRmrk;
    }
    
    public void setLocalRmrk(String localRmrk) {
        this.localRmrk = localRmrk;
    }




}


