package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleEmployeeMaster generated by hbm2java
 */
@Entity
@Table(name="VCLE_EMPLOYEE_MASTER"
    ,schema="CODEATOR"
)
public class VcleEmployeeMaster  implements java.io.Serializable {


     private long employeeId;
     private VcleWorkType vcleWorkType;
     private VcleShiftType vcleShiftType;
     private VcleMainCostCode vcleMainCostCode;
     private VcleMainCost vcleMainCost;
     private VcleJobType vcleJobType;
     private PerLocationCode perLocationCode;
     private long employeeNo;
     private String nationalNo;
     private Boolean licenseDgree;
     private Date licenseFromDate;
     private Integer cardCode;
     private Date licenseToDate;
     private Boolean licensePeriod;
     private Date birthDate;
     private String address;
     private String cellPhone1;
     private String cellPhone2;
     private Integer homePhone;
     private Byte timeFromHh;
     private Byte timeToHh;
     private Byte timeFromMi;
     private Byte timeToMi;
     private Date jobDate;
     private String jobNameBasic;
     private String empName;
     private Boolean licenseState;
     private Integer sectionNoOld;
     private Long depNoOld;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Boolean chkOwner;
     private Set<VcleDistributeDateAhramPm> vcleDistributeDateAhramPms = new HashSet<VcleDistributeDateAhramPm>(0);
     private Set<VcleWorkTypeJoin> vcleWorkTypeJoins = new HashSet<VcleWorkTypeJoin>(0);
     private Set<VcleFuelBookNumber> vcleFuelBookNumbers = new HashSet<VcleFuelBookNumber>(0);
     private Set<VcleDistributeDateAhramAm> vcleDistributeDateAhramAms = new HashSet<VcleDistributeDateAhramAm>(0);
     private Set<VcleEmployeeAbsent> vcleEmployeeAbsents = new HashSet<VcleEmployeeAbsent>(0);
     private VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp;
     private Set<VcleVehicleReceive> vcleVehicleReceives = new HashSet<VcleVehicleReceive>(0);
     private Set<VcleVehicleNotifyTransDtl> vcleVehicleNotifyTransDtls = new HashSet<VcleVehicleNotifyTransDtl>(0);
     private Set<VcleVehicleAccident> vcleVehicleAccidents = new HashSet<VcleVehicleAccident>(0);
     private Set<VcleEmployeeVacationBal> vcleEmployeeVacationBals = new HashSet<VcleEmployeeVacationBal>(0);
     private Set<VcleDistributeMonthsEmp> vcleDistributeMonthsEmps = new HashSet<VcleDistributeMonthsEmp>(0);
     private Set<VcleEmployeeOvertime> vcleEmployeeOvertimes = new HashSet<VcleEmployeeOvertime>(0);
     private Set<VcleIssueDocument> vcleIssueDocuments = new HashSet<VcleIssueDocument>(0);
     private Set<VcleVehicleResponsible> vcleVehicleResponsibles = new HashSet<VcleVehicleResponsible>(0);
     private VcleWorkOnSaturdayEmp vcleWorkOnSaturdayEmp;
     private Set<VcleEmployeeVacation> vcleEmployeeVacations = new HashSet<VcleEmployeeVacation>(0);
     private Set<VcleFuelIssueLiquid> vcleFuelIssueLiquids = new HashSet<VcleFuelIssueLiquid>(0);
     private Set<VcleVehicleInstructionTech> vcleVehicleInstructionTeches = new HashSet<VcleVehicleInstructionTech>(0);
     private Set<VcleWorkshopeResponse> vcleWorkshopeResponses = new HashSet<VcleWorkshopeResponse>(0);
     private Set<VcleWorkOnSaturdays> vcleWorkOnSaturdayses = new HashSet<VcleWorkOnSaturdays>(0);

    public VcleEmployeeMaster() {
    }

	
    public VcleEmployeeMaster(long employeeId, long employeeNo) {
        this.employeeId = employeeId;
        this.employeeNo = employeeNo;
    }
    public VcleEmployeeMaster(long employeeId, VcleWorkType vcleWorkType, VcleShiftType vcleShiftType, VcleMainCostCode vcleMainCostCode, VcleMainCost vcleMainCost, VcleJobType vcleJobType, PerLocationCode perLocationCode, long employeeNo, String nationalNo, Boolean licenseDgree, Date licenseFromDate, Integer cardCode, Date licenseToDate, Boolean licensePeriod, Date birthDate, String address, String cellPhone1, String cellPhone2, Integer homePhone, Byte timeFromHh, Byte timeToHh, Byte timeFromMi, Byte timeToMi, Date jobDate, String jobNameBasic, String empName, Boolean licenseState, Integer sectionNoOld, Long depNoOld, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Boolean chkOwner, Set<VcleDistributeDateAhramPm> vcleDistributeDateAhramPms, Set<VcleWorkTypeJoin> vcleWorkTypeJoins, Set<VcleFuelBookNumber> vcleFuelBookNumbers, Set<VcleDistributeDateAhramAm> vcleDistributeDateAhramAms, Set<VcleEmployeeAbsent> vcleEmployeeAbsents, VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp, Set<VcleVehicleReceive> vcleVehicleReceives, Set<VcleVehicleNotifyTransDtl> vcleVehicleNotifyTransDtls, Set<VcleVehicleAccident> vcleVehicleAccidents, Set<VcleEmployeeVacationBal> vcleEmployeeVacationBals, Set<VcleDistributeMonthsEmp> vcleDistributeMonthsEmps, Set<VcleEmployeeOvertime> vcleEmployeeOvertimes, Set<VcleIssueDocument> vcleIssueDocuments, Set<VcleVehicleResponsible> vcleVehicleResponsibles, VcleWorkOnSaturdayEmp vcleWorkOnSaturdayEmp, Set<VcleEmployeeVacation> vcleEmployeeVacations, Set<VcleFuelIssueLiquid> vcleFuelIssueLiquids, Set<VcleVehicleInstructionTech> vcleVehicleInstructionTeches, Set<VcleWorkshopeResponse> vcleWorkshopeResponses, Set<VcleWorkOnSaturdays> vcleWorkOnSaturdayses) {
       this.employeeId = employeeId;
       this.vcleWorkType = vcleWorkType;
       this.vcleShiftType = vcleShiftType;
       this.vcleMainCostCode = vcleMainCostCode;
       this.vcleMainCost = vcleMainCost;
       this.vcleJobType = vcleJobType;
       this.perLocationCode = perLocationCode;
       this.employeeNo = employeeNo;
       this.nationalNo = nationalNo;
       this.licenseDgree = licenseDgree;
       this.licenseFromDate = licenseFromDate;
       this.cardCode = cardCode;
       this.licenseToDate = licenseToDate;
       this.licensePeriod = licensePeriod;
       this.birthDate = birthDate;
       this.address = address;
       this.cellPhone1 = cellPhone1;
       this.cellPhone2 = cellPhone2;
       this.homePhone = homePhone;
       this.timeFromHh = timeFromHh;
       this.timeToHh = timeToHh;
       this.timeFromMi = timeFromMi;
       this.timeToMi = timeToMi;
       this.jobDate = jobDate;
       this.jobNameBasic = jobNameBasic;
       this.empName = empName;
       this.licenseState = licenseState;
       this.sectionNoOld = sectionNoOld;
       this.depNoOld = depNoOld;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.chkOwner = chkOwner;
       this.vcleDistributeDateAhramPms = vcleDistributeDateAhramPms;
       this.vcleWorkTypeJoins = vcleWorkTypeJoins;
       this.vcleFuelBookNumbers = vcleFuelBookNumbers;
       this.vcleDistributeDateAhramAms = vcleDistributeDateAhramAms;
       this.vcleEmployeeAbsents = vcleEmployeeAbsents;
       this.vcleVehicleResponsibleEmp = vcleVehicleResponsibleEmp;
       this.vcleVehicleReceives = vcleVehicleReceives;
       this.vcleVehicleNotifyTransDtls = vcleVehicleNotifyTransDtls;
       this.vcleVehicleAccidents = vcleVehicleAccidents;
       this.vcleEmployeeVacationBals = vcleEmployeeVacationBals;
       this.vcleDistributeMonthsEmps = vcleDistributeMonthsEmps;
       this.vcleEmployeeOvertimes = vcleEmployeeOvertimes;
       this.vcleIssueDocuments = vcleIssueDocuments;
       this.vcleVehicleResponsibles = vcleVehicleResponsibles;
       this.vcleWorkOnSaturdayEmp = vcleWorkOnSaturdayEmp;
       this.vcleEmployeeVacations = vcleEmployeeVacations;
       this.vcleFuelIssueLiquids = vcleFuelIssueLiquids;
       this.vcleVehicleInstructionTeches = vcleVehicleInstructionTeches;
       this.vcleWorkshopeResponses = vcleWorkshopeResponses;
       this.vcleWorkOnSaturdayses = vcleWorkOnSaturdayses;
    }
   
     @Id 

    
    @Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0)
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="WORK_TYPE")
    public VcleWorkType getVcleWorkType() {
        return this.vcleWorkType;
    }
    
    public void setVcleWorkType(VcleWorkType vcleWorkType) {
        this.vcleWorkType = vcleWorkType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SHIFT_TYPE")
    public VcleShiftType getVcleShiftType() {
        return this.vcleShiftType;
    }
    
    public void setVcleShiftType(VcleShiftType vcleShiftType) {
        this.vcleShiftType = vcleShiftType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COST_CODE")
    public VcleMainCostCode getVcleMainCostCode() {
        return this.vcleMainCostCode;
    }
    
    public void setVcleMainCostCode(VcleMainCostCode vcleMainCostCode) {
        this.vcleMainCostCode = vcleMainCostCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="MAIN_CODE")
    public VcleMainCost getVcleMainCost() {
        return this.vcleMainCost;
    }
    
    public void setVcleMainCost(VcleMainCost vcleMainCost) {
        this.vcleMainCost = vcleMainCost;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="JOB_TYPE")
    public VcleJobType getVcleJobType() {
        return this.vcleJobType;
    }
    
    public void setVcleJobType(VcleJobType vcleJobType) {
        this.vcleJobType = vcleJobType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE"), 
        @JoinColumn(name="LOC_CODE", referencedColumnName="LOC_CODE") } )
    public PerLocationCode getPerLocationCode() {
        return this.perLocationCode;
    }
    
    public void setPerLocationCode(PerLocationCode perLocationCode) {
        this.perLocationCode = perLocationCode;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, precision=10, scale=0)
    public long getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(long employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="NATIONAL_NO", length=15)
    public String getNationalNo() {
        return this.nationalNo;
    }
    
    public void setNationalNo(String nationalNo) {
        this.nationalNo = nationalNo;
    }

    
    @Column(name="LICENSE_DGREE", precision=1, scale=0)
    public Boolean getLicenseDgree() {
        return this.licenseDgree;
    }
    
    public void setLicenseDgree(Boolean licenseDgree) {
        this.licenseDgree = licenseDgree;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LICENSE_FROM_DATE", length=7)
    public Date getLicenseFromDate() {
        return this.licenseFromDate;
    }
    
    public void setLicenseFromDate(Date licenseFromDate) {
        this.licenseFromDate = licenseFromDate;
    }

    
    @Column(name="CARD_CODE", precision=6, scale=0)
    public Integer getCardCode() {
        return this.cardCode;
    }
    
    public void setCardCode(Integer cardCode) {
        this.cardCode = cardCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LICENSE_TO_DATE", length=7)
    public Date getLicenseToDate() {
        return this.licenseToDate;
    }
    
    public void setLicenseToDate(Date licenseToDate) {
        this.licenseToDate = licenseToDate;
    }

    
    @Column(name="LICENSE_PERIOD", precision=1, scale=0)
    public Boolean getLicensePeriod() {
        return this.licensePeriod;
    }
    
    public void setLicensePeriod(Boolean licensePeriod) {
        this.licensePeriod = licensePeriod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BIRTH_DATE", length=7)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="ADDRESS", length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="CELL_PHONE1", length=11)
    public String getCellPhone1() {
        return this.cellPhone1;
    }
    
    public void setCellPhone1(String cellPhone1) {
        this.cellPhone1 = cellPhone1;
    }

    
    @Column(name="CELL_PHONE2", length=11)
    public String getCellPhone2() {
        return this.cellPhone2;
    }
    
    public void setCellPhone2(String cellPhone2) {
        this.cellPhone2 = cellPhone2;
    }

    
    @Column(name="HOME_PHONE", precision=8, scale=0)
    public Integer getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(Integer homePhone) {
        this.homePhone = homePhone;
    }

    
    @Column(name="TIME_FROM_HH", precision=2, scale=0)
    public Byte getTimeFromHh() {
        return this.timeFromHh;
    }
    
    public void setTimeFromHh(Byte timeFromHh) {
        this.timeFromHh = timeFromHh;
    }

    
    @Column(name="TIME_TO_HH", precision=2, scale=0)
    public Byte getTimeToHh() {
        return this.timeToHh;
    }
    
    public void setTimeToHh(Byte timeToHh) {
        this.timeToHh = timeToHh;
    }

    
    @Column(name="TIME_FROM_MI", precision=2, scale=0)
    public Byte getTimeFromMi() {
        return this.timeFromMi;
    }
    
    public void setTimeFromMi(Byte timeFromMi) {
        this.timeFromMi = timeFromMi;
    }

    
    @Column(name="TIME_TO_MI", precision=2, scale=0)
    public Byte getTimeToMi() {
        return this.timeToMi;
    }
    
    public void setTimeToMi(Byte timeToMi) {
        this.timeToMi = timeToMi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="JOB_DATE", length=7)
    public Date getJobDate() {
        return this.jobDate;
    }
    
    public void setJobDate(Date jobDate) {
        this.jobDate = jobDate;
    }

    
    @Column(name="JOB_NAME_BASIC", length=100)
    public String getJobNameBasic() {
        return this.jobNameBasic;
    }
    
    public void setJobNameBasic(String jobNameBasic) {
        this.jobNameBasic = jobNameBasic;
    }

    
    @Column(name="EMP_NAME", length=75)
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    
    @Column(name="LICENSE_STATE", precision=1, scale=0)
    public Boolean getLicenseState() {
        return this.licenseState;
    }
    
    public void setLicenseState(Boolean licenseState) {
        this.licenseState = licenseState;
    }

    
    @Column(name="SECTION_NO_OLD", precision=5, scale=0)
    public Integer getSectionNoOld() {
        return this.sectionNoOld;
    }
    
    public void setSectionNoOld(Integer sectionNoOld) {
        this.sectionNoOld = sectionNoOld;
    }

    
    @Column(name="DEP_NO_OLD", precision=10, scale=0)
    public Long getDepNoOld() {
        return this.depNoOld;
    }
    
    public void setDepNoOld(Long depNoOld) {
        this.depNoOld = depNoOld;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    
    @Column(name="CHK_OWNER", precision=1, scale=0)
    public Boolean getChkOwner() {
        return this.chkOwner;
    }
    
    public void setChkOwner(Boolean chkOwner) {
        this.chkOwner = chkOwner;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleDistributeDateAhramPm> getVcleDistributeDateAhramPms() {
        return this.vcleDistributeDateAhramPms;
    }
    
    public void setVcleDistributeDateAhramPms(Set<VcleDistributeDateAhramPm> vcleDistributeDateAhramPms) {
        this.vcleDistributeDateAhramPms = vcleDistributeDateAhramPms;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleWorkTypeJoin> getVcleWorkTypeJoins() {
        return this.vcleWorkTypeJoins;
    }
    
    public void setVcleWorkTypeJoins(Set<VcleWorkTypeJoin> vcleWorkTypeJoins) {
        this.vcleWorkTypeJoins = vcleWorkTypeJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleFuelBookNumber> getVcleFuelBookNumbers() {
        return this.vcleFuelBookNumbers;
    }
    
    public void setVcleFuelBookNumbers(Set<VcleFuelBookNumber> vcleFuelBookNumbers) {
        this.vcleFuelBookNumbers = vcleFuelBookNumbers;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleDistributeDateAhramAm> getVcleDistributeDateAhramAms() {
        return this.vcleDistributeDateAhramAms;
    }
    
    public void setVcleDistributeDateAhramAms(Set<VcleDistributeDateAhramAm> vcleDistributeDateAhramAms) {
        this.vcleDistributeDateAhramAms = vcleDistributeDateAhramAms;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleEmployeeAbsent> getVcleEmployeeAbsents() {
        return this.vcleEmployeeAbsents;
    }
    
    public void setVcleEmployeeAbsents(Set<VcleEmployeeAbsent> vcleEmployeeAbsents) {
        this.vcleEmployeeAbsents = vcleEmployeeAbsents;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public VcleVehicleResponsibleEmp getVcleVehicleResponsibleEmp() {
        return this.vcleVehicleResponsibleEmp;
    }
    
    public void setVcleVehicleResponsibleEmp(VcleVehicleResponsibleEmp vcleVehicleResponsibleEmp) {
        this.vcleVehicleResponsibleEmp = vcleVehicleResponsibleEmp;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleVehicleReceive> getVcleVehicleReceives() {
        return this.vcleVehicleReceives;
    }
    
    public void setVcleVehicleReceives(Set<VcleVehicleReceive> vcleVehicleReceives) {
        this.vcleVehicleReceives = vcleVehicleReceives;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleVehicleNotifyTransDtl> getVcleVehicleNotifyTransDtls() {
        return this.vcleVehicleNotifyTransDtls;
    }
    
    public void setVcleVehicleNotifyTransDtls(Set<VcleVehicleNotifyTransDtl> vcleVehicleNotifyTransDtls) {
        this.vcleVehicleNotifyTransDtls = vcleVehicleNotifyTransDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleVehicleAccident> getVcleVehicleAccidents() {
        return this.vcleVehicleAccidents;
    }
    
    public void setVcleVehicleAccidents(Set<VcleVehicleAccident> vcleVehicleAccidents) {
        this.vcleVehicleAccidents = vcleVehicleAccidents;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleEmployeeVacationBal> getVcleEmployeeVacationBals() {
        return this.vcleEmployeeVacationBals;
    }
    
    public void setVcleEmployeeVacationBals(Set<VcleEmployeeVacationBal> vcleEmployeeVacationBals) {
        this.vcleEmployeeVacationBals = vcleEmployeeVacationBals;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleDistributeMonthsEmp> getVcleDistributeMonthsEmps() {
        return this.vcleDistributeMonthsEmps;
    }
    
    public void setVcleDistributeMonthsEmps(Set<VcleDistributeMonthsEmp> vcleDistributeMonthsEmps) {
        this.vcleDistributeMonthsEmps = vcleDistributeMonthsEmps;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleEmployeeOvertime> getVcleEmployeeOvertimes() {
        return this.vcleEmployeeOvertimes;
    }
    
    public void setVcleEmployeeOvertimes(Set<VcleEmployeeOvertime> vcleEmployeeOvertimes) {
        this.vcleEmployeeOvertimes = vcleEmployeeOvertimes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleIssueDocument> getVcleIssueDocuments() {
        return this.vcleIssueDocuments;
    }
    
    public void setVcleIssueDocuments(Set<VcleIssueDocument> vcleIssueDocuments) {
        this.vcleIssueDocuments = vcleIssueDocuments;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleVehicleResponsible> getVcleVehicleResponsibles() {
        return this.vcleVehicleResponsibles;
    }
    
    public void setVcleVehicleResponsibles(Set<VcleVehicleResponsible> vcleVehicleResponsibles) {
        this.vcleVehicleResponsibles = vcleVehicleResponsibles;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public VcleWorkOnSaturdayEmp getVcleWorkOnSaturdayEmp() {
        return this.vcleWorkOnSaturdayEmp;
    }
    
    public void setVcleWorkOnSaturdayEmp(VcleWorkOnSaturdayEmp vcleWorkOnSaturdayEmp) {
        this.vcleWorkOnSaturdayEmp = vcleWorkOnSaturdayEmp;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleEmployeeVacation> getVcleEmployeeVacations() {
        return this.vcleEmployeeVacations;
    }
    
    public void setVcleEmployeeVacations(Set<VcleEmployeeVacation> vcleEmployeeVacations) {
        this.vcleEmployeeVacations = vcleEmployeeVacations;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleFuelIssueLiquid> getVcleFuelIssueLiquids() {
        return this.vcleFuelIssueLiquids;
    }
    
    public void setVcleFuelIssueLiquids(Set<VcleFuelIssueLiquid> vcleFuelIssueLiquids) {
        this.vcleFuelIssueLiquids = vcleFuelIssueLiquids;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleVehicleInstructionTech> getVcleVehicleInstructionTeches() {
        return this.vcleVehicleInstructionTeches;
    }
    
    public void setVcleVehicleInstructionTeches(Set<VcleVehicleInstructionTech> vcleVehicleInstructionTeches) {
        this.vcleVehicleInstructionTeches = vcleVehicleInstructionTeches;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleWorkshopeResponse> getVcleWorkshopeResponses() {
        return this.vcleWorkshopeResponses;
    }
    
    public void setVcleWorkshopeResponses(Set<VcleWorkshopeResponse> vcleWorkshopeResponses) {
        this.vcleWorkshopeResponses = vcleWorkshopeResponses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleEmployeeMaster")
    public Set<VcleWorkOnSaturdays> getVcleWorkOnSaturdayses() {
        return this.vcleWorkOnSaturdayses;
    }
    
    public void setVcleWorkOnSaturdayses(Set<VcleWorkOnSaturdays> vcleWorkOnSaturdayses) {
        this.vcleWorkOnSaturdayses = vcleWorkOnSaturdayses;
    }




}


