package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleVehicleDriverJoin generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_DRIVER_JOIN"
    ,schema="CODEATOR"
)
public class VcleVehicleDriverJoin  implements java.io.Serializable {


     private VcleVehicleDriverJoinId id;
     private VcleVehicleMaster vcleVehicleMaster;
     private PerEmploymentMaster perEmploymentMaster;
     private PerDeptOld perDeptOld;
     private String boardNumber;
     private Boolean driverType;
     private Integer boardNumberOld;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;
     private String rmrk;

    public VcleVehicleDriverJoin() {
    }

	
    public VcleVehicleDriverJoin(VcleVehicleDriverJoinId id, VcleVehicleMaster vcleVehicleMaster, PerEmploymentMaster perEmploymentMaster, String boardNumber) {
        this.id = id;
        this.vcleVehicleMaster = vcleVehicleMaster;
        this.perEmploymentMaster = perEmploymentMaster;
        this.boardNumber = boardNumber;
    }
    public VcleVehicleDriverJoin(VcleVehicleDriverJoinId id, VcleVehicleMaster vcleVehicleMaster, PerEmploymentMaster perEmploymentMaster, PerDeptOld perDeptOld, String boardNumber, Boolean driverType, Integer boardNumberOld, Integer boardDigital, String boardAlfa1, String boardAlfa2, String boardAlfa3, String rmrk) {
       this.id = id;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.perEmploymentMaster = perEmploymentMaster;
       this.perDeptOld = perDeptOld;
       this.boardNumber = boardNumber;
       this.driverType = driverType;
       this.boardNumberOld = boardNumberOld;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
       this.rmrk = rmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ) } )
    public VcleVehicleDriverJoinId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleDriverJoinId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD"), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD") } )
    public PerDeptOld getPerDeptOld() {
        return this.perDeptOld;
    }
    
    public void setPerDeptOld(PerDeptOld perDeptOld) {
        this.perDeptOld = perDeptOld;
    }

    
    @Column(name="BOARD_NUMBER", nullable=false, length=12)
    public String getBoardNumber() {
        return this.boardNumber;
    }
    
    public void setBoardNumber(String boardNumber) {
        this.boardNumber = boardNumber;
    }

    
    @Column(name="DRIVER_TYPE", precision=1, scale=0)
    public Boolean getDriverType() {
        return this.driverType;
    }
    
    public void setDriverType(Boolean driverType) {
        this.driverType = driverType;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


