package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleMaintanceRepairDtl generated by hbm2java
 */
@Entity
@Table(name="VCLE_MAINTANCE_REPAIR_DTL"
    ,schema="CODEATOR"
)
public class VcleMaintanceRepairDtl  implements java.io.Serializable {


     private VcleMaintanceRepairDtlId id;
     private VcleVehicleRepairType vcleVehicleRepairType;
     private VcleSuspendType vcleSuspendType;
     private VcleMaintanceRepair vcleMaintanceRepair;
     private String locCode;
     private Date fiscalDate;
     private Byte invoiceType;
     private BigDecimal qty;
     private Boolean itemGha;
     private String invoiceSp;
     private String locationCode;
     private Boolean storeType;
     private Long storeCode;
     private Long issueNo;
     private Long itemNumber;
     private Long storeCodeItem;
     private String rmrk;

    public VcleMaintanceRepairDtl() {
    }

	
    public VcleMaintanceRepairDtl(VcleMaintanceRepairDtlId id, VcleMaintanceRepair vcleMaintanceRepair) {
        this.id = id;
        this.vcleMaintanceRepair = vcleMaintanceRepair;
    }
    public VcleMaintanceRepairDtl(VcleMaintanceRepairDtlId id, VcleVehicleRepairType vcleVehicleRepairType, VcleSuspendType vcleSuspendType, VcleMaintanceRepair vcleMaintanceRepair, String locCode, Date fiscalDate, Byte invoiceType, BigDecimal qty, Boolean itemGha, String invoiceSp, String locationCode, Boolean storeType, Long storeCode, Long issueNo, Long itemNumber, Long storeCodeItem, String rmrk) {
       this.id = id;
       this.vcleVehicleRepairType = vcleVehicleRepairType;
       this.vcleSuspendType = vcleSuspendType;
       this.vcleMaintanceRepair = vcleMaintanceRepair;
       this.locCode = locCode;
       this.fiscalDate = fiscalDate;
       this.invoiceType = invoiceType;
       this.qty = qty;
       this.itemGha = itemGha;
       this.invoiceSp = invoiceSp;
       this.locationCode = locationCode;
       this.storeType = storeType;
       this.storeCode = storeCode;
       this.issueNo = issueNo;
       this.itemNumber = itemNumber;
       this.storeCodeItem = storeCodeItem;
       this.rmrk = rmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="costCode", column=@Column(name="COST_CODE", nullable=false, length=10) ), 
        @AttributeOverride(name="employeeIdHave", column=@Column(name="EMPLOYEE_ID_HAVE", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="instructionDate", column=@Column(name="INSTRUCTION_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="enterDate", column=@Column(name="ENTER_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="notifyDate", column=@Column(name="NOTIFY_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="repairSeq", column=@Column(name="REPAIR_SEQ", nullable=false, precision=4, scale=0) ) } )
    public VcleMaintanceRepairDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleMaintanceRepairDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="REPAIR_TYPE")
    public VcleVehicleRepairType getVcleVehicleRepairType() {
        return this.vcleVehicleRepairType;
    }
    
    public void setVcleVehicleRepairType(VcleVehicleRepairType vcleVehicleRepairType) {
        this.vcleVehicleRepairType = vcleVehicleRepairType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUSPEND_CODE")
    public VcleSuspendType getVcleSuspendType() {
        return this.vcleSuspendType;
    }
    
    public void setVcleSuspendType(VcleSuspendType vcleSuspendType) {
        this.vcleSuspendType = vcleSuspendType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="NOTIFY_DATE", referencedColumnName="NOTIFY_DATE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="INSTRUCTION_DATE", referencedColumnName="INSTRUCTION_DATE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="VEHICLE_SP", referencedColumnName="VEHICLE_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMPLOYEE_ID_HAVE", referencedColumnName="EMPLOYEE_ID_HAVE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="COST_CODE", referencedColumnName="COST_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ENTER_DATE", referencedColumnName="ENTER_DATE", nullable=false, insertable=false, updatable=false) } )
    public VcleMaintanceRepair getVcleMaintanceRepair() {
        return this.vcleMaintanceRepair;
    }
    
    public void setVcleMaintanceRepair(VcleMaintanceRepair vcleMaintanceRepair) {
        this.vcleMaintanceRepair = vcleMaintanceRepair;
    }

    
    @Column(name="LOC_CODE", length=3)
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FISCAL_DATE", length=7)
    public Date getFiscalDate() {
        return this.fiscalDate;
    }
    
    public void setFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }

    
    @Column(name="INVOICE_TYPE", precision=2, scale=0)
    public Byte getInvoiceType() {
        return this.invoiceType;
    }
    
    public void setInvoiceType(Byte invoiceType) {
        this.invoiceType = invoiceType;
    }

    
    @Column(name="QTY", precision=9)
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    
    @Column(name="ITEM_GHA", precision=1, scale=0)
    public Boolean getItemGha() {
        return this.itemGha;
    }
    
    public void setItemGha(Boolean itemGha) {
        this.itemGha = itemGha;
    }

    
    @Column(name="INVOICE_SP", length=240)
    public String getInvoiceSp() {
        return this.invoiceSp;
    }
    
    public void setInvoiceSp(String invoiceSp) {
        this.invoiceSp = invoiceSp;
    }

    
    @Column(name="LOCATION_CODE", length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    
    @Column(name="STORE_TYPE", precision=1, scale=0)
    public Boolean getStoreType() {
        return this.storeType;
    }
    
    public void setStoreType(Boolean storeType) {
        this.storeType = storeType;
    }

    
    @Column(name="STORE_CODE", precision=12, scale=0)
    public Long getStoreCode() {
        return this.storeCode;
    }
    
    public void setStoreCode(Long storeCode) {
        this.storeCode = storeCode;
    }

    
    @Column(name="ISSUE_NO", precision=11, scale=0)
    public Long getIssueNo() {
        return this.issueNo;
    }
    
    public void setIssueNo(Long issueNo) {
        this.issueNo = issueNo;
    }

    
    @Column(name="ITEM_NUMBER", precision=15, scale=0)
    public Long getItemNumber() {
        return this.itemNumber;
    }
    
    public void setItemNumber(Long itemNumber) {
        this.itemNumber = itemNumber;
    }

    
    @Column(name="STORE_CODE_ITEM", precision=12, scale=0)
    public Long getStoreCodeItem() {
        return this.storeCodeItem;
    }
    
    public void setStoreCodeItem(Long storeCodeItem) {
        this.storeCodeItem = storeCodeItem;
    }

    
    @Column(name="RMRK", length=150)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


