package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleDistributeLocation generated by hbm2java
 */
@Entity
@Table(name="VCLE_DISTRIBUTE_LOCATION"
    ,schema="CODEATOR"
)
public class VcleDistributeLocation  implements java.io.Serializable {


     private int distributeCode;
     private String distributeLocName;
     private BigDecimal travelVal;
     private Boolean chkAhramAm;
     private Boolean chkAhramPm;
     private Set<VcleDistributeDateAhramAm> vcleDistributeDateAhramAms = new HashSet<VcleDistributeDateAhramAm>(0);
     private Set<VcleDistributeDateAhramPm> vcleDistributeDateAhramPms = new HashSet<VcleDistributeDateAhramPm>(0);
     private Set<VcleDistributeMonthsEmp> vcleDistributeMonthsEmps = new HashSet<VcleDistributeMonthsEmp>(0);

    public VcleDistributeLocation() {
    }

	
    public VcleDistributeLocation(int distributeCode, String distributeLocName) {
        this.distributeCode = distributeCode;
        this.distributeLocName = distributeLocName;
    }
    public VcleDistributeLocation(int distributeCode, String distributeLocName, BigDecimal travelVal, Boolean chkAhramAm, Boolean chkAhramPm, Set<VcleDistributeDateAhramAm> vcleDistributeDateAhramAms, Set<VcleDistributeDateAhramPm> vcleDistributeDateAhramPms, Set<VcleDistributeMonthsEmp> vcleDistributeMonthsEmps) {
       this.distributeCode = distributeCode;
       this.distributeLocName = distributeLocName;
       this.travelVal = travelVal;
       this.chkAhramAm = chkAhramAm;
       this.chkAhramPm = chkAhramPm;
       this.vcleDistributeDateAhramAms = vcleDistributeDateAhramAms;
       this.vcleDistributeDateAhramPms = vcleDistributeDateAhramPms;
       this.vcleDistributeMonthsEmps = vcleDistributeMonthsEmps;
    }
   
     @Id 

    
    @Column(name="DISTRIBUTE_CODE", unique=true, nullable=false, precision=6, scale=0)
    public int getDistributeCode() {
        return this.distributeCode;
    }
    
    public void setDistributeCode(int distributeCode) {
        this.distributeCode = distributeCode;
    }

    
    @Column(name="DISTRIBUTE_LOC_NAME", nullable=false, length=75)
    public String getDistributeLocName() {
        return this.distributeLocName;
    }
    
    public void setDistributeLocName(String distributeLocName) {
        this.distributeLocName = distributeLocName;
    }

    
    @Column(name="TRAVEL_VAL", precision=3, scale=1)
    public BigDecimal getTravelVal() {
        return this.travelVal;
    }
    
    public void setTravelVal(BigDecimal travelVal) {
        this.travelVal = travelVal;
    }

    
    @Column(name="CHK_AHRAM_AM", precision=1, scale=0)
    public Boolean getChkAhramAm() {
        return this.chkAhramAm;
    }
    
    public void setChkAhramAm(Boolean chkAhramAm) {
        this.chkAhramAm = chkAhramAm;
    }

    
    @Column(name="CHK_AHRAM_PM", precision=1, scale=0)
    public Boolean getChkAhramPm() {
        return this.chkAhramPm;
    }
    
    public void setChkAhramPm(Boolean chkAhramPm) {
        this.chkAhramPm = chkAhramPm;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleDistributeLocation")
    public Set<VcleDistributeDateAhramAm> getVcleDistributeDateAhramAms() {
        return this.vcleDistributeDateAhramAms;
    }
    
    public void setVcleDistributeDateAhramAms(Set<VcleDistributeDateAhramAm> vcleDistributeDateAhramAms) {
        this.vcleDistributeDateAhramAms = vcleDistributeDateAhramAms;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleDistributeLocation")
    public Set<VcleDistributeDateAhramPm> getVcleDistributeDateAhramPms() {
        return this.vcleDistributeDateAhramPms;
    }
    
    public void setVcleDistributeDateAhramPms(Set<VcleDistributeDateAhramPm> vcleDistributeDateAhramPms) {
        this.vcleDistributeDateAhramPms = vcleDistributeDateAhramPms;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleDistributeLocation")
    public Set<VcleDistributeMonthsEmp> getVcleDistributeMonthsEmps() {
        return this.vcleDistributeMonthsEmps;
    }
    
    public void setVcleDistributeMonthsEmps(Set<VcleDistributeMonthsEmp> vcleDistributeMonthsEmps) {
        this.vcleDistributeMonthsEmps = vcleDistributeMonthsEmps;
    }




}


