package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleProcedureLicenseJoin generated by hbm2java
 */
@Entity
@Table(name="VCLE_PROCEDURE_LICENSE_JOIN"
    ,schema="CODEATOR"
)
public class VcleProcedureLicenseJoin  implements java.io.Serializable {


     private VcleProcedureLicenseJoinId id;
     private VcleVehicleType vcleVehicleType;
     private VcleProcedureLicenseType vcleProcedureLicenseType;
     private VcleCostType vcleCostType;
     private BigDecimal val;

    public VcleProcedureLicenseJoin() {
    }

	
    public VcleProcedureLicenseJoin(VcleProcedureLicenseJoinId id, VcleVehicleType vcleVehicleType, VcleProcedureLicenseType vcleProcedureLicenseType, VcleCostType vcleCostType) {
        this.id = id;
        this.vcleVehicleType = vcleVehicleType;
        this.vcleProcedureLicenseType = vcleProcedureLicenseType;
        this.vcleCostType = vcleCostType;
    }
    public VcleProcedureLicenseJoin(VcleProcedureLicenseJoinId id, VcleVehicleType vcleVehicleType, VcleProcedureLicenseType vcleProcedureLicenseType, VcleCostType vcleCostType, BigDecimal val) {
       this.id = id;
       this.vcleVehicleType = vcleVehicleType;
       this.vcleProcedureLicenseType = vcleProcedureLicenseType;
       this.vcleCostType = vcleCostType;
       this.val = val;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="licenseType", column=@Column(name="LICENSE_TYPE", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="vcleType", column=@Column(name="VCLE_TYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="costCode", column=@Column(name="COST_CODE", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="costType", column=@Column(name="COST_TYPE", nullable=false, precision=1, scale=0) ) } )
    public VcleProcedureLicenseJoinId getId() {
        return this.id;
    }
    
    public void setId(VcleProcedureLicenseJoinId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleVehicleType getVcleVehicleType() {
        return this.vcleVehicleType;
    }
    
    public void setVcleVehicleType(VcleVehicleType vcleVehicleType) {
        this.vcleVehicleType = vcleVehicleType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="LICENSE_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleProcedureLicenseType getVcleProcedureLicenseType() {
        return this.vcleProcedureLicenseType;
    }
    
    public void setVcleProcedureLicenseType(VcleProcedureLicenseType vcleProcedureLicenseType) {
        this.vcleProcedureLicenseType = vcleProcedureLicenseType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="COST_TYPE", referencedColumnName="COST_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="COST_CODE", referencedColumnName="COST_CODE", nullable=false, insertable=false, updatable=false) } )
    public VcleCostType getVcleCostType() {
        return this.vcleCostType;
    }
    
    public void setVcleCostType(VcleCostType vcleCostType) {
        this.vcleCostType = vcleCostType;
    }

    
    @Column(name="VAL", precision=9)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }




}


