package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleWorkTypeJoin generated by hbm2java
 */
@Entity
@Table(name="VCLE_WORK_TYPE_JOIN"
    ,schema="CODEATOR"
)
public class VcleWorkTypeJoin  implements java.io.Serializable {


     private VcleWorkTypeJoinId id;
     private VcleWorkType vcleWorkType;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private String empPass;
     private Set<VcleVehicleNotifyTrans> vcleVehicleNotifyTranses = new HashSet<VcleVehicleNotifyTrans>(0);
     private Set<VcleWorkTypeTransCar> vcleWorkTypeTransCars = new HashSet<VcleWorkTypeTransCar>(0);

    public VcleWorkTypeJoin() {
    }

	
    public VcleWorkTypeJoin(VcleWorkTypeJoinId id, VcleWorkType vcleWorkType, VcleEmployeeMaster vcleEmployeeMaster) {
        this.id = id;
        this.vcleWorkType = vcleWorkType;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleWorkTypeJoin(VcleWorkTypeJoinId id, VcleWorkType vcleWorkType, VcleEmployeeMaster vcleEmployeeMaster, String empPass, Set<VcleVehicleNotifyTrans> vcleVehicleNotifyTranses, Set<VcleWorkTypeTransCar> vcleWorkTypeTransCars) {
       this.id = id;
       this.vcleWorkType = vcleWorkType;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.empPass = empPass;
       this.vcleVehicleNotifyTranses = vcleVehicleNotifyTranses;
       this.vcleWorkTypeTransCars = vcleWorkTypeTransCars;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="workType", column=@Column(name="WORK_TYPE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ) } )
    public VcleWorkTypeJoinId getId() {
        return this.id;
    }
    
    public void setId(VcleWorkTypeJoinId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="WORK_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleWorkType getVcleWorkType() {
        return this.vcleWorkType;
    }
    
    public void setVcleWorkType(VcleWorkType vcleWorkType) {
        this.vcleWorkType = vcleWorkType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

    
    @Column(name="EMP_PASS", length=20)
    public String getEmpPass() {
        return this.empPass;
    }
    
    public void setEmpPass(String empPass) {
        this.empPass = empPass;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkTypeJoin")
    public Set<VcleVehicleNotifyTrans> getVcleVehicleNotifyTranses() {
        return this.vcleVehicleNotifyTranses;
    }
    
    public void setVcleVehicleNotifyTranses(Set<VcleVehicleNotifyTrans> vcleVehicleNotifyTranses) {
        this.vcleVehicleNotifyTranses = vcleVehicleNotifyTranses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleWorkTypeJoin")
    public Set<VcleWorkTypeTransCar> getVcleWorkTypeTransCars() {
        return this.vcleWorkTypeTransCars;
    }
    
    public void setVcleWorkTypeTransCars(Set<VcleWorkTypeTransCar> vcleWorkTypeTransCars) {
        this.vcleWorkTypeTransCars = vcleWorkTypeTransCars;
    }




}


