package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleLicenseDtl generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_LICENSE_DTL"
    ,schema="CODEATOR"
)
public class VcleVehicleLicenseDtl  implements java.io.Serializable {


     private VcleVehicleLicenseDtlId id;
     private VcleVehicleLicenseReport vcleVehicleLicenseReport;
     private VcleVehicleLicense vcleVehicleLicense;
     private VcleCostType vcleCostType;
     private PerEmploymentMaster perEmploymentMaster;
     private Date actionDate;
     private Boolean actionPlace;
     private BigDecimal val;
     private Integer receiptNum;
     private Date receiptDate;
     private String rmrk;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;
     private Integer boardNumberOld;
     private String boardNumber;
     private Short fiscalYear;
     private Long vcIssueDocSp;
     private Boolean costState;
     private Boolean chkPrintCost;
     private Date execMm;
     private Integer vcIssueDocSeq;
     private Boolean chkErrFin;
     private Boolean chkErrLin;
     private String rmrkFin;
     private String rmrkLin;
     private Boolean chkLock;
     private Byte repSeq;

    public VcleVehicleLicenseDtl() {
    }

	
    public VcleVehicleLicenseDtl(VcleVehicleLicenseDtlId id, VcleVehicleLicense vcleVehicleLicense, VcleCostType vcleCostType) {
        this.id = id;
        this.vcleVehicleLicense = vcleVehicleLicense;
        this.vcleCostType = vcleCostType;
    }
    public VcleVehicleLicenseDtl(VcleVehicleLicenseDtlId id, VcleVehicleLicenseReport vcleVehicleLicenseReport, VcleVehicleLicense vcleVehicleLicense, VcleCostType vcleCostType, PerEmploymentMaster perEmploymentMaster, Date actionDate, Boolean actionPlace, BigDecimal val, Integer receiptNum, Date receiptDate, String rmrk, Integer boardDigital, String boardAlfa1, String boardAlfa2, String boardAlfa3, Integer boardNumberOld, String boardNumber, Short fiscalYear, Long vcIssueDocSp, Boolean costState, Boolean chkPrintCost, Date execMm, Integer vcIssueDocSeq, Boolean chkErrFin, Boolean chkErrLin, String rmrkFin, String rmrkLin, Boolean chkLock, Byte repSeq) {
       this.id = id;
       this.vcleVehicleLicenseReport = vcleVehicleLicenseReport;
       this.vcleVehicleLicense = vcleVehicleLicense;
       this.vcleCostType = vcleCostType;
       this.perEmploymentMaster = perEmploymentMaster;
       this.actionDate = actionDate;
       this.actionPlace = actionPlace;
       this.val = val;
       this.receiptNum = receiptNum;
       this.receiptDate = receiptDate;
       this.rmrk = rmrk;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
       this.boardNumberOld = boardNumberOld;
       this.boardNumber = boardNumber;
       this.fiscalYear = fiscalYear;
       this.vcIssueDocSp = vcIssueDocSp;
       this.costState = costState;
       this.chkPrintCost = chkPrintCost;
       this.execMm = execMm;
       this.vcIssueDocSeq = vcIssueDocSeq;
       this.chkErrFin = chkErrFin;
       this.chkErrLin = chkErrLin;
       this.rmrkFin = rmrkFin;
       this.rmrkLin = rmrkLin;
       this.chkLock = chkLock;
       this.repSeq = repSeq;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="licenseType", column=@Column(name="LICENSE_TYPE", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="licenseMm", column=@Column(name="LICENSE_MM", nullable=false, length=7) ), 
        @AttributeOverride(name="costCode", column=@Column(name="COST_CODE", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="costType", column=@Column(name="COST_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="licenseSerial", column=@Column(name="LICENSE_SERIAL", nullable=false, precision=9, scale=0) ) } )
    public VcleVehicleLicenseDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleLicenseDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="REPORT_TYPE", referencedColumnName="REPORT_TYPE"), 
        @JoinColumn(name="FISCAL_DATE", referencedColumnName="FISCAL_DATE"), 
        @JoinColumn(name="REPORT_SP", referencedColumnName="REPORT_SP") } )
    public VcleVehicleLicenseReport getVcleVehicleLicenseReport() {
        return this.vcleVehicleLicenseReport;
    }
    
    public void setVcleVehicleLicenseReport(VcleVehicleLicenseReport vcleVehicleLicenseReport) {
        this.vcleVehicleLicenseReport = vcleVehicleLicenseReport;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="VEHICLE_SP", referencedColumnName="VEHICLE_SP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="LICENSE_MM", referencedColumnName="LICENSE_MM", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="LICENSE_TYPE", referencedColumnName="LICENSE_TYPE", nullable=false, insertable=false, updatable=false) } )
    public VcleVehicleLicense getVcleVehicleLicense() {
        return this.vcleVehicleLicense;
    }
    
    public void setVcleVehicleLicense(VcleVehicleLicense vcleVehicleLicense) {
        this.vcleVehicleLicense = vcleVehicleLicense;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="COST_TYPE", referencedColumnName="COST_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="COST_CODE", referencedColumnName="COST_CODE", nullable=false, insertable=false, updatable=false) } )
    public VcleCostType getVcleCostType() {
        return this.vcleCostType;
    }
    
    public void setVcleCostType(VcleCostType vcleCostType) {
        this.vcleCostType = vcleCostType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACTION_DATE", length=7)
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }

    
    @Column(name="ACTION_PLACE", precision=1, scale=0)
    public Boolean getActionPlace() {
        return this.actionPlace;
    }
    
    public void setActionPlace(Boolean actionPlace) {
        this.actionPlace = actionPlace;
    }

    
    @Column(name="VAL", precision=9)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="RECEIPT_NUM", precision=9, scale=0)
    public Integer getReceiptNum() {
        return this.receiptNum;
    }
    
    public void setReceiptNum(Integer receiptNum) {
        this.receiptNum = receiptNum;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECEIPT_DATE", length=7)
    public Date getReceiptDate() {
        return this.receiptDate;
    }
    
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    
    @Column(name="RMRK", length=150)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    
    @Column(name="BOARD_NUMBER", length=240)
    public String getBoardNumber() {
        return this.boardNumber;
    }
    
    public void setBoardNumber(String boardNumber) {
        this.boardNumber = boardNumber;
    }

    
    @Column(name="FISCAL_YEAR", precision=4, scale=0)
    public Short getFiscalYear() {
        return this.fiscalYear;
    }
    
    public void setFiscalYear(Short fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

    
    @Column(name="VC_ISSUE_DOC_SP", precision=12, scale=0)
    public Long getVcIssueDocSp() {
        return this.vcIssueDocSp;
    }
    
    public void setVcIssueDocSp(Long vcIssueDocSp) {
        this.vcIssueDocSp = vcIssueDocSp;
    }

    
    @Column(name="COST_STATE", precision=1, scale=0)
    public Boolean getCostState() {
        return this.costState;
    }
    
    public void setCostState(Boolean costState) {
        this.costState = costState;
    }

    
    @Column(name="CHK_PRINT_COST", precision=1, scale=0)
    public Boolean getChkPrintCost() {
        return this.chkPrintCost;
    }
    
    public void setChkPrintCost(Boolean chkPrintCost) {
        this.chkPrintCost = chkPrintCost;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXEC_MM", length=7)
    public Date getExecMm() {
        return this.execMm;
    }
    
    public void setExecMm(Date execMm) {
        this.execMm = execMm;
    }

    
    @Column(name="VC_ISSUE_DOC_SEQ", precision=6, scale=0)
    public Integer getVcIssueDocSeq() {
        return this.vcIssueDocSeq;
    }
    
    public void setVcIssueDocSeq(Integer vcIssueDocSeq) {
        this.vcIssueDocSeq = vcIssueDocSeq;
    }

    
    @Column(name="CHK_ERR_FIN", precision=1, scale=0)
    public Boolean getChkErrFin() {
        return this.chkErrFin;
    }
    
    public void setChkErrFin(Boolean chkErrFin) {
        this.chkErrFin = chkErrFin;
    }

    
    @Column(name="CHK_ERR_LIN", precision=1, scale=0)
    public Boolean getChkErrLin() {
        return this.chkErrLin;
    }
    
    public void setChkErrLin(Boolean chkErrLin) {
        this.chkErrLin = chkErrLin;
    }

    
    @Column(name="RMRK_FIN", length=150)
    public String getRmrkFin() {
        return this.rmrkFin;
    }
    
    public void setRmrkFin(String rmrkFin) {
        this.rmrkFin = rmrkFin;
    }

    
    @Column(name="RMRK_LIN", length=150)
    public String getRmrkLin() {
        return this.rmrkLin;
    }
    
    public void setRmrkLin(String rmrkLin) {
        this.rmrkLin = rmrkLin;
    }

    
    @Column(name="CHK_LOCK", precision=1, scale=0)
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }

    
    @Column(name="REP_SEQ", precision=2, scale=0)
    public Byte getRepSeq() {
        return this.repSeq;
    }
    
    public void setRepSeq(Byte repSeq) {
        this.repSeq = repSeq;
    }




}


