package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VcleDistributeDateAhramAmId generated by hbm2java
 */
@Embeddable
public class VcleDistributeDateAhramAmId  implements java.io.Serializable {


     private byte travelMm;
     private short fiscalYear;
     private byte travelDd;
     private int travelSp;

    public VcleDistributeDateAhramAmId() {
    }

    public VcleDistributeDateAhramAmId(byte travelMm, short fiscalYear, byte travelDd, int travelSp) {
       this.travelMm = travelMm;
       this.fiscalYear = fiscalYear;
       this.travelDd = travelDd;
       this.travelSp = travelSp;
    }
   


    @Column(name="TRAVEL_MM", nullable=false, precision=2, scale=0)
    public byte getTravelMm() {
        return this.travelMm;
    }
    
    public void setTravelMm(byte travelMm) {
        this.travelMm = travelMm;
    }


    @Column(name="FISCAL_YEAR", nullable=false, precision=4, scale=0)
    public short getFiscalYear() {
        return this.fiscalYear;
    }
    
    public void setFiscalYear(short fiscalYear) {
        this.fiscalYear = fiscalYear;
    }


    @Column(name="TRAVEL_DD", nullable=false, precision=2, scale=0)
    public byte getTravelDd() {
        return this.travelDd;
    }
    
    public void setTravelDd(byte travelDd) {
        this.travelDd = travelDd;
    }


    @Column(name="TRAVEL_SP", nullable=false, precision=6, scale=0)
    public int getTravelSp() {
        return this.travelSp;
    }
    
    public void setTravelSp(int travelSp) {
        this.travelSp = travelSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleDistributeDateAhramAmId) ) return false;
		 VcleDistributeDateAhramAmId castOther = ( VcleDistributeDateAhramAmId ) other; 
         
		 return (this.getTravelMm()==castOther.getTravelMm())
 && (this.getFiscalYear()==castOther.getFiscalYear())
 && (this.getTravelDd()==castOther.getTravelDd())
 && (this.getTravelSp()==castOther.getTravelSp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTravelMm();
         result = 37 * result + this.getFiscalYear();
         result = 37 * result + this.getTravelDd();
         result = 37 * result + this.getTravelSp();
         return result;
   }   


}


