package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleDeptNumberJoin generated by hbm2java
 */
@Entity
@Table(name="VCLE_DEPT_NUMBER_JOIN"
    ,schema="CODEATOR"
)
public class VcleDeptNumberJoin  implements java.io.Serializable {


     private VcleDeptNumberJoinId id;
     private VcleDeptNumber vcleDeptNumber;
     private PerDeptOld perDeptOld;
     private String rmrk;

    public VcleDeptNumberJoin() {
    }

	
    public VcleDeptNumberJoin(VcleDeptNumberJoinId id, VcleDeptNumber vcleDeptNumber, PerDeptOld perDeptOld) {
        this.id = id;
        this.vcleDeptNumber = vcleDeptNumber;
        this.perDeptOld = perDeptOld;
    }
    public VcleDeptNumberJoin(VcleDeptNumberJoinId id, VcleDeptNumber vcleDeptNumber, PerDeptOld perDeptOld, String rmrk) {
       this.id = id;
       this.vcleDeptNumber = vcleDeptNumber;
       this.perDeptOld = perDeptOld;
       this.rmrk = rmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="deptId", column=@Column(name="DEPT_ID", nullable=false, precision=7, scale=0) ), 
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ) } )
    public VcleDeptNumberJoinId getId() {
        return this.id;
    }
    
    public void setId(VcleDeptNumberJoinId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="DEPT_ID", nullable=false, insertable=false, updatable=false)
    public VcleDeptNumber getVcleDeptNumber() {
        return this.vcleDeptNumber;
    }
    
    public void setVcleDeptNumber(VcleDeptNumber vcleDeptNumber) {
        this.vcleDeptNumber = vcleDeptNumber;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false) } )
    public PerDeptOld getPerDeptOld() {
        return this.perDeptOld;
    }
    
    public void setPerDeptOld(PerDeptOld perDeptOld) {
        this.perDeptOld = perDeptOld;
    }

    
    @Column(name="RMRK", length=100)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


