package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleTrafficEmpPerm generated by hbm2java
 */
@Entity
@Table(name="VCLE_TRAFFIC_EMP_PERM"
    ,schema="CODEATOR"
)
public class VcleTrafficEmpPerm  implements java.io.Serializable {


     private VcleTrafficEmpPermId id;
     private VcleTrafficLine vcleTrafficLine;
     private VcleExecutionDate vcleExecutionDate;
     private PerEmploymentMaster perEmploymentMaster;
     private long employeeNo;
     private Integer sectionNoOld;
     private Long depNoOld;
     private BigDecimal val;
     private Boolean chkAsso;
     private String rmrk;

    public VcleTrafficEmpPerm() {
    }

	
    public VcleTrafficEmpPerm(VcleTrafficEmpPermId id, VcleExecutionDate vcleExecutionDate, PerEmploymentMaster perEmploymentMaster, long employeeNo) {
        this.id = id;
        this.vcleExecutionDate = vcleExecutionDate;
        this.perEmploymentMaster = perEmploymentMaster;
        this.employeeNo = employeeNo;
    }
    public VcleTrafficEmpPerm(VcleTrafficEmpPermId id, VcleTrafficLine vcleTrafficLine, VcleExecutionDate vcleExecutionDate, PerEmploymentMaster perEmploymentMaster, long employeeNo, Integer sectionNoOld, Long depNoOld, BigDecimal val, Boolean chkAsso, String rmrk) {
       this.id = id;
       this.vcleTrafficLine = vcleTrafficLine;
       this.vcleExecutionDate = vcleExecutionDate;
       this.perEmploymentMaster = perEmploymentMaster;
       this.employeeNo = employeeNo;
       this.sectionNoOld = sectionNoOld;
       this.depNoOld = depNoOld;
       this.val = val;
       this.chkAsso = chkAsso;
       this.rmrk = rmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="execMm", column=@Column(name="EXEC_MM", nullable=false, length=7) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ) } )
    public VcleTrafficEmpPermId getId() {
        return this.id;
    }
    
    public void setId(VcleTrafficEmpPermId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="LINE_CODE")
    public VcleTrafficLine getVcleTrafficLine() {
        return this.vcleTrafficLine;
    }
    
    public void setVcleTrafficLine(VcleTrafficLine vcleTrafficLine) {
        this.vcleTrafficLine = vcleTrafficLine;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EXEC_MM", nullable=false, insertable=false, updatable=false)
    public VcleExecutionDate getVcleExecutionDate() {
        return this.vcleExecutionDate;
    }
    
    public void setVcleExecutionDate(VcleExecutionDate vcleExecutionDate) {
        this.vcleExecutionDate = vcleExecutionDate;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, precision=10, scale=0)
    public long getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(long employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="SECTION_NO_OLD", precision=5, scale=0)
    public Integer getSectionNoOld() {
        return this.sectionNoOld;
    }
    
    public void setSectionNoOld(Integer sectionNoOld) {
        this.sectionNoOld = sectionNoOld;
    }

    
    @Column(name="DEP_NO_OLD", precision=10, scale=0)
    public Long getDepNoOld() {
        return this.depNoOld;
    }
    
    public void setDepNoOld(Long depNoOld) {
        this.depNoOld = depNoOld;
    }

    
    @Column(name="VAL", precision=5)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="CHK_ASSO", precision=1, scale=0)
    public Boolean getChkAsso() {
        return this.chkAsso;
    }
    
    public void setChkAsso(Boolean chkAsso) {
        this.chkAsso = chkAsso;
    }

    
    @Column(name="RMRK", length=100)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


