package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VclePriceFuelLitre generated by hbm2java
 */
@Entity
@Table(name="VCLE_PRICE_FUEL_LITRE"
    ,schema="CODEATOR"
)
public class VclePriceFuelLitre  implements java.io.Serializable {


     private VclePriceFuelLitreId id;
     private VclePriceDateMaster vclePriceDateMaster;
     private BigDecimal litrePrice;

    public VclePriceFuelLitre() {
    }

	
    public VclePriceFuelLitre(VclePriceFuelLitreId id, VclePriceDateMaster vclePriceDateMaster) {
        this.id = id;
        this.vclePriceDateMaster = vclePriceDateMaster;
    }
    public VclePriceFuelLitre(VclePriceFuelLitreId id, VclePriceDateMaster vclePriceDateMaster, BigDecimal litrePrice) {
       this.id = id;
       this.vclePriceDateMaster = vclePriceDateMaster;
       this.litrePrice = litrePrice;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="priceType", column=@Column(name="PRICE_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="priceDate", column=@Column(name="PRICE_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="fuelType", column=@Column(name="FUEL_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="octane", column=@Column(name="OCTANE", nullable=false, precision=2, scale=0) ) } )
    public VclePriceFuelLitreId getId() {
        return this.id;
    }
    
    public void setId(VclePriceFuelLitreId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="PRICE_TYPE", referencedColumnName="PRICE_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PRICE_DATE", referencedColumnName="PRICE_DATE", nullable=false, insertable=false, updatable=false) } )
    public VclePriceDateMaster getVclePriceDateMaster() {
        return this.vclePriceDateMaster;
    }
    
    public void setVclePriceDateMaster(VclePriceDateMaster vclePriceDateMaster) {
        this.vclePriceDateMaster = vclePriceDateMaster;
    }

    
    @Column(name="LITRE_PRICE", precision=5)
    public BigDecimal getLitrePrice() {
        return this.litrePrice;
    }
    
    public void setLitrePrice(BigDecimal litrePrice) {
        this.litrePrice = litrePrice;
    }




}


