package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VclePriceDateMaster generated by hbm2java
 */
@Entity
@Table(name="VCLE_PRICE_DATE_MASTER"
    ,schema="CODEATOR"
)
public class VclePriceDateMaster  implements java.io.Serializable {


     private VclePriceDateMasterId id;
     private String rmrk;
     private Set<VclePriceKilometer> vclePriceKilometers = new HashSet<VclePriceKilometer>(0);
     private Set<VclePriceOil> vclePriceOils = new HashSet<VclePriceOil>(0);
     private Set<VclePriceFuelLitre> vclePriceFuelLitres = new HashSet<VclePriceFuelLitre>(0);

    public VclePriceDateMaster() {
    }

	
    public VclePriceDateMaster(VclePriceDateMasterId id) {
        this.id = id;
    }
    public VclePriceDateMaster(VclePriceDateMasterId id, String rmrk, Set<VclePriceKilometer> vclePriceKilometers, Set<VclePriceOil> vclePriceOils, Set<VclePriceFuelLitre> vclePriceFuelLitres) {
       this.id = id;
       this.rmrk = rmrk;
       this.vclePriceKilometers = vclePriceKilometers;
       this.vclePriceOils = vclePriceOils;
       this.vclePriceFuelLitres = vclePriceFuelLitres;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="priceType", column=@Column(name="PRICE_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="priceDate", column=@Column(name="PRICE_DATE", nullable=false, length=7) ) } )
    public VclePriceDateMasterId getId() {
        return this.id;
    }
    
    public void setId(VclePriceDateMasterId id) {
        this.id = id;
    }

    
    @Column(name="RMRK", length=100)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vclePriceDateMaster")
    public Set<VclePriceKilometer> getVclePriceKilometers() {
        return this.vclePriceKilometers;
    }
    
    public void setVclePriceKilometers(Set<VclePriceKilometer> vclePriceKilometers) {
        this.vclePriceKilometers = vclePriceKilometers;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vclePriceDateMaster")
    public Set<VclePriceOil> getVclePriceOils() {
        return this.vclePriceOils;
    }
    
    public void setVclePriceOils(Set<VclePriceOil> vclePriceOils) {
        this.vclePriceOils = vclePriceOils;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vclePriceDateMaster")
    public Set<VclePriceFuelLitre> getVclePriceFuelLitres() {
        return this.vclePriceFuelLitres;
    }
    
    public void setVclePriceFuelLitres(Set<VclePriceFuelLitre> vclePriceFuelLitres) {
        this.vclePriceFuelLitres = vclePriceFuelLitres;
    }




}


