package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleOilIssue generated by hbm2java
 */
@Entity
@Table(name="VCLE_OIL_ISSUE"
    ,schema="CODEATOR"
)
public class VcleOilIssue  implements java.io.Serializable {


     private VcleOilIssueId id;
     private VcleWorkshopeCode vcleWorkshopeCode;
     private VcleVehicleMaster vcleVehicleMaster;
     private VcleOilType vcleOilType;
     private VcleDeptNumber vcleDeptNumber;
     private boolean sideType;
     private BigDecimal issueQun;
     private BigDecimal issueSal;
     private BigDecimal issueVal;
     private Long countNumber;

    public VcleOilIssue() {
    }

	
    public VcleOilIssue(VcleOilIssueId id, VcleOilType vcleOilType, boolean sideType, BigDecimal issueQun) {
        this.id = id;
        this.vcleOilType = vcleOilType;
        this.sideType = sideType;
        this.issueQun = issueQun;
    }
    public VcleOilIssue(VcleOilIssueId id, VcleWorkshopeCode vcleWorkshopeCode, VcleVehicleMaster vcleVehicleMaster, VcleOilType vcleOilType, VcleDeptNumber vcleDeptNumber, boolean sideType, BigDecimal issueQun, BigDecimal issueSal, BigDecimal issueVal, Long countNumber) {
       this.id = id;
       this.vcleWorkshopeCode = vcleWorkshopeCode;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.vcleOilType = vcleOilType;
       this.vcleDeptNumber = vcleDeptNumber;
       this.sideType = sideType;
       this.issueQun = issueQun;
       this.issueSal = issueSal;
       this.issueVal = issueVal;
       this.countNumber = countNumber;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="execDate", column=@Column(name="EXEC_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="issueSp", column=@Column(name="ISSUE_SP", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ) } )
    public VcleOilIssueId getId() {
        return this.id;
    }
    
    public void setId(VcleOilIssueId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="WORKSHOPE_CODE")
    public VcleWorkshopeCode getVcleWorkshopeCode() {
        return this.vcleWorkshopeCode;
    }
    
    public void setVcleWorkshopeCode(VcleWorkshopeCode vcleWorkshopeCode) {
        this.vcleWorkshopeCode = vcleWorkshopeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP")
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="OIL_TYPE", nullable=false)
    public VcleOilType getVcleOilType() {
        return this.vcleOilType;
    }
    
    public void setVcleOilType(VcleOilType vcleOilType) {
        this.vcleOilType = vcleOilType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="DEPT_ID")
    public VcleDeptNumber getVcleDeptNumber() {
        return this.vcleDeptNumber;
    }
    
    public void setVcleDeptNumber(VcleDeptNumber vcleDeptNumber) {
        this.vcleDeptNumber = vcleDeptNumber;
    }

    
    @Column(name="SIDE_TYPE", nullable=false, precision=1, scale=0)
    public boolean isSideType() {
        return this.sideType;
    }
    
    public void setSideType(boolean sideType) {
        this.sideType = sideType;
    }

    
    @Column(name="ISSUE_QUN", nullable=false, precision=7)
    public BigDecimal getIssueQun() {
        return this.issueQun;
    }
    
    public void setIssueQun(BigDecimal issueQun) {
        this.issueQun = issueQun;
    }

    
    @Column(name="ISSUE_SAL", precision=9)
    public BigDecimal getIssueSal() {
        return this.issueSal;
    }
    
    public void setIssueSal(BigDecimal issueSal) {
        this.issueSal = issueSal;
    }

    
    @Column(name="ISSUE_VAL", precision=9)
    public BigDecimal getIssueVal() {
        return this.issueVal;
    }
    
    public void setIssueVal(BigDecimal issueVal) {
        this.issueVal = issueVal;
    }

    
    @Column(name="COUNT_NUMBER", precision=11, scale=0)
    public Long getCountNumber() {
        return this.countNumber;
    }
    
    public void setCountNumber(Long countNumber) {
        this.countNumber = countNumber;
    }




}


