package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleFuelProvideLiquid generated by hbm2java
 */
@Entity
@Table(name="VCLE_FUEL_PROVIDE_LIQUID"
    ,schema="CODEATOR"
)
public class VcleFuelProvideLiquid  implements java.io.Serializable {


     private VcleFuelProvideLiquidId id;
     private VcleShiftType vcleShiftType;
     private VcleFuelOpenDay vcleFuelOpenDay;
     private Date invoiceDate;
     private BigDecimal fristBnzQun;
     private BigDecimal secondBnzQun;
     private BigDecimal fristSolQun;
     private Long eznSeqRcv;
     private Byte timeHh;
     private Byte timeMi;
     private Boolean timeType;
     private String rmrk;
     private Boolean chkLock;
     private Integer invoiceNo;
     private BigDecimal fristBnzTankNum;
     private BigDecimal secondBnzTankNum;
     private BigDecimal fristSolTankNum;
     private Boolean provideType;
     private BigDecimal qunOver;
     private Date fiscalDate;

    public VcleFuelProvideLiquid() {
    }

	
    public VcleFuelProvideLiquid(VcleFuelProvideLiquidId id, VcleFuelOpenDay vcleFuelOpenDay) {
        this.id = id;
        this.vcleFuelOpenDay = vcleFuelOpenDay;
    }
    public VcleFuelProvideLiquid(VcleFuelProvideLiquidId id, VcleShiftType vcleShiftType, VcleFuelOpenDay vcleFuelOpenDay, Date invoiceDate, BigDecimal fristBnzQun, BigDecimal secondBnzQun, BigDecimal fristSolQun, Long eznSeqRcv, Byte timeHh, Byte timeMi, Boolean timeType, String rmrk, Boolean chkLock, Integer invoiceNo, BigDecimal fristBnzTankNum, BigDecimal secondBnzTankNum, BigDecimal fristSolTankNum, Boolean provideType, BigDecimal qunOver, Date fiscalDate) {
       this.id = id;
       this.vcleShiftType = vcleShiftType;
       this.vcleFuelOpenDay = vcleFuelOpenDay;
       this.invoiceDate = invoiceDate;
       this.fristBnzQun = fristBnzQun;
       this.secondBnzQun = secondBnzQun;
       this.fristSolQun = fristSolQun;
       this.eznSeqRcv = eznSeqRcv;
       this.timeHh = timeHh;
       this.timeMi = timeMi;
       this.timeType = timeType;
       this.rmrk = rmrk;
       this.chkLock = chkLock;
       this.invoiceNo = invoiceNo;
       this.fristBnzTankNum = fristBnzTankNum;
       this.secondBnzTankNum = secondBnzTankNum;
       this.fristSolTankNum = fristSolTankNum;
       this.provideType = provideType;
       this.qunOver = qunOver;
       this.fiscalDate = fiscalDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locCode", column=@Column(name="LOC_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="execDate", column=@Column(name="EXEC_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="fuelSp", column=@Column(name="FUEL_SP", nullable=false, precision=9, scale=0) ) } )
    public VcleFuelProvideLiquidId getId() {
        return this.id;
    }
    
    public void setId(VcleFuelProvideLiquidId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SHIFT_TYPE")
    public VcleShiftType getVcleShiftType() {
        return this.vcleShiftType;
    }
    
    public void setVcleShiftType(VcleShiftType vcleShiftType) {
        this.vcleShiftType = vcleShiftType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EXEC_DATE", nullable=false, insertable=false, updatable=false)
    public VcleFuelOpenDay getVcleFuelOpenDay() {
        return this.vcleFuelOpenDay;
    }
    
    public void setVcleFuelOpenDay(VcleFuelOpenDay vcleFuelOpenDay) {
        this.vcleFuelOpenDay = vcleFuelOpenDay;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INVOICE_DATE", length=7)
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    
    @Column(name="FRIST_BNZ_QUN", precision=12, scale=3)
    public BigDecimal getFristBnzQun() {
        return this.fristBnzQun;
    }
    
    public void setFristBnzQun(BigDecimal fristBnzQun) {
        this.fristBnzQun = fristBnzQun;
    }

    
    @Column(name="SECOND_BNZ_QUN", precision=12, scale=3)
    public BigDecimal getSecondBnzQun() {
        return this.secondBnzQun;
    }
    
    public void setSecondBnzQun(BigDecimal secondBnzQun) {
        this.secondBnzQun = secondBnzQun;
    }

    
    @Column(name="FRIST_SOL_QUN", precision=12, scale=3)
    public BigDecimal getFristSolQun() {
        return this.fristSolQun;
    }
    
    public void setFristSolQun(BigDecimal fristSolQun) {
        this.fristSolQun = fristSolQun;
    }

    
    @Column(name="EZN_SEQ_RCV", precision=10, scale=0)
    public Long getEznSeqRcv() {
        return this.eznSeqRcv;
    }
    
    public void setEznSeqRcv(Long eznSeqRcv) {
        this.eznSeqRcv = eznSeqRcv;
    }

    
    @Column(name="TIME_HH", precision=2, scale=0)
    public Byte getTimeHh() {
        return this.timeHh;
    }
    
    public void setTimeHh(Byte timeHh) {
        this.timeHh = timeHh;
    }

    
    @Column(name="TIME_MI", precision=2, scale=0)
    public Byte getTimeMi() {
        return this.timeMi;
    }
    
    public void setTimeMi(Byte timeMi) {
        this.timeMi = timeMi;
    }

    
    @Column(name="TIME_TYPE", precision=1, scale=0)
    public Boolean getTimeType() {
        return this.timeType;
    }
    
    public void setTimeType(Boolean timeType) {
        this.timeType = timeType;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="CHK_LOCK", precision=1, scale=0)
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }

    
    @Column(name="INVOICE_NO", precision=9, scale=0)
    public Integer getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(Integer invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    
    @Column(name="FRIST_BNZ_TANK_NUM", precision=12, scale=3)
    public BigDecimal getFristBnzTankNum() {
        return this.fristBnzTankNum;
    }
    
    public void setFristBnzTankNum(BigDecimal fristBnzTankNum) {
        this.fristBnzTankNum = fristBnzTankNum;
    }

    
    @Column(name="SECOND_BNZ_TANK_NUM", precision=12, scale=3)
    public BigDecimal getSecondBnzTankNum() {
        return this.secondBnzTankNum;
    }
    
    public void setSecondBnzTankNum(BigDecimal secondBnzTankNum) {
        this.secondBnzTankNum = secondBnzTankNum;
    }

    
    @Column(name="FRIST_SOL_TANK_NUM", precision=12, scale=3)
    public BigDecimal getFristSolTankNum() {
        return this.fristSolTankNum;
    }
    
    public void setFristSolTankNum(BigDecimal fristSolTankNum) {
        this.fristSolTankNum = fristSolTankNum;
    }

    
    @Column(name="PROVIDE_TYPE", precision=1, scale=0)
    public Boolean getProvideType() {
        return this.provideType;
    }
    
    public void setProvideType(Boolean provideType) {
        this.provideType = provideType;
    }

    
    @Column(name="QUN_OVER", precision=12, scale=3)
    public BigDecimal getQunOver() {
        return this.qunOver;
    }
    
    public void setQunOver(BigDecimal qunOver) {
        this.qunOver = qunOver;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FISCAL_DATE", length=7)
    public Date getFiscalDate() {
        return this.fiscalDate;
    }
    
    public void setFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }




}


