package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleMainCost generated by hbm2java
 */
@Entity
@Table(name="VCLE_MAIN_COST"
    ,schema="CODEATOR"
)
public class VcleMainCost  implements java.io.Serializable {


     private String mainCode;
     private String mainName;
     private Set<VcleMainCostCode> vcleMainCostCodes = new HashSet<VcleMainCostCode>(0);
     private Set<VcleVehicleResponsibleEmp> vcleVehicleResponsibleEmps = new HashSet<VcleVehicleResponsibleEmp>(0);
     private Set<VcleVehicleResponseWork> vcleVehicleResponseWorks = new HashSet<VcleVehicleResponseWork>(0);
     private Set<VcleIssueDocument> vcleIssueDocuments = new HashSet<VcleIssueDocument>(0);
     private Set<VcleEmployeeMaster> vcleEmployeeMasters = new HashSet<VcleEmployeeMaster>(0);

    public VcleMainCost() {
    }

	
    public VcleMainCost(String mainCode, String mainName) {
        this.mainCode = mainCode;
        this.mainName = mainName;
    }
    public VcleMainCost(String mainCode, String mainName, Set<VcleMainCostCode> vcleMainCostCodes, Set<VcleVehicleResponsibleEmp> vcleVehicleResponsibleEmps, Set<VcleVehicleResponseWork> vcleVehicleResponseWorks, Set<VcleIssueDocument> vcleIssueDocuments, Set<VcleEmployeeMaster> vcleEmployeeMasters) {
       this.mainCode = mainCode;
       this.mainName = mainName;
       this.vcleMainCostCodes = vcleMainCostCodes;
       this.vcleVehicleResponsibleEmps = vcleVehicleResponsibleEmps;
       this.vcleVehicleResponseWorks = vcleVehicleResponseWorks;
       this.vcleIssueDocuments = vcleIssueDocuments;
       this.vcleEmployeeMasters = vcleEmployeeMasters;
    }
   
     @Id 

    
    @Column(name="MAIN_CODE", unique=true, nullable=false, length=10)
    public String getMainCode() {
        return this.mainCode;
    }
    
    public void setMainCode(String mainCode) {
        this.mainCode = mainCode;
    }

    
    @Column(name="MAIN_NAME", nullable=false, length=100)
    public String getMainName() {
        return this.mainName;
    }
    
    public void setMainName(String mainName) {
        this.mainName = mainName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleMainCost")
    public Set<VcleMainCostCode> getVcleMainCostCodes() {
        return this.vcleMainCostCodes;
    }
    
    public void setVcleMainCostCodes(Set<VcleMainCostCode> vcleMainCostCodes) {
        this.vcleMainCostCodes = vcleMainCostCodes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleMainCost")
    public Set<VcleVehicleResponsibleEmp> getVcleVehicleResponsibleEmps() {
        return this.vcleVehicleResponsibleEmps;
    }
    
    public void setVcleVehicleResponsibleEmps(Set<VcleVehicleResponsibleEmp> vcleVehicleResponsibleEmps) {
        this.vcleVehicleResponsibleEmps = vcleVehicleResponsibleEmps;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleMainCost")
    public Set<VcleVehicleResponseWork> getVcleVehicleResponseWorks() {
        return this.vcleVehicleResponseWorks;
    }
    
    public void setVcleVehicleResponseWorks(Set<VcleVehicleResponseWork> vcleVehicleResponseWorks) {
        this.vcleVehicleResponseWorks = vcleVehicleResponseWorks;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleMainCost")
    public Set<VcleIssueDocument> getVcleIssueDocuments() {
        return this.vcleIssueDocuments;
    }
    
    public void setVcleIssueDocuments(Set<VcleIssueDocument> vcleIssueDocuments) {
        this.vcleIssueDocuments = vcleIssueDocuments;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleMainCost")
    public Set<VcleEmployeeMaster> getVcleEmployeeMasters() {
        return this.vcleEmployeeMasters;
    }
    
    public void setVcleEmployeeMasters(Set<VcleEmployeeMaster> vcleEmployeeMasters) {
        this.vcleEmployeeMasters = vcleEmployeeMasters;
    }




}


