package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleIssueDocumentDtl generated by hbm2java
 */
@Entity
@Table(name="VCLE_ISSUE_DOCUMENT_DTL"
    ,schema="CODEATOR"
)
public class VcleIssueDocumentDtl  implements java.io.Serializable {


     private VcleIssueDocumentDtlId id;
     private VcleIssueDocument vcleIssueDocument;
     private BigDecimal documentValue;
     private String documentNo;
     private Short documentCount;
     private String documentType;
     private Date documentDate;
     private String documentNote;

    public VcleIssueDocumentDtl() {
    }

	
    public VcleIssueDocumentDtl(VcleIssueDocumentDtlId id, VcleIssueDocument vcleIssueDocument, BigDecimal documentValue) {
        this.id = id;
        this.vcleIssueDocument = vcleIssueDocument;
        this.documentValue = documentValue;
    }
    public VcleIssueDocumentDtl(VcleIssueDocumentDtlId id, VcleIssueDocument vcleIssueDocument, BigDecimal documentValue, String documentNo, Short documentCount, String documentType, Date documentDate, String documentNote) {
       this.id = id;
       this.vcleIssueDocument = vcleIssueDocument;
       this.documentValue = documentValue;
       this.documentNo = documentNo;
       this.documentCount = documentCount;
       this.documentType = documentType;
       this.documentDate = documentDate;
       this.documentNote = documentNote;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="issueDocSp", column=@Column(name="ISSUE_DOC_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="issueDocSerial", column=@Column(name="ISSUE_DOC_SERIAL", nullable=false, precision=2, scale=0) ) } )
    public VcleIssueDocumentDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleIssueDocumentDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="FISCAL_DATE", referencedColumnName="FISCAL_DATE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ISSUE_DOC_SP", referencedColumnName="ISSUE_DOC_SP", nullable=false, insertable=false, updatable=false) } )
    public VcleIssueDocument getVcleIssueDocument() {
        return this.vcleIssueDocument;
    }
    
    public void setVcleIssueDocument(VcleIssueDocument vcleIssueDocument) {
        this.vcleIssueDocument = vcleIssueDocument;
    }

    
    @Column(name="DOCUMENT_VALUE", nullable=false, precision=16, scale=3)
    public BigDecimal getDocumentValue() {
        return this.documentValue;
    }
    
    public void setDocumentValue(BigDecimal documentValue) {
        this.documentValue = documentValue;
    }

    
    @Column(name="DOCUMENT_NO", length=10)
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }

    
    @Column(name="DOCUMENT_COUNT", precision=3, scale=0)
    public Short getDocumentCount() {
        return this.documentCount;
    }
    
    public void setDocumentCount(Short documentCount) {
        this.documentCount = documentCount;
    }

    
    @Column(name="DOCUMENT_TYPE", length=75)
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DOCUMENT_DATE", length=7)
    public Date getDocumentDate() {
        return this.documentDate;
    }
    
    public void setDocumentDate(Date documentDate) {
        this.documentDate = documentDate;
    }

    
    @Column(name="DOCUMENT_NOTE", length=150)
    public String getDocumentNote() {
        return this.documentNote;
    }
    
    public void setDocumentNote(String documentNote) {
        this.documentNote = documentNote;
    }




}


