package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleMaster generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_MASTER"
    ,schema="CODEATOR"
)
public class VcleVehicleMaster  implements java.io.Serializable {


     private int vehicleSp;
     private VcleWorkSide vcleWorkSide;
     private VcleVehicleType vcleVehicleType;
     private VcleVehicleShape vcleVehicleShape;
     private VcleVehicleModel vcleVehicleModel;
     private VcleEquipmentType vcleEquipmentType;
     private VcleColorCode vcleColorCode;
     private Boolean fuelType;
     private String shassNumber;
     private String motorNumber;
     private String boardNumber;
     private Byte octane;
     private BigDecimal purchaseValue;
     private Date purchaseDate;
     private Short depRateVehcl;
     private BigDecimal depKst;
     private Short manufactureYear;
     private Boolean loadType;
     private BigDecimal loadVal;
     private String trafficLetterNumber;
     private Date trafficLetterDate;
     private String ownerCertNo;
     private Date ownerCertDate;
     private Short vehicleCc;
     private Boolean vehicleCylinder;
     private Boolean licensePeriod;
     private String couponNum;
     private Date couponDate;
     private BigDecimal insuranceFirstVal;
     private String vehicleDesc;
     private Integer boardNumberOld;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;
     private Date countNumberDate;
     private Long countNumber;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Date licenseFirstDate;
     private Boolean vcleStatus;
     private Short vehicleCode;
     private Date licenseEndDate;
     private Date inspectDate;
     private Boolean chkOwner;
     private Boolean chkSale;
     private Date saleDate;
     private String saleRmrk;
     private Boolean chkSpecial;
     private Integer vcleNum;
     private Set<VcleTravelExchange> vcleTravelExchanges = new HashSet<VcleTravelExchange>(0);
     private Set<VcleVehicleInspectCar> vcleVehicleInspectCars = new HashSet<VcleVehicleInspectCar>(0);
     private Set<VcleFuelIssueLiquid> vcleFuelIssueLiquids = new HashSet<VcleFuelIssueLiquid>(0);
     private Set<VcleVehicleTransactionDtl> vcleVehicleTransactionDtls = new HashSet<VcleVehicleTransactionDtl>(0);
     private Set<VcleTrafficLine> vcleTrafficLines = new HashSet<VcleTrafficLine>(0);
     private Set<VcleVehicleDriverJoin> vcleVehicleDriverJoins = new HashSet<VcleVehicleDriverJoin>(0);
     private Set<VcleVehicleAccident> vcleVehicleAccidents = new HashSet<VcleVehicleAccident>(0);
     private Set<VcleVehicleCountMm> vcleVehicleCountMms = new HashSet<VcleVehicleCountMm>(0);
     private Set<VcleVehicleInstruction> vcleVehicleInstructions = new HashSet<VcleVehicleInstruction>(0);
     private Set<VcleMotorChange> vcleMotorChanges = new HashSet<VcleMotorChange>(0);
     private Set<VcleRecordMovement> vcleRecordMovements = new HashSet<VcleRecordMovement>(0);
     private Set<VcleVehicleIncome> vcleVehicleIncomes = new HashSet<VcleVehicleIncome>(0);
     private Set<VcleWorkTypeTransCar> vcleWorkTypeTransCars = new HashSet<VcleWorkTypeTransCar>(0);
     private Set<VcleVehicleRequire> vcleVehicleRequires = new HashSet<VcleVehicleRequire>(0);
     private Set<VcleVehicleNotifyTrans> vcleVehicleNotifyTranses = new HashSet<VcleVehicleNotifyTrans>(0);
     private Set<VcleVehicleReceive> vcleVehicleReceives = new HashSet<VcleVehicleReceive>(0);
     private Set<VcleVehicleClassDtl> vcleVehicleClassDtls = new HashSet<VcleVehicleClassDtl>(0);
     private Set<VcleOilIssue> vcleOilIssues = new HashSet<VcleOilIssue>(0);
     private Set<VcleVehicleInvoiceCar> vcleVehicleInvoiceCars = new HashSet<VcleVehicleInvoiceCar>(0);
     private Set<VcleFuelBookNumberDtl> vcleFuelBookNumberDtls = new HashSet<VcleFuelBookNumberDtl>(0);
     private Set<VcleVehicleCost> vcleVehicleCosts = new HashSet<VcleVehicleCost>(0);
     private Set<VcleWorkSideDtl> vcleWorkSideDtls = new HashSet<VcleWorkSideDtl>(0);
     private Set<VcleVehicleLicense> vcleVehicleLicenses = new HashSet<VcleVehicleLicense>(0);
     private Set<VcleVehicleIncluding> vcleVehicleIncludings = new HashSet<VcleVehicleIncluding>(0);
     private Set<VcleVehicleLicenseReportCr> vcleVehicleLicenseReportCrs = new HashSet<VcleVehicleLicenseReportCr>(0);
     private Set<VcleVehicleResponsibleJoin> vcleVehicleResponsibleJoins = new HashSet<VcleVehicleResponsibleJoin>(0);
     private Set<VcleVehicleInvoiceLiq> vcleVehicleInvoiceLiqs = new HashSet<VcleVehicleInvoiceLiq>(0);

    public VcleVehicleMaster() {
    }

	
    public VcleVehicleMaster(int vehicleSp, String boardNumber) {
        this.vehicleSp = vehicleSp;
        this.boardNumber = boardNumber;
    }
    public VcleVehicleMaster(int vehicleSp, VcleWorkSide vcleWorkSide, VcleVehicleType vcleVehicleType, VcleVehicleShape vcleVehicleShape, VcleVehicleModel vcleVehicleModel, VcleEquipmentType vcleEquipmentType, VcleColorCode vcleColorCode, Boolean fuelType, String shassNumber, String motorNumber, String boardNumber, Byte octane, BigDecimal purchaseValue, Date purchaseDate, Short depRateVehcl, BigDecimal depKst, Short manufactureYear, Boolean loadType, BigDecimal loadVal, String trafficLetterNumber, Date trafficLetterDate, String ownerCertNo, Date ownerCertDate, Short vehicleCc, Boolean vehicleCylinder, Boolean licensePeriod, String couponNum, Date couponDate, BigDecimal insuranceFirstVal, String vehicleDesc, Integer boardNumberOld, Integer boardDigital, String boardAlfa1, String boardAlfa2, String boardAlfa3, Date countNumberDate, Long countNumber, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Date licenseFirstDate, Boolean vcleStatus, Short vehicleCode, Date licenseEndDate, Date inspectDate, Boolean chkOwner, Boolean chkSale, Date saleDate, String saleRmrk, Boolean chkSpecial, Integer vcleNum, Set<VcleTravelExchange> vcleTravelExchanges, Set<VcleVehicleInspectCar> vcleVehicleInspectCars, Set<VcleFuelIssueLiquid> vcleFuelIssueLiquids, Set<VcleVehicleTransactionDtl> vcleVehicleTransactionDtls, Set<VcleTrafficLine> vcleTrafficLines, Set<VcleVehicleDriverJoin> vcleVehicleDriverJoins, Set<VcleVehicleAccident> vcleVehicleAccidents, Set<VcleVehicleCountMm> vcleVehicleCountMms, Set<VcleVehicleInstruction> vcleVehicleInstructions, Set<VcleMotorChange> vcleMotorChanges, Set<VcleRecordMovement> vcleRecordMovements, Set<VcleVehicleIncome> vcleVehicleIncomes, Set<VcleWorkTypeTransCar> vcleWorkTypeTransCars, Set<VcleVehicleRequire> vcleVehicleRequires, Set<VcleVehicleNotifyTrans> vcleVehicleNotifyTranses, Set<VcleVehicleReceive> vcleVehicleReceives, Set<VcleVehicleClassDtl> vcleVehicleClassDtls, Set<VcleOilIssue> vcleOilIssues, Set<VcleVehicleInvoiceCar> vcleVehicleInvoiceCars, Set<VcleFuelBookNumberDtl> vcleFuelBookNumberDtls, Set<VcleVehicleCost> vcleVehicleCosts, Set<VcleWorkSideDtl> vcleWorkSideDtls, Set<VcleVehicleLicense> vcleVehicleLicenses, Set<VcleVehicleIncluding> vcleVehicleIncludings, Set<VcleVehicleLicenseReportCr> vcleVehicleLicenseReportCrs, Set<VcleVehicleResponsibleJoin> vcleVehicleResponsibleJoins, Set<VcleVehicleInvoiceLiq> vcleVehicleInvoiceLiqs) {
       this.vehicleSp = vehicleSp;
       this.vcleWorkSide = vcleWorkSide;
       this.vcleVehicleType = vcleVehicleType;
       this.vcleVehicleShape = vcleVehicleShape;
       this.vcleVehicleModel = vcleVehicleModel;
       this.vcleEquipmentType = vcleEquipmentType;
       this.vcleColorCode = vcleColorCode;
       this.fuelType = fuelType;
       this.shassNumber = shassNumber;
       this.motorNumber = motorNumber;
       this.boardNumber = boardNumber;
       this.octane = octane;
       this.purchaseValue = purchaseValue;
       this.purchaseDate = purchaseDate;
       this.depRateVehcl = depRateVehcl;
       this.depKst = depKst;
       this.manufactureYear = manufactureYear;
       this.loadType = loadType;
       this.loadVal = loadVal;
       this.trafficLetterNumber = trafficLetterNumber;
       this.trafficLetterDate = trafficLetterDate;
       this.ownerCertNo = ownerCertNo;
       this.ownerCertDate = ownerCertDate;
       this.vehicleCc = vehicleCc;
       this.vehicleCylinder = vehicleCylinder;
       this.licensePeriod = licensePeriod;
       this.couponNum = couponNum;
       this.couponDate = couponDate;
       this.insuranceFirstVal = insuranceFirstVal;
       this.vehicleDesc = vehicleDesc;
       this.boardNumberOld = boardNumberOld;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
       this.countNumberDate = countNumberDate;
       this.countNumber = countNumber;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.licenseFirstDate = licenseFirstDate;
       this.vcleStatus = vcleStatus;
       this.vehicleCode = vehicleCode;
       this.licenseEndDate = licenseEndDate;
       this.inspectDate = inspectDate;
       this.chkOwner = chkOwner;
       this.chkSale = chkSale;
       this.saleDate = saleDate;
       this.saleRmrk = saleRmrk;
       this.chkSpecial = chkSpecial;
       this.vcleNum = vcleNum;
       this.vcleTravelExchanges = vcleTravelExchanges;
       this.vcleVehicleInspectCars = vcleVehicleInspectCars;
       this.vcleFuelIssueLiquids = vcleFuelIssueLiquids;
       this.vcleVehicleTransactionDtls = vcleVehicleTransactionDtls;
       this.vcleTrafficLines = vcleTrafficLines;
       this.vcleVehicleDriverJoins = vcleVehicleDriverJoins;
       this.vcleVehicleAccidents = vcleVehicleAccidents;
       this.vcleVehicleCountMms = vcleVehicleCountMms;
       this.vcleVehicleInstructions = vcleVehicleInstructions;
       this.vcleMotorChanges = vcleMotorChanges;
       this.vcleRecordMovements = vcleRecordMovements;
       this.vcleVehicleIncomes = vcleVehicleIncomes;
       this.vcleWorkTypeTransCars = vcleWorkTypeTransCars;
       this.vcleVehicleRequires = vcleVehicleRequires;
       this.vcleVehicleNotifyTranses = vcleVehicleNotifyTranses;
       this.vcleVehicleReceives = vcleVehicleReceives;
       this.vcleVehicleClassDtls = vcleVehicleClassDtls;
       this.vcleOilIssues = vcleOilIssues;
       this.vcleVehicleInvoiceCars = vcleVehicleInvoiceCars;
       this.vcleFuelBookNumberDtls = vcleFuelBookNumberDtls;
       this.vcleVehicleCosts = vcleVehicleCosts;
       this.vcleWorkSideDtls = vcleWorkSideDtls;
       this.vcleVehicleLicenses = vcleVehicleLicenses;
       this.vcleVehicleIncludings = vcleVehicleIncludings;
       this.vcleVehicleLicenseReportCrs = vcleVehicleLicenseReportCrs;
       this.vcleVehicleResponsibleJoins = vcleVehicleResponsibleJoins;
       this.vcleVehicleInvoiceLiqs = vcleVehicleInvoiceLiqs;
    }
   
     @Id 

    
    @Column(name="VEHICLE_SP", unique=true, nullable=false, precision=6, scale=0)
    public int getVehicleSp() {
        return this.vehicleSp;
    }
    
    public void setVehicleSp(int vehicleSp) {
        this.vehicleSp = vehicleSp;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="WORK_SIDE_CODE")
    public VcleWorkSide getVcleWorkSide() {
        return this.vcleWorkSide;
    }
    
    public void setVcleWorkSide(VcleWorkSide vcleWorkSide) {
        this.vcleWorkSide = vcleWorkSide;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_TYPE")
    public VcleVehicleType getVcleVehicleType() {
        return this.vcleVehicleType;
    }
    
    public void setVcleVehicleType(VcleVehicleType vcleVehicleType) {
        this.vcleVehicleType = vcleVehicleType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SHAPE_CODE")
    public VcleVehicleShape getVcleVehicleShape() {
        return this.vcleVehicleShape;
    }
    
    public void setVcleVehicleShape(VcleVehicleShape vcleVehicleShape) {
        this.vcleVehicleShape = vcleVehicleShape;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="VCLE_TYPE", referencedColumnName="VCLE_TYPE", insertable=false, updatable=false), 
        @JoinColumn(name="MARK_TYPE", referencedColumnName="MARK_TYPE", insertable=false, updatable=false), 
        @JoinColumn(name="MODEL_CODE", referencedColumnName="MODEL_CODE", insertable=false, updatable=false) } )
    public VcleVehicleModel getVcleVehicleModel() {
        return this.vcleVehicleModel;
    }
    
    public void setVcleVehicleModel(VcleVehicleModel vcleVehicleModel) {
        this.vcleVehicleModel = vcleVehicleModel;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EQUIPMENT_CODE")
    public VcleEquipmentType getVcleEquipmentType() {
        return this.vcleEquipmentType;
    }
    
    public void setVcleEquipmentType(VcleEquipmentType vcleEquipmentType) {
        this.vcleEquipmentType = vcleEquipmentType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COLOR_CODE")
    public VcleColorCode getVcleColorCode() {
        return this.vcleColorCode;
    }
    
    public void setVcleColorCode(VcleColorCode vcleColorCode) {
        this.vcleColorCode = vcleColorCode;
    }

    
    @Column(name="FUEL_TYPE", precision=1, scale=0)
    public Boolean getFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(Boolean fuelType) {
        this.fuelType = fuelType;
    }

    
    @Column(name="SHASS_NUMBER", length=20)
    public String getShassNumber() {
        return this.shassNumber;
    }
    
    public void setShassNumber(String shassNumber) {
        this.shassNumber = shassNumber;
    }

    
    @Column(name="MOTOR_NUMBER", length=40)
    public String getMotorNumber() {
        return this.motorNumber;
    }
    
    public void setMotorNumber(String motorNumber) {
        this.motorNumber = motorNumber;
    }

    
    @Column(name="BOARD_NUMBER", nullable=false, length=12)
    public String getBoardNumber() {
        return this.boardNumber;
    }
    
    public void setBoardNumber(String boardNumber) {
        this.boardNumber = boardNumber;
    }

    
    @Column(name="OCTANE", precision=2, scale=0)
    public Byte getOctane() {
        return this.octane;
    }
    
    public void setOctane(Byte octane) {
        this.octane = octane;
    }

    
    @Column(name="PURCHASE_VALUE", precision=12)
    public BigDecimal getPurchaseValue() {
        return this.purchaseValue;
    }
    
    public void setPurchaseValue(BigDecimal purchaseValue) {
        this.purchaseValue = purchaseValue;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PURCHASE_DATE", length=7)
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    
    @Column(name="DEP_RATE_VEHCL", precision=3, scale=0)
    public Short getDepRateVehcl() {
        return this.depRateVehcl;
    }
    
    public void setDepRateVehcl(Short depRateVehcl) {
        this.depRateVehcl = depRateVehcl;
    }

    
    @Column(name="DEP_KST", precision=9)
    public BigDecimal getDepKst() {
        return this.depKst;
    }
    
    public void setDepKst(BigDecimal depKst) {
        this.depKst = depKst;
    }

    
    @Column(name="MANUFACTURE_YEAR", precision=4, scale=0)
    public Short getManufactureYear() {
        return this.manufactureYear;
    }
    
    public void setManufactureYear(Short manufactureYear) {
        this.manufactureYear = manufactureYear;
    }

    
    @Column(name="LOAD_TYPE", precision=1, scale=0)
    public Boolean getLoadType() {
        return this.loadType;
    }
    
    public void setLoadType(Boolean loadType) {
        this.loadType = loadType;
    }

    
    @Column(name="LOAD_VAL", precision=5)
    public BigDecimal getLoadVal() {
        return this.loadVal;
    }
    
    public void setLoadVal(BigDecimal loadVal) {
        this.loadVal = loadVal;
    }

    
    @Column(name="TRAFFIC_LETTER_NUMBER", length=20)
    public String getTrafficLetterNumber() {
        return this.trafficLetterNumber;
    }
    
    public void setTrafficLetterNumber(String trafficLetterNumber) {
        this.trafficLetterNumber = trafficLetterNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TRAFFIC_LETTER_DATE", length=7)
    public Date getTrafficLetterDate() {
        return this.trafficLetterDate;
    }
    
    public void setTrafficLetterDate(Date trafficLetterDate) {
        this.trafficLetterDate = trafficLetterDate;
    }

    
    @Column(name="OWNER_CERT_NO", length=20)
    public String getOwnerCertNo() {
        return this.ownerCertNo;
    }
    
    public void setOwnerCertNo(String ownerCertNo) {
        this.ownerCertNo = ownerCertNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="OWNER_CERT_DATE", length=7)
    public Date getOwnerCertDate() {
        return this.ownerCertDate;
    }
    
    public void setOwnerCertDate(Date ownerCertDate) {
        this.ownerCertDate = ownerCertDate;
    }

    
    @Column(name="VEHICLE_CC", precision=4, scale=0)
    public Short getVehicleCc() {
        return this.vehicleCc;
    }
    
    public void setVehicleCc(Short vehicleCc) {
        this.vehicleCc = vehicleCc;
    }

    
    @Column(name="VEHICLE_CYLINDER", precision=1, scale=0)
    public Boolean getVehicleCylinder() {
        return this.vehicleCylinder;
    }
    
    public void setVehicleCylinder(Boolean vehicleCylinder) {
        this.vehicleCylinder = vehicleCylinder;
    }

    
    @Column(name="LICENSE_PERIOD", precision=1, scale=0)
    public Boolean getLicensePeriod() {
        return this.licensePeriod;
    }
    
    public void setLicensePeriod(Boolean licensePeriod) {
        this.licensePeriod = licensePeriod;
    }

    
    @Column(name="COUPON_NUM", length=20)
    public String getCouponNum() {
        return this.couponNum;
    }
    
    public void setCouponNum(String couponNum) {
        this.couponNum = couponNum;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COUPON_DATE", length=7)
    public Date getCouponDate() {
        return this.couponDate;
    }
    
    public void setCouponDate(Date couponDate) {
        this.couponDate = couponDate;
    }

    
    @Column(name="INSURANCE_FIRST_VAL", precision=12)
    public BigDecimal getInsuranceFirstVal() {
        return this.insuranceFirstVal;
    }
    
    public void setInsuranceFirstVal(BigDecimal insuranceFirstVal) {
        this.insuranceFirstVal = insuranceFirstVal;
    }

    
    @Column(name="VEHICLE_DESC", length=100)
    public String getVehicleDesc() {
        return this.vehicleDesc;
    }
    
    public void setVehicleDesc(String vehicleDesc) {
        this.vehicleDesc = vehicleDesc;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COUNT_NUMBER_DATE", length=7)
    public Date getCountNumberDate() {
        return this.countNumberDate;
    }
    
    public void setCountNumberDate(Date countNumberDate) {
        this.countNumberDate = countNumberDate;
    }

    
    @Column(name="COUNT_NUMBER", precision=11, scale=0)
    public Long getCountNumber() {
        return this.countNumber;
    }
    
    public void setCountNumber(Long countNumber) {
        this.countNumber = countNumber;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LICENSE_FIRST_DATE", length=7)
    public Date getLicenseFirstDate() {
        return this.licenseFirstDate;
    }
    
    public void setLicenseFirstDate(Date licenseFirstDate) {
        this.licenseFirstDate = licenseFirstDate;
    }

    
    @Column(name="VCLE_STATUS", precision=1, scale=0)
    public Boolean getVcleStatus() {
        return this.vcleStatus;
    }
    
    public void setVcleStatus(Boolean vcleStatus) {
        this.vcleStatus = vcleStatus;
    }

    
    @Column(name="VEHICLE_CODE", precision=3, scale=0)
    public Short getVehicleCode() {
        return this.vehicleCode;
    }
    
    public void setVehicleCode(Short vehicleCode) {
        this.vehicleCode = vehicleCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LICENSE_END_DATE", length=7)
    public Date getLicenseEndDate() {
        return this.licenseEndDate;
    }
    
    public void setLicenseEndDate(Date licenseEndDate) {
        this.licenseEndDate = licenseEndDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INSPECT_DATE", length=7)
    public Date getInspectDate() {
        return this.inspectDate;
    }
    
    public void setInspectDate(Date inspectDate) {
        this.inspectDate = inspectDate;
    }

    
    @Column(name="CHK_OWNER", precision=1, scale=0)
    public Boolean getChkOwner() {
        return this.chkOwner;
    }
    
    public void setChkOwner(Boolean chkOwner) {
        this.chkOwner = chkOwner;
    }

    
    @Column(name="CHK_SALE", precision=1, scale=0)
    public Boolean getChkSale() {
        return this.chkSale;
    }
    
    public void setChkSale(Boolean chkSale) {
        this.chkSale = chkSale;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SALE_DATE", length=7)
    public Date getSaleDate() {
        return this.saleDate;
    }
    
    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }

    
    @Column(name="SALE_RMRK", length=200)
    public String getSaleRmrk() {
        return this.saleRmrk;
    }
    
    public void setSaleRmrk(String saleRmrk) {
        this.saleRmrk = saleRmrk;
    }

    
    @Column(name="CHK_SPECIAL", precision=1, scale=0)
    public Boolean getChkSpecial() {
        return this.chkSpecial;
    }
    
    public void setChkSpecial(Boolean chkSpecial) {
        this.chkSpecial = chkSpecial;
    }

    
    @Column(name="VCLE_NUM", precision=6, scale=0)
    public Integer getVcleNum() {
        return this.vcleNum;
    }
    
    public void setVcleNum(Integer vcleNum) {
        this.vcleNum = vcleNum;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleTravelExchange> getVcleTravelExchanges() {
        return this.vcleTravelExchanges;
    }
    
    public void setVcleTravelExchanges(Set<VcleTravelExchange> vcleTravelExchanges) {
        this.vcleTravelExchanges = vcleTravelExchanges;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleInspectCar> getVcleVehicleInspectCars() {
        return this.vcleVehicleInspectCars;
    }
    
    public void setVcleVehicleInspectCars(Set<VcleVehicleInspectCar> vcleVehicleInspectCars) {
        this.vcleVehicleInspectCars = vcleVehicleInspectCars;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleFuelIssueLiquid> getVcleFuelIssueLiquids() {
        return this.vcleFuelIssueLiquids;
    }
    
    public void setVcleFuelIssueLiquids(Set<VcleFuelIssueLiquid> vcleFuelIssueLiquids) {
        this.vcleFuelIssueLiquids = vcleFuelIssueLiquids;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleTransactionDtl> getVcleVehicleTransactionDtls() {
        return this.vcleVehicleTransactionDtls;
    }
    
    public void setVcleVehicleTransactionDtls(Set<VcleVehicleTransactionDtl> vcleVehicleTransactionDtls) {
        this.vcleVehicleTransactionDtls = vcleVehicleTransactionDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleTrafficLine> getVcleTrafficLines() {
        return this.vcleTrafficLines;
    }
    
    public void setVcleTrafficLines(Set<VcleTrafficLine> vcleTrafficLines) {
        this.vcleTrafficLines = vcleTrafficLines;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleDriverJoin> getVcleVehicleDriverJoins() {
        return this.vcleVehicleDriverJoins;
    }
    
    public void setVcleVehicleDriverJoins(Set<VcleVehicleDriverJoin> vcleVehicleDriverJoins) {
        this.vcleVehicleDriverJoins = vcleVehicleDriverJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleAccident> getVcleVehicleAccidents() {
        return this.vcleVehicleAccidents;
    }
    
    public void setVcleVehicleAccidents(Set<VcleVehicleAccident> vcleVehicleAccidents) {
        this.vcleVehicleAccidents = vcleVehicleAccidents;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleCountMm> getVcleVehicleCountMms() {
        return this.vcleVehicleCountMms;
    }
    
    public void setVcleVehicleCountMms(Set<VcleVehicleCountMm> vcleVehicleCountMms) {
        this.vcleVehicleCountMms = vcleVehicleCountMms;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleInstruction> getVcleVehicleInstructions() {
        return this.vcleVehicleInstructions;
    }
    
    public void setVcleVehicleInstructions(Set<VcleVehicleInstruction> vcleVehicleInstructions) {
        this.vcleVehicleInstructions = vcleVehicleInstructions;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleMotorChange> getVcleMotorChanges() {
        return this.vcleMotorChanges;
    }
    
    public void setVcleMotorChanges(Set<VcleMotorChange> vcleMotorChanges) {
        this.vcleMotorChanges = vcleMotorChanges;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleRecordMovement> getVcleRecordMovements() {
        return this.vcleRecordMovements;
    }
    
    public void setVcleRecordMovements(Set<VcleRecordMovement> vcleRecordMovements) {
        this.vcleRecordMovements = vcleRecordMovements;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleIncome> getVcleVehicleIncomes() {
        return this.vcleVehicleIncomes;
    }
    
    public void setVcleVehicleIncomes(Set<VcleVehicleIncome> vcleVehicleIncomes) {
        this.vcleVehicleIncomes = vcleVehicleIncomes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleWorkTypeTransCar> getVcleWorkTypeTransCars() {
        return this.vcleWorkTypeTransCars;
    }
    
    public void setVcleWorkTypeTransCars(Set<VcleWorkTypeTransCar> vcleWorkTypeTransCars) {
        this.vcleWorkTypeTransCars = vcleWorkTypeTransCars;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleRequire> getVcleVehicleRequires() {
        return this.vcleVehicleRequires;
    }
    
    public void setVcleVehicleRequires(Set<VcleVehicleRequire> vcleVehicleRequires) {
        this.vcleVehicleRequires = vcleVehicleRequires;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleNotifyTrans> getVcleVehicleNotifyTranses() {
        return this.vcleVehicleNotifyTranses;
    }
    
    public void setVcleVehicleNotifyTranses(Set<VcleVehicleNotifyTrans> vcleVehicleNotifyTranses) {
        this.vcleVehicleNotifyTranses = vcleVehicleNotifyTranses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleReceive> getVcleVehicleReceives() {
        return this.vcleVehicleReceives;
    }
    
    public void setVcleVehicleReceives(Set<VcleVehicleReceive> vcleVehicleReceives) {
        this.vcleVehicleReceives = vcleVehicleReceives;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleClassDtl> getVcleVehicleClassDtls() {
        return this.vcleVehicleClassDtls;
    }
    
    public void setVcleVehicleClassDtls(Set<VcleVehicleClassDtl> vcleVehicleClassDtls) {
        this.vcleVehicleClassDtls = vcleVehicleClassDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleOilIssue> getVcleOilIssues() {
        return this.vcleOilIssues;
    }
    
    public void setVcleOilIssues(Set<VcleOilIssue> vcleOilIssues) {
        this.vcleOilIssues = vcleOilIssues;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleInvoiceCar> getVcleVehicleInvoiceCars() {
        return this.vcleVehicleInvoiceCars;
    }
    
    public void setVcleVehicleInvoiceCars(Set<VcleVehicleInvoiceCar> vcleVehicleInvoiceCars) {
        this.vcleVehicleInvoiceCars = vcleVehicleInvoiceCars;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleFuelBookNumberDtl> getVcleFuelBookNumberDtls() {
        return this.vcleFuelBookNumberDtls;
    }
    
    public void setVcleFuelBookNumberDtls(Set<VcleFuelBookNumberDtl> vcleFuelBookNumberDtls) {
        this.vcleFuelBookNumberDtls = vcleFuelBookNumberDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleCost> getVcleVehicleCosts() {
        return this.vcleVehicleCosts;
    }
    
    public void setVcleVehicleCosts(Set<VcleVehicleCost> vcleVehicleCosts) {
        this.vcleVehicleCosts = vcleVehicleCosts;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleWorkSideDtl> getVcleWorkSideDtls() {
        return this.vcleWorkSideDtls;
    }
    
    public void setVcleWorkSideDtls(Set<VcleWorkSideDtl> vcleWorkSideDtls) {
        this.vcleWorkSideDtls = vcleWorkSideDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleLicense> getVcleVehicleLicenses() {
        return this.vcleVehicleLicenses;
    }
    
    public void setVcleVehicleLicenses(Set<VcleVehicleLicense> vcleVehicleLicenses) {
        this.vcleVehicleLicenses = vcleVehicleLicenses;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="VCLE_VEHICLE_INCLUDING_JOIN", schema="AHRAM", joinColumns = { 
        @JoinColumn(name="VEHICLE_SP", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="INCLUDE_CODE", nullable=false, updatable=false) })
    public Set<VcleVehicleIncluding> getVcleVehicleIncludings() {
        return this.vcleVehicleIncludings;
    }
    
    public void setVcleVehicleIncludings(Set<VcleVehicleIncluding> vcleVehicleIncludings) {
        this.vcleVehicleIncludings = vcleVehicleIncludings;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleLicenseReportCr> getVcleVehicleLicenseReportCrs() {
        return this.vcleVehicleLicenseReportCrs;
    }
    
    public void setVcleVehicleLicenseReportCrs(Set<VcleVehicleLicenseReportCr> vcleVehicleLicenseReportCrs) {
        this.vcleVehicleLicenseReportCrs = vcleVehicleLicenseReportCrs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleResponsibleJoin> getVcleVehicleResponsibleJoins() {
        return this.vcleVehicleResponsibleJoins;
    }
    
    public void setVcleVehicleResponsibleJoins(Set<VcleVehicleResponsibleJoin> vcleVehicleResponsibleJoins) {
        this.vcleVehicleResponsibleJoins = vcleVehicleResponsibleJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleMaster")
    public Set<VcleVehicleInvoiceLiq> getVcleVehicleInvoiceLiqs() {
        return this.vcleVehicleInvoiceLiqs;
    }
    
    public void setVcleVehicleInvoiceLiqs(Set<VcleVehicleInvoiceLiq> vcleVehicleInvoiceLiqs) {
        this.vcleVehicleInvoiceLiqs = vcleVehicleInvoiceLiqs;
    }




}


