package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleVehicleRepairType generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_REPAIR_TYPE"
    ,schema="CODEATOR"
)
public class VcleVehicleRepairType  implements java.io.Serializable {


     private byte repairType;
     private String repairNane;
     private Set<VcleVehicleResponsibleEmp> vcleVehicleResponsibleEmps = new HashSet<VcleVehicleResponsibleEmp>(0);
     private Set<VcleMaintanceRepairDtl> vcleMaintanceRepairDtls = new HashSet<VcleMaintanceRepairDtl>(0);

    public VcleVehicleRepairType() {
    }

	
    public VcleVehicleRepairType(byte repairType, String repairNane) {
        this.repairType = repairType;
        this.repairNane = repairNane;
    }
    public VcleVehicleRepairType(byte repairType, String repairNane, Set<VcleVehicleResponsibleEmp> vcleVehicleResponsibleEmps, Set<VcleMaintanceRepairDtl> vcleMaintanceRepairDtls) {
       this.repairType = repairType;
       this.repairNane = repairNane;
       this.vcleVehicleResponsibleEmps = vcleVehicleResponsibleEmps;
       this.vcleMaintanceRepairDtls = vcleMaintanceRepairDtls;
    }
   
     @Id 

    
    @Column(name="REPAIR_TYPE", unique=true, nullable=false, precision=2, scale=0)
    public byte getRepairType() {
        return this.repairType;
    }
    
    public void setRepairType(byte repairType) {
        this.repairType = repairType;
    }

    
    @Column(name="REPAIR_NANE", nullable=false, length=100)
    public String getRepairNane() {
        return this.repairNane;
    }
    
    public void setRepairNane(String repairNane) {
        this.repairNane = repairNane;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleRepairType")
    public Set<VcleVehicleResponsibleEmp> getVcleVehicleResponsibleEmps() {
        return this.vcleVehicleResponsibleEmps;
    }
    
    public void setVcleVehicleResponsibleEmps(Set<VcleVehicleResponsibleEmp> vcleVehicleResponsibleEmps) {
        this.vcleVehicleResponsibleEmps = vcleVehicleResponsibleEmps;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleVehicleRepairType")
    public Set<VcleMaintanceRepairDtl> getVcleMaintanceRepairDtls() {
        return this.vcleMaintanceRepairDtls;
    }
    
    public void setVcleMaintanceRepairDtls(Set<VcleMaintanceRepairDtl> vcleMaintanceRepairDtls) {
        this.vcleMaintanceRepairDtls = vcleMaintanceRepairDtls;
    }




}


