package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleDeptRequireMax generated by hbm2java
 */
@Entity
@Table(name="VCLE_DEPT_REQUIRE_MAX"
    ,schema="CODEATOR"
)
public class VcleDeptRequireMax  implements java.io.Serializable {


     private VcleDeptRequireMaxId id;
     private PerDeptOld perDeptOld;
     private Short maxRequire;

    public VcleDeptRequireMax() {
    }

	
    public VcleDeptRequireMax(VcleDeptRequireMaxId id, PerDeptOld perDeptOld) {
        this.id = id;
        this.perDeptOld = perDeptOld;
    }
    public VcleDeptRequireMax(VcleDeptRequireMaxId id, PerDeptOld perDeptOld, Short maxRequire) {
       this.id = id;
       this.perDeptOld = perDeptOld;
       this.maxRequire = maxRequire;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sectionNoOld", column=@Column(name="SECTION_NO_OLD", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="depNoOld", column=@Column(name="DEP_NO_OLD", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="maxReqSp", column=@Column(name="MAX_REQ_SP", nullable=false, precision=2, scale=0) ) } )
    public VcleDeptRequireMaxId getId() {
        return this.id;
    }
    
    public void setId(VcleDeptRequireMaxId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="SECTION_NO_OLD", referencedColumnName="SECTION_NO_OLD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DEP_NO_OLD", referencedColumnName="DEP_NO_OLD", nullable=false, insertable=false, updatable=false) } )
    public PerDeptOld getPerDeptOld() {
        return this.perDeptOld;
    }
    
    public void setPerDeptOld(PerDeptOld perDeptOld) {
        this.perDeptOld = perDeptOld;
    }

    
    @Column(name="MAX_REQUIRE", precision=3, scale=0)
    public Short getMaxRequire() {
        return this.maxRequire;
    }
    
    public void setMaxRequire(Short maxRequire) {
        this.maxRequire = maxRequire;
    }




}


