package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleVehicleInspectDtl generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_INSPECT_DTL"
    ,schema="CODEATOR"
)
public class VcleVehicleInspectDtl  implements java.io.Serializable {


     private VcleVehicleInspectDtlId id;
     private VcleVehicleInspect vcleVehicleInspect;
     private VcleCostType vcleCostType;
     private BigDecimal val;

    public VcleVehicleInspectDtl() {
    }

    public VcleVehicleInspectDtl(VcleVehicleInspectDtlId id, VcleVehicleInspect vcleVehicleInspect, VcleCostType vcleCostType, BigDecimal val) {
       this.id = id;
       this.vcleVehicleInspect = vcleVehicleInspect;
       this.vcleCostType = vcleCostType;
       this.val = val;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="inspectDate", column=@Column(name="INSPECT_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="licenseType", column=@Column(name="LICENSE_TYPE", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="costType", column=@Column(name="COST_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="costCode", column=@Column(name="COST_CODE", nullable=false, precision=6, scale=0) ) } )
    public VcleVehicleInspectDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleInspectDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="INSPECT_DATE", referencedColumnName="INSPECT_DATE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="LICENSE_TYPE", referencedColumnName="LICENSE_TYPE", nullable=false, insertable=false, updatable=false) } )
    public VcleVehicleInspect getVcleVehicleInspect() {
        return this.vcleVehicleInspect;
    }
    
    public void setVcleVehicleInspect(VcleVehicleInspect vcleVehicleInspect) {
        this.vcleVehicleInspect = vcleVehicleInspect;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="COST_TYPE", referencedColumnName="COST_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="COST_CODE", referencedColumnName="COST_CODE", nullable=false, insertable=false, updatable=false) } )
    public VcleCostType getVcleCostType() {
        return this.vcleCostType;
    }
    
    public void setVcleCostType(VcleCostType vcleCostType) {
        this.vcleCostType = vcleCostType;
    }

    
    @Column(name="VAL", nullable=false, precision=9)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }




}


