package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleJobType generated by hbm2java
 */
@Entity
@Table(name="VCLE_JOB_TYPE"
    ,schema="CODEATOR"
)
public class VcleJobType  implements java.io.Serializable {


     private short jobType;
     private String jobName;
     private Short valDay;
     private Short valDayMore;
     private BigDecimal dedRatio;
     private Short valVac;
     private Set<VcleWorkOnSaturdays> vcleWorkOnSaturdayses = new HashSet<VcleWorkOnSaturdays>(0);
     private Set<VcleEmployeeMaster> vcleEmployeeMasters = new HashSet<VcleEmployeeMaster>(0);
     private Set<VcleTravelExchange> vcleTravelExchanges = new HashSet<VcleTravelExchange>(0);
     private Set<VcleWorkOnSaturdayEmp> vcleWorkOnSaturdayEmps = new HashSet<VcleWorkOnSaturdayEmp>(0);

    public VcleJobType() {
    }

	
    public VcleJobType(short jobType, String jobName) {
        this.jobType = jobType;
        this.jobName = jobName;
    }
    public VcleJobType(short jobType, String jobName, Short valDay, Short valDayMore, BigDecimal dedRatio, Short valVac, Set<VcleWorkOnSaturdays> vcleWorkOnSaturdayses, Set<VcleEmployeeMaster> vcleEmployeeMasters, Set<VcleTravelExchange> vcleTravelExchanges, Set<VcleWorkOnSaturdayEmp> vcleWorkOnSaturdayEmps) {
       this.jobType = jobType;
       this.jobName = jobName;
       this.valDay = valDay;
       this.valDayMore = valDayMore;
       this.dedRatio = dedRatio;
       this.valVac = valVac;
       this.vcleWorkOnSaturdayses = vcleWorkOnSaturdayses;
       this.vcleEmployeeMasters = vcleEmployeeMasters;
       this.vcleTravelExchanges = vcleTravelExchanges;
       this.vcleWorkOnSaturdayEmps = vcleWorkOnSaturdayEmps;
    }
   
     @Id 

    
    @Column(name="JOB_TYPE", unique=true, nullable=false, precision=3, scale=0)
    public short getJobType() {
        return this.jobType;
    }
    
    public void setJobType(short jobType) {
        this.jobType = jobType;
    }

    
    @Column(name="JOB_NAME", nullable=false, length=75)
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    
    @Column(name="VAL_DAY", precision=3, scale=0)
    public Short getValDay() {
        return this.valDay;
    }
    
    public void setValDay(Short valDay) {
        this.valDay = valDay;
    }

    
    @Column(name="VAL_DAY_MORE", precision=3, scale=0)
    public Short getValDayMore() {
        return this.valDayMore;
    }
    
    public void setValDayMore(Short valDayMore) {
        this.valDayMore = valDayMore;
    }

    
    @Column(name="DED_RATIO", precision=3, scale=1)
    public BigDecimal getDedRatio() {
        return this.dedRatio;
    }
    
    public void setDedRatio(BigDecimal dedRatio) {
        this.dedRatio = dedRatio;
    }

    
    @Column(name="VAL_VAC", precision=3, scale=0)
    public Short getValVac() {
        return this.valVac;
    }
    
    public void setValVac(Short valVac) {
        this.valVac = valVac;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleJobType")
    public Set<VcleWorkOnSaturdays> getVcleWorkOnSaturdayses() {
        return this.vcleWorkOnSaturdayses;
    }
    
    public void setVcleWorkOnSaturdayses(Set<VcleWorkOnSaturdays> vcleWorkOnSaturdayses) {
        this.vcleWorkOnSaturdayses = vcleWorkOnSaturdayses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleJobType")
    public Set<VcleEmployeeMaster> getVcleEmployeeMasters() {
        return this.vcleEmployeeMasters;
    }
    
    public void setVcleEmployeeMasters(Set<VcleEmployeeMaster> vcleEmployeeMasters) {
        this.vcleEmployeeMasters = vcleEmployeeMasters;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleJobType")
    public Set<VcleTravelExchange> getVcleTravelExchanges() {
        return this.vcleTravelExchanges;
    }
    
    public void setVcleTravelExchanges(Set<VcleTravelExchange> vcleTravelExchanges) {
        this.vcleTravelExchanges = vcleTravelExchanges;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleJobType")
    public Set<VcleWorkOnSaturdayEmp> getVcleWorkOnSaturdayEmps() {
        return this.vcleWorkOnSaturdayEmps;
    }
    
    public void setVcleWorkOnSaturdayEmps(Set<VcleWorkOnSaturdayEmp> vcleWorkOnSaturdayEmps) {
        this.vcleWorkOnSaturdayEmps = vcleWorkOnSaturdayEmps;
    }




}


