package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleFuelBookNumberDtl generated by hbm2java
 */
@Entity
@Table(name="VCLE_FUEL_BOOK_NUMBER_DTL"
    ,schema="CODEATOR"
)
public class VcleFuelBookNumberDtl  implements java.io.Serializable {


     private VcleFuelBookNumberDtlId id;
     private VcleVehicleMaster vcleVehicleMaster;
     private VcleFuelBookNumber vcleFuelBookNumber;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;
     private int bookNumber;
     private Integer boardDigital;
     private Long employeeNo;
     private Date issueDateNumber;
     private Long countNumber;
     private BigDecimal litreVal;
     private BigDecimal litreSal;
     private BigDecimal litreQty;
     private Integer boardNumberOld;

    public VcleFuelBookNumberDtl() {
    }

	
    public VcleFuelBookNumberDtl(VcleFuelBookNumberDtlId id, VcleFuelBookNumber vcleFuelBookNumber, int bookNumber) {
        this.id = id;
        this.vcleFuelBookNumber = vcleFuelBookNumber;
        this.bookNumber = bookNumber;
    }
    public VcleFuelBookNumberDtl(VcleFuelBookNumberDtlId id, VcleVehicleMaster vcleVehicleMaster, VcleFuelBookNumber vcleFuelBookNumber, String boardAlfa1, String boardAlfa2, String boardAlfa3, int bookNumber, Integer boardDigital, Long employeeNo, Date issueDateNumber, Long countNumber, BigDecimal litreVal, BigDecimal litreSal, BigDecimal litreQty, Integer boardNumberOld) {
       this.id = id;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.vcleFuelBookNumber = vcleFuelBookNumber;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
       this.bookNumber = bookNumber;
       this.boardDigital = boardDigital;
       this.employeeNo = employeeNo;
       this.issueDateNumber = issueDateNumber;
       this.countNumber = countNumber;
       this.litreVal = litreVal;
       this.litreSal = litreSal;
       this.litreQty = litreQty;
       this.boardNumberOld = boardNumberOld;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalDate", column=@Column(name="FISCAL_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="bookSp", column=@Column(name="BOOK_SP", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="fuelType", column=@Column(name="FUEL_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="bookSeq", column=@Column(name="BOOK_SEQ", nullable=false, precision=3, scale=0) ) } )
    public VcleFuelBookNumberDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleFuelBookNumberDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP")
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="FISCAL_DATE", referencedColumnName="FISCAL_DATE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="FUEL_TYPE", referencedColumnName="FUEL_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="BOOK_SP", referencedColumnName="BOOK_SP", nullable=false, insertable=false, updatable=false) } )
    public VcleFuelBookNumber getVcleFuelBookNumber() {
        return this.vcleFuelBookNumber;
    }
    
    public void setVcleFuelBookNumber(VcleFuelBookNumber vcleFuelBookNumber) {
        this.vcleFuelBookNumber = vcleFuelBookNumber;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }

    
    @Column(name="BOOK_NUMBER", nullable=false, precision=9, scale=0)
    public int getBookNumber() {
        return this.bookNumber;
    }
    
    public void setBookNumber(int bookNumber) {
        this.bookNumber = bookNumber;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="EMPLOYEE_NO", precision=10, scale=0)
    public Long getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(Long employeeNo) {
        this.employeeNo = employeeNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DATE_NUMBER", length=7)
    public Date getIssueDateNumber() {
        return this.issueDateNumber;
    }
    
    public void setIssueDateNumber(Date issueDateNumber) {
        this.issueDateNumber = issueDateNumber;
    }

    
    @Column(name="COUNT_NUMBER", precision=11, scale=0)
    public Long getCountNumber() {
        return this.countNumber;
    }
    
    public void setCountNumber(Long countNumber) {
        this.countNumber = countNumber;
    }

    
    @Column(name="LITRE_VAL", precision=7)
    public BigDecimal getLitreVal() {
        return this.litreVal;
    }
    
    public void setLitreVal(BigDecimal litreVal) {
        this.litreVal = litreVal;
    }

    
    @Column(name="LITRE_SAL", precision=7)
    public BigDecimal getLitreSal() {
        return this.litreSal;
    }
    
    public void setLitreSal(BigDecimal litreSal) {
        this.litreSal = litreSal;
    }

    
    @Column(name="LITRE_QTY", precision=7)
    public BigDecimal getLitreQty() {
        return this.litreQty;
    }
    
    public void setLitreQty(BigDecimal litreQty) {
        this.litreQty = litreQty;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }




}


