package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleExecutionDay generated by hbm2java
 */
@Entity
@Table(name="VCLE_EXECUTION_DAY"
    ,schema="CODEATOR"
)
public class VcleExecutionDay  implements java.io.Serializable {


     private VcleExecutionDayId id;
     private VcleExecutionDate vcleExecutionDate;
     private String dayName;
     private Date execDay;
     private Set<VcleTankBalance> vcleTankBalances = new HashSet<VcleTankBalance>(0);

    public VcleExecutionDay() {
    }

	
    public VcleExecutionDay(VcleExecutionDayId id, VcleExecutionDate vcleExecutionDate) {
        this.id = id;
        this.vcleExecutionDate = vcleExecutionDate;
    }
    public VcleExecutionDay(VcleExecutionDayId id, VcleExecutionDate vcleExecutionDate, String dayName, Date execDay, Set<VcleTankBalance> vcleTankBalances) {
       this.id = id;
       this.vcleExecutionDate = vcleExecutionDate;
       this.dayName = dayName;
       this.execDay = execDay;
       this.vcleTankBalances = vcleTankBalances;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="execMm", column=@Column(name="EXEC_MM", nullable=false, length=7) ), 
        @AttributeOverride(name="dayNo", column=@Column(name="DAY_NO", nullable=false, precision=2, scale=0) ) } )
    public VcleExecutionDayId getId() {
        return this.id;
    }
    
    public void setId(VcleExecutionDayId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EXEC_MM", nullable=false, insertable=false, updatable=false)
    public VcleExecutionDate getVcleExecutionDate() {
        return this.vcleExecutionDate;
    }
    
    public void setVcleExecutionDate(VcleExecutionDate vcleExecutionDate) {
        this.vcleExecutionDate = vcleExecutionDate;
    }

    
    @Column(name="DAY_NAME", length=20)
    public String getDayName() {
        return this.dayName;
    }
    
    public void setDayName(String dayName) {
        this.dayName = dayName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXEC_DAY", length=7)
    public Date getExecDay() {
        return this.execDay;
    }
    
    public void setExecDay(Date execDay) {
        this.execDay = execDay;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleExecutionDay")
    public Set<VcleTankBalance> getVcleTankBalances() {
        return this.vcleTankBalances;
    }
    
    public void setVcleTankBalances(Set<VcleTankBalance> vcleTankBalances) {
        this.vcleTankBalances = vcleTankBalances;
    }




}


