package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleDistributeDateOpen generated by hbm2java
 */
@Entity
@Table(name="VCLE_DISTRIBUTE_DATE_OPEN"
    ,schema="CODEATOR"
)
public class VcleDistributeDateOpen  implements java.io.Serializable {


     private VcleDistributeDateOpenId id;
     private Date execMm;
     private Date approvedDate;
     private String rmrk;
     private Boolean chkLock;
     private Set<VcleDistributeDate> vcleDistributeDates = new HashSet<VcleDistributeDate>(0);

    public VcleDistributeDateOpen() {
    }

	
    public VcleDistributeDateOpen(VcleDistributeDateOpenId id) {
        this.id = id;
    }
    public VcleDistributeDateOpen(VcleDistributeDateOpenId id, Date execMm, Date approvedDate, String rmrk, Boolean chkLock, Set<VcleDistributeDate> vcleDistributeDates) {
       this.id = id;
       this.execMm = execMm;
       this.approvedDate = approvedDate;
       this.rmrk = rmrk;
       this.chkLock = chkLock;
       this.vcleDistributeDates = vcleDistributeDates;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalYear", column=@Column(name="FISCAL_YEAR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="travelMm", column=@Column(name="TRAVEL_MM", nullable=false, precision=2, scale=0) ) } )
    public VcleDistributeDateOpenId getId() {
        return this.id;
    }
    
    public void setId(VcleDistributeDateOpenId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXEC_MM", length=7)
    public Date getExecMm() {
        return this.execMm;
    }
    
    public void setExecMm(Date execMm) {
        this.execMm = execMm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="APPROVED_DATE", length=7)
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    
    @Column(name="RMRK", length=240)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="CHK_LOCK", precision=1, scale=0)
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleDistributeDateOpen")
    public Set<VcleDistributeDate> getVcleDistributeDates() {
        return this.vcleDistributeDates;
    }
    
    public void setVcleDistributeDates(Set<VcleDistributeDate> vcleDistributeDates) {
        this.vcleDistributeDates = vcleDistributeDates;
    }




}


