package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VcleVehicleDriverJoinId generated by hbm2java
 */
@Embeddable
public class VcleVehicleDriverJoinId  implements java.io.Serializable {


     private long employeeId;
     private int vehicleSp;

    public VcleVehicleDriverJoinId() {
    }

    public VcleVehicleDriverJoinId(long employeeId, int vehicleSp) {
       this.employeeId = employeeId;
       this.vehicleSp = vehicleSp;
    }
   


    @Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0)
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }


    @Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0)
    public int getVehicleSp() {
        return this.vehicleSp;
    }
    
    public void setVehicleSp(int vehicleSp) {
        this.vehicleSp = vehicleSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleVehicleDriverJoinId) ) return false;
		 VcleVehicleDriverJoinId castOther = ( VcleVehicleDriverJoinId ) other; 
         
		 return (this.getEmployeeId()==castOther.getEmployeeId())
 && (this.getVehicleSp()==castOther.getVehicleSp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getEmployeeId();
         result = 37 * result + this.getVehicleSp();
         return result;
   }   


}


