package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleVehicleTransactionDtl generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_TRANSACTION_DTL"
    ,schema="CODEATOR"
)
public class VcleVehicleTransactionDtl  implements java.io.Serializable {


     private VcleVehicleTransactionDtlId id;
     private VcleVehicleType vcleVehicleType;
     private VcleVehicleTransaction vcleVehicleTransaction;
     private VcleVehicleMaster vcleVehicleMaster;
     private Integer boardNumberOld;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;

    public VcleVehicleTransactionDtl() {
    }

	
    public VcleVehicleTransactionDtl(VcleVehicleTransactionDtlId id, VcleVehicleType vcleVehicleType, VcleVehicleTransaction vcleVehicleTransaction, VcleVehicleMaster vcleVehicleMaster) {
        this.id = id;
        this.vcleVehicleType = vcleVehicleType;
        this.vcleVehicleTransaction = vcleVehicleTransaction;
        this.vcleVehicleMaster = vcleVehicleMaster;
    }
    public VcleVehicleTransactionDtl(VcleVehicleTransactionDtlId id, VcleVehicleType vcleVehicleType, VcleVehicleTransaction vcleVehicleTransaction, VcleVehicleMaster vcleVehicleMaster, Integer boardNumberOld, Integer boardDigital, String boardAlfa1, String boardAlfa2, String boardAlfa3) {
       this.id = id;
       this.vcleVehicleType = vcleVehicleType;
       this.vcleVehicleTransaction = vcleVehicleTransaction;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.boardNumberOld = boardNumberOld;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="transType", column=@Column(name="TRANS_TYPE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ) } )
    public VcleVehicleTransactionDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleTransactionDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_TYPE", nullable=false)
    public VcleVehicleType getVcleVehicleType() {
        return this.vcleVehicleType;
    }
    
    public void setVcleVehicleType(VcleVehicleType vcleVehicleType) {
        this.vcleVehicleType = vcleVehicleType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="TRANS_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleVehicleTransaction getVcleVehicleTransaction() {
        return this.vcleVehicleTransaction;
    }
    
    public void setVcleVehicleTransaction(VcleVehicleTransaction vcleVehicleTransaction) {
        this.vcleVehicleTransaction = vcleVehicleTransaction;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

    
    @Column(name="BOARD_NUMBER_OLD", precision=8, scale=0)
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }

    
    @Column(name="BOARD_DIGITAL", precision=6, scale=0)
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }

    
    @Column(name="BOARD_ALFA1", length=1)
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }

    
    @Column(name="BOARD_ALFA2", length=1)
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }

    
    @Column(name="BOARD_ALFA3", length=1)
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }




}


