package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleCostType generated by hbm2java
 */
@Entity
@Table(name="VCLE_COST_TYPE"
    ,schema="CODEATOR"
)
public class VcleCostType  implements java.io.Serializable {


     private VcleCostTypeId id;
     private String costName;
     private BigDecimal val;
     private Boolean costState;
     private String issueDocTypeName;
     private Byte issueDocFor;
     private String issueDocType;
     private Boolean actionPlace;
     private Set<VcleProcedureLicenseJoin> vcleProcedureLicenseJoins = new HashSet<VcleProcedureLicenseJoin>(0);
     private Set<VcleVehicleInvoiceMan> vcleVehicleInvoiceMans = new HashSet<VcleVehicleInvoiceMan>(0);
     private Set<VcleVehicleInvoiceLiq> vcleVehicleInvoiceLiqs = new HashSet<VcleVehicleInvoiceLiq>(0);
     private Set<VcleTravelExchange> vcleTravelExchanges = new HashSet<VcleTravelExchange>(0);
     private Set<VcleVehicleLicenseReportDt> vcleVehicleLicenseReportDts = new HashSet<VcleVehicleLicenseReportDt>(0);
     private Set<VcleVehicleInspectDtl> vcleVehicleInspectDtls = new HashSet<VcleVehicleInspectDtl>(0);
     private Set<VcleVehicleLicenseDtl> vcleVehicleLicenseDtls = new HashSet<VcleVehicleLicenseDtl>(0);

    public VcleCostType() {
    }

	
    public VcleCostType(VcleCostTypeId id, String costName) {
        this.id = id;
        this.costName = costName;
    }
    public VcleCostType(VcleCostTypeId id, String costName, BigDecimal val, Boolean costState, String issueDocTypeName, Byte issueDocFor, String issueDocType, Boolean actionPlace, Set<VcleProcedureLicenseJoin> vcleProcedureLicenseJoins, Set<VcleVehicleInvoiceMan> vcleVehicleInvoiceMans, Set<VcleVehicleInvoiceLiq> vcleVehicleInvoiceLiqs, Set<VcleTravelExchange> vcleTravelExchanges, Set<VcleVehicleLicenseReportDt> vcleVehicleLicenseReportDts, Set<VcleVehicleInspectDtl> vcleVehicleInspectDtls, Set<VcleVehicleLicenseDtl> vcleVehicleLicenseDtls) {
       this.id = id;
       this.costName = costName;
       this.val = val;
       this.costState = costState;
       this.issueDocTypeName = issueDocTypeName;
       this.issueDocFor = issueDocFor;
       this.issueDocType = issueDocType;
       this.actionPlace = actionPlace;
       this.vcleProcedureLicenseJoins = vcleProcedureLicenseJoins;
       this.vcleVehicleInvoiceMans = vcleVehicleInvoiceMans;
       this.vcleVehicleInvoiceLiqs = vcleVehicleInvoiceLiqs;
       this.vcleTravelExchanges = vcleTravelExchanges;
       this.vcleVehicleLicenseReportDts = vcleVehicleLicenseReportDts;
       this.vcleVehicleInspectDtls = vcleVehicleInspectDtls;
       this.vcleVehicleLicenseDtls = vcleVehicleLicenseDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="costType", column=@Column(name="COST_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="costCode", column=@Column(name="COST_CODE", nullable=false, precision=6, scale=0) ) } )
    public VcleCostTypeId getId() {
        return this.id;
    }
    
    public void setId(VcleCostTypeId id) {
        this.id = id;
    }

    
    @Column(name="COST_NAME", nullable=false, length=100)
    public String getCostName() {
        return this.costName;
    }
    
    public void setCostName(String costName) {
        this.costName = costName;
    }

    
    @Column(name="VAL", precision=9)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="COST_STATE", precision=1, scale=0)
    public Boolean getCostState() {
        return this.costState;
    }
    
    public void setCostState(Boolean costState) {
        this.costState = costState;
    }

    
    @Column(name="ISSUE_DOC_TYPE_NAME", length=100)
    public String getIssueDocTypeName() {
        return this.issueDocTypeName;
    }
    
    public void setIssueDocTypeName(String issueDocTypeName) {
        this.issueDocTypeName = issueDocTypeName;
    }

    
    @Column(name="ISSUE_DOC_FOR", precision=2, scale=0)
    public Byte getIssueDocFor() {
        return this.issueDocFor;
    }
    
    public void setIssueDocFor(Byte issueDocFor) {
        this.issueDocFor = issueDocFor;
    }

    
    @Column(name="ISSUE_DOC_TYPE", length=5)
    public String getIssueDocType() {
        return this.issueDocType;
    }
    
    public void setIssueDocType(String issueDocType) {
        this.issueDocType = issueDocType;
    }

    
    @Column(name="ACTION_PLACE", precision=1, scale=0)
    public Boolean getActionPlace() {
        return this.actionPlace;
    }
    
    public void setActionPlace(Boolean actionPlace) {
        this.actionPlace = actionPlace;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleCostType")
    public Set<VcleProcedureLicenseJoin> getVcleProcedureLicenseJoins() {
        return this.vcleProcedureLicenseJoins;
    }
    
    public void setVcleProcedureLicenseJoins(Set<VcleProcedureLicenseJoin> vcleProcedureLicenseJoins) {
        this.vcleProcedureLicenseJoins = vcleProcedureLicenseJoins;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleCostType")
    public Set<VcleVehicleInvoiceMan> getVcleVehicleInvoiceMans() {
        return this.vcleVehicleInvoiceMans;
    }
    
    public void setVcleVehicleInvoiceMans(Set<VcleVehicleInvoiceMan> vcleVehicleInvoiceMans) {
        this.vcleVehicleInvoiceMans = vcleVehicleInvoiceMans;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleCostType")
    public Set<VcleVehicleInvoiceLiq> getVcleVehicleInvoiceLiqs() {
        return this.vcleVehicleInvoiceLiqs;
    }
    
    public void setVcleVehicleInvoiceLiqs(Set<VcleVehicleInvoiceLiq> vcleVehicleInvoiceLiqs) {
        this.vcleVehicleInvoiceLiqs = vcleVehicleInvoiceLiqs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleCostType")
    public Set<VcleTravelExchange> getVcleTravelExchanges() {
        return this.vcleTravelExchanges;
    }
    
    public void setVcleTravelExchanges(Set<VcleTravelExchange> vcleTravelExchanges) {
        this.vcleTravelExchanges = vcleTravelExchanges;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleCostType")
    public Set<VcleVehicleLicenseReportDt> getVcleVehicleLicenseReportDts() {
        return this.vcleVehicleLicenseReportDts;
    }
    
    public void setVcleVehicleLicenseReportDts(Set<VcleVehicleLicenseReportDt> vcleVehicleLicenseReportDts) {
        this.vcleVehicleLicenseReportDts = vcleVehicleLicenseReportDts;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleCostType")
    public Set<VcleVehicleInspectDtl> getVcleVehicleInspectDtls() {
        return this.vcleVehicleInspectDtls;
    }
    
    public void setVcleVehicleInspectDtls(Set<VcleVehicleInspectDtl> vcleVehicleInspectDtls) {
        this.vcleVehicleInspectDtls = vcleVehicleInspectDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleCostType")
    public Set<VcleVehicleLicenseDtl> getVcleVehicleLicenseDtls() {
        return this.vcleVehicleLicenseDtls;
    }
    
    public void setVcleVehicleLicenseDtls(Set<VcleVehicleLicenseDtl> vcleVehicleLicenseDtls) {
        this.vcleVehicleLicenseDtls = vcleVehicleLicenseDtls;
    }




}


