package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleFiscalDate generated by hbm2java
 */
@Entity
@Table(name="VCLE_FISCAL_DATE"
    ,schema="CODEATOR"
)
public class VcleFiscalDate  implements java.io.Serializable {


     private Date fiscalDate;
     private Boolean flg;
     private Set<VcleVehicleIncome> vcleVehicleIncomes = new HashSet<VcleVehicleIncome>(0);
     private Set<VcleRecordMovement> vcleRecordMovements = new HashSet<VcleRecordMovement>(0);
     private Set<VcleIssueDocument> vcleIssueDocuments = new HashSet<VcleIssueDocument>(0);

    public VcleFiscalDate() {
    }

	
    public VcleFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }
    public VcleFiscalDate(Date fiscalDate, Boolean flg, Set<VcleVehicleIncome> vcleVehicleIncomes, Set<VcleRecordMovement> vcleRecordMovements, Set<VcleIssueDocument> vcleIssueDocuments) {
       this.fiscalDate = fiscalDate;
       this.flg = flg;
       this.vcleVehicleIncomes = vcleVehicleIncomes;
       this.vcleRecordMovements = vcleRecordMovements;
       this.vcleIssueDocuments = vcleIssueDocuments;
    }
   
     @Id 

    @Temporal(TemporalType.DATE)
    @Column(name="FISCAL_DATE", unique=true, nullable=false, length=7)
    public Date getFiscalDate() {
        return this.fiscalDate;
    }
    
    public void setFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }

    
    @Column(name="FLG", precision=1, scale=0)
    public Boolean getFlg() {
        return this.flg;
    }
    
    public void setFlg(Boolean flg) {
        this.flg = flg;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleFiscalDate")
    public Set<VcleVehicleIncome> getVcleVehicleIncomes() {
        return this.vcleVehicleIncomes;
    }
    
    public void setVcleVehicleIncomes(Set<VcleVehicleIncome> vcleVehicleIncomes) {
        this.vcleVehicleIncomes = vcleVehicleIncomes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleFiscalDate")
    public Set<VcleRecordMovement> getVcleRecordMovements() {
        return this.vcleRecordMovements;
    }
    
    public void setVcleRecordMovements(Set<VcleRecordMovement> vcleRecordMovements) {
        this.vcleRecordMovements = vcleRecordMovements;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleFiscalDate")
    public Set<VcleIssueDocument> getVcleIssueDocuments() {
        return this.vcleIssueDocuments;
    }
    
    public void setVcleIssueDocuments(Set<VcleIssueDocument> vcleIssueDocuments) {
        this.vcleIssueDocuments = vcleIssueDocuments;
    }




}


