package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleIssueDocumentLiq generated by hbm2java
 */
@Entity
@Table(name="VCLE_ISSUE_DOCUMENT_LIQ"
    ,schema="CODEATOR"
)
public class VcleIssueDocumentLiq  implements java.io.Serializable {


     private VcleIssueDocumentLiqId id;
     private PerOrganizationStructure perOrganizationStructure;
     private PerEmploymentMaster perEmploymentMaster;
     private Long issueDocSerial;
     private BigDecimal editorUserId;
     private Boolean actionPlace;
     private String issueType;
     private String issueDocStatus;
     private Date issueDocDate;
     private String vcIssueDocType;
     private BigDecimal vcCutValue;
     private Short vcDeserveDocCount;
     private String vcDeserveNotes;
     private String vcDeserveName;
     private BigDecimal vcDeserveValue;
     private String currencyCode;
     private String accountUnitCode;
     private Set<VcleVehicleInvoiceLiq> vcleVehicleInvoiceLiqs = new HashSet<VcleVehicleInvoiceLiq>(0);

    public VcleIssueDocumentLiq() {
    }

	
    public VcleIssueDocumentLiq(VcleIssueDocumentLiqId id) {
        this.id = id;
    }
    public VcleIssueDocumentLiq(VcleIssueDocumentLiqId id, PerOrganizationStructure perOrganizationStructure, PerEmploymentMaster perEmploymentMaster, Long issueDocSerial, BigDecimal editorUserId, Boolean actionPlace, String issueType, String issueDocStatus, Date issueDocDate, String vcIssueDocType, BigDecimal vcCutValue, Short vcDeserveDocCount, String vcDeserveNotes, String vcDeserveName, BigDecimal vcDeserveValue, String currencyCode, String accountUnitCode, Set<VcleVehicleInvoiceLiq> vcleVehicleInvoiceLiqs) {
       this.id = id;
       this.perOrganizationStructure = perOrganizationStructure;
       this.perEmploymentMaster = perEmploymentMaster;
       this.issueDocSerial = issueDocSerial;
       this.editorUserId = editorUserId;
       this.actionPlace = actionPlace;
       this.issueType = issueType;
       this.issueDocStatus = issueDocStatus;
       this.issueDocDate = issueDocDate;
       this.vcIssueDocType = vcIssueDocType;
       this.vcCutValue = vcCutValue;
       this.vcDeserveDocCount = vcDeserveDocCount;
       this.vcDeserveNotes = vcDeserveNotes;
       this.vcDeserveName = vcDeserveName;
       this.vcDeserveValue = vcDeserveValue;
       this.currencyCode = currencyCode;
       this.accountUnitCode = accountUnitCode;
       this.vcleVehicleInvoiceLiqs = vcleVehicleInvoiceLiqs;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalYear", column=@Column(name="FISCAL_YEAR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="vcIssueDocSp", column=@Column(name="VC_ISSUE_DOC_SP", nullable=false, precision=12, scale=0) ) } )
    public VcleIssueDocumentLiqId getId() {
        return this.id;
    }
    
    public void setId(VcleIssueDocumentLiqId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ORG_ID")
    public PerOrganizationStructure getPerOrganizationStructure() {
        return this.perOrganizationStructure;
    }
    
    public void setPerOrganizationStructure(PerOrganizationStructure perOrganizationStructure) {
        this.perOrganizationStructure = perOrganizationStructure;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

    
    @Column(name="ISSUE_DOC_SERIAL", precision=12, scale=0)
    public Long getIssueDocSerial() {
        return this.issueDocSerial;
    }
    
    public void setIssueDocSerial(Long issueDocSerial) {
        this.issueDocSerial = issueDocSerial;
    }

    
    @Column(name="EDITOR_USER_ID", precision=22, scale=0)
    public BigDecimal getEditorUserId() {
        return this.editorUserId;
    }
    
    public void setEditorUserId(BigDecimal editorUserId) {
        this.editorUserId = editorUserId;
    }

    
    @Column(name="ACTION_PLACE", precision=1, scale=0)
    public Boolean getActionPlace() {
        return this.actionPlace;
    }
    
    public void setActionPlace(Boolean actionPlace) {
        this.actionPlace = actionPlace;
    }

    
    @Column(name="ISSUE_TYPE", length=2)
    public String getIssueType() {
        return this.issueType;
    }
    
    public void setIssueType(String issueType) {
        this.issueType = issueType;
    }

    
    @Column(name="ISSUE_DOC_STATUS", length=2)
    public String getIssueDocStatus() {
        return this.issueDocStatus;
    }
    
    public void setIssueDocStatus(String issueDocStatus) {
        this.issueDocStatus = issueDocStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUE_DOC_DATE", length=7)
    public Date getIssueDocDate() {
        return this.issueDocDate;
    }
    
    public void setIssueDocDate(Date issueDocDate) {
        this.issueDocDate = issueDocDate;
    }

    
    @Column(name="VC_ISSUE_DOC_TYPE", length=5)
    public String getVcIssueDocType() {
        return this.vcIssueDocType;
    }
    
    public void setVcIssueDocType(String vcIssueDocType) {
        this.vcIssueDocType = vcIssueDocType;
    }

    
    @Column(name="VC_CUT_VALUE", precision=16, scale=3)
    public BigDecimal getVcCutValue() {
        return this.vcCutValue;
    }
    
    public void setVcCutValue(BigDecimal vcCutValue) {
        this.vcCutValue = vcCutValue;
    }

    
    @Column(name="VC_DESERVE_DOC_COUNT", precision=3, scale=0)
    public Short getVcDeserveDocCount() {
        return this.vcDeserveDocCount;
    }
    
    public void setVcDeserveDocCount(Short vcDeserveDocCount) {
        this.vcDeserveDocCount = vcDeserveDocCount;
    }

    
    @Column(name="VC_DESERVE_NOTES", length=100)
    public String getVcDeserveNotes() {
        return this.vcDeserveNotes;
    }
    
    public void setVcDeserveNotes(String vcDeserveNotes) {
        this.vcDeserveNotes = vcDeserveNotes;
    }

    
    @Column(name="VC_DESERVE_NAME", length=150)
    public String getVcDeserveName() {
        return this.vcDeserveName;
    }
    
    public void setVcDeserveName(String vcDeserveName) {
        this.vcDeserveName = vcDeserveName;
    }

    
    @Column(name="VC_DESERVE_VALUE", precision=16, scale=3)
    public BigDecimal getVcDeserveValue() {
        return this.vcDeserveValue;
    }
    
    public void setVcDeserveValue(BigDecimal vcDeserveValue) {
        this.vcDeserveValue = vcDeserveValue;
    }

    
    @Column(name="CURRENCY_CODE", length=4)
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="ACCOUNT_UNIT_CODE", length=4)
    public String getAccountUnitCode() {
        return this.accountUnitCode;
    }
    
    public void setAccountUnitCode(String accountUnitCode) {
        this.accountUnitCode = accountUnitCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleIssueDocumentLiq")
    public Set<VcleVehicleInvoiceLiq> getVcleVehicleInvoiceLiqs() {
        return this.vcleVehicleInvoiceLiqs;
    }
    
    public void setVcleVehicleInvoiceLiqs(Set<VcleVehicleInvoiceLiq> vcleVehicleInvoiceLiqs) {
        this.vcleVehicleInvoiceLiqs = vcleVehicleInvoiceLiqs;
    }




}


