package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleMotorChange generated by hbm2java
 */
@Entity
@Table(name="VCLE_MOTOR_CHANGE"
    ,schema="CODEATOR"
)
public class VcleMotorChange  implements java.io.Serializable {


     private VcleMotorChangeId id;
     private VcleVehicleMaster vcleVehicleMaster;
     private PerEmploymentMaster perEmploymentMaster;
     private short changeSp;
     private Date purchaseDate;
     private BigDecimal purchaseValue;
     private String motorNumber;
     private Date fixDate;
     private Integer fixLetterNo;
     private String shassNumber;
     private Integer invoiceNumber;

    public VcleMotorChange() {
    }

	
    public VcleMotorChange(VcleMotorChangeId id, VcleVehicleMaster vcleVehicleMaster, short changeSp, Date fixDate) {
        this.id = id;
        this.vcleVehicleMaster = vcleVehicleMaster;
        this.changeSp = changeSp;
        this.fixDate = fixDate;
    }
    public VcleMotorChange(VcleMotorChangeId id, VcleVehicleMaster vcleVehicleMaster, PerEmploymentMaster perEmploymentMaster, short changeSp, Date purchaseDate, BigDecimal purchaseValue, String motorNumber, Date fixDate, Integer fixLetterNo, String shassNumber, Integer invoiceNumber) {
       this.id = id;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.perEmploymentMaster = perEmploymentMaster;
       this.changeSp = changeSp;
       this.purchaseDate = purchaseDate;
       this.purchaseValue = purchaseValue;
       this.motorNumber = motorNumber;
       this.fixDate = fixDate;
       this.fixLetterNo = fixLetterNo;
       this.shassNumber = shassNumber;
       this.invoiceNumber = invoiceNumber;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="changeType", column=@Column(name="CHANGE_TYPE", nullable=false, precision=1, scale=0) ) } )
    public VcleMotorChangeId getId() {
        return this.id;
    }
    
    public void setId(VcleMotorChangeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

    
    @Column(name="CHANGE_SP", nullable=false, precision=4, scale=0)
    public short getChangeSp() {
        return this.changeSp;
    }
    
    public void setChangeSp(short changeSp) {
        this.changeSp = changeSp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PURCHASE_DATE", length=7)
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    
    @Column(name="PURCHASE_VALUE", precision=9)
    public BigDecimal getPurchaseValue() {
        return this.purchaseValue;
    }
    
    public void setPurchaseValue(BigDecimal purchaseValue) {
        this.purchaseValue = purchaseValue;
    }

    
    @Column(name="MOTOR_NUMBER", length=40)
    public String getMotorNumber() {
        return this.motorNumber;
    }
    
    public void setMotorNumber(String motorNumber) {
        this.motorNumber = motorNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FIX_DATE", nullable=false, length=7)
    public Date getFixDate() {
        return this.fixDate;
    }
    
    public void setFixDate(Date fixDate) {
        this.fixDate = fixDate;
    }

    
    @Column(name="FIX_LETTER_NO", precision=9, scale=0)
    public Integer getFixLetterNo() {
        return this.fixLetterNo;
    }
    
    public void setFixLetterNo(Integer fixLetterNo) {
        this.fixLetterNo = fixLetterNo;
    }

    
    @Column(name="SHASS_NUMBER", length=40)
    public String getShassNumber() {
        return this.shassNumber;
    }
    
    public void setShassNumber(String shassNumber) {
        this.shassNumber = shassNumber;
    }

    
    @Column(name="INVOICE_NUMBER", precision=6, scale=0)
    public Integer getInvoiceNumber() {
        return this.invoiceNumber;
    }
    
    public void setInvoiceNumber(Integer invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }




}


