package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleFuelBalanceLiquid generated by hbm2java
 */
@Entity
@Table(name="VCLE_FUEL_BALANCE_LIQUID"
    ,schema="CODEATOR"
)
public class VcleFuelBalanceLiquid  implements java.io.Serializable {


     private VcleFuelBalanceLiquidId id;
     private VcleShiftType vcleShiftType;
     private VcleFuelOpenDay vcleFuelOpenDay;
     private Date fiscalDate;
     private BigDecimal fristBnzStartQun;
     private BigDecimal fristBnzStartNum;
     private BigDecimal fristBnzQun;
     private BigDecimal fristBnzNum;
     private Boolean fristBnzSign;
     private BigDecimal fristBnzFrk;
     private BigDecimal secondBnzStartQun;
     private BigDecimal secondBnzStartNum;
     private BigDecimal secondBnzQun;
     private BigDecimal secondBnzNum;
     private Boolean secondBnzSign;
     private BigDecimal secondBnzFrk;
     private BigDecimal fristSolStartQun;
     private BigDecimal fristSolStartNum;
     private BigDecimal fristSolQun;
     private BigDecimal fristSolNum;
     private Boolean fristSolSign;
     private BigDecimal fristSolFrk;
     private Long eznSeqBal;
     private Boolean chkLockShift;
     private Boolean chkLockDay;
     private BigDecimal secondSolStartNum;
     private BigDecimal secondSolNum;

    public VcleFuelBalanceLiquid() {
    }

	
    public VcleFuelBalanceLiquid(VcleFuelBalanceLiquidId id, VcleShiftType vcleShiftType, VcleFuelOpenDay vcleFuelOpenDay, Date fiscalDate) {
        this.id = id;
        this.vcleShiftType = vcleShiftType;
        this.vcleFuelOpenDay = vcleFuelOpenDay;
        this.fiscalDate = fiscalDate;
    }
    public VcleFuelBalanceLiquid(VcleFuelBalanceLiquidId id, VcleShiftType vcleShiftType, VcleFuelOpenDay vcleFuelOpenDay, Date fiscalDate, BigDecimal fristBnzStartQun, BigDecimal fristBnzStartNum, BigDecimal fristBnzQun, BigDecimal fristBnzNum, Boolean fristBnzSign, BigDecimal fristBnzFrk, BigDecimal secondBnzStartQun, BigDecimal secondBnzStartNum, BigDecimal secondBnzQun, BigDecimal secondBnzNum, Boolean secondBnzSign, BigDecimal secondBnzFrk, BigDecimal fristSolStartQun, BigDecimal fristSolStartNum, BigDecimal fristSolQun, BigDecimal fristSolNum, Boolean fristSolSign, BigDecimal fristSolFrk, Long eznSeqBal, Boolean chkLockShift, Boolean chkLockDay, BigDecimal secondSolStartNum, BigDecimal secondSolNum) {
       this.id = id;
       this.vcleShiftType = vcleShiftType;
       this.vcleFuelOpenDay = vcleFuelOpenDay;
       this.fiscalDate = fiscalDate;
       this.fristBnzStartQun = fristBnzStartQun;
       this.fristBnzStartNum = fristBnzStartNum;
       this.fristBnzQun = fristBnzQun;
       this.fristBnzNum = fristBnzNum;
       this.fristBnzSign = fristBnzSign;
       this.fristBnzFrk = fristBnzFrk;
       this.secondBnzStartQun = secondBnzStartQun;
       this.secondBnzStartNum = secondBnzStartNum;
       this.secondBnzQun = secondBnzQun;
       this.secondBnzNum = secondBnzNum;
       this.secondBnzSign = secondBnzSign;
       this.secondBnzFrk = secondBnzFrk;
       this.fristSolStartQun = fristSolStartQun;
       this.fristSolStartNum = fristSolStartNum;
       this.fristSolQun = fristSolQun;
       this.fristSolNum = fristSolNum;
       this.fristSolSign = fristSolSign;
       this.fristSolFrk = fristSolFrk;
       this.eznSeqBal = eznSeqBal;
       this.chkLockShift = chkLockShift;
       this.chkLockDay = chkLockDay;
       this.secondSolStartNum = secondSolStartNum;
       this.secondSolNum = secondSolNum;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locCode", column=@Column(name="LOC_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="execDate", column=@Column(name="EXEC_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="shiftType", column=@Column(name="SHIFT_TYPE", nullable=false, precision=1, scale=0) ) } )
    public VcleFuelBalanceLiquidId getId() {
        return this.id;
    }
    
    public void setId(VcleFuelBalanceLiquidId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SHIFT_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleShiftType getVcleShiftType() {
        return this.vcleShiftType;
    }
    
    public void setVcleShiftType(VcleShiftType vcleShiftType) {
        this.vcleShiftType = vcleShiftType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EXEC_DATE", nullable=false, insertable=false, updatable=false)
    public VcleFuelOpenDay getVcleFuelOpenDay() {
        return this.vcleFuelOpenDay;
    }
    
    public void setVcleFuelOpenDay(VcleFuelOpenDay vcleFuelOpenDay) {
        this.vcleFuelOpenDay = vcleFuelOpenDay;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FISCAL_DATE", nullable=false, length=7)
    public Date getFiscalDate() {
        return this.fiscalDate;
    }
    
    public void setFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }

    
    @Column(name="FRIST_BNZ_START_QUN", precision=12, scale=3)
    public BigDecimal getFristBnzStartQun() {
        return this.fristBnzStartQun;
    }
    
    public void setFristBnzStartQun(BigDecimal fristBnzStartQun) {
        this.fristBnzStartQun = fristBnzStartQun;
    }

    
    @Column(name="FRIST_BNZ_START_NUM", precision=12, scale=3)
    public BigDecimal getFristBnzStartNum() {
        return this.fristBnzStartNum;
    }
    
    public void setFristBnzStartNum(BigDecimal fristBnzStartNum) {
        this.fristBnzStartNum = fristBnzStartNum;
    }

    
    @Column(name="FRIST_BNZ_QUN", precision=12, scale=3)
    public BigDecimal getFristBnzQun() {
        return this.fristBnzQun;
    }
    
    public void setFristBnzQun(BigDecimal fristBnzQun) {
        this.fristBnzQun = fristBnzQun;
    }

    
    @Column(name="FRIST_BNZ_NUM", precision=12, scale=3)
    public BigDecimal getFristBnzNum() {
        return this.fristBnzNum;
    }
    
    public void setFristBnzNum(BigDecimal fristBnzNum) {
        this.fristBnzNum = fristBnzNum;
    }

    
    @Column(name="FRIST_BNZ_SIGN", precision=1, scale=0)
    public Boolean getFristBnzSign() {
        return this.fristBnzSign;
    }
    
    public void setFristBnzSign(Boolean fristBnzSign) {
        this.fristBnzSign = fristBnzSign;
    }

    
    @Column(name="FRIST_BNZ_FRK", precision=12)
    public BigDecimal getFristBnzFrk() {
        return this.fristBnzFrk;
    }
    
    public void setFristBnzFrk(BigDecimal fristBnzFrk) {
        this.fristBnzFrk = fristBnzFrk;
    }

    
    @Column(name="SECOND_BNZ_START_QUN", precision=12, scale=3)
    public BigDecimal getSecondBnzStartQun() {
        return this.secondBnzStartQun;
    }
    
    public void setSecondBnzStartQun(BigDecimal secondBnzStartQun) {
        this.secondBnzStartQun = secondBnzStartQun;
    }

    
    @Column(name="SECOND_BNZ_START_NUM", precision=12, scale=3)
    public BigDecimal getSecondBnzStartNum() {
        return this.secondBnzStartNum;
    }
    
    public void setSecondBnzStartNum(BigDecimal secondBnzStartNum) {
        this.secondBnzStartNum = secondBnzStartNum;
    }

    
    @Column(name="SECOND_BNZ_QUN", precision=12, scale=3)
    public BigDecimal getSecondBnzQun() {
        return this.secondBnzQun;
    }
    
    public void setSecondBnzQun(BigDecimal secondBnzQun) {
        this.secondBnzQun = secondBnzQun;
    }

    
    @Column(name="SECOND_BNZ_NUM", precision=12, scale=3)
    public BigDecimal getSecondBnzNum() {
        return this.secondBnzNum;
    }
    
    public void setSecondBnzNum(BigDecimal secondBnzNum) {
        this.secondBnzNum = secondBnzNum;
    }

    
    @Column(name="SECOND_BNZ_SIGN", precision=1, scale=0)
    public Boolean getSecondBnzSign() {
        return this.secondBnzSign;
    }
    
    public void setSecondBnzSign(Boolean secondBnzSign) {
        this.secondBnzSign = secondBnzSign;
    }

    
    @Column(name="SECOND_BNZ_FRK", precision=12, scale=3)
    public BigDecimal getSecondBnzFrk() {
        return this.secondBnzFrk;
    }
    
    public void setSecondBnzFrk(BigDecimal secondBnzFrk) {
        this.secondBnzFrk = secondBnzFrk;
    }

    
    @Column(name="FRIST_SOL_START_QUN", precision=12, scale=3)
    public BigDecimal getFristSolStartQun() {
        return this.fristSolStartQun;
    }
    
    public void setFristSolStartQun(BigDecimal fristSolStartQun) {
        this.fristSolStartQun = fristSolStartQun;
    }

    
    @Column(name="FRIST_SOL_START_NUM", precision=12, scale=3)
    public BigDecimal getFristSolStartNum() {
        return this.fristSolStartNum;
    }
    
    public void setFristSolStartNum(BigDecimal fristSolStartNum) {
        this.fristSolStartNum = fristSolStartNum;
    }

    
    @Column(name="FRIST_SOL_QUN", precision=12, scale=3)
    public BigDecimal getFristSolQun() {
        return this.fristSolQun;
    }
    
    public void setFristSolQun(BigDecimal fristSolQun) {
        this.fristSolQun = fristSolQun;
    }

    
    @Column(name="FRIST_SOL_NUM", precision=12, scale=3)
    public BigDecimal getFristSolNum() {
        return this.fristSolNum;
    }
    
    public void setFristSolNum(BigDecimal fristSolNum) {
        this.fristSolNum = fristSolNum;
    }

    
    @Column(name="FRIST_SOL_SIGN", precision=1, scale=0)
    public Boolean getFristSolSign() {
        return this.fristSolSign;
    }
    
    public void setFristSolSign(Boolean fristSolSign) {
        this.fristSolSign = fristSolSign;
    }

    
    @Column(name="FRIST_SOL_FRK", precision=12, scale=3)
    public BigDecimal getFristSolFrk() {
        return this.fristSolFrk;
    }
    
    public void setFristSolFrk(BigDecimal fristSolFrk) {
        this.fristSolFrk = fristSolFrk;
    }

    
    @Column(name="EZN_SEQ_BAL", precision=10, scale=0)
    public Long getEznSeqBal() {
        return this.eznSeqBal;
    }
    
    public void setEznSeqBal(Long eznSeqBal) {
        this.eznSeqBal = eznSeqBal;
    }

    
    @Column(name="CHK_LOCK_SHIFT", precision=1, scale=0)
    public Boolean getChkLockShift() {
        return this.chkLockShift;
    }
    
    public void setChkLockShift(Boolean chkLockShift) {
        this.chkLockShift = chkLockShift;
    }

    
    @Column(name="CHK_LOCK_DAY", precision=1, scale=0)
    public Boolean getChkLockDay() {
        return this.chkLockDay;
    }
    
    public void setChkLockDay(Boolean chkLockDay) {
        this.chkLockDay = chkLockDay;
    }

    
    @Column(name="SECOND_SOL_START_NUM", precision=12, scale=3)
    public BigDecimal getSecondSolStartNum() {
        return this.secondSolStartNum;
    }
    
    public void setSecondSolStartNum(BigDecimal secondSolStartNum) {
        this.secondSolStartNum = secondSolStartNum;
    }

    
    @Column(name="SECOND_SOL_NUM", precision=12, scale=3)
    public BigDecimal getSecondSolNum() {
        return this.secondSolNum;
    }
    
    public void setSecondSolNum(BigDecimal secondSolNum) {
        this.secondSolNum = secondSolNum;
    }




}


