package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcleIssueDocumentMainDtl generated by hbm2java
 */
@Entity
@Table(name="VCLE_ISSUE_DOCUMENT_MAIN_DTL"
    ,schema="CODEATOR"
)
public class VcleIssueDocumentMainDtl  implements java.io.Serializable {


     private VcleIssueDocumentMainDtlId id;
     private VcleIssueDocumentMain vcleIssueDocumentMain;
     private PerEmploymentMaster perEmploymentMaster;
     private BigDecimal editorUserId;

    public VcleIssueDocumentMainDtl() {
    }

	
    public VcleIssueDocumentMainDtl(VcleIssueDocumentMainDtlId id, VcleIssueDocumentMain vcleIssueDocumentMain, PerEmploymentMaster perEmploymentMaster) {
        this.id = id;
        this.vcleIssueDocumentMain = vcleIssueDocumentMain;
        this.perEmploymentMaster = perEmploymentMaster;
    }
    public VcleIssueDocumentMainDtl(VcleIssueDocumentMainDtlId id, VcleIssueDocumentMain vcleIssueDocumentMain, PerEmploymentMaster perEmploymentMaster, BigDecimal editorUserId) {
       this.id = id;
       this.vcleIssueDocumentMain = vcleIssueDocumentMain;
       this.perEmploymentMaster = perEmploymentMaster;
       this.editorUserId = editorUserId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vcleDeptType", column=@Column(name="VCLE_DEPT_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="userType", column=@Column(name="USER_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ) } )
    public VcleIssueDocumentMainDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleIssueDocumentMainDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VCLE_DEPT_TYPE", nullable=false, insertable=false, updatable=false)
    public VcleIssueDocumentMain getVcleIssueDocumentMain() {
        return this.vcleIssueDocumentMain;
    }
    
    public void setVcleIssueDocumentMain(VcleIssueDocumentMain vcleIssueDocumentMain) {
        this.vcleIssueDocumentMain = vcleIssueDocumentMain;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }

    
    @Column(name="EDITOR_USER_ID", precision=22, scale=0)
    public BigDecimal getEditorUserId() {
        return this.editorUserId;
    }
    
    public void setEditorUserId(BigDecimal editorUserId) {
        this.editorUserId = editorUserId;
    }




}


