package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcleVehicleReceive generated by hbm2java
 */
@Entity
@Table(name="VCLE_VEHICLE_RECEIVE"
    ,schema="CODEATOR"
)
public class VcleVehicleReceive  implements java.io.Serializable {


     private VcleVehicleReceiveId id;
     private VcleVehicleMaster vcleVehicleMaster;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private Date receiveDate;
     private Date returnDate;
     private String returnReason;
     private String rmrk;
     private Boolean receiveTimeType;
     private Byte receiveHh;
     private Byte receiveMi;
     private Boolean returnTimeType;
     private Byte returnHh;
     private Byte returnMi;

    public VcleVehicleReceive() {
    }

	
    public VcleVehicleReceive(VcleVehicleReceiveId id, VcleVehicleMaster vcleVehicleMaster, VcleEmployeeMaster vcleEmployeeMaster, Date receiveDate) {
        this.id = id;
        this.vcleVehicleMaster = vcleVehicleMaster;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
        this.receiveDate = receiveDate;
    }
    public VcleVehicleReceive(VcleVehicleReceiveId id, VcleVehicleMaster vcleVehicleMaster, VcleEmployeeMaster vcleEmployeeMaster, Date receiveDate, Date returnDate, String returnReason, String rmrk, Boolean receiveTimeType, Byte receiveHh, Byte receiveMi, Boolean returnTimeType, Byte returnHh, Byte returnMi) {
       this.id = id;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.receiveDate = receiveDate;
       this.returnDate = returnDate;
       this.returnReason = returnReason;
       this.rmrk = rmrk;
       this.receiveTimeType = receiveTimeType;
       this.receiveHh = receiveHh;
       this.receiveMi = receiveMi;
       this.returnTimeType = returnTimeType;
       this.returnHh = returnHh;
       this.returnMi = returnMi;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehicleSp", column=@Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="receiveSerial", column=@Column(name="RECEIVE_SERIAL", nullable=false, precision=6, scale=0) ) } )
    public VcleVehicleReceiveId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleReceiveId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VEHICLE_SP", nullable=false, insertable=false, updatable=false)
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECEIVE_DATE", nullable=false, length=7)
    public Date getReceiveDate() {
        return this.receiveDate;
    }
    
    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RETURN_DATE", length=7)
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    
    @Column(name="RETURN_REASON", length=60)
    public String getReturnReason() {
        return this.returnReason;
    }
    
    public void setReturnReason(String returnReason) {
        this.returnReason = returnReason;
    }

    
    @Column(name="RMRK", length=400)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="RECEIVE_TIME_TYPE", precision=1, scale=0)
    public Boolean getReceiveTimeType() {
        return this.receiveTimeType;
    }
    
    public void setReceiveTimeType(Boolean receiveTimeType) {
        this.receiveTimeType = receiveTimeType;
    }

    
    @Column(name="RECEIVE_HH", precision=2, scale=0)
    public Byte getReceiveHh() {
        return this.receiveHh;
    }
    
    public void setReceiveHh(Byte receiveHh) {
        this.receiveHh = receiveHh;
    }

    
    @Column(name="RECEIVE_MI", precision=2, scale=0)
    public Byte getReceiveMi() {
        return this.receiveMi;
    }
    
    public void setReceiveMi(Byte receiveMi) {
        this.receiveMi = receiveMi;
    }

    
    @Column(name="RETURN_TIME_TYPE", precision=1, scale=0)
    public Boolean getReturnTimeType() {
        return this.returnTimeType;
    }
    
    public void setReturnTimeType(Boolean returnTimeType) {
        this.returnTimeType = returnTimeType;
    }

    
    @Column(name="RETURN_HH", precision=2, scale=0)
    public Byte getReturnHh() {
        return this.returnHh;
    }
    
    public void setReturnHh(Byte returnHh) {
        this.returnHh = returnHh;
    }

    
    @Column(name="RETURN_MI", precision=2, scale=0)
    public Byte getReturnMi() {
        return this.returnMi;
    }
    
    public void setReturnMi(Byte returnMi) {
        this.returnMi = returnMi;
    }




}


