package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleOilType generated by hbm2java
 */
@Entity
@Table(name="VCLE_OIL_TYPE"
    ,schema="CODEATOR"
)
public class VcleOilType  implements java.io.Serializable {


     private byte oilType;
     private String oilName;
     private Set<VcleOilIssue> vcleOilIssues = new HashSet<VcleOilIssue>(0);
     private Set<VclePriceOil> vclePriceOils = new HashSet<VclePriceOil>(0);

    public VcleOilType() {
    }

	
    public VcleOilType(byte oilType, String oilName) {
        this.oilType = oilType;
        this.oilName = oilName;
    }
    public VcleOilType(byte oilType, String oilName, Set<VcleOilIssue> vcleOilIssues, Set<VclePriceOil> vclePriceOils) {
       this.oilType = oilType;
       this.oilName = oilName;
       this.vcleOilIssues = vcleOilIssues;
       this.vclePriceOils = vclePriceOils;
    }
   
     @Id 

    
    @Column(name="OIL_TYPE", unique=true, nullable=false, precision=2, scale=0)
    public byte getOilType() {
        return this.oilType;
    }
    
    public void setOilType(byte oilType) {
        this.oilType = oilType;
    }

    
    @Column(name="OIL_NAME", nullable=false, length=100)
    public String getOilName() {
        return this.oilName;
    }
    
    public void setOilName(String oilName) {
        this.oilName = oilName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleOilType")
    public Set<VcleOilIssue> getVcleOilIssues() {
        return this.vcleOilIssues;
    }
    
    public void setVcleOilIssues(Set<VcleOilIssue> vcleOilIssues) {
        this.vcleOilIssues = vcleOilIssues;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleOilType")
    public Set<VclePriceOil> getVclePriceOils() {
        return this.vclePriceOils;
    }
    
    public void setVclePriceOils(Set<VclePriceOil> vclePriceOils) {
        this.vclePriceOils = vclePriceOils;
    }




}


