package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcleSuspendType generated by hbm2java
 */
@Entity
@Table(name="VCLE_SUSPEND_TYPE"
    ,schema="CODEATOR"
)
public class VcleSuspendType  implements java.io.Serializable {


     private int suspendCode;
     private String suspendNane;
     private Set<VcleMaintanceRepairDtl> vcleMaintanceRepairDtls = new HashSet<VcleMaintanceRepairDtl>(0);
     private Set<VcleVehicleInstructionDtl> vcleVehicleInstructionDtls = new HashSet<VcleVehicleInstructionDtl>(0);

    public VcleSuspendType() {
    }

	
    public VcleSuspendType(int suspendCode, String suspendNane) {
        this.suspendCode = suspendCode;
        this.suspendNane = suspendNane;
    }
    public VcleSuspendType(int suspendCode, String suspendNane, Set<VcleMaintanceRepairDtl> vcleMaintanceRepairDtls, Set<VcleVehicleInstructionDtl> vcleVehicleInstructionDtls) {
       this.suspendCode = suspendCode;
       this.suspendNane = suspendNane;
       this.vcleMaintanceRepairDtls = vcleMaintanceRepairDtls;
       this.vcleVehicleInstructionDtls = vcleVehicleInstructionDtls;
    }
   
     @Id 

    
    @Column(name="SUSPEND_CODE", unique=true, nullable=false, precision=6, scale=0)
    public int getSuspendCode() {
        return this.suspendCode;
    }
    
    public void setSuspendCode(int suspendCode) {
        this.suspendCode = suspendCode;
    }

    
    @Column(name="SUSPEND_NANE", nullable=false, length=150)
    public String getSuspendNane() {
        return this.suspendNane;
    }
    
    public void setSuspendNane(String suspendNane) {
        this.suspendNane = suspendNane;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleSuspendType")
    public Set<VcleMaintanceRepairDtl> getVcleMaintanceRepairDtls() {
        return this.vcleMaintanceRepairDtls;
    }
    
    public void setVcleMaintanceRepairDtls(Set<VcleMaintanceRepairDtl> vcleMaintanceRepairDtls) {
        this.vcleMaintanceRepairDtls = vcleMaintanceRepairDtls;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="vcleSuspendType")
    public Set<VcleVehicleInstructionDtl> getVcleVehicleInstructionDtls() {
        return this.vcleVehicleInstructionDtls;
    }
    
    public void setVcleVehicleInstructionDtls(Set<VcleVehicleInstructionDtl> vcleVehicleInstructionDtls) {
        this.vcleVehicleInstructionDtls = vcleVehicleInstructionDtls;
    }




}


