package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VcleVehicleReceiveId generated by hbm2java
 */
@Embeddable
public class VcleVehicleReceiveId  implements java.io.Serializable {


     private int vehicleSp;
     private long employeeId;
     private int receiveSerial;

    public VcleVehicleReceiveId() {
    }

    public VcleVehicleReceiveId(int vehicleSp, long employeeId, int receiveSerial) {
       this.vehicleSp = vehicleSp;
       this.employeeId = employeeId;
       this.receiveSerial = receiveSerial;
    }
   


    @Column(name="VEHICLE_SP", nullable=false, precision=6, scale=0)
    public int getVehicleSp() {
        return this.vehicleSp;
    }
    
    public void setVehicleSp(int vehicleSp) {
        this.vehicleSp = vehicleSp;
    }


    @Column(name="EMPLOYEE_ID", nullable=false, precision=10, scale=0)
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }


    @Column(name="RECEIVE_SERIAL", nullable=false, precision=6, scale=0)
    public int getReceiveSerial() {
        return this.receiveSerial;
    }
    
    public void setReceiveSerial(int receiveSerial) {
        this.receiveSerial = receiveSerial;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleVehicleReceiveId) ) return false;
		 VcleVehicleReceiveId castOther = ( VcleVehicleReceiveId ) other; 
         
		 return (this.getVehicleSp()==castOther.getVehicleSp())
 && (this.getEmployeeId()==castOther.getEmployeeId())
 && (this.getReceiveSerial()==castOther.getReceiveSerial());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVehicleSp();
         result = 37 * result + (int) this.getEmployeeId();
         result = 37 * result + this.getReceiveSerial();
         return result;
   }   


}


