package com.codeator.www._1_2_DB_entities;
// Generated Sep 1, 2020 9:49:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VcleVehicleTypeUserId generated by hbm2java
 */
@Embeddable
public class VcleVehicleTypeUserId  implements java.io.Serializable {


     private String vcleType;
     private BigDecimal userId;

    public VcleVehicleTypeUserId() {
    }

    public VcleVehicleTypeUserId(String vcleType, BigDecimal userId) {
       this.vcleType = vcleType;
       this.userId = userId;
    }
   


    @Column(name="VCLE_TYPE", nullable=false, length=2)
    public String getVcleType() {
        return this.vcleType;
    }
    
    public void setVcleType(String vcleType) {
        this.vcleType = vcleType;
    }


    @Column(name="USER_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleVehicleTypeUserId) ) return false;
		 VcleVehicleTypeUserId castOther = ( VcleVehicleTypeUserId ) other; 
         
		 return ( (this.getVcleType()==castOther.getVcleType()) || ( this.getVcleType()!=null && castOther.getVcleType()!=null && this.getVcleType().equals(castOther.getVcleType()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVcleType() == null ? 0 : this.getVcleType().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         return result;
   }   


}


