package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InvoDeptItemJoinDescDtl generated by hbm2java
 */
public class InvoDeptItemJoinDescDtl  implements java.io.Serializable {


     private long itemSeq;
     private InvoDeptItemJoin invoDeptItemJoin;
     private String AItemDesc;
     private String EItemDesc;
     private String itemBarcode;
     private Set invoInvoiceMasterItems = new HashSet(0);

    public InvoDeptItemJoinDescDtl() {
    }

	
    public InvoDeptItemJoinDescDtl(long itemSeq, InvoDeptItemJoin invoDeptItemJoin) {
        this.itemSeq = itemSeq;
        this.invoDeptItemJoin = invoDeptItemJoin;
    }
    public InvoDeptItemJoinDescDtl(long itemSeq, InvoDeptItemJoin invoDeptItemJoin, String AItemDesc, String EItemDesc, String itemBarcode, Set invoInvoiceMasterItems) {
       this.itemSeq = itemSeq;
       this.invoDeptItemJoin = invoDeptItemJoin;
       this.AItemDesc = AItemDesc;
       this.EItemDesc = EItemDesc;
       this.itemBarcode = itemBarcode;
       this.invoInvoiceMasterItems = invoInvoiceMasterItems;
    }
   
    public long getItemSeq() {
        return this.itemSeq;
    }
    
    public void setItemSeq(long itemSeq) {
        this.itemSeq = itemSeq;
    }
    public InvoDeptItemJoin getInvoDeptItemJoin() {
        return this.invoDeptItemJoin;
    }
    
    public void setInvoDeptItemJoin(InvoDeptItemJoin invoDeptItemJoin) {
        this.invoDeptItemJoin = invoDeptItemJoin;
    }
    public String getAItemDesc() {
        return this.AItemDesc;
    }
    
    public void setAItemDesc(String AItemDesc) {
        this.AItemDesc = AItemDesc;
    }
    public String getEItemDesc() {
        return this.EItemDesc;
    }
    
    public void setEItemDesc(String EItemDesc) {
        this.EItemDesc = EItemDesc;
    }
    public String getItemBarcode() {
        return this.itemBarcode;
    }
    
    public void setItemBarcode(String itemBarcode) {
        this.itemBarcode = itemBarcode;
    }
    public Set getInvoInvoiceMasterItems() {
        return this.invoInvoiceMasterItems;
    }
    
    public void setInvoInvoiceMasterItems(Set invoInvoiceMasterItems) {
        this.invoInvoiceMasterItems = invoInvoiceMasterItems;
    }




}


