package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * InvoInvoiceMasterId generated by hbm2java
 */
public class InvoInvoiceMasterId  implements java.io.Serializable {


     private int sectionNoOld;
     private long depNoOld;
     private long invoSp;

    public InvoInvoiceMasterId() {
    }

    public InvoInvoiceMasterId(int sectionNoOld, long depNoOld, long invoSp) {
       this.sectionNoOld = sectionNoOld;
       this.depNoOld = depNoOld;
       this.invoSp = invoSp;
    }
   
    public int getSectionNoOld() {
        return this.sectionNoOld;
    }
    
    public void setSectionNoOld(int sectionNoOld) {
        this.sectionNoOld = sectionNoOld;
    }
    public long getDepNoOld() {
        return this.depNoOld;
    }
    
    public void setDepNoOld(long depNoOld) {
        this.depNoOld = depNoOld;
    }
    public long getInvoSp() {
        return this.invoSp;
    }
    
    public void setInvoSp(long invoSp) {
        this.invoSp = invoSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvoInvoiceMasterId) ) return false;
		 InvoInvoiceMasterId castOther = ( InvoInvoiceMasterId ) other; 
         
		 return (this.getSectionNoOld()==castOther.getSectionNoOld())
 && (this.getDepNoOld()==castOther.getDepNoOld())
 && (this.getInvoSp()==castOther.getInvoSp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSectionNoOld();
         result = 37 * result + (int) this.getDepNoOld();
         result = 37 * result + (int) this.getInvoSp();
         return result;
   }   


}


