package com.codeator.www._6_1_Json_entities;
// Generated Sep 12, 2021 9:58:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InvoAccUnitsCode generated by hbm2java
 */

public class InvoAccUnitsCode  implements java.io.Serializable {


     private String accUnitCode;
     private String accUnitName;
     private Set<InvoAccUintDept> invoAccUintDepts = new HashSet<InvoAccUintDept>(0);

    public InvoAccUnitsCode() {
    }

	
    public InvoAccUnitsCode(String accUnitCode) {
        this.accUnitCode = accUnitCode;
    }
    public InvoAccUnitsCode(String accUnitCode, String accUnitName, Set<InvoAccUintDept> invoAccUintDepts) {
       this.accUnitCode = accUnitCode;
       this.accUnitName = accUnitName;
       this.invoAccUintDepts = invoAccUintDepts;
    }

    public String getAccUnitCode() {
        return accUnitCode;
    }

    public void setAccUnitCode(String accUnitCode) {
        this.accUnitCode = accUnitCode;
    }

    public String getAccUnitName() {
        return accUnitName;
    }

    public void setAccUnitName(String accUnitName) {
        this.accUnitName = accUnitName;
    }

    public Set<InvoAccUintDept> getInvoAccUintDepts() {
        return invoAccUintDepts;
    }

    public void setInvoAccUintDepts(Set<InvoAccUintDept> invoAccUintDepts) {
        this.invoAccUintDepts = invoAccUintDepts;
    }
   



}


