package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * InvoInvoiceMasterItemId generated by hbm2java
 */
public class InvoInvoiceMasterItemId  implements java.io.Serializable {


     private long invoSp;
     private long depNoOld;
     private int sectionNoOld;
     private int invoSpItem;

    public InvoInvoiceMasterItemId() {
    }

    public InvoInvoiceMasterItemId(long invoSp, long depNoOld, int sectionNoOld, int invoSpItem) {
       this.invoSp = invoSp;
       this.depNoOld = depNoOld;
       this.sectionNoOld = sectionNoOld;
       this.invoSpItem = invoSpItem;
    }
   
    public long getInvoSp() {
        return this.invoSp;
    }
    
    public void setInvoSp(long invoSp) {
        this.invoSp = invoSp;
    }
    public long getDepNoOld() {
        return this.depNoOld;
    }
    
    public void setDepNoOld(long depNoOld) {
        this.depNoOld = depNoOld;
    }
    public int getSectionNoOld() {
        return this.sectionNoOld;
    }
    
    public void setSectionNoOld(int sectionNoOld) {
        this.sectionNoOld = sectionNoOld;
    }
    public int getInvoSpItem() {
        return this.invoSpItem;
    }
    
    public void setInvoSpItem(int invoSpItem) {
        this.invoSpItem = invoSpItem;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvoInvoiceMasterItemId) ) return false;
		 InvoInvoiceMasterItemId castOther = ( InvoInvoiceMasterItemId ) other; 
         
		 return (this.getInvoSp()==castOther.getInvoSp())
 && (this.getDepNoOld()==castOther.getDepNoOld())
 && (this.getSectionNoOld()==castOther.getSectionNoOld())
 && (this.getInvoSpItem()==castOther.getInvoSpItem());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getInvoSp();
         result = 37 * result + (int) this.getDepNoOld();
         result = 37 * result + this.getSectionNoOld();
         result = 37 * result + this.getInvoSpItem();
         return result;
   }   


}


