package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InvoDocumentStatus generated by hbm2java
 */
public class InvoDocumentStatus  implements java.io.Serializable {


     private byte docStatus;
     private String docStatusName;
     private Set invoInvoiceMasters = new HashSet(0);
     private Set invoInvoiceMasterStatuses = new HashSet(0);

    public InvoDocumentStatus() {
    }

	
    public InvoDocumentStatus(byte docStatus) {
        this.docStatus = docStatus;
    }
    public InvoDocumentStatus(byte docStatus, String docStatusName, Set invoInvoiceMasters, Set invoInvoiceMasterStatuses) {
       this.docStatus = docStatus;
       this.docStatusName = docStatusName;
       this.invoInvoiceMasters = invoInvoiceMasters;
       this.invoInvoiceMasterStatuses = invoInvoiceMasterStatuses;
    }
   
    public byte getDocStatus() {
        return this.docStatus;
    }
    
    public void setDocStatus(byte docStatus) {
        this.docStatus = docStatus;
    }
    public String getDocStatusName() {
        return this.docStatusName;
    }
    
    public void setDocStatusName(String docStatusName) {
        this.docStatusName = docStatusName;
    }
    public Set getInvoInvoiceMasters() {
        return this.invoInvoiceMasters;
    }
    
    public void setInvoInvoiceMasters(Set invoInvoiceMasters) {
        this.invoInvoiceMasters = invoInvoiceMasters;
    }
    public Set getInvoInvoiceMasterStatuses() {
        return this.invoInvoiceMasterStatuses;
    }
    
    public void setInvoInvoiceMasterStatuses(Set invoInvoiceMasterStatuses) {
        this.invoInvoiceMasterStatuses = invoInvoiceMasterStatuses;
    }




}


