package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PerCountryCode generated by hbm2java
 */
public class PerCountryCode  implements java.io.Serializable {


     private String countryCode;
     private String ACountryName;
     private String ECountryName;
     private String countryType;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private String countrySymbol;
     private Set purSuppWorks = new HashSet(0);
     private Set invoInvoiceMasters = new HashSet(0);
     private Set perGovernorateCodes = new HashSet(0);

    public PerCountryCode() {
    }

	
    public PerCountryCode(String countryCode, String ACountryName, String countryType, String countrySymbol) {
        this.countryCode = countryCode;
        this.ACountryName = ACountryName;
        this.countryType = countryType;
        this.countrySymbol = countrySymbol;
    }
    public PerCountryCode(String countryCode, String ACountryName, String ECountryName, String countryType, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, String countrySymbol, Set purSuppWorks, Set invoInvoiceMasters, Set perGovernorateCodes) {
       this.countryCode = countryCode;
       this.ACountryName = ACountryName;
       this.ECountryName = ECountryName;
       this.countryType = countryType;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.countrySymbol = countrySymbol;
       this.purSuppWorks = purSuppWorks;
       this.invoInvoiceMasters = invoInvoiceMasters;
       this.perGovernorateCodes = perGovernorateCodes;
    }
   
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getACountryName() {
        return this.ACountryName;
    }
    
    public void setACountryName(String ACountryName) {
        this.ACountryName = ACountryName;
    }
    public String getECountryName() {
        return this.ECountryName;
    }
    
    public void setECountryName(String ECountryName) {
        this.ECountryName = ECountryName;
    }
    public String getCountryType() {
        return this.countryType;
    }
    
    public void setCountryType(String countryType) {
        this.countryType = countryType;
    }
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }
    public String getCountrySymbol() {
        return this.countrySymbol;
    }
    
    public void setCountrySymbol(String countrySymbol) {
        this.countrySymbol = countrySymbol;
    }
    public Set getPurSuppWorks() {
        return this.purSuppWorks;
    }
    
    public void setPurSuppWorks(Set purSuppWorks) {
        this.purSuppWorks = purSuppWorks;
    }
    public Set getInvoInvoiceMasters() {
        return this.invoInvoiceMasters;
    }
    
    public void setInvoInvoiceMasters(Set invoInvoiceMasters) {
        this.invoInvoiceMasters = invoInvoiceMasters;
    }
    public Set getPerGovernorateCodes() {
        return this.perGovernorateCodes;
    }
    
    public void setPerGovernorateCodes(Set perGovernorateCodes) {
        this.perGovernorateCodes = perGovernorateCodes;
    }




}


