package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PerCityCode generated by hbm2java
 */
public class PerCityCode  implements java.io.Serializable {


     private PerCityCodeId id;
     private PerGovernorateCode perGovernorateCode;
     private String ACityName;
     private String ECityName;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private boolean cityType;
     private Set purSuppliers = new HashSet(0);

    public PerCityCode() {
    }

	
    public PerCityCode(PerCityCodeId id, PerGovernorateCode perGovernorateCode, String ACityName, boolean cityType) {
        this.id = id;
        this.perGovernorateCode = perGovernorateCode;
        this.ACityName = ACityName;
        this.cityType = cityType;
    }
    public PerCityCode(PerCityCodeId id, PerGovernorateCode perGovernorateCode, String ACityName, String ECityName, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, boolean cityType, Set purSuppliers) {
       this.id = id;
       this.perGovernorateCode = perGovernorateCode;
       this.ACityName = ACityName;
       this.ECityName = ECityName;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.cityType = cityType;
       this.purSuppliers = purSuppliers;
    }
   
    public PerCityCodeId getId() {
        return this.id;
    }
    
    public void setId(PerCityCodeId id) {
        this.id = id;
    }
    public PerGovernorateCode getPerGovernorateCode() {
        return this.perGovernorateCode;
    }
    
    public void setPerGovernorateCode(PerGovernorateCode perGovernorateCode) {
        this.perGovernorateCode = perGovernorateCode;
    }
    public String getACityName() {
        return this.ACityName;
    }
    
    public void setACityName(String ACityName) {
        this.ACityName = ACityName;
    }
    public String getECityName() {
        return this.ECityName;
    }
    
    public void setECityName(String ECityName) {
        this.ECityName = ECityName;
    }
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }
    public boolean isCityType() {
        return this.cityType;
    }
    
    public void setCityType(boolean cityType) {
        this.cityType = cityType;
    }
    public Set getPurSuppliers() {
        return this.purSuppliers;
    }
    
    public void setPurSuppliers(Set purSuppliers) {
        this.purSuppliers = purSuppliers;
    }




}


