package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * PurActivity generated by hbm2java
 */
public class PurActivity  implements java.io.Serializable {


     private short activityCode;
     private String activityName;
     private String activityNatureCode;

    public PurActivity() {
    }

	
    public PurActivity(short activityCode, String activityName) {
        this.activityCode = activityCode;
        this.activityName = activityName;
    }
    public PurActivity(short activityCode, String activityName, String activityNatureCode) {
       this.activityCode = activityCode;
       this.activityName = activityName;
       this.activityNatureCode = activityNatureCode;
    }
   
    public short getActivityCode() {
        return this.activityCode;
    }
    
    public void setActivityCode(short activityCode) {
        this.activityCode = activityCode;
    }
    public String getActivityName() {
        return this.activityName;
    }
    
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }
    public String getActivityNatureCode() {
        return this.activityNatureCode;
    }
    
    public void setActivityNatureCode(String activityNatureCode) {
        this.activityNatureCode = activityNatureCode;
    }




}


