package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * PurContractMasterFileId generated by hbm2java
 */
public class PurContractMasterFileId  implements java.io.Serializable {


     private long contractSp;
     private int fileSp;

    public PurContractMasterFileId() {
    }

    public PurContractMasterFileId(long contractSp, int fileSp) {
       this.contractSp = contractSp;
       this.fileSp = fileSp;
    }
   
    public long getContractSp() {
        return this.contractSp;
    }
    
    public void setContractSp(long contractSp) {
        this.contractSp = contractSp;
    }
    public int getFileSp() {
        return this.fileSp;
    }
    
    public void setFileSp(int fileSp) {
        this.fileSp = fileSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PurContractMasterFileId) ) return false;
		 PurContractMasterFileId castOther = ( PurContractMasterFileId ) other; 
         
		 return (this.getContractSp()==castOther.getContractSp())
 && (this.getFileSp()==castOther.getFileSp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getContractSp();
         result = 37 * result + this.getFileSp();
         return result;
   }   


}


