package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * PurSupplierActivity generated by hbm2java
 */
public class PurSupplierActivity  implements java.io.Serializable {


     private PurSupplierActivityId id;
     private PurSupplier purSupplier;

    public PurSupplierActivity() {
    }

    public PurSupplierActivity(PurSupplierActivityId id, PurSupplier purSupplier) {
       this.id = id;
       this.purSupplier = purSupplier;
    }
   
    public PurSupplierActivityId getId() {
        return this.id;
    }
    
    public void setId(PurSupplierActivityId id) {
        this.id = id;
    }
    public PurSupplier getPurSupplier() {
        return this.purSupplier;
    }
    
    public void setPurSupplier(PurSupplier purSupplier) {
        this.purSupplier = purSupplier;
    }




}


