package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PurSupplier generated by hbm2java
 */
public class PurSupplier  implements java.io.Serializable {


     private long suppCode;
     private PerCityCode perCityCode;
     private PurSupplierTypeCode purSupplierTypeCode;
     private String locationCode;
     private String suppName;
     private boolean suppStatus;
     private boolean suppStateType;
     private String taxOfficeCode;
     private String suppNickname;
     private String manager;
     private String address;
     private String telegraphAddress;
     private String mailboxNo;
     private String EMail;
     private String identNo;
     private String identSide;
     private String recordType;
     private String recordNo;
     private Date recordDate;
     private String tel1;
     private String tel2;
     private String tel3;
     private String fax;
     private String mobile;
     private String notes;
     private Date suppTypeDate;
     private String taxFileNo;
     private Date taxDate;
     private String taxCardNo;
     private String salesTaxNo;
     private String accountUnitCode;
     private String suppNo;
     private String companySite;
     private String managerCardId;
     private String managerJob;
     private String managerTelephone;
     private String managerFax;
     private String managerMobile;
     private String managerEmail;
     private String instractionNo;
     private String companyId;
     private Date instractionDate;
     private Date taxEnddate;
     private Date salesTaxDate;
     private String commercialOfficeCode;
     private String buildingNum;
     private String dealerType;
     private Set invoInvoiceMasters = new HashSet(0);
     private Set purSuppWorks = new HashSet(0);
     private Set purSupplierActivities = new HashSet(0);

    public PurSupplier() {
    }

	
    public PurSupplier(long suppCode, PurSupplierTypeCode purSupplierTypeCode, String locationCode, String suppName, boolean suppStatus, boolean suppStateType, String accountUnitCode, String suppNo, String dealerType) {
        this.suppCode = suppCode;
        this.purSupplierTypeCode = purSupplierTypeCode;
        this.locationCode = locationCode;
        this.suppName = suppName;
        this.suppStatus = suppStatus;
        this.suppStateType = suppStateType;
        this.accountUnitCode = accountUnitCode;
        this.suppNo = suppNo;
        this.dealerType = dealerType;
    }
    public PurSupplier(long suppCode, PerCityCode perCityCode, PurSupplierTypeCode purSupplierTypeCode, String locationCode, String suppName, boolean suppStatus, boolean suppStateType, String taxOfficeCode, String suppNickname, String manager, String address, String telegraphAddress, String mailboxNo, String EMail, String identNo, String identSide, String recordType, String recordNo, Date recordDate, String tel1, String tel2, String tel3, String fax, String mobile, String notes, Date suppTypeDate, String taxFileNo, Date taxDate, String taxCardNo, String salesTaxNo, String accountUnitCode, String suppNo, String companySite, String managerCardId, String managerJob, String managerTelephone, String managerFax, String managerMobile, String managerEmail, String instractionNo, String companyId, Date instractionDate, Date taxEnddate, Date salesTaxDate, String commercialOfficeCode, String buildingNum, String dealerType, Set invoInvoiceMasters, Set purSuppWorks, Set purSupplierActivities) {
       this.suppCode = suppCode;
       this.perCityCode = perCityCode;
       this.purSupplierTypeCode = purSupplierTypeCode;
       this.locationCode = locationCode;
       this.suppName = suppName;
       this.suppStatus = suppStatus;
       this.suppStateType = suppStateType;
       this.taxOfficeCode = taxOfficeCode;
       this.suppNickname = suppNickname;
       this.manager = manager;
       this.address = address;
       this.telegraphAddress = telegraphAddress;
       this.mailboxNo = mailboxNo;
       this.EMail = EMail;
       this.identNo = identNo;
       this.identSide = identSide;
       this.recordType = recordType;
       this.recordNo = recordNo;
       this.recordDate = recordDate;
       this.tel1 = tel1;
       this.tel2 = tel2;
       this.tel3 = tel3;
       this.fax = fax;
       this.mobile = mobile;
       this.notes = notes;
       this.suppTypeDate = suppTypeDate;
       this.taxFileNo = taxFileNo;
       this.taxDate = taxDate;
       this.taxCardNo = taxCardNo;
       this.salesTaxNo = salesTaxNo;
       this.accountUnitCode = accountUnitCode;
       this.suppNo = suppNo;
       this.companySite = companySite;
       this.managerCardId = managerCardId;
       this.managerJob = managerJob;
       this.managerTelephone = managerTelephone;
       this.managerFax = managerFax;
       this.managerMobile = managerMobile;
       this.managerEmail = managerEmail;
       this.instractionNo = instractionNo;
       this.companyId = companyId;
       this.instractionDate = instractionDate;
       this.taxEnddate = taxEnddate;
       this.salesTaxDate = salesTaxDate;
       this.commercialOfficeCode = commercialOfficeCode;
       this.buildingNum = buildingNum;
       this.dealerType = dealerType;
       this.invoInvoiceMasters = invoInvoiceMasters;
       this.purSuppWorks = purSuppWorks;
       this.purSupplierActivities = purSupplierActivities;
    }
   
    public long getSuppCode() {
        return this.suppCode;
    }
    
    public void setSuppCode(long suppCode) {
        this.suppCode = suppCode;
    }
    public PerCityCode getPerCityCode() {
        return this.perCityCode;
    }
    
    public void setPerCityCode(PerCityCode perCityCode) {
        this.perCityCode = perCityCode;
    }
    public PurSupplierTypeCode getPurSupplierTypeCode() {
        return this.purSupplierTypeCode;
    }
    
    public void setPurSupplierTypeCode(PurSupplierTypeCode purSupplierTypeCode) {
        this.purSupplierTypeCode = purSupplierTypeCode;
    }
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }
    public String getSuppName() {
        return this.suppName;
    }
    
    public void setSuppName(String suppName) {
        this.suppName = suppName;
    }
    public boolean isSuppStatus() {
        return this.suppStatus;
    }
    
    public void setSuppStatus(boolean suppStatus) {
        this.suppStatus = suppStatus;
    }
    public boolean isSuppStateType() {
        return this.suppStateType;
    }
    
    public void setSuppStateType(boolean suppStateType) {
        this.suppStateType = suppStateType;
    }
    public String getTaxOfficeCode() {
        return this.taxOfficeCode;
    }
    
    public void setTaxOfficeCode(String taxOfficeCode) {
        this.taxOfficeCode = taxOfficeCode;
    }
    public String getSuppNickname() {
        return this.suppNickname;
    }
    
    public void setSuppNickname(String suppNickname) {
        this.suppNickname = suppNickname;
    }
    public String getManager() {
        return this.manager;
    }
    
    public void setManager(String manager) {
        this.manager = manager;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTelegraphAddress() {
        return this.telegraphAddress;
    }
    
    public void setTelegraphAddress(String telegraphAddress) {
        this.telegraphAddress = telegraphAddress;
    }
    public String getMailboxNo() {
        return this.mailboxNo;
    }
    
    public void setMailboxNo(String mailboxNo) {
        this.mailboxNo = mailboxNo;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getIdentNo() {
        return this.identNo;
    }
    
    public void setIdentNo(String identNo) {
        this.identNo = identNo;
    }
    public String getIdentSide() {
        return this.identSide;
    }
    
    public void setIdentSide(String identSide) {
        this.identSide = identSide;
    }
    public String getRecordType() {
        return this.recordType;
    }
    
    public void setRecordType(String recordType) {
        this.recordType = recordType;
    }
    public String getRecordNo() {
        return this.recordNo;
    }
    
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo;
    }
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }
    public String getTel1() {
        return this.tel1;
    }
    
    public void setTel1(String tel1) {
        this.tel1 = tel1;
    }
    public String getTel2() {
        return this.tel2;
    }
    
    public void setTel2(String tel2) {
        this.tel2 = tel2;
    }
    public String getTel3() {
        return this.tel3;
    }
    
    public void setTel3(String tel3) {
        this.tel3 = tel3;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Date getSuppTypeDate() {
        return this.suppTypeDate;
    }
    
    public void setSuppTypeDate(Date suppTypeDate) {
        this.suppTypeDate = suppTypeDate;
    }
    public String getTaxFileNo() {
        return this.taxFileNo;
    }
    
    public void setTaxFileNo(String taxFileNo) {
        this.taxFileNo = taxFileNo;
    }
    public Date getTaxDate() {
        return this.taxDate;
    }
    
    public void setTaxDate(Date taxDate) {
        this.taxDate = taxDate;
    }
    public String getTaxCardNo() {
        return this.taxCardNo;
    }
    
    public void setTaxCardNo(String taxCardNo) {
        this.taxCardNo = taxCardNo;
    }
    public String getSalesTaxNo() {
        return this.salesTaxNo;
    }
    
    public void setSalesTaxNo(String salesTaxNo) {
        this.salesTaxNo = salesTaxNo;
    }
    public String getAccountUnitCode() {
        return this.accountUnitCode;
    }
    
    public void setAccountUnitCode(String accountUnitCode) {
        this.accountUnitCode = accountUnitCode;
    }
    public String getSuppNo() {
        return this.suppNo;
    }
    
    public void setSuppNo(String suppNo) {
        this.suppNo = suppNo;
    }
    public String getCompanySite() {
        return this.companySite;
    }
    
    public void setCompanySite(String companySite) {
        this.companySite = companySite;
    }
    public String getManagerCardId() {
        return this.managerCardId;
    }
    
    public void setManagerCardId(String managerCardId) {
        this.managerCardId = managerCardId;
    }
    public String getManagerJob() {
        return this.managerJob;
    }
    
    public void setManagerJob(String managerJob) {
        this.managerJob = managerJob;
    }
    public String getManagerTelephone() {
        return this.managerTelephone;
    }
    
    public void setManagerTelephone(String managerTelephone) {
        this.managerTelephone = managerTelephone;
    }
    public String getManagerFax() {
        return this.managerFax;
    }
    
    public void setManagerFax(String managerFax) {
        this.managerFax = managerFax;
    }
    public String getManagerMobile() {
        return this.managerMobile;
    }
    
    public void setManagerMobile(String managerMobile) {
        this.managerMobile = managerMobile;
    }
    public String getManagerEmail() {
        return this.managerEmail;
    }
    
    public void setManagerEmail(String managerEmail) {
        this.managerEmail = managerEmail;
    }
    public String getInstractionNo() {
        return this.instractionNo;
    }
    
    public void setInstractionNo(String instractionNo) {
        this.instractionNo = instractionNo;
    }
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    public Date getInstractionDate() {
        return this.instractionDate;
    }
    
    public void setInstractionDate(Date instractionDate) {
        this.instractionDate = instractionDate;
    }
    public Date getTaxEnddate() {
        return this.taxEnddate;
    }
    
    public void setTaxEnddate(Date taxEnddate) {
        this.taxEnddate = taxEnddate;
    }
    public Date getSalesTaxDate() {
        return this.salesTaxDate;
    }
    
    public void setSalesTaxDate(Date salesTaxDate) {
        this.salesTaxDate = salesTaxDate;
    }
    public String getCommercialOfficeCode() {
        return this.commercialOfficeCode;
    }
    
    public void setCommercialOfficeCode(String commercialOfficeCode) {
        this.commercialOfficeCode = commercialOfficeCode;
    }
    public String getBuildingNum() {
        return this.buildingNum;
    }
    
    public void setBuildingNum(String buildingNum) {
        this.buildingNum = buildingNum;
    }
    public String getDealerType() {
        return this.dealerType;
    }
    
    public void setDealerType(String dealerType) {
        this.dealerType = dealerType;
    }
    public Set getInvoInvoiceMasters() {
        return this.invoInvoiceMasters;
    }
    
    public void setInvoInvoiceMasters(Set invoInvoiceMasters) {
        this.invoInvoiceMasters = invoInvoiceMasters;
    }
    public Set getPurSuppWorks() {
        return this.purSuppWorks;
    }
    
    public void setPurSuppWorks(Set purSuppWorks) {
        this.purSuppWorks = purSuppWorks;
    }
    public Set getPurSupplierActivities() {
        return this.purSupplierActivities;
    }
    
    public void setPurSupplierActivities(Set purSupplierActivities) {
        this.purSupplierActivities = purSupplierActivities;
    }




}


