package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PurSupplierTypeCode generated by hbm2java
 */
public class PurSupplierTypeCode  implements java.io.Serializable {


     private byte suppType;
     private String suppTypeName;
     private boolean activityFlag;
     private boolean classFlag;
     private Set purSuppliers = new HashSet(0);

    public PurSupplierTypeCode() {
    }

	
    public PurSupplierTypeCode(byte suppType, String suppTypeName, boolean activityFlag, boolean classFlag) {
        this.suppType = suppType;
        this.suppTypeName = suppTypeName;
        this.activityFlag = activityFlag;
        this.classFlag = classFlag;
    }
    public PurSupplierTypeCode(byte suppType, String suppTypeName, boolean activityFlag, boolean classFlag, Set purSuppliers) {
       this.suppType = suppType;
       this.suppTypeName = suppTypeName;
       this.activityFlag = activityFlag;
       this.classFlag = classFlag;
       this.purSuppliers = purSuppliers;
    }
   
    public byte getSuppType() {
        return this.suppType;
    }
    
    public void setSuppType(byte suppType) {
        this.suppType = suppType;
    }
    public String getSuppTypeName() {
        return this.suppTypeName;
    }
    
    public void setSuppTypeName(String suppTypeName) {
        this.suppTypeName = suppTypeName;
    }
    public boolean isActivityFlag() {
        return this.activityFlag;
    }
    
    public void setActivityFlag(boolean activityFlag) {
        this.activityFlag = activityFlag;
    }
    public boolean isClassFlag() {
        return this.classFlag;
    }
    
    public void setClassFlag(boolean classFlag) {
        this.classFlag = classFlag;
    }
    public Set getPurSuppliers() {
        return this.purSuppliers;
    }
    
    public void setPurSuppliers(Set purSuppliers) {
        this.purSuppliers = purSuppliers;
    }




}


