package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * StoResponsibilityDeptDtl generated by hbm2java
 */
public class StoResponsibilityDeptDtl  implements java.io.Serializable {


     private StoResponsibilityDeptDtlId id;
     private StoResponsibilityDept stoResponsibilityDept;
     private String itemDigital;
     private String serialNoInc;
     private String itemRespDesc;
     private Boolean respTypeActDtl;
     private String rmrk;

    public StoResponsibilityDeptDtl() {
    }

	
    public StoResponsibilityDeptDtl(StoResponsibilityDeptDtlId id, StoResponsibilityDept stoResponsibilityDept, String itemRespDesc) {
        this.id = id;
        this.stoResponsibilityDept = stoResponsibilityDept;
        this.itemRespDesc = itemRespDesc;
    }
    public StoResponsibilityDeptDtl(StoResponsibilityDeptDtlId id, StoResponsibilityDept stoResponsibilityDept, String itemDigital, String serialNoInc, String itemRespDesc, Boolean respTypeActDtl, String rmrk) {
       this.id = id;
       this.stoResponsibilityDept = stoResponsibilityDept;
       this.itemDigital = itemDigital;
       this.serialNoInc = serialNoInc;
       this.itemRespDesc = itemRespDesc;
       this.respTypeActDtl = respTypeActDtl;
       this.rmrk = rmrk;
    }
   
    public StoResponsibilityDeptDtlId getId() {
        return this.id;
    }
    
    public void setId(StoResponsibilityDeptDtlId id) {
        this.id = id;
    }
    public StoResponsibilityDept getStoResponsibilityDept() {
        return this.stoResponsibilityDept;
    }
    
    public void setStoResponsibilityDept(StoResponsibilityDept stoResponsibilityDept) {
        this.stoResponsibilityDept = stoResponsibilityDept;
    }
    public String getItemDigital() {
        return this.itemDigital;
    }
    
    public void setItemDigital(String itemDigital) {
        this.itemDigital = itemDigital;
    }
    public String getSerialNoInc() {
        return this.serialNoInc;
    }
    
    public void setSerialNoInc(String serialNoInc) {
        this.serialNoInc = serialNoInc;
    }
    public String getItemRespDesc() {
        return this.itemRespDesc;
    }
    
    public void setItemRespDesc(String itemRespDesc) {
        this.itemRespDesc = itemRespDesc;
    }
    public Boolean getRespTypeActDtl() {
        return this.respTypeActDtl;
    }
    
    public void setRespTypeActDtl(Boolean respTypeActDtl) {
        this.respTypeActDtl = respTypeActDtl;
    }
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


