package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VcleVehicleInvoiceLiq generated by hbm2java
 */
public class VcleVehicleInvoiceLiq  implements java.io.Serializable {


     private VcleVehicleInvoiceLiqId id;
     private VcleIssueDocumentLiq vcleIssueDocumentLiq;
     private VcleCostType vcleCostType;
     private VcleVehicleMaster vcleVehicleMaster;
     private Integer invoiceN0;
     private Long userEmployeeNo;
     private String ghaName;
     private BigDecimal invoiceValue;
     private Date issueDocDate;
     private Long issueDocSerial;
     private String boardNumber;
     private Boolean fuelType;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;

    public VcleVehicleInvoiceLiq() {
    }

	
    public VcleVehicleInvoiceLiq(VcleVehicleInvoiceLiqId id, VcleCostType vcleCostType) {
        this.id = id;
        this.vcleCostType = vcleCostType;
    }
    public VcleVehicleInvoiceLiq(VcleVehicleInvoiceLiqId id, VcleIssueDocumentLiq vcleIssueDocumentLiq, VcleCostType vcleCostType, VcleVehicleMaster vcleVehicleMaster, Integer invoiceN0, Long userEmployeeNo, String ghaName, BigDecimal invoiceValue, Date issueDocDate, Long issueDocSerial, String boardNumber, Boolean fuelType, Integer boardDigital, String boardAlfa1, String boardAlfa2, String boardAlfa3) {
       this.id = id;
       this.vcleIssueDocumentLiq = vcleIssueDocumentLiq;
       this.vcleCostType = vcleCostType;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.invoiceN0 = invoiceN0;
       this.userEmployeeNo = userEmployeeNo;
       this.ghaName = ghaName;
       this.invoiceValue = invoiceValue;
       this.issueDocDate = issueDocDate;
       this.issueDocSerial = issueDocSerial;
       this.boardNumber = boardNumber;
       this.fuelType = fuelType;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
    }
   
    public VcleVehicleInvoiceLiqId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleInvoiceLiqId id) {
        this.id = id;
    }
    public VcleIssueDocumentLiq getVcleIssueDocumentLiq() {
        return this.vcleIssueDocumentLiq;
    }
    
    public void setVcleIssueDocumentLiq(VcleIssueDocumentLiq vcleIssueDocumentLiq) {
        this.vcleIssueDocumentLiq = vcleIssueDocumentLiq;
    }
    public VcleCostType getVcleCostType() {
        return this.vcleCostType;
    }
    
    public void setVcleCostType(VcleCostType vcleCostType) {
        this.vcleCostType = vcleCostType;
    }
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }
    public Integer getInvoiceN0() {
        return this.invoiceN0;
    }
    
    public void setInvoiceN0(Integer invoiceN0) {
        this.invoiceN0 = invoiceN0;
    }
    public Long getUserEmployeeNo() {
        return this.userEmployeeNo;
    }
    
    public void setUserEmployeeNo(Long userEmployeeNo) {
        this.userEmployeeNo = userEmployeeNo;
    }
    public String getGhaName() {
        return this.ghaName;
    }
    
    public void setGhaName(String ghaName) {
        this.ghaName = ghaName;
    }
    public BigDecimal getInvoiceValue() {
        return this.invoiceValue;
    }
    
    public void setInvoiceValue(BigDecimal invoiceValue) {
        this.invoiceValue = invoiceValue;
    }
    public Date getIssueDocDate() {
        return this.issueDocDate;
    }
    
    public void setIssueDocDate(Date issueDocDate) {
        this.issueDocDate = issueDocDate;
    }
    public Long getIssueDocSerial() {
        return this.issueDocSerial;
    }
    
    public void setIssueDocSerial(Long issueDocSerial) {
        this.issueDocSerial = issueDocSerial;
    }
    public String getBoardNumber() {
        return this.boardNumber;
    }
    
    public void setBoardNumber(String boardNumber) {
        this.boardNumber = boardNumber;
    }
    public Boolean getFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(Boolean fuelType) {
        this.fuelType = fuelType;
    }
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }




}


