package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VcleMaintanceRepair generated by hbm2java
 */
public class VcleMaintanceRepair  implements java.io.Serializable {


     private VcleMaintanceRepairId id;
     private VcleMainCostCode vcleMainCostCode;
     private String rmrk;
     private Date exitDate;
     private Set vcleMaintanceRepairDtls = new HashSet(0);

    public VcleMaintanceRepair() {
    }

	
    public VcleMaintanceRepair(VcleMaintanceRepairId id, VcleMainCostCode vcleMainCostCode) {
        this.id = id;
        this.vcleMainCostCode = vcleMainCostCode;
    }
    public VcleMaintanceRepair(VcleMaintanceRepairId id, VcleMainCostCode vcleMainCostCode, String rmrk, Date exitDate, Set vcleMaintanceRepairDtls) {
       this.id = id;
       this.vcleMainCostCode = vcleMainCostCode;
       this.rmrk = rmrk;
       this.exitDate = exitDate;
       this.vcleMaintanceRepairDtls = vcleMaintanceRepairDtls;
    }
   
    public VcleMaintanceRepairId getId() {
        return this.id;
    }
    
    public void setId(VcleMaintanceRepairId id) {
        this.id = id;
    }
    public VcleMainCostCode getVcleMainCostCode() {
        return this.vcleMainCostCode;
    }
    
    public void setVcleMainCostCode(VcleMainCostCode vcleMainCostCode) {
        this.vcleMainCostCode = vcleMainCostCode;
    }
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }
    public Date getExitDate() {
        return this.exitDate;
    }
    
    public void setExitDate(Date exitDate) {
        this.exitDate = exitDate;
    }
    public Set getVcleMaintanceRepairDtls() {
        return this.vcleMaintanceRepairDtls;
    }
    
    public void setVcleMaintanceRepairDtls(Set vcleMaintanceRepairDtls) {
        this.vcleMaintanceRepairDtls = vcleMaintanceRepairDtls;
    }




}


