package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VcleFuelIssueLiquid generated by hbm2java
 */
public class VcleFuelIssueLiquid  implements java.io.Serializable {


     private VcleFuelIssueLiquidId id;
     private VcleFuelOpenDay vcleFuelOpenDay;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private VcleDeptNumber vcleDeptNumber;
     private VcleShiftType vcleShiftType;
     private VcleVehicleMaster vcleVehicleMaster;
     private VcleVehicleType vcleVehicleType;
     private VcleWorkshopeCode vcleWorkshopeCode;
     private Boolean fuelType;
     private BigDecimal issueQun;
     private BigDecimal fuelRate;
     private Long eznSeqIss;
     private Integer boardDigital;
     private String boardAlfa1;
     private String boardAlfa2;
     private String boardAlfa3;
     private Boolean chkLock;
     private String rmrk;
     private BigDecimal tankNum;
     private Integer boardNumberOld;
     private Long countNumber;
     private Boolean chkBarrel;
     private Byte chkOwner;
     private Date fiscalDate;
     private BigDecimal issueSal;
     private BigDecimal issueVal;
     private Date provideExecDate;

    public VcleFuelIssueLiquid() {
    }

	
    public VcleFuelIssueLiquid(VcleFuelIssueLiquidId id, VcleFuelOpenDay vcleFuelOpenDay) {
        this.id = id;
        this.vcleFuelOpenDay = vcleFuelOpenDay;
    }
    public VcleFuelIssueLiquid(VcleFuelIssueLiquidId id, VcleFuelOpenDay vcleFuelOpenDay, VcleEmployeeMaster vcleEmployeeMaster, VcleDeptNumber vcleDeptNumber, VcleShiftType vcleShiftType, VcleVehicleMaster vcleVehicleMaster, VcleVehicleType vcleVehicleType, VcleWorkshopeCode vcleWorkshopeCode, Boolean fuelType, BigDecimal issueQun, BigDecimal fuelRate, Long eznSeqIss, Integer boardDigital, String boardAlfa1, String boardAlfa2, String boardAlfa3, Boolean chkLock, String rmrk, BigDecimal tankNum, Integer boardNumberOld, Long countNumber, Boolean chkBarrel, Byte chkOwner, Date fiscalDate, BigDecimal issueSal, BigDecimal issueVal, Date provideExecDate) {
       this.id = id;
       this.vcleFuelOpenDay = vcleFuelOpenDay;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.vcleDeptNumber = vcleDeptNumber;
       this.vcleShiftType = vcleShiftType;
       this.vcleVehicleMaster = vcleVehicleMaster;
       this.vcleVehicleType = vcleVehicleType;
       this.vcleWorkshopeCode = vcleWorkshopeCode;
       this.fuelType = fuelType;
       this.issueQun = issueQun;
       this.fuelRate = fuelRate;
       this.eznSeqIss = eznSeqIss;
       this.boardDigital = boardDigital;
       this.boardAlfa1 = boardAlfa1;
       this.boardAlfa2 = boardAlfa2;
       this.boardAlfa3 = boardAlfa3;
       this.chkLock = chkLock;
       this.rmrk = rmrk;
       this.tankNum = tankNum;
       this.boardNumberOld = boardNumberOld;
       this.countNumber = countNumber;
       this.chkBarrel = chkBarrel;
       this.chkOwner = chkOwner;
       this.fiscalDate = fiscalDate;
       this.issueSal = issueSal;
       this.issueVal = issueVal;
       this.provideExecDate = provideExecDate;
    }
   
    public VcleFuelIssueLiquidId getId() {
        return this.id;
    }
    
    public void setId(VcleFuelIssueLiquidId id) {
        this.id = id;
    }
    public VcleFuelOpenDay getVcleFuelOpenDay() {
        return this.vcleFuelOpenDay;
    }
    
    public void setVcleFuelOpenDay(VcleFuelOpenDay vcleFuelOpenDay) {
        this.vcleFuelOpenDay = vcleFuelOpenDay;
    }
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleDeptNumber getVcleDeptNumber() {
        return this.vcleDeptNumber;
    }
    
    public void setVcleDeptNumber(VcleDeptNumber vcleDeptNumber) {
        this.vcleDeptNumber = vcleDeptNumber;
    }
    public VcleShiftType getVcleShiftType() {
        return this.vcleShiftType;
    }
    
    public void setVcleShiftType(VcleShiftType vcleShiftType) {
        this.vcleShiftType = vcleShiftType;
    }
    public VcleVehicleMaster getVcleVehicleMaster() {
        return this.vcleVehicleMaster;
    }
    
    public void setVcleVehicleMaster(VcleVehicleMaster vcleVehicleMaster) {
        this.vcleVehicleMaster = vcleVehicleMaster;
    }
    public VcleVehicleType getVcleVehicleType() {
        return this.vcleVehicleType;
    }
    
    public void setVcleVehicleType(VcleVehicleType vcleVehicleType) {
        this.vcleVehicleType = vcleVehicleType;
    }
    public VcleWorkshopeCode getVcleWorkshopeCode() {
        return this.vcleWorkshopeCode;
    }
    
    public void setVcleWorkshopeCode(VcleWorkshopeCode vcleWorkshopeCode) {
        this.vcleWorkshopeCode = vcleWorkshopeCode;
    }
    public Boolean getFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(Boolean fuelType) {
        this.fuelType = fuelType;
    }
    public BigDecimal getIssueQun() {
        return this.issueQun;
    }
    
    public void setIssueQun(BigDecimal issueQun) {
        this.issueQun = issueQun;
    }
    public BigDecimal getFuelRate() {
        return this.fuelRate;
    }
    
    public void setFuelRate(BigDecimal fuelRate) {
        this.fuelRate = fuelRate;
    }
    public Long getEznSeqIss() {
        return this.eznSeqIss;
    }
    
    public void setEznSeqIss(Long eznSeqIss) {
        this.eznSeqIss = eznSeqIss;
    }
    public Integer getBoardDigital() {
        return this.boardDigital;
    }
    
    public void setBoardDigital(Integer boardDigital) {
        this.boardDigital = boardDigital;
    }
    public String getBoardAlfa1() {
        return this.boardAlfa1;
    }
    
    public void setBoardAlfa1(String boardAlfa1) {
        this.boardAlfa1 = boardAlfa1;
    }
    public String getBoardAlfa2() {
        return this.boardAlfa2;
    }
    
    public void setBoardAlfa2(String boardAlfa2) {
        this.boardAlfa2 = boardAlfa2;
    }
    public String getBoardAlfa3() {
        return this.boardAlfa3;
    }
    
    public void setBoardAlfa3(String boardAlfa3) {
        this.boardAlfa3 = boardAlfa3;
    }
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }
    public BigDecimal getTankNum() {
        return this.tankNum;
    }
    
    public void setTankNum(BigDecimal tankNum) {
        this.tankNum = tankNum;
    }
    public Integer getBoardNumberOld() {
        return this.boardNumberOld;
    }
    
    public void setBoardNumberOld(Integer boardNumberOld) {
        this.boardNumberOld = boardNumberOld;
    }
    public Long getCountNumber() {
        return this.countNumber;
    }
    
    public void setCountNumber(Long countNumber) {
        this.countNumber = countNumber;
    }
    public Boolean getChkBarrel() {
        return this.chkBarrel;
    }
    
    public void setChkBarrel(Boolean chkBarrel) {
        this.chkBarrel = chkBarrel;
    }
    public Byte getChkOwner() {
        return this.chkOwner;
    }
    
    public void setChkOwner(Byte chkOwner) {
        this.chkOwner = chkOwner;
    }
    public Date getFiscalDate() {
        return this.fiscalDate;
    }
    
    public void setFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }
    public BigDecimal getIssueSal() {
        return this.issueSal;
    }
    
    public void setIssueSal(BigDecimal issueSal) {
        this.issueSal = issueSal;
    }
    public BigDecimal getIssueVal() {
        return this.issueVal;
    }
    
    public void setIssueVal(BigDecimal issueVal) {
        this.issueVal = issueVal;
    }
    public Date getProvideExecDate() {
        return this.provideExecDate;
    }
    
    public void setProvideExecDate(Date provideExecDate) {
        this.provideExecDate = provideExecDate;
    }




}


