package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VcleTrafficCode generated by hbm2java
 */
public class VcleTrafficCode  implements java.io.Serializable {


     private short trafficCode;
     private PerGovernorateCode perGovernorateCode;
     private String trafficName;
     private Set vcleVehicleLicenses = new HashSet(0);

    public VcleTrafficCode() {
    }

	
    public VcleTrafficCode(short trafficCode, String trafficName) {
        this.trafficCode = trafficCode;
        this.trafficName = trafficName;
    }
    public VcleTrafficCode(short trafficCode, PerGovernorateCode perGovernorateCode, String trafficName, Set vcleVehicleLicenses) {
       this.trafficCode = trafficCode;
       this.perGovernorateCode = perGovernorateCode;
       this.trafficName = trafficName;
       this.vcleVehicleLicenses = vcleVehicleLicenses;
    }
   
    public short getTrafficCode() {
        return this.trafficCode;
    }
    
    public void setTrafficCode(short trafficCode) {
        this.trafficCode = trafficCode;
    }
    public PerGovernorateCode getPerGovernorateCode() {
        return this.perGovernorateCode;
    }
    
    public void setPerGovernorateCode(PerGovernorateCode perGovernorateCode) {
        this.perGovernorateCode = perGovernorateCode;
    }
    public String getTrafficName() {
        return this.trafficName;
    }
    
    public void setTrafficName(String trafficName) {
        this.trafficName = trafficName;
    }
    public Set getVcleVehicleLicenses() {
        return this.vcleVehicleLicenses;
    }
    
    public void setVcleVehicleLicenses(Set vcleVehicleLicenses) {
        this.vcleVehicleLicenses = vcleVehicleLicenses;
    }




}


