package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VcleWorkshopeCode generated by hbm2java
 */
public class VcleWorkshopeCode  implements java.io.Serializable {


     private byte workshopeCode;
     private String workshopeName;
     private String workshopeDesc;
     private Boolean fuelType;
     private Set vcleVehicleNotifyTransDtls = new HashSet(0);
     private Set vcleWorkshopeResponses = new HashSet(0);
     private Set vcleVehicleResponsibleEmps = new HashSet(0);
     private Set vcleOilIssues = new HashSet(0);
     private Set vcleFuelIssueLiquids = new HashSet(0);

    public VcleWorkshopeCode() {
    }

	
    public VcleWorkshopeCode(byte workshopeCode, String workshopeName) {
        this.workshopeCode = workshopeCode;
        this.workshopeName = workshopeName;
    }
    public VcleWorkshopeCode(byte workshopeCode, String workshopeName, String workshopeDesc, Boolean fuelType, Set vcleVehicleNotifyTransDtls, Set vcleWorkshopeResponses, Set vcleVehicleResponsibleEmps, Set vcleOilIssues, Set vcleFuelIssueLiquids) {
       this.workshopeCode = workshopeCode;
       this.workshopeName = workshopeName;
       this.workshopeDesc = workshopeDesc;
       this.fuelType = fuelType;
       this.vcleVehicleNotifyTransDtls = vcleVehicleNotifyTransDtls;
       this.vcleWorkshopeResponses = vcleWorkshopeResponses;
       this.vcleVehicleResponsibleEmps = vcleVehicleResponsibleEmps;
       this.vcleOilIssues = vcleOilIssues;
       this.vcleFuelIssueLiquids = vcleFuelIssueLiquids;
    }
   
    public byte getWorkshopeCode() {
        return this.workshopeCode;
    }
    
    public void setWorkshopeCode(byte workshopeCode) {
        this.workshopeCode = workshopeCode;
    }
    public String getWorkshopeName() {
        return this.workshopeName;
    }
    
    public void setWorkshopeName(String workshopeName) {
        this.workshopeName = workshopeName;
    }
    public String getWorkshopeDesc() {
        return this.workshopeDesc;
    }
    
    public void setWorkshopeDesc(String workshopeDesc) {
        this.workshopeDesc = workshopeDesc;
    }
    public Boolean getFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(Boolean fuelType) {
        this.fuelType = fuelType;
    }
    public Set getVcleVehicleNotifyTransDtls() {
        return this.vcleVehicleNotifyTransDtls;
    }
    
    public void setVcleVehicleNotifyTransDtls(Set vcleVehicleNotifyTransDtls) {
        this.vcleVehicleNotifyTransDtls = vcleVehicleNotifyTransDtls;
    }
    public Set getVcleWorkshopeResponses() {
        return this.vcleWorkshopeResponses;
    }
    
    public void setVcleWorkshopeResponses(Set vcleWorkshopeResponses) {
        this.vcleWorkshopeResponses = vcleWorkshopeResponses;
    }
    public Set getVcleVehicleResponsibleEmps() {
        return this.vcleVehicleResponsibleEmps;
    }
    
    public void setVcleVehicleResponsibleEmps(Set vcleVehicleResponsibleEmps) {
        this.vcleVehicleResponsibleEmps = vcleVehicleResponsibleEmps;
    }
    public Set getVcleOilIssues() {
        return this.vcleOilIssues;
    }
    
    public void setVcleOilIssues(Set vcleOilIssues) {
        this.vcleOilIssues = vcleOilIssues;
    }
    public Set getVcleFuelIssueLiquids() {
        return this.vcleFuelIssueLiquids;
    }
    
    public void setVcleFuelIssueLiquids(Set vcleFuelIssueLiquids) {
        this.vcleFuelIssueLiquids = vcleFuelIssueLiquids;
    }




}


