package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VcleShiftType generated by hbm2java
 */
public class VcleShiftType  implements java.io.Serializable {


     private boolean shiftType;
     private Byte shiftFromHh;
     private Byte shiftFromMi;
     private Byte shiftToHh;
     private Byte shiftToMi;
     private Boolean shiftFromType;
     private Boolean shiftToType;
     private Set vcleFuelIssueLiquids = new HashSet(0);
     private Set vcleEmployeeMasters = new HashSet(0);
     private Set vcleFuelProvideLiquids = new HashSet(0);
     private Set vcleRecordMovementsForShiftTypeComming = new HashSet(0);
     private Set vcleRecordMovementsForShiftType = new HashSet(0);
     private Set vcleTankBalances = new HashSet(0);
     private Set vcleFuelBalanceLiquids = new HashSet(0);

    public VcleShiftType() {
    }

	
    public VcleShiftType(boolean shiftType) {
        this.shiftType = shiftType;
    }
    public VcleShiftType(boolean shiftType, Byte shiftFromHh, Byte shiftFromMi, Byte shiftToHh, Byte shiftToMi, Boolean shiftFromType, Boolean shiftToType, Set vcleFuelIssueLiquids, Set vcleEmployeeMasters, Set vcleFuelProvideLiquids, Set vcleRecordMovementsForShiftTypeComming, Set vcleRecordMovementsForShiftType, Set vcleTankBalances, Set vcleFuelBalanceLiquids) {
       this.shiftType = shiftType;
       this.shiftFromHh = shiftFromHh;
       this.shiftFromMi = shiftFromMi;
       this.shiftToHh = shiftToHh;
       this.shiftToMi = shiftToMi;
       this.shiftFromType = shiftFromType;
       this.shiftToType = shiftToType;
       this.vcleFuelIssueLiquids = vcleFuelIssueLiquids;
       this.vcleEmployeeMasters = vcleEmployeeMasters;
       this.vcleFuelProvideLiquids = vcleFuelProvideLiquids;
       this.vcleRecordMovementsForShiftTypeComming = vcleRecordMovementsForShiftTypeComming;
       this.vcleRecordMovementsForShiftType = vcleRecordMovementsForShiftType;
       this.vcleTankBalances = vcleTankBalances;
       this.vcleFuelBalanceLiquids = vcleFuelBalanceLiquids;
    }
   
    public boolean isShiftType() {
        return this.shiftType;
    }
    
    public void setShiftType(boolean shiftType) {
        this.shiftType = shiftType;
    }
    public Byte getShiftFromHh() {
        return this.shiftFromHh;
    }
    
    public void setShiftFromHh(Byte shiftFromHh) {
        this.shiftFromHh = shiftFromHh;
    }
    public Byte getShiftFromMi() {
        return this.shiftFromMi;
    }
    
    public void setShiftFromMi(Byte shiftFromMi) {
        this.shiftFromMi = shiftFromMi;
    }
    public Byte getShiftToHh() {
        return this.shiftToHh;
    }
    
    public void setShiftToHh(Byte shiftToHh) {
        this.shiftToHh = shiftToHh;
    }
    public Byte getShiftToMi() {
        return this.shiftToMi;
    }
    
    public void setShiftToMi(Byte shiftToMi) {
        this.shiftToMi = shiftToMi;
    }
    public Boolean getShiftFromType() {
        return this.shiftFromType;
    }
    
    public void setShiftFromType(Boolean shiftFromType) {
        this.shiftFromType = shiftFromType;
    }
    public Boolean getShiftToType() {
        return this.shiftToType;
    }
    
    public void setShiftToType(Boolean shiftToType) {
        this.shiftToType = shiftToType;
    }
    public Set getVcleFuelIssueLiquids() {
        return this.vcleFuelIssueLiquids;
    }
    
    public void setVcleFuelIssueLiquids(Set vcleFuelIssueLiquids) {
        this.vcleFuelIssueLiquids = vcleFuelIssueLiquids;
    }
    public Set getVcleEmployeeMasters() {
        return this.vcleEmployeeMasters;
    }
    
    public void setVcleEmployeeMasters(Set vcleEmployeeMasters) {
        this.vcleEmployeeMasters = vcleEmployeeMasters;
    }
    public Set getVcleFuelProvideLiquids() {
        return this.vcleFuelProvideLiquids;
    }
    
    public void setVcleFuelProvideLiquids(Set vcleFuelProvideLiquids) {
        this.vcleFuelProvideLiquids = vcleFuelProvideLiquids;
    }
    public Set getVcleRecordMovementsForShiftTypeComming() {
        return this.vcleRecordMovementsForShiftTypeComming;
    }
    
    public void setVcleRecordMovementsForShiftTypeComming(Set vcleRecordMovementsForShiftTypeComming) {
        this.vcleRecordMovementsForShiftTypeComming = vcleRecordMovementsForShiftTypeComming;
    }
    public Set getVcleRecordMovementsForShiftType() {
        return this.vcleRecordMovementsForShiftType;
    }
    
    public void setVcleRecordMovementsForShiftType(Set vcleRecordMovementsForShiftType) {
        this.vcleRecordMovementsForShiftType = vcleRecordMovementsForShiftType;
    }
    public Set getVcleTankBalances() {
        return this.vcleTankBalances;
    }
    
    public void setVcleTankBalances(Set vcleTankBalances) {
        this.vcleTankBalances = vcleTankBalances;
    }
    public Set getVcleFuelBalanceLiquids() {
        return this.vcleFuelBalanceLiquids;
    }
    
    public void setVcleFuelBalanceLiquids(Set vcleFuelBalanceLiquids) {
        this.vcleFuelBalanceLiquids = vcleFuelBalanceLiquids;
    }




}


