package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VcleIssueDocumentMan generated by hbm2java
 */
public class VcleIssueDocumentMan  implements java.io.Serializable {


     private VcleIssueDocumentManId id;
     private AccCurrencyCode accCurrencyCode;
     private PerOrganizationStructure perOrganizationStructure;
     private PerEmploymentMaster perEmploymentMaster;
     private Long issueDocSerial;
     private Date issueDocDate;
     private String issueType;
     private BigDecimal editorUserId;
     private String issueDocStatus;
     private BigDecimal vcDeserveValue;
     private BigDecimal vcCutValue;
     private String vcDeserveNoyes;
     private String vcDeserveName;
     private String accountUnitCode;
     private Short vcDeserveDocCount;
     private String vcIssueDocType;
     private Set vcleVehicleInvoiceMans = new HashSet(0);
     private Set vcleIssueDocumentManTypes = new HashSet(0);

    public VcleIssueDocumentMan() {
    }

	
    public VcleIssueDocumentMan(VcleIssueDocumentManId id) {
        this.id = id;
    }
    public VcleIssueDocumentMan(VcleIssueDocumentManId id, AccCurrencyCode accCurrencyCode, PerOrganizationStructure perOrganizationStructure, PerEmploymentMaster perEmploymentMaster, Long issueDocSerial, Date issueDocDate, String issueType, BigDecimal editorUserId, String issueDocStatus, BigDecimal vcDeserveValue, BigDecimal vcCutValue, String vcDeserveNoyes, String vcDeserveName, String accountUnitCode, Short vcDeserveDocCount, String vcIssueDocType, Set vcleVehicleInvoiceMans, Set vcleIssueDocumentManTypes) {
       this.id = id;
       this.accCurrencyCode = accCurrencyCode;
       this.perOrganizationStructure = perOrganizationStructure;
       this.perEmploymentMaster = perEmploymentMaster;
       this.issueDocSerial = issueDocSerial;
       this.issueDocDate = issueDocDate;
       this.issueType = issueType;
       this.editorUserId = editorUserId;
       this.issueDocStatus = issueDocStatus;
       this.vcDeserveValue = vcDeserveValue;
       this.vcCutValue = vcCutValue;
       this.vcDeserveNoyes = vcDeserveNoyes;
       this.vcDeserveName = vcDeserveName;
       this.accountUnitCode = accountUnitCode;
       this.vcDeserveDocCount = vcDeserveDocCount;
       this.vcIssueDocType = vcIssueDocType;
       this.vcleVehicleInvoiceMans = vcleVehicleInvoiceMans;
       this.vcleIssueDocumentManTypes = vcleIssueDocumentManTypes;
    }
   
    public VcleIssueDocumentManId getId() {
        return this.id;
    }
    
    public void setId(VcleIssueDocumentManId id) {
        this.id = id;
    }
    public AccCurrencyCode getAccCurrencyCode() {
        return this.accCurrencyCode;
    }
    
    public void setAccCurrencyCode(AccCurrencyCode accCurrencyCode) {
        this.accCurrencyCode = accCurrencyCode;
    }
    public PerOrganizationStructure getPerOrganizationStructure() {
        return this.perOrganizationStructure;
    }
    
    public void setPerOrganizationStructure(PerOrganizationStructure perOrganizationStructure) {
        this.perOrganizationStructure = perOrganizationStructure;
    }
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }
    public Long getIssueDocSerial() {
        return this.issueDocSerial;
    }
    
    public void setIssueDocSerial(Long issueDocSerial) {
        this.issueDocSerial = issueDocSerial;
    }
    public Date getIssueDocDate() {
        return this.issueDocDate;
    }
    
    public void setIssueDocDate(Date issueDocDate) {
        this.issueDocDate = issueDocDate;
    }
    public String getIssueType() {
        return this.issueType;
    }
    
    public void setIssueType(String issueType) {
        this.issueType = issueType;
    }
    public BigDecimal getEditorUserId() {
        return this.editorUserId;
    }
    
    public void setEditorUserId(BigDecimal editorUserId) {
        this.editorUserId = editorUserId;
    }
    public String getIssueDocStatus() {
        return this.issueDocStatus;
    }
    
    public void setIssueDocStatus(String issueDocStatus) {
        this.issueDocStatus = issueDocStatus;
    }
    public BigDecimal getVcDeserveValue() {
        return this.vcDeserveValue;
    }
    
    public void setVcDeserveValue(BigDecimal vcDeserveValue) {
        this.vcDeserveValue = vcDeserveValue;
    }
    public BigDecimal getVcCutValue() {
        return this.vcCutValue;
    }
    
    public void setVcCutValue(BigDecimal vcCutValue) {
        this.vcCutValue = vcCutValue;
    }
    public String getVcDeserveNoyes() {
        return this.vcDeserveNoyes;
    }
    
    public void setVcDeserveNoyes(String vcDeserveNoyes) {
        this.vcDeserveNoyes = vcDeserveNoyes;
    }
    public String getVcDeserveName() {
        return this.vcDeserveName;
    }
    
    public void setVcDeserveName(String vcDeserveName) {
        this.vcDeserveName = vcDeserveName;
    }
    public String getAccountUnitCode() {
        return this.accountUnitCode;
    }
    
    public void setAccountUnitCode(String accountUnitCode) {
        this.accountUnitCode = accountUnitCode;
    }
    public Short getVcDeserveDocCount() {
        return this.vcDeserveDocCount;
    }
    
    public void setVcDeserveDocCount(Short vcDeserveDocCount) {
        this.vcDeserveDocCount = vcDeserveDocCount;
    }
    public String getVcIssueDocType() {
        return this.vcIssueDocType;
    }
    
    public void setVcIssueDocType(String vcIssueDocType) {
        this.vcIssueDocType = vcIssueDocType;
    }
    public Set getVcleVehicleInvoiceMans() {
        return this.vcleVehicleInvoiceMans;
    }
    
    public void setVcleVehicleInvoiceMans(Set vcleVehicleInvoiceMans) {
        this.vcleVehicleInvoiceMans = vcleVehicleInvoiceMans;
    }
    public Set getVcleIssueDocumentManTypes() {
        return this.vcleIssueDocumentManTypes;
    }
    
    public void setVcleIssueDocumentManTypes(Set vcleIssueDocumentManTypes) {
        this.vcleIssueDocumentManTypes = vcleIssueDocumentManTypes;
    }




}


