package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VcleFiscalDate generated by hbm2java
 */
public class VcleFiscalDate  implements java.io.Serializable {


     private Date fiscalDate;
     private Boolean flg;
     private Set vcleVehicleIncomes = new HashSet(0);
     private Set vcleRecordMovements = new HashSet(0);
     private Set vcleIssueDocuments = new HashSet(0);

    public VcleFiscalDate() {
    }

	
    public VcleFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }
    public VcleFiscalDate(Date fiscalDate, Boolean flg, Set vcleVehicleIncomes, Set vcleRecordMovements, Set vcleIssueDocuments) {
       this.fiscalDate = fiscalDate;
       this.flg = flg;
       this.vcleVehicleIncomes = vcleVehicleIncomes;
       this.vcleRecordMovements = vcleRecordMovements;
       this.vcleIssueDocuments = vcleIssueDocuments;
    }
   
    public Date getFiscalDate() {
        return this.fiscalDate;
    }
    
    public void setFiscalDate(Date fiscalDate) {
        this.fiscalDate = fiscalDate;
    }
    public Boolean getFlg() {
        return this.flg;
    }
    
    public void setFlg(Boolean flg) {
        this.flg = flg;
    }
    public Set getVcleVehicleIncomes() {
        return this.vcleVehicleIncomes;
    }
    
    public void setVcleVehicleIncomes(Set vcleVehicleIncomes) {
        this.vcleVehicleIncomes = vcleVehicleIncomes;
    }
    public Set getVcleRecordMovements() {
        return this.vcleRecordMovements;
    }
    
    public void setVcleRecordMovements(Set vcleRecordMovements) {
        this.vcleRecordMovements = vcleRecordMovements;
    }
    public Set getVcleIssueDocuments() {
        return this.vcleIssueDocuments;
    }
    
    public void setVcleIssueDocuments(Set vcleIssueDocuments) {
        this.vcleIssueDocuments = vcleIssueDocuments;
    }




}


