package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VcleFuelBookNumber generated by hbm2java
 */
public class VcleFuelBookNumber  implements java.io.Serializable {


     private VcleFuelBookNumberId id;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private Date orderDate;
     private Date priceDate;
     private Date issueDate;
     private boolean litreType;
     private Short litreQty;
     private BigDecimal litrePrice;
     private Integer fromBook;
     private Integer toBook;
     private Date returnDate;
     private Boolean octane;
     private Boolean chkLock;
     private Integer vehicleSpOnly;
     private Integer boardDigitalOnly;
     private String boardAlfa1Only;
     private String boardAlfa2Only;
     private String boardAlfa3Only;
     private BigDecimal litreValAll;
     private Set vcleFuelBookNumberDtls = new HashSet(0);

    public VcleFuelBookNumber() {
    }

	
    public VcleFuelBookNumber(VcleFuelBookNumberId id, boolean litreType) {
        this.id = id;
        this.litreType = litreType;
    }
    public VcleFuelBookNumber(VcleFuelBookNumberId id, VcleEmployeeMaster vcleEmployeeMaster, Date orderDate, Date priceDate, Date issueDate, boolean litreType, Short litreQty, BigDecimal litrePrice, Integer fromBook, Integer toBook, Date returnDate, Boolean octane, Boolean chkLock, Integer vehicleSpOnly, Integer boardDigitalOnly, String boardAlfa1Only, String boardAlfa2Only, String boardAlfa3Only, BigDecimal litreValAll, Set vcleFuelBookNumberDtls) {
       this.id = id;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.orderDate = orderDate;
       this.priceDate = priceDate;
       this.issueDate = issueDate;
       this.litreType = litreType;
       this.litreQty = litreQty;
       this.litrePrice = litrePrice;
       this.fromBook = fromBook;
       this.toBook = toBook;
       this.returnDate = returnDate;
       this.octane = octane;
       this.chkLock = chkLock;
       this.vehicleSpOnly = vehicleSpOnly;
       this.boardDigitalOnly = boardDigitalOnly;
       this.boardAlfa1Only = boardAlfa1Only;
       this.boardAlfa2Only = boardAlfa2Only;
       this.boardAlfa3Only = boardAlfa3Only;
       this.litreValAll = litreValAll;
       this.vcleFuelBookNumberDtls = vcleFuelBookNumberDtls;
    }
   
    public VcleFuelBookNumberId getId() {
        return this.id;
    }
    
    public void setId(VcleFuelBookNumberId id) {
        this.id = id;
    }
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getPriceDate() {
        return this.priceDate;
    }
    
    public void setPriceDate(Date priceDate) {
        this.priceDate = priceDate;
    }
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }
    public boolean isLitreType() {
        return this.litreType;
    }
    
    public void setLitreType(boolean litreType) {
        this.litreType = litreType;
    }
    public Short getLitreQty() {
        return this.litreQty;
    }
    
    public void setLitreQty(Short litreQty) {
        this.litreQty = litreQty;
    }
    public BigDecimal getLitrePrice() {
        return this.litrePrice;
    }
    
    public void setLitrePrice(BigDecimal litrePrice) {
        this.litrePrice = litrePrice;
    }
    public Integer getFromBook() {
        return this.fromBook;
    }
    
    public void setFromBook(Integer fromBook) {
        this.fromBook = fromBook;
    }
    public Integer getToBook() {
        return this.toBook;
    }
    
    public void setToBook(Integer toBook) {
        this.toBook = toBook;
    }
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }
    public Boolean getOctane() {
        return this.octane;
    }
    
    public void setOctane(Boolean octane) {
        this.octane = octane;
    }
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }
    public Integer getVehicleSpOnly() {
        return this.vehicleSpOnly;
    }
    
    public void setVehicleSpOnly(Integer vehicleSpOnly) {
        this.vehicleSpOnly = vehicleSpOnly;
    }
    public Integer getBoardDigitalOnly() {
        return this.boardDigitalOnly;
    }
    
    public void setBoardDigitalOnly(Integer boardDigitalOnly) {
        this.boardDigitalOnly = boardDigitalOnly;
    }
    public String getBoardAlfa1Only() {
        return this.boardAlfa1Only;
    }
    
    public void setBoardAlfa1Only(String boardAlfa1Only) {
        this.boardAlfa1Only = boardAlfa1Only;
    }
    public String getBoardAlfa2Only() {
        return this.boardAlfa2Only;
    }
    
    public void setBoardAlfa2Only(String boardAlfa2Only) {
        this.boardAlfa2Only = boardAlfa2Only;
    }
    public String getBoardAlfa3Only() {
        return this.boardAlfa3Only;
    }
    
    public void setBoardAlfa3Only(String boardAlfa3Only) {
        this.boardAlfa3Only = boardAlfa3Only;
    }
    public BigDecimal getLitreValAll() {
        return this.litreValAll;
    }
    
    public void setLitreValAll(BigDecimal litreValAll) {
        this.litreValAll = litreValAll;
    }
    public Set getVcleFuelBookNumberDtls() {
        return this.vcleFuelBookNumberDtls;
    }
    
    public void setVcleFuelBookNumberDtls(Set vcleFuelBookNumberDtls) {
        this.vcleFuelBookNumberDtls = vcleFuelBookNumberDtls;
    }




}


