package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * VcleWorkTypeTransCarId generated by hbm2java
 */
public class VcleWorkTypeTransCarId  implements java.io.Serializable {


     private byte workType;
     private long employeeId;
     private int vehicleSp;

    public VcleWorkTypeTransCarId() {
    }

    public VcleWorkTypeTransCarId(byte workType, long employeeId, int vehicleSp) {
       this.workType = workType;
       this.employeeId = employeeId;
       this.vehicleSp = vehicleSp;
    }
   
    public byte getWorkType() {
        return this.workType;
    }
    
    public void setWorkType(byte workType) {
        this.workType = workType;
    }
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }
    public int getVehicleSp() {
        return this.vehicleSp;
    }
    
    public void setVehicleSp(int vehicleSp) {
        this.vehicleSp = vehicleSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleWorkTypeTransCarId) ) return false;
		 VcleWorkTypeTransCarId castOther = ( VcleWorkTypeTransCarId ) other; 
         
		 return (this.getWorkType()==castOther.getWorkType())
 && (this.getEmployeeId()==castOther.getEmployeeId())
 && (this.getVehicleSp()==castOther.getVehicleSp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getWorkType();
         result = 37 * result + (int) this.getEmployeeId();
         result = 37 * result + this.getVehicleSp();
         return result;
   }   


}


