package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VcleMaintanceRepairId generated by hbm2java
 */
public class VcleMaintanceRepairId  implements java.io.Serializable {


     private Date notifyDate;
     private Date instructionDate;
     private int vehicleSp;
     private long employeeIdHave;
     private long employeeId;
     private String costCode;
     private Date enterDate;

    public VcleMaintanceRepairId() {
    }

    public VcleMaintanceRepairId(Date notifyDate, Date instructionDate, int vehicleSp, long employeeIdHave, long employeeId, String costCode, Date enterDate) {
       this.notifyDate = notifyDate;
       this.instructionDate = instructionDate;
       this.vehicleSp = vehicleSp;
       this.employeeIdHave = employeeIdHave;
       this.employeeId = employeeId;
       this.costCode = costCode;
       this.enterDate = enterDate;
    }
   
    public Date getNotifyDate() {
        return this.notifyDate;
    }
    
    public void setNotifyDate(Date notifyDate) {
        this.notifyDate = notifyDate;
    }
    public Date getInstructionDate() {
        return this.instructionDate;
    }
    
    public void setInstructionDate(Date instructionDate) {
        this.instructionDate = instructionDate;
    }
    public int getVehicleSp() {
        return this.vehicleSp;
    }
    
    public void setVehicleSp(int vehicleSp) {
        this.vehicleSp = vehicleSp;
    }
    public long getEmployeeIdHave() {
        return this.employeeIdHave;
    }
    
    public void setEmployeeIdHave(long employeeIdHave) {
        this.employeeIdHave = employeeIdHave;
    }
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }
    public String getCostCode() {
        return this.costCode;
    }
    
    public void setCostCode(String costCode) {
        this.costCode = costCode;
    }
    public Date getEnterDate() {
        return this.enterDate;
    }
    
    public void setEnterDate(Date enterDate) {
        this.enterDate = enterDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleMaintanceRepairId) ) return false;
		 VcleMaintanceRepairId castOther = ( VcleMaintanceRepairId ) other; 
         
		 return ( (this.getNotifyDate()==castOther.getNotifyDate()) || ( this.getNotifyDate()!=null && castOther.getNotifyDate()!=null && this.getNotifyDate().equals(castOther.getNotifyDate()) ) )
 && ( (this.getInstructionDate()==castOther.getInstructionDate()) || ( this.getInstructionDate()!=null && castOther.getInstructionDate()!=null && this.getInstructionDate().equals(castOther.getInstructionDate()) ) )
 && (this.getVehicleSp()==castOther.getVehicleSp())
 && (this.getEmployeeIdHave()==castOther.getEmployeeIdHave())
 && (this.getEmployeeId()==castOther.getEmployeeId())
 && ( (this.getCostCode()==castOther.getCostCode()) || ( this.getCostCode()!=null && castOther.getCostCode()!=null && this.getCostCode().equals(castOther.getCostCode()) ) )
 && ( (this.getEnterDate()==castOther.getEnterDate()) || ( this.getEnterDate()!=null && castOther.getEnterDate()!=null && this.getEnterDate().equals(castOther.getEnterDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNotifyDate() == null ? 0 : this.getNotifyDate().hashCode() );
         result = 37 * result + ( getInstructionDate() == null ? 0 : this.getInstructionDate().hashCode() );
         result = 37 * result + this.getVehicleSp();
         result = 37 * result + (int) this.getEmployeeIdHave();
         result = 37 * result + (int) this.getEmployeeId();
         result = 37 * result + ( getCostCode() == null ? 0 : this.getCostCode().hashCode() );
         result = 37 * result + ( getEnterDate() == null ? 0 : this.getEnterDate().hashCode() );
         return result;
   }   


}


