package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VcleVehicleRequireStatus generated by hbm2java
 */
public class VcleVehicleRequireStatus  implements java.io.Serializable {


     private byte requireStatus;
     private String requireStatusNm;
     private Byte respType;
     private String requireStatusColor;
     private String requireStatusFafa;
     private Set vcleVehicleRequires = new HashSet(0);
     private Set vcleVehicleRequireStatusDts = new HashSet(0);

    public VcleVehicleRequireStatus() {
    }

	
    public VcleVehicleRequireStatus(byte requireStatus) {
        this.requireStatus = requireStatus;
    }
    public VcleVehicleRequireStatus(byte requireStatus, String requireStatusNm, Byte respType, String requireStatusColor, String requireStatusFafa, Set vcleVehicleRequires, Set vcleVehicleRequireStatusDts) {
       this.requireStatus = requireStatus;
       this.requireStatusNm = requireStatusNm;
       this.respType = respType;
       this.requireStatusColor = requireStatusColor;
       this.requireStatusFafa = requireStatusFafa;
       this.vcleVehicleRequires = vcleVehicleRequires;
       this.vcleVehicleRequireStatusDts = vcleVehicleRequireStatusDts;
    }
   
    public byte getRequireStatus() {
        return this.requireStatus;
    }
    
    public void setRequireStatus(byte requireStatus) {
        this.requireStatus = requireStatus;
    }
    public String getRequireStatusNm() {
        return this.requireStatusNm;
    }
    
    public void setRequireStatusNm(String requireStatusNm) {
        this.requireStatusNm = requireStatusNm;
    }
    public Byte getRespType() {
        return this.respType;
    }
    
    public void setRespType(Byte respType) {
        this.respType = respType;
    }
    public String getRequireStatusColor() {
        return this.requireStatusColor;
    }
    
    public void setRequireStatusColor(String requireStatusColor) {
        this.requireStatusColor = requireStatusColor;
    }
    public String getRequireStatusFafa() {
        return this.requireStatusFafa;
    }
    
    public void setRequireStatusFafa(String requireStatusFafa) {
        this.requireStatusFafa = requireStatusFafa;
    }
    public Set getVcleVehicleRequires() {
        return this.vcleVehicleRequires;
    }
    
    public void setVcleVehicleRequires(Set vcleVehicleRequires) {
        this.vcleVehicleRequires = vcleVehicleRequires;
    }
    public Set getVcleVehicleRequireStatusDts() {
        return this.vcleVehicleRequireStatusDts;
    }
    
    public void setVcleVehicleRequireStatusDts(Set vcleVehicleRequireStatusDts) {
        this.vcleVehicleRequireStatusDts = vcleVehicleRequireStatusDts;
    }




}


