package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * VcleVehicleResponsibleJoinId generated by hbm2java
 */
public class VcleVehicleResponsibleJoinId  implements java.io.Serializable {


     private int vehicleSp;
     private long employeeId;
     private byte workshopeCode;

    public VcleVehicleResponsibleJoinId() {
    }

    public VcleVehicleResponsibleJoinId(int vehicleSp, long employeeId, byte workshopeCode) {
       this.vehicleSp = vehicleSp;
       this.employeeId = employeeId;
       this.workshopeCode = workshopeCode;
    }
   
    public int getVehicleSp() {
        return this.vehicleSp;
    }
    
    public void setVehicleSp(int vehicleSp) {
        this.vehicleSp = vehicleSp;
    }
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }
    public byte getWorkshopeCode() {
        return this.workshopeCode;
    }
    
    public void setWorkshopeCode(byte workshopeCode) {
        this.workshopeCode = workshopeCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleVehicleResponsibleJoinId) ) return false;
		 VcleVehicleResponsibleJoinId castOther = ( VcleVehicleResponsibleJoinId ) other; 
         
		 return (this.getVehicleSp()==castOther.getVehicleSp())
 && (this.getEmployeeId()==castOther.getEmployeeId())
 && (this.getWorkshopeCode()==castOther.getWorkshopeCode());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVehicleSp();
         result = 37 * result + (int) this.getEmployeeId();
         result = 37 * result + this.getWorkshopeCode();
         return result;
   }   


}


