package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VcleVehicleLicenseId generated by hbm2java
 */
public class VcleVehicleLicenseId  implements java.io.Serializable {


     private int vehicleSp;
     private Date licenseMm;
     private short licenseType;

    public VcleVehicleLicenseId() {
    }

    public VcleVehicleLicenseId(int vehicleSp, Date licenseMm, short licenseType) {
       this.vehicleSp = vehicleSp;
       this.licenseMm = licenseMm;
       this.licenseType = licenseType;
    }
   
    public int getVehicleSp() {
        return this.vehicleSp;
    }
    
    public void setVehicleSp(int vehicleSp) {
        this.vehicleSp = vehicleSp;
    }
    public Date getLicenseMm() {
        return this.licenseMm;
    }
    
    public void setLicenseMm(Date licenseMm) {
        this.licenseMm = licenseMm;
    }
    public short getLicenseType() {
        return this.licenseType;
    }
    
    public void setLicenseType(short licenseType) {
        this.licenseType = licenseType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleVehicleLicenseId) ) return false;
		 VcleVehicleLicenseId castOther = ( VcleVehicleLicenseId ) other; 
         
		 return (this.getVehicleSp()==castOther.getVehicleSp())
 && ( (this.getLicenseMm()==castOther.getLicenseMm()) || ( this.getLicenseMm()!=null && castOther.getLicenseMm()!=null && this.getLicenseMm().equals(castOther.getLicenseMm()) ) )
 && (this.getLicenseType()==castOther.getLicenseType());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVehicleSp();
         result = 37 * result + ( getLicenseMm() == null ? 0 : this.getLicenseMm().hashCode() );
         result = 37 * result + this.getLicenseType();
         return result;
   }   


}


