package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VcleDistributeDateAhramAm generated by hbm2java
 */
public class VcleDistributeDateAhramAm  implements java.io.Serializable {


     private VcleDistributeDateAhramAmId id;
     private VcleDistributeDate vcleDistributeDate;
     private VcleDistributeLocation vcleDistributeLocation;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private Date execMm;
     private BigDecimal val;
     private Boolean chkLock;

    public VcleDistributeDateAhramAm() {
    }

	
    public VcleDistributeDateAhramAm(VcleDistributeDateAhramAmId id, VcleDistributeDate vcleDistributeDate, VcleDistributeLocation vcleDistributeLocation, VcleEmployeeMaster vcleEmployeeMaster) {
        this.id = id;
        this.vcleDistributeDate = vcleDistributeDate;
        this.vcleDistributeLocation = vcleDistributeLocation;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleDistributeDateAhramAm(VcleDistributeDateAhramAmId id, VcleDistributeDate vcleDistributeDate, VcleDistributeLocation vcleDistributeLocation, VcleEmployeeMaster vcleEmployeeMaster, Date execMm, BigDecimal val, Boolean chkLock) {
       this.id = id;
       this.vcleDistributeDate = vcleDistributeDate;
       this.vcleDistributeLocation = vcleDistributeLocation;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.execMm = execMm;
       this.val = val;
       this.chkLock = chkLock;
    }
   
    public VcleDistributeDateAhramAmId getId() {
        return this.id;
    }
    
    public void setId(VcleDistributeDateAhramAmId id) {
        this.id = id;
    }
    public VcleDistributeDate getVcleDistributeDate() {
        return this.vcleDistributeDate;
    }
    
    public void setVcleDistributeDate(VcleDistributeDate vcleDistributeDate) {
        this.vcleDistributeDate = vcleDistributeDate;
    }
    public VcleDistributeLocation getVcleDistributeLocation() {
        return this.vcleDistributeLocation;
    }
    
    public void setVcleDistributeLocation(VcleDistributeLocation vcleDistributeLocation) {
        this.vcleDistributeLocation = vcleDistributeLocation;
    }
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public Date getExecMm() {
        return this.execMm;
    }
    
    public void setExecMm(Date execMm) {
        this.execMm = execMm;
    }
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }




}


