package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VcleIssueDocumentFinType generated by hbm2java
 */
public class VcleIssueDocumentFinType  implements java.io.Serializable {


     private VcleIssueDocumentFinTypeId id;
     private VcleIssueDocumentMainType vcleIssueDocumentMainType;
     private VcleIssueDocumentFin vcleIssueDocumentFin;
     private Byte docCount;
     private Date docDate;
     private Long docNo;
     private String rmrk;

    public VcleIssueDocumentFinType() {
    }

	
    public VcleIssueDocumentFinType(VcleIssueDocumentFinTypeId id, VcleIssueDocumentFin vcleIssueDocumentFin) {
        this.id = id;
        this.vcleIssueDocumentFin = vcleIssueDocumentFin;
    }
    public VcleIssueDocumentFinType(VcleIssueDocumentFinTypeId id, VcleIssueDocumentMainType vcleIssueDocumentMainType, VcleIssueDocumentFin vcleIssueDocumentFin, Byte docCount, Date docDate, Long docNo, String rmrk) {
       this.id = id;
       this.vcleIssueDocumentMainType = vcleIssueDocumentMainType;
       this.vcleIssueDocumentFin = vcleIssueDocumentFin;
       this.docCount = docCount;
       this.docDate = docDate;
       this.docNo = docNo;
       this.rmrk = rmrk;
    }
   
    public VcleIssueDocumentFinTypeId getId() {
        return this.id;
    }
    
    public void setId(VcleIssueDocumentFinTypeId id) {
        this.id = id;
    }
    public VcleIssueDocumentMainType getVcleIssueDocumentMainType() {
        return this.vcleIssueDocumentMainType;
    }
    
    public void setVcleIssueDocumentMainType(VcleIssueDocumentMainType vcleIssueDocumentMainType) {
        this.vcleIssueDocumentMainType = vcleIssueDocumentMainType;
    }
    public VcleIssueDocumentFin getVcleIssueDocumentFin() {
        return this.vcleIssueDocumentFin;
    }
    
    public void setVcleIssueDocumentFin(VcleIssueDocumentFin vcleIssueDocumentFin) {
        this.vcleIssueDocumentFin = vcleIssueDocumentFin;
    }
    public Byte getDocCount() {
        return this.docCount;
    }
    
    public void setDocCount(Byte docCount) {
        this.docCount = docCount;
    }
    public Date getDocDate() {
        return this.docDate;
    }
    
    public void setDocDate(Date docDate) {
        this.docDate = docDate;
    }
    public Long getDocNo() {
        return this.docNo;
    }
    
    public void setDocNo(Long docNo) {
        this.docNo = docNo;
    }
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


