package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VcleVehicleInvoiceCarId generated by hbm2java
 */
public class VcleVehicleInvoiceCarId  implements java.io.Serializable {


     private int vehicleSp;
     private Date invoiceDate;
     private Date currDate;
     private int invoiceSp;
     private byte invoiceType;
     private int vcleSeq;

    public VcleVehicleInvoiceCarId() {
    }

    public VcleVehicleInvoiceCarId(int vehicleSp, Date invoiceDate, Date currDate, int invoiceSp, byte invoiceType, int vcleSeq) {
       this.vehicleSp = vehicleSp;
       this.invoiceDate = invoiceDate;
       this.currDate = currDate;
       this.invoiceSp = invoiceSp;
       this.invoiceType = invoiceType;
       this.vcleSeq = vcleSeq;
    }
   
    public int getVehicleSp() {
        return this.vehicleSp;
    }
    
    public void setVehicleSp(int vehicleSp) {
        this.vehicleSp = vehicleSp;
    }
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public Date getCurrDate() {
        return this.currDate;
    }
    
    public void setCurrDate(Date currDate) {
        this.currDate = currDate;
    }
    public int getInvoiceSp() {
        return this.invoiceSp;
    }
    
    public void setInvoiceSp(int invoiceSp) {
        this.invoiceSp = invoiceSp;
    }
    public byte getInvoiceType() {
        return this.invoiceType;
    }
    
    public void setInvoiceType(byte invoiceType) {
        this.invoiceType = invoiceType;
    }
    public int getVcleSeq() {
        return this.vcleSeq;
    }
    
    public void setVcleSeq(int vcleSeq) {
        this.vcleSeq = vcleSeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleVehicleInvoiceCarId) ) return false;
		 VcleVehicleInvoiceCarId castOther = ( VcleVehicleInvoiceCarId ) other; 
         
		 return (this.getVehicleSp()==castOther.getVehicleSp())
 && ( (this.getInvoiceDate()==castOther.getInvoiceDate()) || ( this.getInvoiceDate()!=null && castOther.getInvoiceDate()!=null && this.getInvoiceDate().equals(castOther.getInvoiceDate()) ) )
 && ( (this.getCurrDate()==castOther.getCurrDate()) || ( this.getCurrDate()!=null && castOther.getCurrDate()!=null && this.getCurrDate().equals(castOther.getCurrDate()) ) )
 && (this.getInvoiceSp()==castOther.getInvoiceSp())
 && (this.getInvoiceType()==castOther.getInvoiceType())
 && (this.getVcleSeq()==castOther.getVcleSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVehicleSp();
         result = 37 * result + ( getInvoiceDate() == null ? 0 : this.getInvoiceDate().hashCode() );
         result = 37 * result + ( getCurrDate() == null ? 0 : this.getCurrDate().hashCode() );
         result = 37 * result + this.getInvoiceSp();
         result = 37 * result + this.getInvoiceType();
         result = 37 * result + this.getVcleSeq();
         return result;
   }   


}


