package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * VcleIssueDocumentFinTypeId generated by hbm2java
 */
public class VcleIssueDocumentFinTypeId  implements java.io.Serializable {


     private long vcIssueDocSp;
     private short fiscalYear;
     private byte vcIssueDocSeq;

    public VcleIssueDocumentFinTypeId() {
    }

    public VcleIssueDocumentFinTypeId(long vcIssueDocSp, short fiscalYear, byte vcIssueDocSeq) {
       this.vcIssueDocSp = vcIssueDocSp;
       this.fiscalYear = fiscalYear;
       this.vcIssueDocSeq = vcIssueDocSeq;
    }
   
    public long getVcIssueDocSp() {
        return this.vcIssueDocSp;
    }
    
    public void setVcIssueDocSp(long vcIssueDocSp) {
        this.vcIssueDocSp = vcIssueDocSp;
    }
    public short getFiscalYear() {
        return this.fiscalYear;
    }
    
    public void setFiscalYear(short fiscalYear) {
        this.fiscalYear = fiscalYear;
    }
    public byte getVcIssueDocSeq() {
        return this.vcIssueDocSeq;
    }
    
    public void setVcIssueDocSeq(byte vcIssueDocSeq) {
        this.vcIssueDocSeq = vcIssueDocSeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleIssueDocumentFinTypeId) ) return false;
		 VcleIssueDocumentFinTypeId castOther = ( VcleIssueDocumentFinTypeId ) other; 
         
		 return (this.getVcIssueDocSp()==castOther.getVcIssueDocSp())
 && (this.getFiscalYear()==castOther.getFiscalYear())
 && (this.getVcIssueDocSeq()==castOther.getVcIssueDocSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getVcIssueDocSp();
         result = 37 * result + this.getFiscalYear();
         result = 37 * result + this.getVcIssueDocSeq();
         return result;
   }   


}


