package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VcleIssueDocumentMainDtl generated by hbm2java
 */
public class VcleIssueDocumentMainDtl  implements java.io.Serializable {


     private VcleIssueDocumentMainDtlId id;
     private VcleIssueDocumentMain vcleIssueDocumentMain;
     private PerEmploymentMaster perEmploymentMaster;
     private BigDecimal editorUserId;

    public VcleIssueDocumentMainDtl() {
    }

	
    public VcleIssueDocumentMainDtl(VcleIssueDocumentMainDtlId id, VcleIssueDocumentMain vcleIssueDocumentMain, PerEmploymentMaster perEmploymentMaster) {
        this.id = id;
        this.vcleIssueDocumentMain = vcleIssueDocumentMain;
        this.perEmploymentMaster = perEmploymentMaster;
    }
    public VcleIssueDocumentMainDtl(VcleIssueDocumentMainDtlId id, VcleIssueDocumentMain vcleIssueDocumentMain, PerEmploymentMaster perEmploymentMaster, BigDecimal editorUserId) {
       this.id = id;
       this.vcleIssueDocumentMain = vcleIssueDocumentMain;
       this.perEmploymentMaster = perEmploymentMaster;
       this.editorUserId = editorUserId;
    }
   
    public VcleIssueDocumentMainDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleIssueDocumentMainDtlId id) {
        this.id = id;
    }
    public VcleIssueDocumentMain getVcleIssueDocumentMain() {
        return this.vcleIssueDocumentMain;
    }
    
    public void setVcleIssueDocumentMain(VcleIssueDocumentMain vcleIssueDocumentMain) {
        this.vcleIssueDocumentMain = vcleIssueDocumentMain;
    }
    public PerEmploymentMaster getPerEmploymentMaster() {
        return this.perEmploymentMaster;
    }
    
    public void setPerEmploymentMaster(PerEmploymentMaster perEmploymentMaster) {
        this.perEmploymentMaster = perEmploymentMaster;
    }
    public BigDecimal getEditorUserId() {
        return this.editorUserId;
    }
    
    public void setEditorUserId(BigDecimal editorUserId) {
        this.editorUserId = editorUserId;
    }




}


