package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VcleDistributeMonthsEmpId generated by hbm2java
 */
public class VcleDistributeMonthsEmpId  implements java.io.Serializable {


     private short fiscalYear;
     private Date execMm;
     private int distributeCode;
     private long employeeId;
     private boolean ahramType;

    public VcleDistributeMonthsEmpId() {
    }

    public VcleDistributeMonthsEmpId(short fiscalYear, Date execMm, int distributeCode, long employeeId, boolean ahramType) {
       this.fiscalYear = fiscalYear;
       this.execMm = execMm;
       this.distributeCode = distributeCode;
       this.employeeId = employeeId;
       this.ahramType = ahramType;
    }
   
    public short getFiscalYear() {
        return this.fiscalYear;
    }
    
    public void setFiscalYear(short fiscalYear) {
        this.fiscalYear = fiscalYear;
    }
    public Date getExecMm() {
        return this.execMm;
    }
    
    public void setExecMm(Date execMm) {
        this.execMm = execMm;
    }
    public int getDistributeCode() {
        return this.distributeCode;
    }
    
    public void setDistributeCode(int distributeCode) {
        this.distributeCode = distributeCode;
    }
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }
    public boolean isAhramType() {
        return this.ahramType;
    }
    
    public void setAhramType(boolean ahramType) {
        this.ahramType = ahramType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleDistributeMonthsEmpId) ) return false;
		 VcleDistributeMonthsEmpId castOther = ( VcleDistributeMonthsEmpId ) other; 
         
		 return (this.getFiscalYear()==castOther.getFiscalYear())
 && ( (this.getExecMm()==castOther.getExecMm()) || ( this.getExecMm()!=null && castOther.getExecMm()!=null && this.getExecMm().equals(castOther.getExecMm()) ) )
 && (this.getDistributeCode()==castOther.getDistributeCode())
 && (this.getEmployeeId()==castOther.getEmployeeId())
 && (this.isAhramType()==castOther.isAhramType());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFiscalYear();
         result = 37 * result + ( getExecMm() == null ? 0 : this.getExecMm().hashCode() );
         result = 37 * result + this.getDistributeCode();
         result = 37 * result + (int) this.getEmployeeId();
         result = 37 * result + (this.isAhramType()?1:0);
         return result;
   }   


}


