package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VcleMaintanceRepairDtlId generated by hbm2java
 */
public class VcleMaintanceRepairDtlId  implements java.io.Serializable {


     private String costCode;
     private long employeeIdHave;
     private Date instructionDate;
     private Date enterDate;
     private Date notifyDate;
     private long employeeId;
     private int vehicleSp;
     private short repairSeq;

    public VcleMaintanceRepairDtlId() {
    }

    public VcleMaintanceRepairDtlId(String costCode, long employeeIdHave, Date instructionDate, Date enterDate, Date notifyDate, long employeeId, int vehicleSp, short repairSeq) {
       this.costCode = costCode;
       this.employeeIdHave = employeeIdHave;
       this.instructionDate = instructionDate;
       this.enterDate = enterDate;
       this.notifyDate = notifyDate;
       this.employeeId = employeeId;
       this.vehicleSp = vehicleSp;
       this.repairSeq = repairSeq;
    }
   
    public String getCostCode() {
        return this.costCode;
    }
    
    public void setCostCode(String costCode) {
        this.costCode = costCode;
    }
    public long getEmployeeIdHave() {
        return this.employeeIdHave;
    }
    
    public void setEmployeeIdHave(long employeeIdHave) {
        this.employeeIdHave = employeeIdHave;
    }
    public Date getInstructionDate() {
        return this.instructionDate;
    }
    
    public void setInstructionDate(Date instructionDate) {
        this.instructionDate = instructionDate;
    }
    public Date getEnterDate() {
        return this.enterDate;
    }
    
    public void setEnterDate(Date enterDate) {
        this.enterDate = enterDate;
    }
    public Date getNotifyDate() {
        return this.notifyDate;
    }
    
    public void setNotifyDate(Date notifyDate) {
        this.notifyDate = notifyDate;
    }
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }
    public int getVehicleSp() {
        return this.vehicleSp;
    }
    
    public void setVehicleSp(int vehicleSp) {
        this.vehicleSp = vehicleSp;
    }
    public short getRepairSeq() {
        return this.repairSeq;
    }
    
    public void setRepairSeq(short repairSeq) {
        this.repairSeq = repairSeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VcleMaintanceRepairDtlId) ) return false;
		 VcleMaintanceRepairDtlId castOther = ( VcleMaintanceRepairDtlId ) other; 
         
		 return ( (this.getCostCode()==castOther.getCostCode()) || ( this.getCostCode()!=null && castOther.getCostCode()!=null && this.getCostCode().equals(castOther.getCostCode()) ) )
 && (this.getEmployeeIdHave()==castOther.getEmployeeIdHave())
 && ( (this.getInstructionDate()==castOther.getInstructionDate()) || ( this.getInstructionDate()!=null && castOther.getInstructionDate()!=null && this.getInstructionDate().equals(castOther.getInstructionDate()) ) )
 && ( (this.getEnterDate()==castOther.getEnterDate()) || ( this.getEnterDate()!=null && castOther.getEnterDate()!=null && this.getEnterDate().equals(castOther.getEnterDate()) ) )
 && ( (this.getNotifyDate()==castOther.getNotifyDate()) || ( this.getNotifyDate()!=null && castOther.getNotifyDate()!=null && this.getNotifyDate().equals(castOther.getNotifyDate()) ) )
 && (this.getEmployeeId()==castOther.getEmployeeId())
 && (this.getVehicleSp()==castOther.getVehicleSp())
 && (this.getRepairSeq()==castOther.getRepairSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCostCode() == null ? 0 : this.getCostCode().hashCode() );
         result = 37 * result + (int) this.getEmployeeIdHave();
         result = 37 * result + ( getInstructionDate() == null ? 0 : this.getInstructionDate().hashCode() );
         result = 37 * result + ( getEnterDate() == null ? 0 : this.getEnterDate().hashCode() );
         result = 37 * result + ( getNotifyDate() == null ? 0 : this.getNotifyDate().hashCode() );
         result = 37 * result + (int) this.getEmployeeId();
         result = 37 * result + this.getVehicleSp();
         result = 37 * result + this.getRepairSeq();
         return result;
   }   


}


