package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VcleEmployeeVacation generated by hbm2java
 */
public class VcleEmployeeVacation  implements java.io.Serializable {


     private VcleEmployeeVacationId id;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private VcleVacationType vcleVacationType;
     private Date recordDate;
     private Date vacToDate;
     private Byte vacVal;
     private Boolean vacStatus;
     private String rmrk;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Date vacationLockDate;
     private Set vcleEmployeeVacationDates = new HashSet(0);

    public VcleEmployeeVacation() {
    }

	
    public VcleEmployeeVacation(VcleEmployeeVacationId id, VcleEmployeeMaster vcleEmployeeMaster, VcleVacationType vcleVacationType) {
        this.id = id;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
        this.vcleVacationType = vcleVacationType;
    }
    public VcleEmployeeVacation(VcleEmployeeVacationId id, VcleEmployeeMaster vcleEmployeeMaster, VcleVacationType vcleVacationType, Date recordDate, Date vacToDate, Byte vacVal, Boolean vacStatus, String rmrk, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Date vacationLockDate, Set vcleEmployeeVacationDates) {
       this.id = id;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.vcleVacationType = vcleVacationType;
       this.recordDate = recordDate;
       this.vacToDate = vacToDate;
       this.vacVal = vacVal;
       this.vacStatus = vacStatus;
       this.rmrk = rmrk;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.vacationLockDate = vacationLockDate;
       this.vcleEmployeeVacationDates = vcleEmployeeVacationDates;
    }
   
    public VcleEmployeeVacationId getId() {
        return this.id;
    }
    
    public void setId(VcleEmployeeVacationId id) {
        this.id = id;
    }
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleVacationType getVcleVacationType() {
        return this.vcleVacationType;
    }
    
    public void setVcleVacationType(VcleVacationType vcleVacationType) {
        this.vcleVacationType = vcleVacationType;
    }
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }
    public Date getVacToDate() {
        return this.vacToDate;
    }
    
    public void setVacToDate(Date vacToDate) {
        this.vacToDate = vacToDate;
    }
    public Byte getVacVal() {
        return this.vacVal;
    }
    
    public void setVacVal(Byte vacVal) {
        this.vacVal = vacVal;
    }
    public Boolean getVacStatus() {
        return this.vacStatus;
    }
    
    public void setVacStatus(Boolean vacStatus) {
        this.vacStatus = vacStatus;
    }
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }
    public Date getVacationLockDate() {
        return this.vacationLockDate;
    }
    
    public void setVacationLockDate(Date vacationLockDate) {
        this.vacationLockDate = vacationLockDate;
    }
    public Set getVcleEmployeeVacationDates() {
        return this.vcleEmployeeVacationDates;
    }
    
    public void setVcleEmployeeVacationDates(Set vcleEmployeeVacationDates) {
        this.vcleEmployeeVacationDates = vcleEmployeeVacationDates;
    }




}


