package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VcleDistributeDateOpen generated by hbm2java
 */
public class VcleDistributeDateOpen  implements java.io.Serializable {


     private VcleDistributeDateOpenId id;
     private Date execMm;
     private Date approvedDate;
     private String rmrk;
     private Boolean chkLock;
     private Set vcleDistributeDates = new HashSet(0);

    public VcleDistributeDateOpen() {
    }

	
    public VcleDistributeDateOpen(VcleDistributeDateOpenId id) {
        this.id = id;
    }
    public VcleDistributeDateOpen(VcleDistributeDateOpenId id, Date execMm, Date approvedDate, String rmrk, Boolean chkLock, Set vcleDistributeDates) {
       this.id = id;
       this.execMm = execMm;
       this.approvedDate = approvedDate;
       this.rmrk = rmrk;
       this.chkLock = chkLock;
       this.vcleDistributeDates = vcleDistributeDates;
    }
   
    public VcleDistributeDateOpenId getId() {
        return this.id;
    }
    
    public void setId(VcleDistributeDateOpenId id) {
        this.id = id;
    }
    public Date getExecMm() {
        return this.execMm;
    }
    
    public void setExecMm(Date execMm) {
        this.execMm = execMm;
    }
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }
    public Set getVcleDistributeDates() {
        return this.vcleDistributeDates;
    }
    
    public void setVcleDistributeDates(Set vcleDistributeDates) {
        this.vcleDistributeDates = vcleDistributeDates;
    }




}


