package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1



/**
 * VcleEmployeeVacationDate generated by hbm2java
 */
public class VcleEmployeeVacationDate  implements java.io.Serializable {


     private VcleEmployeeVacationDateId id;
     private VcleEmployeeVacation vcleEmployeeVacation;
     private Boolean chkLock;

    public VcleEmployeeVacationDate() {
    }

	
    public VcleEmployeeVacationDate(VcleEmployeeVacationDateId id, VcleEmployeeVacation vcleEmployeeVacation) {
        this.id = id;
        this.vcleEmployeeVacation = vcleEmployeeVacation;
    }
    public VcleEmployeeVacationDate(VcleEmployeeVacationDateId id, VcleEmployeeVacation vcleEmployeeVacation, Boolean chkLock) {
       this.id = id;
       this.vcleEmployeeVacation = vcleEmployeeVacation;
       this.chkLock = chkLock;
    }
   
    public VcleEmployeeVacationDateId getId() {
        return this.id;
    }
    
    public void setId(VcleEmployeeVacationDateId id) {
        this.id = id;
    }
    public VcleEmployeeVacation getVcleEmployeeVacation() {
        return this.vcleEmployeeVacation;
    }
    
    public void setVcleEmployeeVacation(VcleEmployeeVacation vcleEmployeeVacation) {
        this.vcleEmployeeVacation = vcleEmployeeVacation;
    }
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }




}


