package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VcleEmployeeOvertime generated by hbm2java
 */
public class VcleEmployeeOvertime  implements java.io.Serializable {


     private VcleEmployeeOvertimeId id;
     private VcleEmployeeMaster vcleEmployeeMaster;
     private VcleWorkType vcleWorkType;
     private BigDecimal valHour;
     private BigDecimal valHourOk;
     private String rmrk;
     private Boolean chkLock;

    public VcleEmployeeOvertime() {
    }

	
    public VcleEmployeeOvertime(VcleEmployeeOvertimeId id, VcleEmployeeMaster vcleEmployeeMaster, VcleWorkType vcleWorkType) {
        this.id = id;
        this.vcleEmployeeMaster = vcleEmployeeMaster;
        this.vcleWorkType = vcleWorkType;
    }
    public VcleEmployeeOvertime(VcleEmployeeOvertimeId id, VcleEmployeeMaster vcleEmployeeMaster, VcleWorkType vcleWorkType, BigDecimal valHour, BigDecimal valHourOk, String rmrk, Boolean chkLock) {
       this.id = id;
       this.vcleEmployeeMaster = vcleEmployeeMaster;
       this.vcleWorkType = vcleWorkType;
       this.valHour = valHour;
       this.valHourOk = valHourOk;
       this.rmrk = rmrk;
       this.chkLock = chkLock;
    }
   
    public VcleEmployeeOvertimeId getId() {
        return this.id;
    }
    
    public void setId(VcleEmployeeOvertimeId id) {
        this.id = id;
    }
    public VcleEmployeeMaster getVcleEmployeeMaster() {
        return this.vcleEmployeeMaster;
    }
    
    public void setVcleEmployeeMaster(VcleEmployeeMaster vcleEmployeeMaster) {
        this.vcleEmployeeMaster = vcleEmployeeMaster;
    }
    public VcleWorkType getVcleWorkType() {
        return this.vcleWorkType;
    }
    
    public void setVcleWorkType(VcleWorkType vcleWorkType) {
        this.vcleWorkType = vcleWorkType;
    }
    public BigDecimal getValHour() {
        return this.valHour;
    }
    
    public void setValHour(BigDecimal valHour) {
        this.valHour = valHour;
    }
    public BigDecimal getValHourOk() {
        return this.valHourOk;
    }
    
    public void setValHourOk(BigDecimal valHourOk) {
        this.valHourOk = valHourOk;
    }
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }
    public Boolean getChkLock() {
        return this.chkLock;
    }
    
    public void setChkLock(Boolean chkLock) {
        this.chkLock = chkLock;
    }




}


