package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VcleMarkType generated by hbm2java
 */
public class VcleMarkType  implements java.io.Serializable {


     private String markType;
     private String markName;
     private Set vcleVehicleClassDtls = new HashSet(0);
     private Set vcleVehicleModels = new HashSet(0);

    public VcleMarkType() {
    }

	
    public VcleMarkType(String markType, String markName) {
        this.markType = markType;
        this.markName = markName;
    }
    public VcleMarkType(String markType, String markName, Set vcleVehicleClassDtls, Set vcleVehicleModels) {
       this.markType = markType;
       this.markName = markName;
       this.vcleVehicleClassDtls = vcleVehicleClassDtls;
       this.vcleVehicleModels = vcleVehicleModels;
    }
   
    public String getMarkType() {
        return this.markType;
    }
    
    public void setMarkType(String markType) {
        this.markType = markType;
    }
    public String getMarkName() {
        return this.markName;
    }
    
    public void setMarkName(String markName) {
        this.markName = markName;
    }
    public Set getVcleVehicleClassDtls() {
        return this.vcleVehicleClassDtls;
    }
    
    public void setVcleVehicleClassDtls(Set vcleVehicleClassDtls) {
        this.vcleVehicleClassDtls = vcleVehicleClassDtls;
    }
    public Set getVcleVehicleModels() {
        return this.vcleVehicleModels;
    }
    
    public void setVcleVehicleModels(Set vcleVehicleModels) {
        this.vcleVehicleModels = vcleVehicleModels;
    }




}


