package com.codeator.www._6_1_Json_entities;
// Generated Aug 21, 2021 10:55:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VcleVehicleInspectDtl generated by hbm2java
 */
public class VcleVehicleInspectDtl  implements java.io.Serializable {


     private VcleVehicleInspectDtlId id;
     private VcleCostType vcleCostType;
     private VcleVehicleInspect vcleVehicleInspect;
     private BigDecimal val;

    public VcleVehicleInspectDtl() {
    }

    public VcleVehicleInspectDtl(VcleVehicleInspectDtlId id, VcleCostType vcleCostType, VcleVehicleInspect vcleVehicleInspect, BigDecimal val) {
       this.id = id;
       this.vcleCostType = vcleCostType;
       this.vcleVehicleInspect = vcleVehicleInspect;
       this.val = val;
    }
   
    public VcleVehicleInspectDtlId getId() {
        return this.id;
    }
    
    public void setId(VcleVehicleInspectDtlId id) {
        this.id = id;
    }
    public VcleCostType getVcleCostType() {
        return this.vcleCostType;
    }
    
    public void setVcleCostType(VcleCostType vcleCostType) {
        this.vcleCostType = vcleCostType;
    }
    public VcleVehicleInspect getVcleVehicleInspect() {
        return this.vcleVehicleInspect;
    }
    
    public void setVcleVehicleInspect(VcleVehicleInspect vcleVehicleInspect) {
        this.vcleVehicleInspect = vcleVehicleInspect;
    }
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }




}


