package com.codeator.www._1_2_DB_entities_mysql;
// Generated Jun 16, 2019 2:30:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ExternalGov generated by hbm2java
 */
@Entity
@Table(name="external_gov"
    ,catalog="alert_demo"
)
public class ExternalGov  implements java.io.Serializable {


     private Integer extenalGovId;
     private String externalGovName;
     private String externalGovPhone;
     private Set<CalenderAlertNotifications> calenderAlertNotificationses = new HashSet<CalenderAlertNotifications>(0);

    public ExternalGov() {
    }

	
    public ExternalGov(String externalGovName) {
        this.externalGovName = externalGovName;
    }
    public ExternalGov(String externalGovName, String externalGovPhone, Set<CalenderAlertNotifications> calenderAlertNotificationses) {
       this.externalGovName = externalGovName;
       this.externalGovPhone = externalGovPhone;
       this.calenderAlertNotificationses = calenderAlertNotificationses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="extenal_gov_id", unique=true, nullable=false)
    public Integer getExtenalGovId() {
        return this.extenalGovId;
    }
    
    public void setExtenalGovId(Integer extenalGovId) {
        this.extenalGovId = extenalGovId;
    }

    
    @Column(name="external_gov_name", nullable=false, length=45)
    public String getExternalGovName() {
        return this.externalGovName;
    }
    
    public void setExternalGovName(String externalGovName) {
        this.externalGovName = externalGovName;
    }

    
    @Column(name="external_gov_phone", length=45)
    public String getExternalGovPhone() {
        return this.externalGovPhone;
    }
    
    public void setExternalGovPhone(String externalGovPhone) {
        this.externalGovPhone = externalGovPhone;
    }

@ManyToMany(fetch=FetchType.EAGER, mappedBy="externalGovs")
    public Set<CalenderAlertNotifications> getCalenderAlertNotificationses() {
        return this.calenderAlertNotificationses;
    }
    
    public void setCalenderAlertNotificationses(Set<CalenderAlertNotifications> calenderAlertNotificationses) {
        this.calenderAlertNotificationses = calenderAlertNotificationses;
    }




}


